### ISSUE TITLE
admin web UI

### ISSUE THREAD

**Issue by ghost** [nodester/nodester#104]
would  be nice to have a web UI for the whole of Nodster multi tenants.
for example you could use: "admin.nodster.com" 

This could show stats and maybe some commands

**Comment by michealbenedict** [comment]
Hi,

you can try admin.nodester.com --> Web Admin UI (this is very much under development, so you may not find all the functionalities exposed by the API)

**Comment by chrismatthieu** [comment]
The code for admin.nodester.com is available at https://github.com/nodester/admin-panel.  Please feel free to check it out and send pull requests if you would like to get involved.
