### ISSUE TITLE
Set NODE_ENV environment variable

### ISSUE THREAD

**Issue by cjoudrey** [nodester/nodester#106]
Although it isn't official, a few Node.js frameworks (namely [Express](https://github.com/visionmedia/express/blob/2.2.2/lib/http.js#L59) and [Connect](https://github.com/senchalabs/connect/blob/1.3.0/lib/http.js#L18)) have adopted the `NODE_ENV` env. variable to specify the environment of the app.

For now, it would be great if Nodester defaulted to `NODE_ENV=production` as it would make life a lot easier for people using these frameworks.

At the moment, the fallback value for `NODE_ENV` in these frameworks is `development`, which means having to manually set the value to `production`.

In the future, it could also be useful to let the user decide the value of `NODE_ENV`.

Thoughts?

**Comment by ckknight** [comment]
If we could set which NODE_ENV the app was running in (through the REST/cli API), that'd be best.

It should clearly default to "production", but being able to set my app manually to "staging" or "development" or "my-custom-thingy" would be handy.

**Comment by cjoudrey** [comment]
Agreed :)

**Comment by city41** [comment]
It doesn't look like github has any kind of "me too" button for issues, so I'd like to show support for this feature suggestion. I agree with this, it'd be nice to be able to set at least NODE_ENV, if not any arbitrary env variable.

**Comment by chrismatthieu** [comment]
fixed by ckknight!  w00t :)

**Comment by blindsey** [comment]
Is there any documentation on how to use this feature?

**Comment by rstacruz** [comment]
_(comment deleted)_

**Comment by blindsey** [comment]
@rstacruz - yeah, that's how I expect this feature should work, but the code doesn't seem to do that.

**Comment by wachunga** [comment]
In case anyone else is searching for this: it's only supported by the REST interface, not the CLI, for now: http://nodester.com/api.html#rest

**Comment by chrismatthieu** [comment]
Someone should add it to the nodester-cli and nodester-api repos and send a pull request to get it added to the CLI ;)

**Comment by ghost** [comment]
Here ya go: https://github.com/nodester/nodester-cli/pull/35

For some reason, GET calls to /env on the API keep 404'ing for me. Nice 404 page you've got there, though.
