### ISSUE TITLE
During a downtime, serve a static HTML page and give a 503.

### ISSUE THREAD

**Issue by ckknight** [nodester/nodester#109]
If an app is stopped, it could be very handy to serve a single static HTML page and give a 503 Service Unavailable.

This would be mostly for the case where there is a pending database migration or some other external data that needs to be updated before the app can come back online.

The HTML page should be configurable on a per-app basis. Possibly check for /503.html or some other hard-coded name.

**Comment by DanBUK** [comment]
We are going to work some larger cluster logic into the lb layer in front of the apps. Therefore things like this well be possible, just not right now :/

**Comment by yocontra** [comment]
New proxy fixes this. Closing now.
