### ISSUE TITLE
Allow for an app to configure how many processes it runs on.

### ISSUE THREAD

**Issue by ckknight** [nodester/nodester#110]
For certain (very few, really) apps, they may want to run on more than one process, so it could be handy to ask to run on 2 or 4 processes.

I'd think that there should be a maximum per-app that defaults to 1 process and that admins would have to approve to increase that maximum.

I'm sure that this would add extra complications to the load balancing system.

**Comment by chrismatthieu** [comment]
This feature will likely be implemented as a pay-to-play offering.  Smaller, single process apps will always be free but we should develop a pricing model for hosting the more complex or resource intensive apps running on nodester.com.

**Comment by ckknight** [comment]
Yeah, that'd make sense. In that case, you might want to run your app across multiple VMs.

**Comment by yocontra** [comment]
Closed due to absence from V2 roadmap. LXC containers have strict sandboxing that will be standard for each user
