### ISSUE TITLE
Allow configuration of arbitrary env variables

### ISSUE THREAD

**Issue by ckknight** [nodester/nodester#112]
If I wanted to have an app that I publish to both github and to nodester, I wouldn't want to put my super-secret database password into the app itself, and would be better if I could access it through process.env.DB_PASSWORD (or something). I could similarly do something with application cookie secret keys or various other things.

**Comment by ckknight** [comment]
I realize this is related to https://github.com/nodester/nodester/issues/106

**Comment by davglass** [comment]
What's the difference in this and using a config.json file to load at app start? You could always have a github branch that has the .gitignore in it to ignore the config.json file. I mean, you would have to provide that data to the nodester app anyway.

**Comment by ckknight** [comment]
Hmm, you do have a point there. I'll try it out.

**Comment by chrismatthieu** [comment]
fixed by ckknight!  w00t :)
