### ISSUE TITLE
app not running, but all signs show that it is

### ISSUE THREAD

**Issue by adrusi** [nodester/nodester#115]
I have an app hosted at `http://cloudcode.nodester.com/` and it runs perfectly locally. However, when I pushed it to the server, it didn't work. I checked the logs, and there's nothing worth noting there. When I ran `nodester apps list` it said that "cloudcode" is running, just like my other apps. The app was working on the server earlier without problems.

**Comment by chrismatthieu** [comment]
Culd you run nodester apps logs your-app-name? This will show your error log on the server.

**Comment by adrusi** [comment]
I don't get anything special

```
Munging require paths..
Globallizing Buffer
Reading file...
Nodester wrapped script starting (2290) at  Mon, 25 Apr 2011 04:43:10
```

GMT
    [INFO] Nodester listening on port: 9600
    25 Apr 04:43:10 - socket.io ready - accepting connections
    Express server listening on port 9600

It's almost as if nothing is wrong.

**Comment by chrismatthieu** [comment]
weird, indeed.  What does your code look like?

**Comment by adrusi** [comment]
well, it uses express and nowjs (so it requires sockets, but I already have
a socket app running). It uses the filesystem api and
`require("child_processes").exec` (very sparingly). That's about it for the
server-side.

**Comment by chrismatthieu** [comment]
Did you remember to use port 80 on the client-side for your websockets?

**Comment by adrusi** [comment]
I'm using nowjs, which completely abstracts the websockets api. I just run
`var everyone = require("now").initialize(app);` where app is the express
server object and all the setup is done for me. [I've used it before](http://privatechat.nodester.com/) on nodester and it worked flawlessly, and
the last time that I pushed this app to nodester, the websockets worked, so
I doubt it has anything to do with the websockets. However, I'm worried
about how it executes shell commands, that may have been disabled for
security reasons, although it's vital to the function of the app (it's a
lightweight cloud code editor).

**Comment by chrismatthieu** [comment]
Are you still having an issue with deploying http://cloudcode.nodester.com/

**Comment by adrusi** [comment]
yes, i haven't tried in a day or two, but I haven't changed anything either

**Comment by chrismatthieu** [comment]
We just deployed an update and upgraded to node.js 0.4.7.  Could you try it
again?

Thanks,
Chris

**Comment by adrusi** [comment]
Ok, that may make a difference, because I'm running v0.4.7 locally.

**Comment by adrusi** [comment]
yes that works, I guess it was some nuance difference between the versions.
I think that they added the "encoding" parameter for the fs module readFile
and writeFile methods.

**Comment by DanBUK** [comment]
Is this issue resolved now adrusi?

**Comment by funkytek** [comment]
is this resolved? can you restart?

**Comment by yocontra** [comment]
Closing as this seems to be resolved.
