### ISSUE TITLE
Timezone Bug using node-time

### ISSUE THREAD

**Issue by clintandrewhall** [nodester/nodester#116]
I wrote a test for this [1]... I'm seeing deployments on Nodester [2] ignore the timezone setting, and I'm not sure why.  Any advice is appreciated.

If you run it locally, no problem.  On Nodester, the setting is ignored and all times are returned in UTC.

[1] https://github.com/clintandrewhall/nodester-nodetime-test
[2] http://nodester-nodetime-test.nodester.com/

**Comment by davglass** [comment]
All Nodester apps are sandboxed and chrooted. So I would assume that the C extension is trying to load TZ data from the system but doesn't have access to the files.

**Comment by clintandrewhall** [comment]
Please see this issue/reply reply in node-time:

https://github.com/TooTallNate/node-time/issues/4

Any advice or insight?

**Comment by TooTallNate** [comment]
Dav, what does the chrooted environment look like? i.e. is there an `/etc` dir at all, and would it be possible for Nodester to set up a symlink to the global `/etc/share/zoneinfo` dir so that these C functions will work properly?

**Comment by davglass** [comment]
A symlink won't work, the chroot would invalidate that path. I would have to copy the TZ info into each apps directory (I already have to create an /etc/resolv.conf for DNS lookups). This would be a big hack to force the creation of this dir and copy all the TZ data into it.

Is there a "preload" for your module? So I can require it in the script before we initialize the chroot, then share it with the chroot ENV.

We have to do something similar for SSL connections, I have to do this to make SSL connections work inside the chroot:

```
var crypto = require('crypto');
var creds = crypto.createCredentials();
```

**Comment by TooTallNate** [comment]
It can also easily be done by setting the TZDIR env variable, and pointing
it to a path inside your app's chroot. This only works on Glibc2 and above
though. Which version of GlibC is Nodester running?

**Comment by davglass** [comment]
We "might" be able to "hard link" the directories, but I would have to test to see the best way to handle that.

**Comment by davglass** [comment]
On Amazon AWS 2.12.

I'm not sure if setting the ENV will help either, since the chroot will remap that once the call it actually done.

**Comment by davglass** [comment]
Pointing to a path inside is another issue, that means I have to copy 5MB of tz data per app. That's not a valid solution for us at the moment. I will have to work out another way to get this data available to the node addon.

**Comment by TooTallNate** [comment]
I meant for the end-user to set their TZDIR env themselves. But ya, it would
be nice if `node-time` _"just worked"_ on Nodester, instead of telling
people to copy their own versions of the zoneinfo dirs into their repos and
setting the TZDIR env variable manually. Hopefully you can figure out "hard
linking"!

**Comment by clintandrewhall** [comment]
In the interim, I can just write a simple web service as a Nodester app with a copy of the files and simply invoke that from my app until a longer term solution is found... then just alter the service to read from the system copy using that solution?  People might like to use such a service anyway...?

**Comment by davglass** [comment]
Now, what I may be able to do it write a proxy method on the chrooted process that looks into the global environment for the date info.

**Comment by clintandrewhall** [comment]
Let me know if I can help with a test case, or redeploying my test project! Thanks for looking into this...

**Comment by clintandrewhall** [comment]
Hi Dav, don't mean to pester, but I was curious if you were able to discover anything else on this issue.  My app is nearly ready to go, and I'd like to use Nodester; it's been the most stable hosting option thus far.

**Comment by TooTallNate** [comment]
Well you could still try copying the zoneinfo files into your deployment repo, and setting the `TZDIR` environment variable to the (chrooted) location in your repo. It _should_ work then assuming Nodester is using glibc 2 or newer.

**Comment by chrismatthieu** [comment]
We recently added environment variables in the REST API (http://nodester.com/api.html#env) if that helps...

**Comment by clintandrewhall** [comment]
Sorry, I'm still struggling here... I've copied the zoneinfo directory into my lib directory and pushed to Nodester.

How do I set the path properly using the REST API?  I'm assuming it needs to be a qualified and not relative path, right?  Setting it to "./lib/zoneinfo" has no effect.

**Comment by clintandrewhall** [comment]
Not that I thought it would work, I also added the following to the top of my server.js file:

```
  process.env.TZDIR = __dirname + "/lib/zoneinfo";
```

**Comment by TooTallNate** [comment]
Update your `nodester-nodetime-test` repo so we can see what's going on

**Comment by clintandrewhall** [comment]
Updated.

I tried a number of combinations, nothing seemed to work, including:

```
curl -X PUT -u "clintandrewhall:xxx" -d "appname=nodester-nodetime-test&key=TZDIR&value=..." http://api.nodester.com/env

value=lib/zoneinfo
value=/lib/zoneinfo
value=./lib/zoneinfo
```

It's currently running at: http://nodester-nodetime-test.nodester.com/

**Comment by clintandrewhall** [comment]
Has anyone had a chance to look at this at all?  Chris, if there's a proper way to set the environment variable that I'm missing, please let me know!

**Comment by DanBUK** [comment]
I will be setting up the chroots with proper zoneinfo folders in /usr/share/zoneinfo once #143 has been fully tested.
