### ISSUE TITLE
install.txt

### ISSUE THREAD

**Issue by eventi** [nodester/nodester#12]
https://github.com/nodester/nodester/blob/master/install.txt#L47 references a node-daemon repo that doesn't exist...

**Comment by DanBUK** [comment]
Updating install.txt to reference daemon-tools package; you will need to &#39;git submodule update&#39;. Closed by b6d161ad308ab80b48d1094258d57196d90bb255

**Comment by DanBUK** [comment]
And: npm install daemon-tools

**Comment by eventi** [comment]
Thanks Dan - but I'm still stuck when following the current install.txt when I get to ./start.sh - 

The following is the error: 

```
nodester@bossnode:~/nodester$ ./start.sh 
sudo: unable to resolve host bossnode

node.js:68
    throw e; // process.nextTick error, or 'error' event on first tick
    ^
Error: Cannot find module 'daemon'
  at resolveModuleFilename (node.js:276:15)
  at loadModule (node.js:238:22)
  at require (node.js:302:16)
  at Object.<anonymous> (/var/nodester/nodester/deps/nodemon/nodemon:132:14)
  at Module._compile (node.js:359:32)
  at Object..js (node.js:367:14)
  at Module.load (node.js:290:27)
  at Array.<anonymous> (node.js:381:26)
  at EventEmitter._tickCallback (node.js:60:24)

node.js:68
    throw e; // process.nextTick error, or 'error' event on first tick
    ^
Error: Cannot find module 'daemon'
  at resolveModuleFilename (node.js:276:15)
  at loadModule (node.js:238:22)
  at require (node.js:302:16)
  at Object.<anonymous> (/var/nodester/nodester/deps/nodemon/nodemon:132:14)
  at Module._compile (node.js:359:32)
  at Object..js (node.js:367:14)
  at Module.load (node.js:290:27)
  at Array.<anonymous> (node.js:381:26)
  at EventEmitter._tickCallback (node.js:60:24)
```

I tried the daemon from npm, but I don't think it's the right module, since it complains about missing members of the object.

Here's my npm installed modules, I don't have much else installed

```
nodester@bossnode:~/nodester$ npm ls installed
npm info it worked if it ends with ok
npm info using npm@0.2.16
npm info using node@v0.3.4-pre
base64@2.0.0         =pkrumins active installed latest remote   A C++ module for node-js that does base64 encoding and d
colors@0.3.0         =marak active installed latest remote   get colors in your node.js console like what    
connect@0.5.6        =creationix =tjholowaychuk active installed latest remote   High performance middleware framework  
couch-client@0.0.3   =creationix active installed latest remote   A Simple, Fast, and Flexible CouchDB Client    
daemon-tools@0.1.4   =DanBUK active installed latest remote   Add-on for creating *nix daemons, handling chroots, etc.  
express@1.0.3        =tjholowaychuk active installed latest remote   Sinatra inspired web development framework     fram
eyes@0.1.6           =cloudhead active installed latest remote   a customizable value inspector     inspector debug insp
http-proxy@0.3.1     =indexzero =marak active installed latest remote stable   A full-featured http reverse proxy for no
nave@0.1.3           =isaacs active installed latest remote   Virtual Environments for Node    
node-base64@0.0.1    =astro active installed latest remote   Node.js module for base64 encoding and decoding.    
npm@0.2.16           =isaacs active installed latest remote   A package manager for node     package manager modules ins
npm-wrapper@0.0.1    =DanBUK active installed latest remote   A dumb class wrapper around npm to make it easy to manage 
optimist@0.1.3       =substack active installed latest remote   Light-weight option parsing with an argv hash. No optstr
pool@0.4.1           =mikeal active installed latest remote   HTTP client pools.    
request@1.1.1        =mikeal active installed latest remote   Simplified HTTP request client.    
vows@0.5.3           =cloudhead active installed latest remote stable   Asynchronous BDD & continuous integration for no
npm ok
nodester@bossnode:~/nodester$ 
```

**Comment by eventi** [comment]
OK - got it - I changed the require('daemon') to require('daemon-tools') -

I see that you updated nodemon, but it's not committed into the super project - you'll see that if you clone nodester, git submodule init, git submodule update, deps/daemon-tools will have the old version - you need to git pull in the submodule, then commit in the supermodule, or the "git submodules update" will only bring it to where the supermodule thinks it should be.

Try the clone, init and update, and you'll see

nodester@bossnode:~/nodester$ git diff deps/nodemon
diff --git a/deps/nodemon b/deps/nodemon
index 1738324..1521052 160000
--- a/deps/nodemon
+++ b/deps/nodemon
@@ -1 +1 @@
-Subproject commit 1738324cfa6abc37cbfeeee341eff0f88dbf28ca
+Subproject commit 152105206ca655876447a35398045586af8ae70e
nodester@bossnode:~/nodester$

**Comment by DanBUK** [comment]
Sorry about that eventi, we are slowly moving away from using nodemon, current master is now using app_stop|app_start|app_restart to do that actions to apps, with changes to the post commit hook.

I need to start working on upgrade guides.. But as we haven't got to a formal release it's still a bit up in the air; hope you understand!

**Comment by eventi** [comment]
no need to apologize :)  Thanks for the fix
