### ISSUE TITLE
Multiple issues with application

### ISSUE THREAD

**Issue by stewart** [nodester/nodester#120]
I got invited to Nodester today, and was attempting to set up a test application. Once my application was set up, I tried pushing with git, and this went fine. When I try to go to the [app](http://nstatus.nodester.com), I get told that the application is not responding, and that this error message:

```
ECONNREFUSED, Connection refused
```

I attempted to check out what was up with the nodester-cli, and "nodester app info nstatus" returns 

```
nodester info Gathering information about: nstatus
nodester info nstatus on port 9689 running: failed-to-start (pid: unknown)
nodester info gitrepo: ec2-user@nodester.com:/node/hosted_apps/andrewstewart/1536-fdaa2e03cf1a4f9d2edfbf7aa8c4ea5c.git
nodester info appfile: server.js
```

I've tried restarting the application several times, and even creating deleting and recreating the nodester app, and nothing seems to work.

Can anyone give me a hand with this?

**Comment by stewart** [comment]
The app I'm trying to start can be found [here](http://github.com/stewart/nstat.us)

**Comment by chrismatthieu** [comment]
Hi Stewart,

Nodester doesn't support coffee script yet but it's on our list.  You can run the following command to see your system log:

nodester app logs nstatus

Hope this helps...
Chris

**Comment by stewart** [comment]
There's a compiled server.js file that Nodester is set to run. Here's the contents of the log:

```
$ nodester app logs nstatus

nodester info Showing logs for: nstatus
Munging require paths..
Globallizing Buffer
Reading file...
Nodester wrapped script starting (3711) at  Thu, 28 Apr 2011 03:49:00 GMT
Error: Cannot find module 'express'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at Function.require (module.js:348:19)
    at /node/nodester/scripts/launch_chrooted_app.js:159:26
    at server.js:3:13
    at server.js:52:4
    at /node/nodester/scripts/launch_chrooted_app.js:205:20
    at [object Object].<anonymous> (fs.js:107:5)
    at [object Object].emit (events.js:61:17)
    at afterRead (fs.js:878:12){ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Cannot find module \'express\'' }
```

**Comment by chrismatthieu** [comment]
Ah, you need to install express like this:

nodester npm install nstatus express

**Comment by chrismatthieu** [comment]
after installing express, you will either need to repush your app or restart it like this:

nodester app restart nstatus

**Comment by stewart** [comment]
That seems to have finally done it, wasn't working last time I tried installing all the required NPM packages.

Thank you for you help.

**Comment by ghost** [comment]
If you Windows user add location to your path. 

<pre>export NODE_PATH="C:\Users\IMarek\AppData\Roaming\npm\node_modules"</pre>

Change: IMarek to your user name :) 

I explained in bit more details on my post <a href="http://blog.i-evaluation.com/2012/09/17/error-cannot-find-module-express/">Error can not find module</a> but bottom line it can be fixed (on Windows) by:
