### ISSUE TITLE
missing dependency doesn't show nice

### ISSUE THREAD

**Issue by danielb2** [nodester/nodester#121]
Installed express using jade as my templating system. Restarted app, but didn't run npm. The error gave no clue whatsoever ( after running nodester app logs ) that there were packages missing:

```
 nodester app logs
nodester info Showing logs for: gbtrading
Munging require paths..
Globallizing Buffer
Reading file...
Nodester wrapped script starting (6392) at  Sun, 01 May 2011 21:45:33 GMT
Warning: connection.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and obviously only work within a single process.[ERROR] You asked to listen on port 3000 but nodester will use port 9746 instead..
Express server listening on port 9746
```

In this case, I knew of the missing deps, but that could be tricky to debug otherwise.

**Comment by davglass** [comment]
Did express throw an error locally? If express didn't throw how are we supposed to know something is wrong?

**Comment by danielb2** [comment]
no, express runs fine locally. But this is not a local problem. Let me try to explain the problem again.

If I do not install a package, such as express on your end via nodester npm install express, the resulting error when trying to run the app, is not clear.

**Comment by davglass** [comment]
Again, I understand that. My question is still very valid.

If you don't have the dependency locally does express throw an error? If express throws an error, we can trap it. If it doesn't, we can't.

**Comment by danielb2** [comment]
I see. Sorry for the confusion. I had already installed the package locally, made my modifications, and pushed to the server, hence I never saw a local error.

So to answer your question; yes, the require fails like it always fails if it doesn't find a dependency.

**Comment by danielb2** [comment]
to be clear, require fails, not express... express isn't installed so it wouldn't throw an error.

**Comment by chrismatthieu** [comment]
I've read this issue 3 times and still don't follow the gist of the request.  Are we not installing express' NPM dependencies properly?

**Comment by danielb2** [comment]
1. on your local machine, write an app using express installed via `npm install express`
2. be happy with app running very nicely locally
3. deploy the application to nodester
4. watch application fail
5.  _check logs and see no clue why application failed_
6.  suddenly remember that you forgot to run `nodester npm install express` and run it
7.  restart app and watch app run
8.  rejoice

This is what happened to me. Hopefully this is more clear.

Nothing on your end is broken as such. I would, however, imagine that the lack of errors in step no. 5 would make it hard to debug. That was the intended feedback with this issue.

**Comment by clintandrewhall** [comment]
That's strange... I recall getting errors in the logs when I don't have a dependency...?  Perhaps it's a specific dependency, or how they're being included?  Maybe I'm mistaken... (could be).

**Comment by DanBUK** [comment]
I think we should move to having package.json in the root of an application to ensure that deps are installed. As this isn't actually an issue I'm closing it off.
