### ISSUE TITLE
__dirname and __filename is not correct

### ISSUE THREAD

**Issue by paintenzero** [nodester/nodester#123]
I tried to get the directory of the project to run child process. When I output 

```
console.log( 'DIRNAME: %s, FILENAME: %s, HACKED: %s', __dirname, __filename, path.join(path.dirname(__filename)) );
```

On nodester I get: 

```
DIRNAME: /, FILENAME: server.js, HACKED: .
```

While on my local machine I get:

```
DIRNAME: /home/net_serv/sksrv, FILENAME: /home/net_serv/sksrv/server.js, HACKED: /home/net_serv/sksrv
```

**Comment by davglass** [comment]
Your in a chrooted environment while in nodester, so your app is actually '/'.

**Comment by paintenzero** [comment]
Thanks for the fast reply. I see. Then there is a problem starting a child process:

```
Starting worker: /worker.js (<--that is my console.log)
CHILD STDERR: execvp(): No such file or directory
```

Worker.js is in the same (root) directory as the start file. It is working on local machine. Should I open another issue?

**Comment by DanBUK** [comment]
This is due to the nature of the current style of chroot system. I will be changing the chroot method in the next few days so will be resolving this issue.

**Comment by DanBUK** [comment]
Once #143 has been tested more this should be resolved.
