### ISSUE TITLE
app can't write to /tmp

### ISSUE THREAD

**Issue by talgiat** [nodester/nodester#124]
I have an app that uploads a file from a form and processes it (using connect-form module).

I get the following exception (in the logs):

```
Error: ENOENT, No such file or directory '/tmp/3aeab46ee8555bcdfa206cc77413c8a9.csv'{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'ENOENT, No such file or directory \'/tmp/3aeab46ee8555bcdfa206cc77413c8a9.csv\'',
  errno: 2,
  code: 'ENOENT',
  path: '/tmp/3aeab46ee8555bcdfa206cc77413c8a9.csv' }
```

Is nodester disables writing to the /tmp folder ?

**Comment by chrismatthieu** [comment]
Nodester doesnt disable writes.  Its probably because the /tmp directory doesnt exist.  Try writing to /etc and let me know if that works.

**Comment by davglass** [comment]
You need to create the directory before writing to it. Nodester is a
chroot environment, so you don't have access to the system.

On May 7, 2011, at 6:39 AM, talgiat
reply@reply.github.com
wrote:

**Comment by talgiat** [comment]
thanks !

**Comment by kud** [comment]
Oi oi,

I've got the same problem. The thing is as we use git to push files on nodester, I can't upload an empty folder. 

Any idea?

**Comment by julien** [comment]
Same issue here, 
I create a tmp dir in my project and pushed it, but still can't upload there. 

I then tried to use /etc as the upload path but still throws an error
Error: EACCES, Permission denied '/etc/16f832feb4815ef031325849008e6560'

Any workaround?

**Comment by yocontra** [comment]
Put an empty file in your temp directory.

Worst case at the start of your app check for (your temp dir) and if it doesn't exist you can always fs.mkDir to create it
