### ISSUE TITLE
dont restart app?

### ISSUE THREAD

**Issue by thientruong** [nodester/nodester#125]
1.can you tell me?

[root@www2160uc ~]# nodester app restart truongnew
nodester info Attemping to restart app: truongnew
nodester ERROR false
[root@www2160uc ~]#
1.  my vps is a Centos . it had openssl. but when run ./configure, have a problem

Checking for openssl : not found
Checking for function SSL_library_init : not found
Checking for header openssl/crypto.h : not found
/root/node-v0.4.7/wscript:338: error: Could not autodetect OpenSSL support. Make sure OpenSSL development packages are installed. Use configure --without-ssl to disable this message.
[root@www2160uc node-v0.4.7]#

**Comment by chrismatthieu** [comment]
We need more information. Is nodester running in your own VPS?  Are you trying to install an ssl cert? As you can tell, I'm not sure where to begin.

**Comment by DanBUK** [comment]
Due to no updates on this issue I'm closing it off.
