### ISSUE TITLE
push fails after gitreset (.git/FETCH_HEAD: Permission denied)

### ISSUE THREAD

**Issue by JasonWoof** [nodester/nodester#126]
I did the following reset command (because pushing an "--amend"ed commit borked my app)

```
curl -u user:pass -X DELETE http://api.nodester.com/gitreset -d appname=xxx
```

That worked. But now when I push, I get this line:

```
remote: error: cannot open .git/FETCH_HEAD: Permission denied
```

(full transcript below) and my app is still running the old version (from before my push). Another call to the reset command above, and it's running the latest version.

Well, I guess that's all there is to it. I'll file a separate bug about the gitreset command not being documented on the site's API page.

Take care,   - Jason

P.S. Here's the full transcript:

```
> git push live
Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 302 bytes, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Syncing repo with chroot
remote: error: cannot open .git/FETCH_HEAD: Permission denied
remote:
remote: Checking ./.git/hooks/post-receive
remote: Attempting to restart your app: xxxx-xxxxxxxxxxxxxxxxxx
remote: App restarted..
remote:
remote:
remote:    \m/ Nodester out \m/
remote:
remote:
To ec2-user@nodester.com:/node/hosted_apps/[...].git
   xxx..xxx  master -> master
```

**Comment by chrismatthieu** [comment]
Do you get the same result if you use the CLI?  Nodester app gitreset app_name

**Comment by ghost** [comment]
I have exactly the same problem and I use the CLI.

When I got through the process of:
- git push nodester master
- nodester app gitreset <appname>
- nodester npm install <packages>
- nodester app restart <appname>

The code is updated but I get the same error the next time I try to push and have to go through the process again.

**Comment by DanBUK** [comment]
I've been working on permissions of the git folders and running app dirs. I will test this issue to see if it still remains.

**Comment by DanBUK** [comment]
Due to the file system changes in #143 this should be fixed with that as the only changes occurring to the git folder will be via git. Then a separate r/w area for the app to run inside.
