### ISSUE TITLE
restart fails

### ISSUE THREAD

**Issue by mattpage** [nodester/nodester#133]
got my coupon, created my app per email instructions.

when I run:

nodester info Attemping to restart app: ockley
nodester ERROR false

what did I do wrong?

**Comment by davglass** [comment]
Try running:

`nodester app logs`

**Comment by mattpage** [comment]
Thanks for the reply. I run it and get:

nodester ERROR [HTTP 404] Cannot GET /applogs

**Comment by ethagnawl** [comment]
I'm having the same problem; what was the fix?

**Comment by mattpage** [comment]
there wasn't one. I gave up and switched to heroku. Note: my app didn't deploy cleanly there, but the logs function didn't fail either. I was able to quickly figure out the problem once I got the logs. Hope this helps.

**Comment by ethagnawl** [comment]
Renaming my 'start' file server.js, instead of trying to use the API to tell nodester to use foo.js worked for me.
