### ISSUE TITLE
Add TCP support to Proxy.js

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester#134]
We would like to support TCP in addition to HTTP protocols.  It may be good timing to include this update in with the work required for Ticket #91 to update the proxy.js to include better support for web sockets.

**Comment by DanBUK** [comment]
How do you mean with this Chris? Something like listening on high port numbers and forwarding to tenants? On a different port than www tenant process as well? Once we start n processes on same host of tenant app, it will be auto set in process.env['http_port'], so custom tcp listening could be setup with env['tcp_port'] & ['http_port'] per instance, and all have same env['tcp_external_port']. Then the external port is enabled on the proxy host.

**Comment by yocontra** [comment]
Closed due to new proxy
