### ISSUE TITLE
Consider including express npm installation in all new apps

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester#135]
Express is becoming so popular that many apps have it always included.  People frequently forget to npm install express on their deployments and send support inquiries about their app not running.  There are pros and cons to this idea.

**Comment by DanBUK** [comment]
I think rather change app start/stop to sleep for 5 seconds, then do app log on their console, actually do that with all git pushes as well.

Therefore I'll make those changes :)

**Comment by yocontra** [comment]
Closing issue, seems to be resolved.
