### ISSUE TITLE
nodester official npm-installer

### ISSUE THREAD

**Issue by eldios** [nodester/nodester#136]
I _think_ that creating an installer for **nodester** which does the heavy work with a kind of _automagic-crossplatform-selfcorrecting_ process could be an **awesome idea**..
..and I'm so much in this idea that **_I'm actually making one_**.

As for now everything it's kinda a stub but it's progressing.. when I'll have the skeleton settled down you're all welcome to help me out.

The repo is still ready and it's in my profile --> [nodester_installer](https://github.com/eldios/nodester_installer)

**Comment by yocontra** [comment]
I created a package.json and a dependency installer. It's a start... the nodester 2.0 WILL have an npm installer

**Comment by yocontra** [comment]
Added to V2 roadmap

**Comment by eldios** [comment]
kewl.. I started talking again about this with Chris but the conversation ended without a conclusion.. let's say that I'm in, if you want my help

**Comment by yocontra** [comment]
If you look at V2 the installer is already almost done.

**Comment by eldios** [comment]
mm.. look a bit raw what's in the nodester repo, but if it actually works it's more than I produced.

**Comment by yocontra** [comment]
Nodester V2 is very organized and doesn't need much more than node, npm, redis, lxc, and a few of their dependencies installed before it's good to go. The npm installer just needs to run the ./install file which is very simple to set up

**Comment by eldios** [comment]
well actually no.. and at a wuick glance that script will either 1. not work 2. work bad .. anyway, as I already said as a start point it's just fine.. but a proper state-of-the-art installer is quite a lot more than that IMO.

**Comment by yocontra** [comment]
The whole point of V2 is simplicity. A state-of-the-art installer isn't needed because there shouldn't be more than 2 or 3 things that actually need to be installed to begin with. The whole V2 system will be kept within it's own folder and won't mess with anything on the system like the current model does

**Comment by yocontra** [comment]
Closing this as it doesn't seem relevant
