### ISSUE TITLE
Add a Password Reset feature to Nodester

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester#137]
We currently dont have a way to reset passwords when people forget them.

**Comment by marcosvm** [comment]
I'll work on that this weekend.

On Thu, Jun 2, 2011 at 9:25 PM, chrismatthieu
reply@reply.github.com
wrote:

**Comment by malaniz** [comment]
if anybody need help about this, please tell me

**Comment by marcosvm** [comment]
Closed by https://github.com/nodester/nodester/pull/166, waiting merge.
