### ISSUE TITLE
WARN bins installing to ....  outside PATH

### ISSUE THREAD

**Issue by huang47** [nodester/nodester#140]
Hi Dav,

I try to apply your examples (yui3+nodejs) and deploy to nodester

However I met some problems while installing npm packages

nodester npm WARN bins installing to /node/hosted_apps/huge/...................../.npm_bin, outside PATH

It works in my local machine but not in nodester, I also see there is another same issue recorded in #86
(https://github.com/nodester/nodester/issues/86)

any ideas?

Thanks
-Huge

**Comment by davglass** [comment]
The bins warning is nothing more than a warning, it's telling you that CLI apps (which are not directly supported by nodester) are installed outside of the path. But modules are still installed normally.

I just tested this and it works as expected:

https://gist.github.com/1017249

**Comment by DanBUK** [comment]
We have updated how npm's are installed now, the follow the current npm standard of cwd/node_modules/. Therefore this error no longer occurs.
