### ISSUE TITLE
Nodester.com is down and "nodester app create [appname]" is hanging

### ISSUE THREAD

**Issue by Gooseus** [nodester/nodester#141]
Hey guys, not sure if this is scheduled maintenance, but a bunch of stuff is down.  It doesn't look like I can get to my app logs either, though I am still able to access my app and push my app up.

**Comment by davglass** [comment]
The system is up and working. I can access the site, the CLI, the API and all 17 of my apps.

**Comment by Gooseus** [comment]
yeah, it's up for me too, it was down from probably 12am - 3 or 4 PDT
