### ISSUE TITLE
CPU/MEM usage of an app

### ISSUE THREAD

**Issue by Fabryz** [nodester/nodester#146]
This is actually a request, so: did you plan any feature about application statistics like showing the actual CPU/MEM usage?

I'm not already asking for blinking graphs, but at least some quick realtime numbers per user app =)

**Comment by yocontra** [comment]
You can use the 'nodeinfo' npm package for this
We're working on a global nodeinfo instance that will be up soon but you can run it in your app for the same stats/graphs
