### ISSUE TITLE
not able to create app using nodester-cli

### ISSUE THREAD

**Issue by buzzshiva** [nodester/nodester#151]
Can someone let me know why i'm not able to create using nodester.

version 
node 
version - 0.4.8

$ nodester app create testappnew
nodester info creating app: testappnew server.js
nodester info successfully created app testappnew to will run on port 10843 from
 server.js
nodester info run nodester app init testappnew to setup this app.

user@asd ~
$ nodester app init testappnew
nodester info initializing git repo for testappnew into folder testappnew
nodester info cloning the repo git clone ec2-user@nodester.com:/node/hosted_apps
/buzzshiva/2690-5307aa1ecd25dc24e5880eace6e5497a.git testappnew
nodester info clone complete
nodester info writing app data to config

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: EBADF, Bad file descriptor 'testappnew/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:483:15)
    at Object.writeApp (/usr/local/lib/node_modules/nodester-cli/lib/config.js:5
4:8)
    at /usr/local/lib/node_modules/nodester-cli/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at Socket.<anonymous> (child_process.js:179:12)
    at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:831:12)
    at EventEmitter._tickCallback (node.js:126:26)

user@asd ~
$
# 

$ npm info nodester-cli
npm WARN nodester-cli@0.2.0 package.json: 'modules' object is deprecated
npm WARN nodester-cli@0.2.1 package.json: 'modules' object is deprecated
{ name: 'nodester-cli',
  description: 'A CLI tool to allow interaction with the http://nodester.com/ pl
atform.',
  'dist-tags': { latest: '0.2.15' },
  versions:
   [ '0.1.0',
     '0.1.1',
     '0.1.2',
     '0.1.3',
     '0.1.5',
     '0.1.6',
     '0.1.7',
     '0.2.0',
     '0.2.1',
     '0.2.3',
     '0.2.4',
     '0.2.5',
     '0.2.6',
     '0.2.7',
     '0.2.8',
     '0.2.9',
     '0.2.10',
     '0.2.11',
     '0.2.12',
     '0.2.13',
     '0.2.14',
     '0.2.15' ],
  maintainers:
   [ 'DanBUK dan@f-box.org',
     'davglass davglass@gmail.com',
     'chrismatthieu chris@matthieu.us' ],
  time:
   { '0.1.0': '2011-01-31T16:26:42.334Z',
     '0.1.1': '2011-02-01T13:48:46.448Z',
     '0.1.2': '2011-02-01T13:58:42.336Z',
     '0.1.3': '2011-02-03T17:32:01.199Z',
     '0.1.5': '2011-02-05T21:06:12.443Z',
     '0.1.6': '2011-02-06T20:41:43.597Z',
     '0.1.7': '2011-02-08T13:08:37.065Z',
     '0.2.0': '2011-02-12T17:53:03.951Z',
$
     '0.2.3': '2011-02-14T11:42:12.845Z',
     '0.2.4': '2011-03-10T16:13:12.690Z',
     '0.2.5': '2011-03-10T16:26:37.174Z',
     '0.2.6': '2011-03-10T22:48:01.097Z',
     '0.2.7': '2011-03-11T13:52:15.657Z',
     '0.2.8': '2011-03-11T19:56:21.111Z',
     '0.2.9': '2011-03-13T19:29:23.301Z',
     '0.2.10': '2011-03-22T12:16:43.778Z',
     '0.2.11': '2011-03-22T13:45:16.739Z',
     '0.2.12': '2011-03-22T18:15:02.563Z',
     '0.2.13': '2011-05-02T19:24:23.523Z',
     '0.2.14': '2011-07-07T16:55:19.896Z',
     '0.2.15': '2011-07-07T17:04:12.947Z' },
  author: 'Daniel Bartlett dan@f-box.org (http://danb-uk.net/)',
  repository:
   { type: 'git',
     url: 'git://github.com/nodester/nodester-cli.git' },
  version: '0.2.15',
  homepage: 'http://nodester.com/',
  contributors:
   [ 'Dav Glass davglass@gmail.com',
     'Chris Matthieu chris@matthieu.us',
     'Abraham Williams 4braham@gmail.com' ],
  preferGlobal: 'true',
  bin: { nodester: 'bin/nodester.js' },
  main: './lib/commands.js',
  engines: { node: '*' },
  dependencies:
   { 'nodester-api': '0.1.8',
     colors: '0.3.0',
     iniparser: '1.0.1' },
  directories: { lib: './lib', bin: './bin' },
  files: '',
  dist:
   { shasum: '00b9d4343cac1f12bc9bf71d979b1cef6e294f95',
     tarball: 'http://registry.npmjs.org/nodester-cli/-/nodester-cli-0.2.15.tgz'
 },
  devDependencies: {} }
#

**Comment by DanBUK** [comment]
Do you have a passphrase on your ssh key? If you can you try using an ssh-agent to mean the phrase isn't required to be entered every time.

**Comment by buzzshiva** [comment]
No i didnt set any passphrase for the ssh public key. I used ssh-keygen,

**Comment by chrismatthieu** [comment]
I'm having the same issue. I ran ssh-agent as follows:

ssh-keygen -t rsa -f ~/.ssh/id_rsa -C "chris@matthieu.us"
Generating public/private rsa key pair.
/Users/christoffe/.ssh/id_rsa already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved 

when i tried to create a new app, I got the following response:

nodester app create clm007nodester info creating app: clm007 server.js
nodester ERROR [HTTP 401] No authentication data sent.

so i added my creds to the nodester CLI again like this:

 nodester user setup myusername mypassword

nodester info verifying credentials
nodester info user verified..
nodester info writing user data to config

now i can create apps (but I could before I ran ssh-agent too):

nodester app create clm007nodester info creating app: clm007 server.js
nodester info successfully created app clm007 to will run on port 10975 from server.js
nodester info run nodester app init clm007 to setup this app.

nodester app init clm007
nodester info initializing git repo for clm007 into folder clm007
nodester info cloning the repo git clone git@nodester.com:/node/git/topher/2822-a73b0e7317b70717b4530e858ab60883.git clm007
nodester info clone complete
nodester info writing app data to config

fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'clm007/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:483:15)
    at Object.writeApp (/usr/local/lib/node/.npm/nodester-cli/0.2.15/package/lib/config.js:54:8)
    at /usr/local/lib/node/.npm/nodester-cli/0.2.15/package/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)

**Comment by chrismatthieu** [comment]
npm info nodester-cli
npm info it worked if it ends with ok
npm info using npm@0.3.18
npm info using node@v0.4.9
{ name: 'nodester-cli',
  description: 'A CLI tool to allow interaction with the http://nodester.com/ platform.',
  'dist-tags': { latest: '0.2.15' },
  maintainers: 
   [ 'DanBUK dan@f-box.org',
     'davglass davglass@gmail.com',
     'chrismatthieu chris@matthieu.us' ],
  time: 
   { '0.1.0': '2011-01-31T16:26:42.334Z',
     '0.1.1': '2011-02-01T13:48:46.448Z',
     '0.1.2': '2011-02-01T13:58:42.336Z',
     '0.1.3': '2011-02-03T17:32:01.199Z',
     '0.1.5': '2011-02-05T21:06:12.443Z',
     '0.1.6': '2011-02-06T20:41:43.597Z',
     '0.1.7': '2011-02-08T13:08:37.065Z',
     '0.2.0': '2011-02-12T17:53:03.951Z',
     '0.2.1': '2011-02-13T11:58:41.785Z',
     '0.2.3': '2011-02-14T11:42:12.845Z',
     '0.2.4': '2011-03-10T16:13:12.690Z',
     '0.2.5': '2011-03-10T16:26:37.174Z',
     '0.2.6': '2011-03-10T22:48:01.097Z',
     '0.2.7': '2011-03-11T13:52:15.657Z',
     '0.2.8': '2011-03-11T19:56:21.111Z',
     '0.2.9': '2011-03-13T19:29:23.301Z',
     '0.2.10': '2011-03-22T12:16:43.778Z',
     '0.2.11': '2011-03-22T13:45:16.739Z',
     '0.2.12': '2011-03-22T18:15:02.563Z',
     '0.2.13': '2011-05-02T19:24:23.523Z',
     '0.2.14': '2011-07-07T16:55:19.896Z',
     '0.2.15': '2011-07-07T17:04:12.947Z' },
  author: 'Daniel Bartlett dan@f-box.org (http://danb-uk.net/)',
  repository: 
   { type: 'git',
     url: 'git://github.com/nodester/nodester-cli.git' },
  version: '0.2.15',
  homepage: 'http://nodester.com/',
  contributors: 
   [ 'Dav Glass davglass@gmail.com',
     'Chris Matthieu chris@matthieu.us',
     'Abraham Williams 4braham@gmail.com' ],
  preferGlobal: 'true',
  bin: { nodester: 'bin/nodester.js' },
  main: './lib/commands.js',
  engines: { node: '*' },
  dependencies: 
   { 'nodester-api': '0.1.8',
     colors: '0.3.0',
     iniparser: '1.0.1' },
  directories: { lib: './lib', bin: './bin' },
  files: '',
  dist: 
   { shasum: '00b9d4343cac1f12bc9bf71d979b1cef6e294f95',
     tarball: 'http://registry.npmjs.org/nodester-cli/-/nodester-cli-0.2.15.tgz' } }
npm ok

**Comment by buzzshiva** [comment]
$ ssh-keygen -t rsa -f ~/.ssh/id_rsa -C "learn.xyz@gmail.com"
Generating public/private rsa key pair.
/home/user/.ssh/id_rsa already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/user/.ssh/id_rsa.
Your public key has been saved in /home/user/.ssh/id_rsa.pub.
The key fingerprint is:
82:7e:46:32:7d:f6:ca:4f:35:89:05:c8:41:7f:8e:68 learn.xyz@gmail.com
The key's randomart image is:
+--[ RSA 2048]----+
|       ooo.      |
|        o. .     |
|          . o    |
|     o   . \* .   |
|    + + E o =    |
|   . + = . . .   |
|    . o   o      |
|     o . o       |
|        o..      |
+-----------------+

nodester info verifying credentials
nodester info user verified..
nodester info writing user data to config

user@asd ~
$ nodester app create clm700
nodester info creating app: clm700 server.js
nodester info successfully created app clm700 to will run on port 11051 from ser
ver.js
nodester info run nodester app init clm700 to setup this app.

user@asd ~
$ nodester app init clm700
nodester info initializing git repo for clm700 into folder clm700
nodester info cloning the repo git clone git@nodester.com:/node/git/buzzshiva/28
98-16f8b933d9abbf644efe651e64104739.git clm700
The authenticity of host 'nodester.com (50.16.203.53)' can't be established.
RSA key fingerprint is a1:64:54:7c:9b:73:9f:22:a8:95:44:4f:7b:25:15:68.
Are you sure you want to continue connecting (yes/no)? yes
nodester info clone complete
nodester info writing app data to config

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: EBADF, Bad file descriptor 'clm700/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:483:15)
    at Object.writeApp (/usr/local/lib/node_modules/nodester-cli/lib/config.js:5
4:8)
    at /usr/local/lib/node_modules/nodester-cli/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at Socket.<anonymous> (child_process.js:172:12)
    at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:831:12)
    at EventEmitter._tickCallback (node.js:126:26)

user@asd ~
$ nodester info nodester-cli
nodester info Gathering information about: nodester-cli
nodester ERROR [HTTP 400] failure - app not found (nodester-cli)

user@asd ~
$ nodester info nodester-cli
nodester info Gathering information about: nodester-cli
nodester ERROR [HTTP 400] failure - app not found (nodester-cli)

$ssh-agent 

$ nodester app init clm700
nodester info initializing git repo for clm700 into folder clm700
nodester info cloning the repo git clone git@nodester.com:/node/git/buzzshiva/28
98-16f8b933d9abbf644efe651e64104739.git clm700
nodester info clone complete
nodester info writing app data to config
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR [HTTP 500] An error has occurred: {"stack":"Error: Parse Error\n
   at Socket.ondata (http.js:1227:22)\n    at Socket._onReadable (net.js:683:27)
\n    at IOWatcher.onReadable [as callback](net.js:177:10)","message":"Parse Er
ror","bytesParsed":9}

app  got created why it has thrown   "ERROR [HTTP 500] An error has occurred: {"stack":"Error: Parse Error\n
   at Socket.ondata (http.js:1227:22)\n    at Socket._onReadable (net.js:683:27)
\n    at IOWatcher.onReadable [as callback](net.js:177:10)","message":"Parse Er
ror","bytesParsed":9}
"

**Comment by DanBUK** [comment]
$ nodester info nodester-cli 
^^ That's incorrect unless you've an app on nodester called nodester-cli

$ nodester info clm700

I am investigating why the app isn't starting.

**Comment by DanBUK** [comment]
I have restarted your application, I'm not sure what happened there. Further pushes will restart your app also.

**Comment by chrismatthieu** [comment]
i am still having this problem.  I upgraded to node 0.4.9 and reinstalled npm nodester-cli -g

nodester app create cm1000
nodester info creating app: cm1000 server.js
nodester info successfully created app cm1000 to will run on port 11084 from server.js
nodester info run nodester app init cm1000 to setup this app.
topher:src topher$ nodester app init cm1000
nodester info initializing git repo for cm1000 into folder cm1000
nodester info cloning the repo git clone git@nodester.com:/node/git/topher/2931-6e9839a437e6fdcd195832dd41dec9c3.git cm1000
nodester info clone complete
nodester info writing app data to config
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR [HTTP 500] An error has occurred: {"stack":"Error: Parse Error\n    at Socket.ondata (http.js:1227:22)\n    at Socket._onReadable (net.js:683:27)\n    at IOWatcher.onReadable [as callback](net.js:177:10)","message":"Parse Error","bytesParsed":9}

**Comment by DanBUK** [comment]
Ahe, /click/ It makes bad sense, initial commit starts app, api when cli starts app says 500 already running. But doesn't due to parse fail. Know where to look for this.

**Comment by banacorn** [comment]
i got exactly the same thing, too

**Comment by DanBUK** [comment]
I have updated the API to deal with things more nicely, please re-test & close if it's fixed!

**Comment by chrismatthieu** [comment]
My issue still exists.  Here's the details:

npm install nodester-cli -g
npm info it worked if it ends with ok
npm info using npm@0.3.18
npm info using node@v0.4.9
npm info preinstall nodester-cli@0.2.19
npm info install nodester-cli@0.2.19
npm info postinstall nodester-cli@0.2.19
npm info predeactivate nodester-cli@0.2.19
npm info deactivate nodester-cli@0.2.19
npm info postdeactivate nodester-cli@0.2.19
npm info preactivate nodester-cli@0.2.19
npm info activate nodester-cli@0.2.19
npm info postactivate nodester-cli@0.2.19
npm info build Success: nodester-cli@0.2.19
npm ok
christoffe:src christoffe$ nodester user setup topher my_password
nodester info verifying credentials
nodester info user verified..
nodester info writing user data to config
christoffe:src christoffe$ nodester user setkey
nodester info sending sshkey: /Users/christoffe/.ssh/id_rsa.pub
nodester info ssh key successfully sent
christoffe:src christoffe$ nodester app create chrisrox
nodester info creating app: chrisrox server.js
nodester info successfully created app chrisrox to will run on port 11203 from server.js
nodester info run nodester app init chrisrox to setup this app.
christoffe:src christoffe$ nodester app init chrisrox
nodester info initializing git repo for chrisrox into folder chrisrox
nodester info cloning the repo git clone git@nodester.com:/node/git/topher/3050-f29e2e5ed1d4f031f13ee7a7213e658b.git chrisrox
nodester info clone complete
nodester info writing app data to config

fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'chrisrox/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:483:15)
    at Object.writeApp (/usr/local/lib/node/.npm/nodester-cli/0.2.19/package/lib/config.js:54:8)
    at /usr/local/lib/node/.npm/nodester-cli/0.2.19/package/lib/app.js:283:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)
christoffe:src christoffe$ 

I'm not sure if it makes a difference but my RSA key on this mac is symlinked to another file...

**Comment by chrismatthieu** [comment]
Received email from a Nodester user today with the same problem:

Nathan Cartwright to Chris

Hi and thanks - just wanted to note that I cannot seem to get this to work on my end.  Following the instructions was fine until step 4, when I got this error message:
Error: EBADF, Bad file descriptor 'dragnshine/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:483:15)
    at Object.writeApp (/usr/lib/node_modules/nodester-cli/lib/config.js:54:8)
    at /usr/lib/node_modules/nodester-cli/lib/app.js:283:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at Socket.<anonymous> (child_process.js:172:12)
    at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:831:12)
    at EventEmitter._tickCallback (node.js:126:26)

additional info: 
error while attempting to create app named 'dragnshine' using 'terminal' in ubuntu 10.04 virtualbox guest hosted on Windows 7 x64.  

Any attempts to create any new applciations via nodester app create my_app results in:
nodester info creating app: my_app server.js
nodester ERROR failure

I'll try from my dedicated linux dev box (rather than vbox guest on this pc) to see if I have any better luck but thought I'd go ahead and shoot you this email.

Thanks,

**Comment by chrismatthieu** [comment]
This having this problem. For fun I ran the nodester init using sudo and received more information back from the request:

sudo nodester app init mofo
Password:

nodester info initializing git repo for mofo into folder mofo
nodester info cloning the repo git clone git@nodester.com:/node/git/topher/3234-137db17a5ef9c9fe8da2bbfd55484fc7.git mofo
The authenticity of host 'nodester.com (50.16.203.53)' can't be established.
RSA key fingerprint is a1:64:54:7c:9b:73:9f:22:a8:95:44:4f:7b:25:15:68.

Are you sure you want to continue connecting (yes/no)? yes
Warning: the RSA host key for 'nodester.com' differs from the key for the IP address '50.16.203.53'
Offending key for IP in /var/root/.ssh/known_hosts:1

Are you sure you want to continue connecting (yes/no)? yes
nodester info clone complete
nodester info writing app data to config
nodester info writing app files
nodester info processing the initial commit
Warning: the RSA host key for 'nodester.com' differs from the key for the IP address '50.16.203.53'
Offending key for IP in /var/root/.ssh/known_hosts:1
Matching host key in /var/root/.ssh/known_hosts:2
Are you sure you want to continue connecting (yes/no)? yes
nodester info attemping to start the new app.
nodester ERROR [HTTP 408] failure - application already running.

christoffe:src christoffe$ cd mofo
-bash: cd: mofo: Permission denied

I think this is an issue with the RSA key.  1 Macbook works for me while the other does not - even after running nodester user setkey and getting a positive response on the key update.  The only difference in the machines as far as i can tell is the failing one uses a symlink on the rsa_id file.  I'll test it without the symlink today.

**Comment by chrismatthieu** [comment]
So much for the symlink theory.  I deleted my symlinks and renamed my key files to id_rsa and id_rsa.pub but it resulted in the same error.

**Comment by chrismatthieu** [comment]
FYI - I setup a new Nodester account on my MBA with the key problem and I am getting the same results.

**Comment by yocontra** [comment]
What operating system is everyone running?

**Comment by chrismatthieu** [comment]
snow leopard.

**Comment by yocontra** [comment]
Bug has been fixed in my latest commit. For some reason on some people's computers writing a file to a non-existent folder would error out instead of creating the folder. Just added a line to check and create the folder before writing

Let me know if it doesn't work for anyone
