### ISSUE TITLE
Curse of EBADF on 'nodester create app'

### ISSUE THREAD

**Issue by martypdx** [nodester/nodester#152]
I know the nodester issue list is peppered with this problem, but still wanted to pass on my details for the many ways it's not working.

Details:

Running under cygwin.

With passphrase key:
-  tried both as-is and with creating `pbcopy` replace '+' file
-  using an agent via: `ssh-agent bash --login -i`

Create a seperate key with no passphrase:
-  tried both as-is and with creating `pbcopy` replace '+' file

**Comment by DanBUK** [comment]
Have you tried using native windows node.exe ? Rather than in cygwin?

**Comment by martypdx** [comment]
No, I was waiting for it (node on windows) to mature a bit first

**Comment by yocontra** [comment]
I fixed this in the CLI as far as I know, closing this. Let me know if it's still broken

**Comment by martypdx** [comment]
Yes, CLI works work with security now. However, doing an app init on existing project not a good idea :(
