### ISSUE TITLE
Flash Socket Policy Issue with Socket.io

### ISSUE THREAD

**Issue by abdulmueid** [nodester/nodester#153]
I wrote a simple chat app using Socket.io. When accessing the app, it cannot establish a WebSocket or FlashSocket connection and always falls back to XHR-Polling.

I ran the same app locally and it connected using websockets just fine.

Firebug console reports that following error:
[WebSocket] cannot connect to Web Socket server at ws://chatr.nodester.com:80/socket.io/1/flashsocket/2125152068727591007 (SecurityError)
make sure the server is running and Flash socket policy file is correctly placed
http://chatr.nodester.com/socket.io/socket.io.js

Browser: Firefox 5
Operating System: Ubuntu 11.04

If you need more details, I will be more than willing to help.

**Comment by DanBUK** [comment]
Tested this just now, http://dan.nodester.com/ is set to transports websocket and flashsocket only. Works in FF, Safari & Chrome.

**Comment by abdulmueid** [comment]
Firefox 5 console output:
[WebSocket] bad response: HTTP/1.0 500 Internal Server Error
http://dan.nodester.com/socket.io/socket.io.js
Line 2789

Chrome/Chromium console output:
Unexpected response code: 500

Tested in Windows and Linux.
