### ISSUE TITLE
nodester user setup, Domain name not found

### ISSUE THREAD

**Issue by DJWalker** [nodester/nodester#155]
Hello. I'm trying out your service to experiment with node.js, but am having a problem getting started.

I have created user, but when I try to run:
nodester user setup <my username> <my password>

it fails with the following message:
nodester info verifying credentials
nodester ERROR ENOTFOUND, Domain name not found

I'm using Cygwin.

Any suggestions?

**Comment by yocontra** [comment]
Have you tried using the new Node/NPM for Windows? I'm going to guess the issue lies with Cygwin

**Comment by DJWalker** [comment]
Thanks for the reply. That might be the case, but the problem seems to have gone away after I deleted and recreated the user through curl.
