### ISSUE TITLE
nodester-cli logs returning a 500

### ISSUE THREAD

**Issue by blindsey** [nodester/nodester#159]
bash$ nodester app logs
nodester ERROR HTTP Error 500

Here's the tcp dump:

```
0x0030:  033a ba33 7b22 7375 6363 6573 7322 3a66  .:.3{"success":f
0x0040:  616c 7365 2c22 6572 726f 7222 3a22 4661  alse,"error":"Fa
0x0050:  696c 6564 2074 6f20 7265 6164 2065 7272  iled.to.read.err
0x0060:  6f72 206c 6f67 2e22 7d0a 0d0a 300d 0a0d  or.log."}...0...
```

**Comment by DanBUK** [comment]
Yep sorry about this. There were some server side issues with the logging mechanism that I had to disable. I will be bringing logs back online later on today.

**Comment by DanBUK** [comment]
This is finally fixed!

**Comment by gtramontina** [comment]
sad to report, but I'm still getting a 500 even after updating nodester-cli. :-(
From the tcpdump I can see it is a Timeout.

**Comment by DanBUK** [comment]
Ah can you please restart your application, that will mean it uses the new logging mech.

**Comment by gtramontina** [comment]
It worked. Thanks a lot!
