### ISSUE TITLE
NPM Modules Install, Update, and Uninstall should support string of modules to avoid making the call several times.

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester#16]
curl -X POST -u "testuser:123" -d "appname=a&action=install&package=express,jade,require" http://api.nodester/appnpm

**Comment by DanBUK** [comment]
Been thinking about a package.json usage pattern. So when an app is deployed all the relevant npm's get installed before it starts. I think this would simplify things...

Thoughts anyone?

**Comment by davglass** [comment]
Actually, you don't need to put the commas in. Just put spaces and it should work fine:

curl -X POST -u "testuser:123" -d "appname=a&action=install&package=express jade colors express-extras" http://api.nodester/appnpm

I'm doing this in the command line rewrite I did..

Gist of the output of: `nodester npm install express jade colors

https://gist.github.com/5950dfdcee306c18f2d2

**Comment by chrismatthieu** [comment]
Nice job!
