### ISSUE TITLE
git push Permission denied (publickey).

### ISSUE THREAD

**Issue by kmiyashiro** [nodester/nodester#160]
Can't push or set new key.

```
bash-3.2$ git push
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
bash-3.2$ nodester user setkey
nodester info sending sshkey: /Users/Kelly/.ssh/id_rsa.pub
nodester ERROR socket hang up
```

**Comment by DanBUK** [comment]
Hi kmiyashiro, Can you please check that you are using the updated git path? We had some migrations last week.
$ nodester app info <appname> will show you the current repo uri.

**Comment by kmiyashiro** [comment]
info gitrepo: git@nodester.com:/node/git/kelly/2779-0fefce8f9e37ca546aa009b753d55cfa.git

**Comment by DanBUK** [comment]
I can see why your app is not running you are using app.listen(3000); You should be using app.listen(process.env['app_port']). 

Can you please check that your git checkout is using the correct remote:
$ git remote -v

1 If the git remote isn't git@nodester.com:/node/git/kelly/2779-0fefce8f9e37ca546aa009b753d55cfa.git then update it ( git remote update origin git@nodester.com:/node/git/kelly/2779-0fefce8f9e37ca546aa009b753d55cfa.git )
2 Try git push
3 If it still isn't working then can you please re-try submitting your key.
4 Wait 60 seconds, keys are deployed at most once per 60s.
5 Try push
3 If it fails please gist the public key along with any other output that is pertinent.

**Comment by DanBUK** [comment]
Is this issue resolved kmiyashiro?

**Comment by kmiyashiro** [comment]
Yep, sorry!
