### ISSUE TITLE
App error: Connection Refused

### ISSUE THREAD

**Issue by kmiyashiro** [nodester/nodester#161]
`An error has occurred: {"stack":"Error: ECONNREFUSED, Connection refused\n    at Socket._onConnect (net.js:601:18)\n    at IOWatcher.onWritable [as callback] (net.js:186:12)","message":"ECONNREFUSED, Connection refused","errno":111,"code":"ECONNREFUSED","syscall":"connect"}`

http://yelpvis.nodster.com

Might be related to #160?

**Comment by fchasen** [comment]
I am also getting the same error

taboo.nodster.com

**Comment by banacorn** [comment]
: (

**Comment by DanBUK** [comment]
kmiyashiro - your app.js is calling .listen(8080), you can see your currently allocated port on nodester app info yelpvis, alternatively for conveniece we have process.env['app_port'] to allow it to be auto set. (This will be needed in the future for multi process apps..) so I recommend you call .listen(process.env['app_port'])

fchasen - Your app.js is calling .listen(11054) when your app should be 11055 :) I still recommend as above, process.env['app_port'] is the safest way :)

**Comment by cosmospostman** [comment]
Hmmm I'm getting the same error after trying Dan's fix :'(
cpchess.nodester.com

**Comment by DanBUK** [comment]
Your app is setup to look for an initial file of server.js, yet I don't see that in your app. I only see an app.js. Therefore it's failing to start. Either rename the file in git or update your app setting so it searches for app.js to start the app.

**Comment by cosmospostman** [comment]
Thanks for the quick reply Dan.  Renamed app.js as server.js in git, but to
no avail.  This app was working until about a fortnight ago, have there been
any changes to the nodester stack that could've broken it?

**Comment by DanBUK** [comment]
We did have some chroot changes and migrations, that might have affected it.

Please check the output of: nodester app logs cpchess It's having issues with a folder called public that I cannot see :/

**Comment by cosmospostman** [comment]
I was trying to write to a file in /public, but I've commented out those
sections so there are no longer any errors in the log.  Still can't connect
to the app though :s

nodester app logs cpchess
New PID: 33130
chroot_runner
chroot_runner

**Comment by DanBUK** [comment]
I can connect to your app, just I get a blank page.

I think "var file = new nodeStatic.Server('./public', {" will be catching GET / and failing to render any page?

**Comment by cosmospostman** [comment]
Got it.  Replaced './public' with __dirname+'/public'.  That section was
lifted from the documentation from node-static.  Seems strange to me that
the recent changes to Nodester broke this when it still works fine on my
local machine.  Regardless, I really do appreciate your help with this silly
one-liner.  Thankyou Dan!

**Comment by banacorn** [comment]
node-static!
thanks a lot, I was fighting with the path name last night and i got 404 all the time.

Is there any documentation about the recent changes like this or the previous process.env['app_port'] coz they are killing me?

**Comment by DanBUK** [comment]
I'm going to write a doc describing the app env whilst it is running.

**Comment by DanBUK** [comment]
The start of a doc! https://github.com/nodester/nodester/wiki/App-Environment

**Comment by fchasen** [comment]
Thanks guys. I woke up and you guys had figured everything wrong with mine out. (other than a couple of missing dependancies)

I was also using a "./" path, though my app was running at server.js

**Comment by banacorn** [comment]
love ya <3
