### ISSUE TITLE
why admin.nodester.com not working.

### ISSUE THREAD

**Issue by buzzshiva** [nodester/nodester#162]
this is what i'm getting... 

An error has occurred: {"stack":"Error: ECONNREFUSED, Connection refused\n    at Socket._onConnect (net.js:601:18)\n    at IOWatcher.onWritable [as callback](net.js:186:12)","message":"ECONNREFUSED, Connection refused","errno":111,"code":"ECONNREFUSED","syscall":"connect"}

**Comment by DanBUK** [comment]
http://admin.nodester.com/ is actually an app run by rowoot not actually a "nodester" ran app, and it looks like it has some template issues. It is running now but throwing Internal Server Error.
