### ISSUE TITLE
How to push new files to git repo

### ISSUE THREAD

**Issue by buzzshiva** [nodester/nodester#163]
I'm not able to push new files to below repo.

git@nodester.com:/node/git/buzzshiva/2900-c4679e71e4c6842361505c67399d7a6b.git

user@asd ~/testApp
$ nodester app info apptest
nodester info Gathering information about: apptest
nodester info apptest on port 11053 running: true (pid: 21248)
nodester info gitrepo: git@nodester.com:/node/git/buzzshiva/2900-c4679e71e4c6842
361505c67399d7a6b.git
nodester info appfile: server.js

**Comment by DanBUK** [comment]
What is the output from a 'git push' from you local checkout of the app's repo?

**Comment by buzzshiva** [comment]
It works fine ... 

but if i do the same add / commit / push of local checkout copy using windows based git... it throws ...

" the remote hung up unexpectedly"

screenshot of error:
http://imageupload.org/?d=621227B11 

$ git show
commit f823b780aafca10bea35729d68fa31d0ea960b69
Author: unknown <user@.(none)>
Date:   Tue Jul 26 10:53:24 2011 +0530

```
new test
```

diff --git a/server.js b/server.js
index 0f6a0a3..8494fdf 100644
--- a/server.js
+++ b/server.js
@@ -1,5 +1,5 @@
 var http = require('http');
 http.createServer(function (req, res) {
   res.writeHead(200, {'Content-Type': 'text/plain'});
-  res.end('Hello World\nApp (clm700) is running..');
-  res.end('Hello World.......\nApp (clm700) is running..');
  }).listen(11051);

**Comment by DanBUK** [comment]
I don't know this git client, does it support ssh keys? If so are you using them?

**Comment by DanBUK** [comment]
buzzshiva Does push work using git from the command line?

**Comment by buzzshiva** [comment]
yes it does works ... the push from command line 

git push
