### ISSUE TITLE
Websocket and Flashsocket not working with Socket.io

### ISSUE THREAD

**Issue by abdulmueid** [nodester/nodester#164]
My socket.io based application only has Websocket and Flashsocket enabled.

Firebug console in Firefox shows this error:

```[WebSocket] bad response: HTTP/1.0 500 Internal Server Error
http://shuffle.nodester.com/socket.io/socket.io.js
Line 2789

``````
The developer console in Chrome shows this error:
```Unexpected response code: 500
``````

My guess is that opening a connection to the WebSocket (Native Browser or via Flashsocket) returns error code 500.

**Comment by DanBUK** [comment]
I'm not getting the same 500, I get a pending WebSocket. I am trying to debug this issue and will update it further shortly.

**Comment by insidewhy** [comment]
Here WebSocket works but FlashSocket does not. I don't receive the "connect" event and the nodejs terminal logs this as the last thing:

```
debug - served static /static/flashsocket/WebSocketMain.swf
```

Firebug shows my browser receives the swf.

**Comment by jeffbaier** [comment]
Is this still an issue? I'm trying to use websockets with SockJS in my nodester app. It fails over to xhr-streaming. 

If I manually try to force websockets, it never connects. It stays in readySate 0 for a while, then goes to 3 and is closed.

**Comment by insidewhy** [comment]
I gave up on it, maybe it was fixed in the interim.

**Comment by yocontra** [comment]
Our new proxy should fix this issue. Closing now
