### ISSUE TITLE
NowJS/Socket.IO issue

### ISSUE THREAD

**Issue by ttaiyo** [nodester/nodester#168]
First time to submit a ticket/bug report of any sort so please bear with me.

My app (http://webteam-chat.nodester.com) was working fine until a few weeks ago. Deleting and re-creating the app didn't help.

Accessing my app shows the following error:

> An error has occurred: {"stack":"Error: ECONNREFUSED, Connection refused\n    at Socket._onConnect (net.js:601:18)\n    at IOWatcher.onWritable [as callback](net.js:186:12)","message":"ECONNREFUSED, Connection refused","errno":111,"code":"ECONNREFUSED","syscall":"connect"}

To be clear, I have the port setup as: **app.listen(process.env["app_port"]);** 

I have the following modules installed: **now** **express** **jade** **stylus**, and **"nodester npm list"** shows the following:

> nodester ├─┬ express@2.4.3 
> nodester │ ├── connect@1.6.0 
> nodester │ ├── mime@1.2.2 
> nodester │ └── qs@0.3.0 
> nodester ├── jade@0.13.0 
> nodester ├─┬ now@0.7.0 
> nodester │ ├── node-proxy@0.4.0 
> nodester │ └─┬ socket.io@0.7.7 
> nodester │   ├── policyfile@0.0.3 
> nodester │   └─┬ socket.io-client@0.7.4 
> nodester │     └── uglify-js@1.0.3 
> nodester └─┬ stylus@0.13.7 
> nodester   ├─┬ connect@1.6.0  extraneous
> nodester   │ ├── UNMET DEPENDENCY mime >= 0.0.1
> nodester   │ └── UNMET DEPENDENCY qs >= 0.0.6
> nodester   ├── cssom@0.2.0 
> nodester   └── growl@1.1.0

And **"nodester app logs"** shows the following:

> New PID: 40815
> chroot_runner
> chroot_runner
> Express server listening on port 11103
> 
> node.js:134
> 
> throw e; // process.nextTick error, or 'error' event on first tick
> 
> ^
> 
> Error: Cannot find module 'socket.io-client'
>     at Function._resolveFilename (module.js:317:11)
>     at Function._load (module.js:262:25)
>     at require (module.js:346:19)
>     at Object.<anonymous> (/app/node_modules/now/node_modules/socket.io/lib/socket.io.js:12:14)
>     at Module._compile (module.js:402:26)
>     at Object..js (module.js:408:10)
>     at Module.load (module.js:334:31)
>     at Function._load (module.js:293:12)
>     at require (module.js:346:19)
>     at Object.<anonymous> (/app/node_modules/now/node_modules/socket.io/index.js:8:18)

The differences between my local setup and Nodester are:
- I have **now@0.7.3** compared to **now@0.7.0** on Nodester
- On my localhost **socket.io@0.7.7** has the following sub-modules: **bison@1.1.1** **redis@0.6.0** that Nodester doesn't install

Am I having this problem because Nodester installs an older version of NowJS?

**Comment by DanBUK** [comment]
Sorry about the registry for nodester npm's being a little out of sync. I'm just working on that currently.

You can also I think npm install socket.io-client onto your nodester app to fix.

**Comment by ttaiyo** [comment]
I installed the missing modules separately and it's working now :)

Thanks for you help.
