### ISSUE TITLE
Going to try my first app, again, but is nodester up?

### ISSUE THREAD

**Issue by egilchri** [nodester/nodester#169]
When I do:

 curl http://nodester.com/status

I get

An error has occurred: {"stack":"Error: socket hang up\n    at Socket.<anonymous> (http.js:1286:45)\n    at Socket.emit (events.js:64:17)\n    at Array.0 (net.js:831:12)\n    at EventEmitter._tickCallback (node.js:126:26)","message":"socket hang up"}

Does this mean I should try back later?

**Comment by DanBUK** [comment]
Hi egilchri,

There was an issue with our API talking to out CouchDB, this problem was actually fixed on Saturday. Sorry I forgot to update this ticket.

Cheers,

DanB.
