### ISSUE TITLE
Ensure all apps are lower case when matched...

### ISSUE THREAD

**Issue by DanBUK** [nodester/nodester#17]

**Comment by chrismatthieu** [comment]
are you referring to the match app subdomain lookup in the proxy.js?

**Comment by DanBUK** [comment]
I'm referring to the myapp.post(/app upon app creation, we should force to lowercase to ensure that only ever there is one subdomain a. or A.

Of course sub dom matching in proxy should probably all be str.toLowerCase() as well :)

**Comment by chrismatthieu** [comment]
added toLowerCase to proxy and app for subdomains. Closed by b7afd961725706e132205ed40409d7ba8d633e65.
