### ISSUE TITLE
Can't initiate app

### ISSUE THREAD

**Issue by ghost** [nodester/nodester#170]
I am able to create new apps but when I try to initiate them, I get an error as seen below:

```
>>> nodester app create ecom46

nodester info creating app: ecom46 server.js
nodester info successfully created app ecom46 to will run on port 11143 from server.js
nodester info run nodester app init ecom46 to setup this app.

>>> nodester app init ecom46

nodester info initializing git repo for ecom46 into folder ecom46
nodester info cloning the repo git clone git@nodester.com:/node/git/idophir/2990-aff449452ea1d86dc7bf1139c289c04a.git ecom46
nodester info clone complete
nodester info writing app data to config
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR [HTTP 500] An error has occurred: {"stack":"Error: Parse Error\n    at Socket.ondata (http.js:1227:22)\n    at Socket._onReadable (net.js:683:27)\n    at IOWatcher.onReadable [as callback] (net.js:177:10)","message":"Parse Error","bytesParsed":9}
```

Using nodester 0.2.19 on OSX Lion

**Comment by DanBUK** [comment]
Please re-test this issue I have updated the API's response codes to work again :)

**Comment by mftaher** [comment]
I am also having same problem except the error is different then the one above.  ERROR [HTTP 500] An error has occurred: {"stack":"Error: socket hang up\n at Socket.<anonymous> (http.js:1286:45)\n at Socket.emit (events.js:64:17)\n at Array.0 (net.js:831:12)\n at EventEmitter._tickCallback (node.js:126:26)","message":"socket hang up"}

**Comment by ghost** [comment]
Initializing the app works now but I still get an "nodester ERROR [HTTP 408] failure - application already running."
You'd probably want to fix it to make the experience more pleasant.

That's for the great service!

**Comment by ghost** [comment]
Sorry, maybe @mftaher wants to continue his problem on this thread.

BTW, when I try to delete an app I get the "socket hang up" error described by @mftaher. It looks like the app is deleted but I get that error every time.

**Comment by DanBUK** [comment]
@mftaher What is your username on nodester.com along with the application name? Kinda hard for me to help without knowing that ;)

**Comment by DanBUK** [comment]
@idophir2 I'll double check the delete call.

**Comment by mftaher** [comment]
application: tawkee, tawkee_server, chat_server no matter which I try I have always had the same error as written in my previous post. Even if I try to delete the app I get the same error.

thanks,

**Comment by DanBUK** [comment]
mftaher, you appear to have deleted all of the apps you mention, so I cannot look into what is causing the problem. Can you create an app and then let me know the app name.

**Comment by mftaher** [comment]
the problem I was having is to initiate an app, every time I would try to initiate I got that error, then I try delete I get the same error, I'm not sure if those apps were created.

Anyways I tried this morning I was able to setup an app 'ftaher'. I still get the same error when try to delete

**Comment by funkytek** [comment]
can you guys make sure you update to the latest nodester cli - $ npm install -g nodester-cli

**Comment by ghost** [comment]
Cool.
Version 0.2.34 works great when creating and deleting apps.
Thanks!
