### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by gtramontina** [nodester/nodester#171]
I'm using stylus to write my CSS... since a few days ago, I started getting the following error when serving css
Error: EACCES, Permission denied '/app/lib/public/stylesheets/index.css'

If I try to reach 'index.styl' it works fine.
It seems that I'm having trouble serving generated files.

**Comment by DanBUK** [comment]
Since we have migrated to newer chroot, your node process runs with base os/node at / and your application at /app/

Can you try using __dirname now for your paths relative to your initial script?

**Comment by gtramontina** [comment]
Couldn't get it work yet. :-/
Would you mind taking a look at https://github.com/gtramontina/Writeboard to help me out with this?
All my static stuff were already being served like "#{__dirname}/public". I changed the way I require initial stuff. Instead of "./lib/server", I unshifed "__dirname" and required "lib/server".

EDIT: just a reminder, the CSS files are compiled upon request and then served. They live together with the .styl files. Can this issue be related to the user who generated these files? I mean, the generated .css files are owned by the user who has started the application?

Thanks a lot!

**Comment by DanBUK** [comment]
So the application runs with the rights to write to the filesystem, although app files in the git clone will be uid git and gid app.

So it will be able to generate files ok. (And read them back)

Has the error changed since you updated the path?

**Comment by gtramontina** [comment]
No, it didn't change... I'm still getting Permission Denied. o_O
This is weird... The files are in the exact same place, i.e. the same way I'm able to read the .styl files, I should be able to read the .css.

I'll add a few console.logs to make sure the files are being generated correctly... 
Is there a simple way I can reproduce Nodester's environment locally? So that I don't have to keep on publishing every time?

**Comment by tracend** [comment]
I agree that there seems to be a permissions issue for the apps modifying the filesystem. 

I was trying to make my app "emotiglobe" read and write json files and ultimately had to comment out that code. 

If you're interested, you can have a look at how I'm using the fs module at the repo: 
https://github.com/makesites/emotiglobe

**Comment by gtramontina** [comment]
Couldn't make it work... I tried reading the CSS files to make sure they exist, but I'm getting: 
Error: ENOENT, No such file or directory '/app/lib/public/stylesheets/writeboard.css'

It would be fine for the first time because the file hadn't been generated yet, but it should work fine from the 2nd try.
I'm also having problems serving my JavaScripts, I mean, I'm also compiling .coffee to .js...

Is the new chroot with file writing permissions working correctly?

Thanks a lot for the support, btw.

**Comment by gtramontina** [comment]
Any update on this?

**Comment by yocontra** [comment]
Is this still an issue? I'd be glad to look into it

**Comment by gtramontina** [comment]
Yep, I've just tried and my app is not being able to write its compiled resources to the disk:
*.styl -> *.css
*.coffee -> *.js

Let me know if you need more info.
Thanks

**Comment by yocontra** [comment]
/app/lib/public/stylesheets/

```
total 60
drwxr-xr-x 1 git git  4096 Aug  1 21:59 .
drwxr-xr-x 1 git git  4096 Jul 27 00:18 ..
-rw-r--r-- 1 git git  1044 Jul 27 00:18 about.styl
-rw-r--r-- 1 git git   663 Jul 27 00:18 alpha_tag.styl
-rw-r--r-- 1 git git 26904 Aug  1 21:59 GTramontina.ttf
-rw-r--r-- 1 git git   871 Aug  1 21:59 index.styl
-rw-r--r-- 1 git git   314 Jul 27 00:18 layout.styl
drwxr-xr-x 1 git git  4096 Jul 27 00:18 lib
-rw-r--r-- 1 git git  1789 Jul 27 00:18 writeboard.styl
```

Nothing looks out of the ordinary... looking at server.coffee it seems you do quite a bit of debugging. Can you send me full logs including the debugging from stylusCompiler()?

**Comment by gtramontina** [comment]
Yeah, I added some logs to help us debugging this. I don't have a complete log but this is what I got from the last attempt:

[-_-] Reading: /app/lib/public/stylesheets/index.css
[+_+] Error: ENOENT, No such file or directory '/app/lib/public/stylesheets/index.css'
Error: EACCES, Permission denied '/app/lib/public/stylesheets/index.css'

The problem, by the directory listing you posted, is that I don't see the *.css files, whereas when running locally (and a few months ago in Nodester) they exist. I mean, they are compiled upon request and then served. Maybe because the user who started my app process don't have write permission.

Cheers,

**Comment by martypdx** [comment]
nodester reports __dirname as /app, but you are looking in app/lib for public???

**Comment by gtramontina** [comment]
That is correct. All my production related code live under /lib. Check out the project structure https://github.com/gtramontina/Writeboard

As mentioned, this was working prior to the change of the chroot. It seems that the apps no longer have writing permission. In the listing @Contra showed, we should see *.css files (compiled *.styl).

**Comment by martypdx** [comment]
Just happened to be searching issues because I had to go add `__dirname` to all my paths. So I took a look at your project, and I noticed that you set

```
 app.use stylus.middleware src: "#{__dirname}/public", compile: stylusCompiler
```

nodester returns `/app` for `__dirname`, so looks like you are pointing to `/app/public`, _not_ `/app/lib/public`. Maybe you need to set stylus to:

```
 app.use stylus.middleware src: "#{__dirname}/lib/public", compile: stylusCompiler
```

**Comment by gtramontina** [comment]
I got what you're saying. It didn't work, though :-/ Thanks for the tip.
Also, if the paths were wrong, not even the views would work.

**Comment by victorgoh** [comment]
I am getting Permission denied using stylus too. 

Error: EACCES, Permission denied '/app/stylesheets/main.css'
GET /stylesheets/main.css 500 582ms

``` javascript
var connect = require('connect')
  , stylus = require('stylus')
  , bootstrap = require('./');

function compile(str, path) {
  return stylus(str)
    .set('filename', path)
    .use(bootstrap());
}

process.on('uncaughtException', function(err) {
  console.log(err);
});

var port = process.env.PORT || 11976; // default port of nodester

connect()
  .use(connect.logger('dev'))
  .use(stylus.middleware({ compile: compile, src: __dirname}))
  .use(connect.static(__dirname))
  .listen(port);

console.log('Connect server listening on port ' + port);
```

The same app works in no.de and heroku. So, what's wrong with my nodester setup?

**Comment by obazoud** [comment]
Got same problem when I try to create files or directories.

```

warning: { stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'EACCES, Permission denied \'/app/tmp/tagpages/tag/Uncategorized.html.markdown\'',
  errno: 13,
  code: 'EACCES',
  path: '/app/tmp/tagpages/tag/Uncategorized.html.markdown' }
    → [2011-10-23 22:00:46.238] [/app/plugins/tagpages.plugin.coffee:82] [unknown]
```

**Comment by yocontra** [comment]
@obazoud - Can you please post your code associated with the error? Are you making sure the /tag/ folder exists before writing to it?

**Comment by dobesv** [comment]
I think I may be having a similar problem with our app 'foodjing' although the error is different:

```
   Error: EBADF, Bad file descriptor '/app/src/main/webapp/css/style.css'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:483:15)
    at /app/src/main/nodejs/genfiles.js:56:32
    at /app/src/main/nodejs/node_modules/less/lib/less/index.js:24:17
    at Object.parse (/app/src/main/nodejs/node_modules/less/lib/less/parser.js:375:17)
    at Object.render (/app/src/main/nodejs/node_modules/less/lib/less/index.js:23:20)
    at compileThisOne (/app/src/main/nodejs/genfiles.js:50:26)
    at /app/src/main/nodejs/genfiles.js:60:17
    at Array.forEach (native)
    at Object.genfiles (/app/src/main/nodejs/genfiles.js:43:36)


   Tue Oct 25 2011 12:10:45 GMT+0000 (UTC) Failed to compile jade file index.jade { stack: [Getter/Setter],
   arguments: undefined,
   type: undefined,
   message: 'EBADF, Bad file descriptor \'/app/src/main/webapp/index.html\'',
   errno: 9,
   code: 'EBADF',
   path: '/app/src/main/webapp/index.html' }
```

Basically looks like it can't write out those generated files in the source tree.

**Comment by yocontra** [comment]
@dobesv - EBADF usually means you're trying to write to a folder that doesn't exist or you're trying to read a file that doesn't exist. Make sure you use path.exists or path.existsSync before using any references to files in your code.

**Comment by scan** [comment]
Is there any solution to this yet? I am also having this problem, with code that worked fine yesterday. I used `connect-assets` for a test, it did not work at all, so I went back to the normal stylus middleware, and suddenly I get this `Permission Denied` error for all my `.css` files.

**Comment by dobesv** [comment]
@Contra That folder (src/main/webapp) exists, and that line is writing a file, not reading.  The same code has worked fine in other environments.  Anyhow, I solved the problem by getting a VPS and running the app from there instead of using nodester, for now.  That'll take some pressure off you guys :-).  Great project, though, keep at it!  Definitely something I'd recommend to someone who can use it.

**Comment by scan** [comment]
I did the same as dobesv, but also because the nodester servers were too slow for proper `socket.io` stuffs. But nodester did what it wanted to do: Help me get into node.js.

**Comment by yocontra** [comment]
We're working on a massive overhaul so check back sometime soon and problems like this will cease to be an issue!
