### ISSUE TITLE
Included express modules but throws error saying undefined

### ISSUE THREAD

**Issue by buzzshiva** [nodester/nodester#176]
I add this simple script to test expressjs but it failed and logs throws the below message 

var app = express.createServer();
app.get('/', function(req, res){
    res.send('Hello World');
});
app.listen(process.env['app_port']);

ERROR

^

ReferenceError: express is not defined
    at Object.<anonymous> (/app/server.js:2:1)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)

Also I have installed the appropriate modules to the application.

$ nodester npm list
nodester info list npm packages for app: apptest
nodester ├─┬ express@2.4.3
nodester │ ├── connect@1.6.0
nodester │ ├── mime@1.2.2
nodester │ └── qs@0.3.0
nodester ├─┬ jquery@1.6.2
nodester │ └── htmlparser@1.7.3
nodester ├─┬ jsdom@0.2.1
nodester │ ├── cssom@0.2.0
nodester │ ├── htmlparser@1.7.3
nodester │ └── request@2.0.1
nodester ├─┬ socket.io@0.7.7
nodester │ ├── policyfile@0.0.3
nodester │ └─┬ socket.io-client@0.7.4
nodester │   └── uglify-js@1.0.3
nodester └─┬ yui3@0.6.2
nodester   ├── htmlparser@1.7.3
nodester   └── yui3-core@3.3.0
nodester

Error: Restarted too many times, bailing.

**Comment by yocontra** [comment]
var express = require('express');

Should go before that code block

**Comment by buzzshiva** [comment]
that worked... Thanks.

**Comment by yocontra** [comment]
For future reference, adding something to NPM doesn't make it available in your code immediately. You have to require() the module and assign it to a variable.

**Comment by immanueliman** [comment]
i write requre code, but show like this
