### ISSUE TITLE
Issue with branches?

### ISSUE THREAD

**Issue by akiva** [nodester/nodester#177]
My nodester app seems to not be reflecting the changes I have made after merging a local branch to the master branch. Each branch was also pushed to the Nodester repo. Now that I am back on my master branch, pushing to Nodester results in no changes. Is this just me or is something wrong?

**Comment by yocontra** [comment]
Can you send me a log of your git bash so I can have a look at what commands you ran?

Try a `git checkout master`

**Comment by akiva** [comment]
Odd, I replied via e-mail. I guess it didn't make it? :S

I performed my usual way of doing Git branches: when on `master`, `git branch newbranch`, make some changes, commit, `git checkout master`, `git merge newbranch`, `git commit`, `git push nodester master`.

Apologies about the brevity, my original reply was much more verbose.

**Comment by yocontra** [comment]
Closed due to absence from V2 roadmap.
