### ISSUE TITLE
npm repository out of sync?

### ISSUE THREAD

**Issue by gtramontina** [nodester/nodester#179]
Hey there,
I'm trying to install reds@0.1.0 in my app, but Nodester's npm repository doesn't find it.
How often is this repository updated or refreshed?

Thanks!

**Comment by yocontra** [comment]
I'll be pushing some code to deal with this and some other issues concerning NPM sometime today. Hopefully it should fix the issues people have been having with NPM being out of sync and also add some functionality.

**Comment by gtramontina** [comment]
Cool! Looking forward to get it fixed. I've faced this issue a few times before.

**Comment by yocontra** [comment]
According to Dan we keep a separate NPM repo that needs to be synced. I'll take care of it once I get some more details about it

**Comment by kmiyashiro** [comment]
This wouldn't really be an issue if bundled modules were all recognized.

For some reason, only some of my bundled node_modules don't get found by my app when I run it on nodester, but it finds them locally just fine (installed in node_modules only, not with npm -g). Why is that? Is ./node_modules not in the require.paths?

**Comment by yocontra** [comment]
DanBUK went ahead and synced up the NPM repo. Closing this now
