### ISSUE TITLE
Debug /appnpm handler

### ISSUE THREAD

**Issue by DanBUK** [nodester/nodester#18]
It doesn't seem to be 100% reliable.
Sometimes it does install, sometimes not.

I haven't worked out a reproducible case yet though :(

**Comment by DanBUK** [comment]
Think we might have nearly worked this one out! Whoo hoo!

**Comment by chrismatthieu** [comment]
Good job!

**Comment by DanBUK** [comment]
After watching some things run for a while I'm quite confident this one is fixed so closing it off.
