### ISSUE TITLE
Unable to load Stylesheet - using stylus (Express) throws - Internal Server Error 

### ISSUE THREAD

**Issue by buzzshiva** [nodester/nodester#180]
I'm getting this "Internal Server Error" when executed on nodester.com but When I do the same on localhost I dont get it.... The stylesheets are not getting loaded under nodester platform.

Error Message:
15 Internal Server Error 0

What does 15 and 0 Means in nodester Environment! 

I'm using Express with Stylus; 
Also Nodester logs does'nt detail more information.
$ nodester logs
nodester info Showing logs for: apptest
New PID: 52596
chroot_runner
chroot_runner
Express server listening on port 11053 in production mode

Under Nodester :
Request URL:http://apptest.nodester.com/stylesheets/style.css
Request Method:GET
Status Code:500 Internal Server Error
Request Headersview source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Charset:ISO-8859-1,utf-8;q=0.7,*;q=0.3
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Host:apptest.nodester.com
User-Agent:Mozilla/5.0 (Windows NT 6.1) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.112 Safari/535.1

LOCALHOST ;
Request URL:http://localhost:3010/stylesheets/style.css
Request Method:GET
Status Code:304 Not Modified
Request Headersview parsed
GET /stylesheets/style.css HTTP/1.1

Host: localhost:3010

Connection: keep-alive

User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.112 Safari/535.1

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8

Accept-Encoding: gzip,deflate,sdch

Accept-Language: en-US,en;q=0.8

Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3

If-None-Match: "4818-1313500185000"

If-Modified-Since: Tue, 16 Aug 2011 13:09:45 GMT

**Comment by buzzshiva** [comment]
I think I found the solution: 
There was a string(#!/bin/sh) somehow got attached to style.styl file.  So nodester or stylus parser throwed this error which was stopping the whole execution of style.css.

Now that I removed string from style.styl its working normal.

**Comment by yocontra** [comment]
In the future please run `nodester app logs` and post that as well so we can figure out if it is a nodester issue or an issue in your code

**Comment by buzzshiva** [comment]
Hi Contra..
  I had added nodester log as well .... it didn't showed much information .... please check in the above issue description. Here is what i noticed whenever I face such minor issues, like junk character added in style.styl , the nodester logs did'nt gave enough information. Is there any way to set it as DEBUG: true, so that I could see whats happening at nodester side. 

$ nodester logs
nodester info Showing logs for: apptest
New PID: 52596
chroot_runner
chroot_runner
Express server listening on port 11053 in production mode

**Comment by yocontra** [comment]
I figured the error would be reported when stylus tried to parse the file but I guess they keep those silent.

I believe if you want to log any errors and make them available to `nodester logs` you can put this at the start of your server

`process.on('uncaughtException', function(err) {
          console.log(err);
    });`

Sidenote this will also prevent your server from crashing on errors

**Comment by buzzshiva** [comment]
Thanks, that will be helpful during troubleshooting/debugging
