### ISSUE TITLE
support git push -f

### ISSUE THREAD

**Issue by zTrix** [nodester/nodester#182]
When developing app, If I use `git push nodester master` which changed git commit history, then nodester app won't work.

Could you please solve this?

Thanks.

**Comment by yocontra** [comment]
Can you try to run `nodester app restart` and tell me if that fixes it?

**Comment by zTrix** [comment]
In fact, something is wrong with my nodester app, `nodester app restart` only gives 

```
#nodester app restart ztrix-blog
nodester info Attemping to restart app: ztrix-blog
nodester ERROR socket hang up
#
```

But `nodester app info`  gives this:

```
nodester info Gathering information about: ztrix-blog
nodester info ztrix-blog on port 11415 running: true (pid: 29731)
```

**Comment by yocontra** [comment]
We seem to be having some issues at the moment, we're looking into it. I'll reply again when it's fixed

**Comment by funkytek** [comment]
can you try another restart?

**Comment by zTrix** [comment]
I tried again.

`nodester app restart ztrix-blog`

```
nodester info Attemping to restart app: ztrix-blog
nodester ERROR socket hang up
```

and I also tried `nodester app info ztrix-blog`

```
nodester info Gathering information about: ztrix-blog
nodester info ztrix-blog on port 11415 running: true (pid: 22112)
```

And http://ztrix-blog.nodester.com/ still gives me `Application is offline`

**Comment by dobesv** [comment]
I'm having a similar issue.  I did a git amend and a git push which casued conflicts on the server.  I can't seem to resolve the conflicts.  I think maybe when nodester runs its internal merge/pull it needs to specify the resolve strategy of "theirs".  gitreset doesn't seem to have solved the issue.  Here are some logs:

```
$ git push nodester +master:master
Counting objects: 11, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (6/6), 504 bytes, done.
Total 6 (delta 2), reused 0 (delta 0)
remote: Syncing repo with chroot
remote: From /node/git/foodjing/4024-7d68594c4a2fcabbffb1d73736d6e47c
remote:  + f86a392...1d8b72f master     -> origin/master  (forced update)
remote: Auto-merging src/api/js/server.js
remote: CONFLICT (content): Merge conflict in src/api/js/server.js
remote: Automatic merge failed; fix conflicts and then commit the result.
remote: Attempting to restart your app: 4024-7d68594c4a2fcabbffb1d73736d6e47c
remote: {"status":"restarted"}
remote: App restarted..
remote:
remote:   \m/ Nodester out \m/
remote:
To git@nodester.com:/node/git/foodjing/4024-7d68594c4a2fcabbffb1d73736d6e47c.git
 + f86a392...1d8b72f master -> master (forced update)
$ git push nodester +master:master
Everything up-to-date
$ nodester app gitreset foodjing
nodester warn resetting app: foodjing
nodester warn successfully reset app foodjing
$ nodester app restart foodjing
nodester info Attemping to restart app: foodjing
nodester info app restarted.
$ curl -i foodjing.nodester.com
HTTP/1.1 500 Internal Server Error
... page saying the application is down ...
$ nodester app logs foodjing
nodester info Showing logs for: foodjing
New PID: 16589
chroot_runner
chroot_runner


/app/src/api/js/server.js:6

<<<<<<< HEAD

^
^

```

So, I think there might be no way out of this besides deleting and re-creating the app.  It would be more helpful if the git commands would somehow avoid merge conflicts and the gitreset would get out of this state.

**Comment by dobesv** [comment]
I tried deleting and creating my app again and that fixed it for now, as a workaround.  Does require you to reset your port #'s and git remote but its better than having your site down!

**Comment by yocontra** [comment]
Closing this as V2 won't have git and this won't be fixed in V1.
