### ISSUE TITLE
Issue with creating basic app

### ISSUE THREAD

**Issue by salilpradhan** [nodester/nodester#184]
Hey,

Just got a coupon and created a new nodester account, but could not get past the step of creating a sample account -

salilp$ nodester app create junk123456
nodester info creating app: junk123456 server.js
nodester info successfully created app junk123456 to will run on port 11443 from server.js
nodester info run nodester app init junk123456 to setup this app.

salilp$ nodester app init junk123456
nodester info initializing git repo for junk123456 into folder junk123456
nodester info cloning the repo git clone git@nodester.com:/node/git/salilp/3290-1f75be367bb01c9e381e7f8188fe6392.git junk123456
nodester info clone complete
nodester info writing app data to config
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR false

What could be wrong?

**Comment by yocontra** [comment]
Should be fixed now, let me know if it isn't.
