### ISSUE TITLE
nodester user setup <username> <password> throwing error on ubuntu platform

### ISSUE THREAD

**Issue by buzzshiva** [nodester/nodester#185]
I'm using ubuntu 11.04

and node v0.4.11 and npm 1.0.26 and i have generated the ssh-keygen plus ssh-agent is running in the background. Please let me know if i'm missing something here.

here is my USERNAME  : buzzshiva

Case 1:
nodester user setup <username> <password> throwing error on ubuntu platform
Error:
nodester info verifying credentials
nodester ERROR socket hang up

Error:
nodester info verifying credentials
nodester ERROR Request ended prematurely.

Case 2:
curl -u "buzzshiva:<password>" http://api.nodester.com/app/apptest

Response:
curl: (52) Empty reply from server

**Comment by yocontra** [comment]
Can you try again? We were having server issues around the time you filed this and that could be the cause

**Comment by buzzshiva** [comment]
I tried 3 times still throwing socket hung up error. Is there any way to connect to database (i guess its mongodb) and check if the password is authenticated or not. 

Test 1
$nodester user setup buzzshiva < password >
nodester info verifying credentials
nodester ERROR socket hang up

Test 2
$ nodester user setup buzzshiva <  password  >
nodester info verifying credentials
nodester ERROR socket hang up

Test 3
$ nodester user setup buzzshiva < password >
nodester info verifying credentials
nodester ERROR socket hang up

**Comment by buzzshiva** [comment]
today it got working 

nodester info verifying credentials
nodester info user verified..
nodester info writing user data to config
