### ISSUE TITLE
cannot get info for app

### ISSUE THREAD

**Issue by ianswilliams** [nodester/nodester#186]
Hi guys,

my app 'ianwilliamses.nodester.com' is running but 

> nodester app info ianwilliamses
> causes:
>  nodester ERROR socket hang up

as does 
nodester app stop/start etc.

regards,
Ian

**Comment by buzzshiva** [comment]
try it now .. I had somewhat similar issue; I was been told its a server issue and its been resolved now.

when I do 
nodester user setup <username> <password> it was throwing "socket hung up" error, Now its working perfectly for me.

**Comment by yocontra** [comment]
Should be resolved now, closing this.
