### ISSUE TITLE
Can't Create Simple App- ECONNREFUSED

### ISSUE THREAD

**Issue by grahamcracker** [nodester/nodester#188]
I'm trying to get setup with nodester.

First, I run `nodester app create archio`. Everything runs great. The problems start when I run `nodester app init archio`:

```
nodester info initializing git repo for archio into folder archio
nodester info cloning the repo git clone git@nodester.com:/node/git/Archio/3387-4e239d557f6904f4c6409ef4ca1c6336.git  archio
nodester info clone complete
nodester info Writing app data to config in archio/.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR false
```

I RTFM'd, and couldn't figure out what "ERROR false" meant... Checking archio.nodester.com reveals the following error:

```
An error has occurred: {"stack":"Error: ECONNREFUSED, Connection refused\n    at Socket._onConnect (net.js:601:18)\n    at IOWatcher.onWritable [as callback] (net.js:186:12)","message":"ECONNREFUSED, Connection refused","errno":111,"code":"ECONNREFUSED","syscall":"connect"}
```

`nodester app info archio` says "`archio on port 11540 running: failed-to-start`". What does this mean- is this a problem with my system, or an issue with nodester?

Thanks for any help you can give me, I really appreciate it.

**Comment by yocontra** [comment]
ECONNREFUSED is the standard error for application level issues. Run init again then do `nodester app logs archio` and paste the output in here

**Comment by grahamcracker** [comment]
`nodester app logs archio` just returns the following:

```
nodester ERROR HTTP Error 500
```

**Comment by yocontra** [comment]
Should be fixed, let me know if it isn't.

**Comment by grahamcracker** [comment]
Nope... I wish it was, but I deleted the app, made a new one, tried `nodester app logs` and got `nodester ERROR HTTP Error 500`.

And, the same issue with ECONNREFUSED: http://archio.nodester.com/

**Comment by madhums** [comment]
I am having the same issue too! http://nodejs-express-demo.nodester.com/

**Comment by hanspinckaers** [comment]
Got this error too. http://ucheck.nodester.com/ (ECONNREFUSED)

Also can't view my logs anymore. (HTTP Error 500).

This app has been running for a month or so. So the code is ok. 

I hope we can find a solution.

**Comment by yocontra** [comment]
We are out of disk space atm. Chris is working on it

**Comment by yocontra** [comment]
We've implemented a large number of changes to the server. Let me know if you are still having the same issues and we can iron them out now

**Comment by hanspinckaers** [comment]
It worked, a lot faster btw. But now it doesn't work anymore.

**Comment by funkytek** [comment]
Can you guys give it another try?

**Comment by hanspinckaers** [comment]
Works. Thanks!

**Comment by minikomi** [comment]
Getting this same issue at the moment with nodepen.nodester.com ...

**Comment by funkytek** [comment]
can you make sure to update to the latest version of the cli ($ npm update -g) and try again?

**Comment by yocontra** [comment]
@minikomi - ECONNREFUSED is a generic application error message. Have a look at your code or open a new issue

**Comment by minikomi** [comment]
OK.. this was an app which was running, I cloned and tried to update the socket number to the one advised on the blog, re-pushed and I'm now getting the error.. perhaps socket.io's API has changed or something in the meantime,.. I'll investigate

**Comment by minikomi** [comment]
Just to clarify - there were some major changes to Socket.io, which I had not stayed up to date with. Adjusting for the new style fixed my app.
