### ISSUE TITLE
HTTP 500 on nodester start and log

### ISSUE THREAD

**Issue by Deebster** [nodester/nodester#189]
My newly created apps just reply with HTTP 500:

**deebster@bernie:~/code$ nodester app create deebhellog**
nodester info creating app: deebhellog server.js
nodester info successfully created app deebhellog to will run on port 11541 from server.js
nodester info run nodester app init deebhellog to setup this app.
deebster@bernie:~/code$ nodester app init !$
**nodester app init deebhellog**
nodester info initializing git repo for deebhellog into folder deebhellog
nodester info cloning the repo git clone git@nodester.com:/node/git/deebster/3388-1b88db30af0838d2813a26790d8e0796.git deebhellog
nodester info clone complete
nodester info Writing app data to config in deebhellog/.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR false
deebster@bernie:~/code$ nodester app logs !$
**nodester app logs deebhellog**
nodester ERROR HTTP Error 500
**deebster@bernie:~/code$ node -v && npm -v && nodester -v**
v0.4.12-pre
1.0.27
0.2.20
**deebster@bernie:~/code$ cat deebhellog/server.js**
var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\nApp (deebhellog) is running..');
}).listen(11541);
**deebster@bernie:~/code$ npm info nodester-cli**
npm WARN nodester-cli@0.2.0 package.json: 'modules' object is deprecated
npm WARN nodester-cli@0.2.1 package.json: 'modules' object is deprecated
{ name: 'nodester-cli',
  description: 'A CLI tool to allow interaction with the http://nodester.com/ platform.',
  'dist-tags': { latest: '0.2.20' },
  versions:
   [ '0.1.0',
     '0.1.1',
     '0.1.2',
     '0.1.3',
     '0.1.5',
     '0.1.6',
     '0.1.7',
     '0.2.0',
     '0.2.1',
     '0.2.3',
     '0.2.4',
     '0.2.5',
     '0.2.6',
     '0.2.7',
     '0.2.8',
     '0.2.9',
     '0.2.10',
     '0.2.11',
     '0.2.12',
     '0.2.13',
     '0.2.14',
     '0.2.15',
     '0.2.17',
     '0.2.18',
     '0.2.19',
     '0.2.20' ],
  maintainers:
   [ 'DanBUK dan@f-box.org',
     'davglass davglass@gmail.com',
     'chrismatthieu chris@matthieu.us' ],
  time:
   { '0.1.0': '2011-01-31T16:26:42.334Z',
     '0.1.1': '2011-02-01T13:48:46.448Z',
     '0.1.2': '2011-02-01T13:58:42.336Z',
     '0.1.3': '2011-02-03T17:32:01.199Z',
     '0.1.5': '2011-02-05T21:06:12.443Z',
     '0.1.6': '2011-02-06T20:41:43.597Z',
     '0.1.7': '2011-02-08T13:08:37.065Z',
     '0.2.0': '2011-02-12T17:53:03.951Z',
     '0.2.1': '2011-02-13T11:58:41.785Z',
     '0.2.3': '2011-02-14T11:42:12.845Z',
     '0.2.4': '2011-03-10T16:13:12.690Z',
     '0.2.5': '2011-03-10T16:26:37.174Z',
     '0.2.6': '2011-03-10T22:48:01.097Z',
     '0.2.7': '2011-03-11T13:52:15.657Z',
     '0.2.8': '2011-03-11T19:56:21.111Z',
     '0.2.9': '2011-03-13T19:29:23.301Z',
     '0.2.10': '2011-03-22T12:16:43.778Z',
     '0.2.11': '2011-03-22T13:45:16.739Z',
     '0.2.12': '2011-03-22T18:15:02.563Z',
     '0.2.13': '2011-05-02T19:24:23.523Z',
     '0.2.14': '2011-07-07T16:55:19.896Z',
     '0.2.15': '2011-07-07T17:04:12.947Z',
     '0.2.17': '2011-07-22T10:07:01.877Z',
     '0.2.18': '2011-07-22T10:47:50.265Z',
     '0.2.19': '2011-07-22T10:49:09.534Z',
     '0.2.20': '2011-08-22T02:02:39.089Z' },
  author: 'Daniel Bartlett dan@f-box.org (http://danb-uk.net/)',
  repository:
   { type: 'git',
     url: 'git://github.com/nodester/nodester-cli.git' },
  version: '0.2.20',
  homepage: 'http://nodester.com/',
  contributors:
   [ 'Dav Glass davglass@gmail.com',
     'Chris Matthieu chris@matthieu.us',
     'Abraham Williams 4braham@gmail.com',
     'Contra contra@australia.edu',
     'Marcos Oliveira' ],
  preferGlobal: 'true',
  bin: { nodester: 'bin/nodester.js' },
  main: './lib/commands.js',
  engines: { node: '*' },
  dependencies:
   { 'nodester-api': '0.1.9',
     colors: '0.3.0',
     iniparser: '1.0.1' },
  directories: { lib: './lib', bin: './bin' },
  files: '',
  dist:
   { shasum: 'fd7f55c27c269ceea41c5774b17bf983552cd5d6',
     tarball: 'http://registry.npmjs.org/nodester-cli/-/nodester-cli-0.2.20.tgz' },
  devDependencies: {} }

**deebster@bernie:~/code$ uname -a && cat /etc/issue**
Linux bernie 2.6.32-26-generic #48-Ubuntu SMP Wed Nov 24 09:00:03 UTC 2010 i686 GNU/Linux
Ubuntu 10.04.3 LTS \n \l

**Comment by DanBUK** [comment]
Please re-test, there was an errant process that I've fixed.

**Comment by Deebster** [comment]
No joy:

**deebster@bernie:~/code$ nodester app create hellodeebh**
nodester info creating app: hellodeebh server.js
nodester info successfully created app hellodeebh to will run on port 11542 from server.js
nodester info run nodester app init hellodeebh to setup this app.
deebster@bernie:~/code$ nodester app init !$
**nodester app init hellodeebh**
nodester info initializing git repo for hellodeebh into folder hellodeebh
nodester info cloning the repo git clone git@nodester.com:/node/git/deebster/3389-3dfd089377a265a778ff9bfc73146f1f.git hellodeebh
nodester info clone complete
nodester info Writing app data to config in hellodeebh/.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR false
**deebster@bernie:~/code$ nodester app logs hellodeebh**
nodester ERROR HTTP Error 500

**Comment by DanBUK** [comment]
It doesn't appear as if the git master branch has been pushed to. Can you check whether the server.js has been committed?

**Comment by Deebster** [comment]
The new app doesn't appear to be a git repo

**deebster@bernie:~/code/hellodeebh$ ls -lAph**
total 12K
-rw-r--r-- 1 deebster deebster  20 2011-08-25 11:25 .gitignore
-rw-r--r-- 1 deebster deebster  19 2011-08-25 11:25 .nodester.appconfig
-rw-r--r-- 1 deebster deebster 197 2011-08-25 11:25 server.js

Looks like ssh is the problem:

**deebster@bernie:~/code$ git clone git@nodester.com:/node/git/deebster/3389-3dfd089377a265a778ff9bfc73146f1f.git hellodeebh**
Initialized empty Git repository in /home/deebster/code/hellodeebh/.git/
ssh: connect to host nodester.com port 22: Connection refused
fatal: The remote end hung up unexpectedly
**deebster@bernie:~/code$ nodester user setkey**
nodester info sending sshkey: /home/deebster/.ssh/id_rsa.pub
nodester info ssh key successfully sent
**deebster@bernie:~/code$ ssh -vvv git@nodester.com**
OpenSSH_5.3p1 Debian-3ubuntu7, OpenSSL 0.9.8k 25 Mar 2009
debug1: Reading configuration data /home/deebster/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to nodester.com [50.16.203.53] port 22.
debug1: connect to address 50.16.203.53 port 22: Connection refused
ssh: connect to host nodester.com port 22: Connection refused

**Comment by yocontra** [comment]
Are you still having issues with this?

**Comment by Deebster** [comment]
Yes, I still get exactly the same output when attempting to ssh in.  Has my IP been blacklisted for too many failed attempts while testing?

**Comment by chrismatthieu** [comment]
Yep, just got this error again:

topher:src topher$ git clone https://github.com/eldios/node-hq.git
Cloning into node-hq...
remote: Counting objects: 26, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 26 (delta 7), reused 24 (delta 5)
Unpacking objects: 100% (26/26), done.
topher:src topher$ cd node-hq
topher:node-hq topher$ nodester app create nodehqtest
nodester info creating app: nodehqtest server.js
nodester info successfully created app nodehqtest to will run on port 11679 from server.js
nodester info run nodester app init nodehqtest to setup this app.
topher:node-hq topher$ nodester app info nodehqtest
nodester info Gathering information about: nodehqtest
nodester warn nodehqtest on port 11679 running: false (pid: unknown)
nodester info gitrepo: git@nodester.com:/node/git/topher/3526-32495e5f32f865db2c15027d7e4105e9.git
nodester info appfile: server.js
topher:node-hq topher$ git remote add nodester git@nodester.com:/node/git/topher/3526-32495e5f32f865db2c15027d7e4105e9.git
topher:node-hq topher$ mate .
topher:node-hq topher$ node hq.js
Listening on port 11679
^Ctopher:node-hq topher$ git add .
topher:node-hq topher$ git commit -m "updated port"
[master 715b4fb] updated port
 1 files changed, 1 insertions(+), 1 deletions(-)
topher:node-hq topher$ nodester npm install nodehqtest express jade
nodester info installing to app: nodehqtest
nodester info installing these npm packages: express,jade
nodester express@2.4.3 ./node_modules/express 
nodester ├── connect@1.6.0
nodester ├── mime@1.2.2
nodester └── qs@0.3.0
nodester /bin/sh: line 0: cd: /node/app/topher/3526-32495e5f32f865db2c15027d7e4105e9_rw: No such file or directory

nodester warn you should restart your app after you are finished installing packages.
topher:node-hq topher$ git push nodester master
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that the RSA host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
a1:64:54:7c:9b:73:9f:22:a8:95:44:4f:7b:25:15:68.
Please contact your system administrator.
Add correct host key in /Users/topher/.ssh/known_hosts to get rid of this message.
Offending key in /Users/topher/.ssh/known_hosts:38
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
Counting objects: 29, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (24/24), done.
Writing objects: 100% (29/29), 3.94 KiB, done.
Total 29 (delta 9), reused 0 (delta 0)
remote: Syncing repo with chroot
remote: From /node/git/topher/3526-32495e5f32f865db2c15027d7e4105e9
remote:  \* [new branch]      master     -> origin/master
remote: Attempting to restart your app: 3526-32495e5f32f865db2c15027d7e4105e9
remote: {"status":"failed to restart"}
remote: App restarted..
remote: 
remote:   \m/ Nodester out \m/
remote: 
To git@nodester.com:/node/git/topher/3526-32495e5f32f865db2c15027d7e4105e9.git
- [new branch]      master -> master
  topher:node-hq topher$ nodester app logs nodehqtest
  nodester ERROR HTTP Error 500
  topher:node-hq topher$ nodester app logs nodehqtest
  nodester ERROR HTTP Error 500

**Comment by yocontra** [comment]
Fixed in e8d504a9b45f3c104169ea08f5469bf554f50207
