### ISSUE TITLE
App is still running after being deleted

### ISSUE THREAD

**Issue by mnfloresv** [nodester/nodester#192]
When I delete my application after some tests, the process is not stopped, but continues working...

```
$ nodester app delete ohaijs
nodester warn deleting app: ohaijs
nodester warn Are you sure you want to do this?
     Waiting 10 seconds before continuing, Ctrl+C to abort)
...........
nodester warn Really deleting app now, you were warned..
<<long delay here>>
nodester ERROR socket hang up
```

Now, the app doesn't exists,

```
$ nodester apps
nodester warn no apps to report

```

 but is still alive:
http://ohaijs.nodester.com/

And no way to stop it and release the subdomain...

I have the latest version of nodester-cli: 0.2.20

**Comment by yocontra** [comment]
API was down, try pulling down your app and deleting it again so the server acknowledges it.
