### ISSUE TITLE
why nodester app clone <appname> does'nt work 

### ISSUE THREAD

**Issue by buzzshiva** [nodester/nodester#193]
why nodester app clone <appname> does'nt work 

```
nodester app clone <appname>  
```

The above command creates a directory named <appname> but does'nt pulls the app files. Why and whats happening here.

**Comment by grahamcracker** [comment]
Having the same issue, it was working before, but now it's not.

**Comment by yocontra** [comment]
API went wonky, I restarted it and it appears to be working fine now.

Let me know if you still have any issues
