### ISSUE TITLE
app init does not work

### ISSUE THREAD

**Issue by broncha** [nodester/nodester#194]
Hi,
I have tried this so many times but I cant get this working.
Here is the output of my tests.
Please help

broncha@broncha-lapi ~ $ nodester app create broncha12
nodester info creating app: broncha12 server.js
nodester info successfully created app broncha12 to will run on port 11591 from server.js
nodester info run nodester app init broncha12 to setup this app.
broncha@broncha-lapi ~ $ nodester app init broncha12
nodester info initializing git repo for broncha12 into folder broncha12
nodester info cloning the repo git clone git@nodester.com:/node/git/broncha/3438-a77b4be2fee33a85a44123fc4b80a866.git broncha12
nodester info clone complete
nodester info Writing app data to config in broncha12/.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR false
broncha@broncha-lapi ~ $

**Comment by yocontra** [comment]
It looks like your app made it to the server alright. That "error" isn't really an error at all it seems, just a cosmetic bug that needs to be ironed out

**Comment by grahamcracker** [comment]
Contra: I thought before it wasn't an error, but he seems to be revealing the same issue that causes the problem I had where app's status is "failed-to-start".

**Comment by yocontra** [comment]
Ah interesting that this "ERROR false" is actually more than cosmetic for once! I'll have a look into this when I wake up

**Comment by broncha** [comment]
And to add to it, when I try to delete the app the socket times out.
Can that be a problem at my end?

**Comment by grahamcracker** [comment]
broncha: Not your system, I'm having the same problem! It seems like all these issues:
1. `nodester app init` ERROR false
2. `nodester app info` failed-to-start
3. `nodester app delete` socket hang up

...seem to be related in some way, because the people experiencing them get the same errors.

**Comment by yocontra** [comment]
The API has been acting up recently. I'm on the server right now looking into it, hopefully I'll be able to restart it and get it up and running again

**Comment by yocontra** [comment]
Restarted the API, appears to be working fine for me now. Let me know if it hasn't been fixed and I'll reopen it

**Comment by broncha** [comment]
@Contra I am still getting those errors:

broncha@broncha-lapi ~ $ nodester app create broncha00
nodester info creating app: broncha00 server.js
nodester info successfully created app broncha00 to will run on port 11604 from server.js
nodester info run nodester app init broncha00 to setup this app.
broncha@broncha-lapi ~ $ nnodester app init broncha00
nnodester: command not found
broncha@broncha-lapi ~ $ nodester app init broncha00
nodester info initializing git repo for broncha00 into folder broncha00
nodester info cloning the repo git clone git@nodester.com:/node/git/broncha/3451-4d053e48ed1a94620ec9fe9bbff56078.git broncha00
nodester info clone complete
nodester info Writing app data to config in broncha00/.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR false
broncha@broncha-lapi ~ $ nodester app info broncha00
nodester info Gathering information about: broncha00
nodester info broncha00 on port 11604 running: failed-to-start 
nodester info gitrepo: git@nodester.com:/node/git/broncha/3451-4d053e48ed1a94620ec9fe9bbff56078.git
nodester info appfile: server.js
broncha@broncha-lapi ~ $

**Comment by yocontra** [comment]
Seems my fix was only temporary but I think I got it now. Try again and lets see if I finally nabbed it

**Comment by broncha** [comment]
@Contra Not working.. I still get the same errors

**Comment by yocontra** [comment]
Strange it will work fine for a few minutes then break again. Still having a look at things, I'd suggest just to keep trying until a mystic wizard comes along and helps out

Opening this again

**Comment by broncha** [comment]
@contra I checked it just now, and I still get the same result..

**Comment by yocontra** [comment]
We've implemented a large number of changes to the server. Let me know if you are still having the same issues and we can iron them out now

**Comment by broncha** [comment]
Hi @Contra
Right now I am not being able to connect to nodester. Are the servers down? I cannot even access the website nodester.com

nodester user setup broncha password gives me 

nodester info verifying credentials
nodester ERROR ECONNREFUSED, Connection refused

**Comment by yocontra** [comment]
I was restarting the server to pull in some of the new changes. Try again and let me know how it works

**Comment by broncha** [comment]
@contra, this is what I got right now..

broncha@broncha-lapi ~ $ nodester app create broncha99
nodester info creating app: broncha99 server.js
nodester info successfully created app broncha99 to will run on port 11863 from server.js
nodester info run nodester app init broncha99 to setup this app.
broncha@broncha-lapi ~ $ nodester app init broncha99
nodester info initializing git repo for broncha99 into folder broncha99
nodester info cloning the repo git clone git@nodester.com:/node/git/broncha/3710-48ec2552222b3986dbca74d316aeeddd.git broncha99
nodester info clone complete
nodester info Writing app data to config in broncha99/.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR false
broncha@broncha-lapi ~ $ nodester app info broncha99
nodester info Gathering information about: broncha99
nodester info broncha99 on port 11863 running: failed-to-start 
nodester info gitrepo: git@nodester.com:/node/git/broncha/3710-48ec2552222b3986dbca74d316aeeddd.git
nodester info appfile: server.js
broncha@broncha-lapi ~ $

**Comment by funkytek** [comment]
broncha, can you give it another try the API is back up

**Comment by funkytek** [comment]
@broncha please make sure you cli is updated ($ npm update -g) and try again

**Comment by broncha** [comment]
Hi finally worked:

broncha@broncha-lapi ~ $ nodester app init broncha420
nodester info initializing git repo for broncha420 into folder broncha420
nodester info cloning the repo git clone git@nodester.com:/node/git/broncha/3788-df46fb6daa43194d66393b275ee013b0.git broncha420
The authenticity of host 'nodester.com (50.16.203.53)' can't be established.
RSA key fingerprint is a1:64:54:7c:9b:73:9f:22:a8:95:44:4f:7b:25:15:68.
Are you sure you want to continue connecting (yes/no)? yes
nodester info clone complete
nodester info Writing app data to config in broncha420/.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
nodester info broncha420 started.
nodester info Some helpful app commands:

```
 cd ./broncha420
 curl http://broncha420.nodester.com/
  nodester app info
  nodester app logs
  nodester app stop|start|restart
```

but seconds later the app was not running. And I cant get it running.

broncha@broncha-lapi ~/broncha420 $ nodester app info broncha420
nodester info Gathering information about: broncha420
nodester warn broncha420 on port 11941 running: false (pid: unknown)
nodester info gitrepo: git@nodester.com:/node/git/broncha/3788-df46fb6daa43194d66393b275ee013b0.git
nodester info appfile: server.js
broncha@broncha-lapi ~/broncha420 $ nodester app restart broncha420
nodester info Attemping to restart app: broncha420
nodester info { body: '{"status":"false","port":11941,"gitrepo":"git@nodester.com:/node/git/broncha/3788-df46fb6daa43194d66393b275ee013b0.git","start":"server.js","running":"failed-to-restart","pid":null}',
  response: 200 }
nodester ERROR false
broncha@broncha-lapi ~/broncha420 $ nodester app start broncha420
nodester info Attemping to start app: broncha420
nodester info { body: '{"status":"false","port":11941,"gitrepo":"git@nodester.com:/node/git/broncha/3788-df46fb6daa43194d66393b275ee013b0.git","start":"server.js","running":"failed-to-start","pid":null}',
  response: 200 }
nodester ERROR false

**Comment by yocontra** [comment]
Some users are broken atm and unable to start apps (which is why anything related to app starts is failing) because their git files aren't being cloned over. I'm already halfway through a fix but I need to do extensive testing on it

Also nice to see the new update to the CLI helps make errors not-so-worthless! Thanks for being patient

**Comment by funkytek** [comment]
@broncha please try again

**Comment by broncha** [comment]
Finally, it worked !! :)
Thank you guys for your support.

I found some typos in the nodester cli, not a big issue :)
broncha@broncha-lapi ~ $ nodester app start broncha420
nodester info **Attemping** to start app: broncha420

It is Attempting we know :) thanks again guys !!!
