### ISSUE TITLE
Create VM appliance

### ISSUE THREAD

**Issue by cime** [nodester/nodester#195]
Create a VM appliance (for example Ubuntu based, for VirtualBox) containing everything to make nodester work.
It's hard to setup nodester from zero because installation instructions are old now.

**Comment by DanBUK** [comment]
Please take a look at bin/install.js it's more up to date than the install.txt

**Comment by funkytek** [comment]
we're working on creating a VM image currently

**Comment by matbeedotcom** [comment]
How is this VM going?

**Comment by yocontra** [comment]
V2 will have a simple `curl http://nodester.com/install.sh | sudo sh` that will install the entire system and all dependencies. Is an image still needed?

**Comment by matbeedotcom** [comment]
Most definitely would be great for testing!
