### ISSUE TITLE
git push nodester master Permission denied(public key)

### ISSUE THREAD

**Issue by amoln** [nodester/nodester#197]
My repo is located at ec2-user@nodester.com:/node/hosted_apps/akn/1731-8a3b25a6e53bfee528df3db2b9bed1e9.git

I created it back in May 2011, but now when trying to access it, the app looks down, and I am not able to push any code changes.
I tried updating a new ssh key after getting the 'Permission Denied' error, but that is still not helping.

Not able to get any help on the site.

**Comment by yocontra** [comment]
What commands did you run to update your ssh key?

**Comment by matbeedotcom** [comment]
mathieu@mathieu-VirtualBox:~/node$ nodester app clone anonysms
nodester info initializing git repo for anonysms into folder anonysms
nodester info cloning the repo git clone git@nodester.com:/node/git/matbee/1952-368e68bfa6269daab666e67f004cec3f.git anonysms
nodester info Writing app data to config in anonysms/.nodester.appconfig

mathieu@mathieu-VirtualBox:~/node$ cd anonysms/
mathieu@mathieu-VirtualBox:~/node/anonysms$ ls -a
.  ..  .gitignore  .nodester.appconfig

mathieu@mathieu-VirtualBox:~/node/anonysms$ git remote add nodester git@nodester.com:/node/git/matbee/1952-368e68bfa6269daab666e67f004cec3f.git
mathieu@mathieu-VirtualBox:~/node/anonysms$ git push nodester master
Agent admitted failure to sign using the key.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

It's still empty, please help me get my code off of nodester

Someone please post steps to creating the correct SSH keys. Please. So much undocumented.

**Comment by amoln** [comment]
Contra,

I tried nodester user setkey <path to key> and it returned success as shown below - 

nodester user setkey ~/.ssh/id_nodester_rsa2.pub 
nodester info sending sshkey: /Users/aneurgao/.ssh/id_nodester_rsa2.pub
nodester info ssh key successfully sent

yet trying git push nodester master returns failure message - 
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

I am not able to update my code, and hence fixing bugs is not possible. The reason my app is down I think is because earlier ( few months back) it used to run on port 8080, but now that port has been changed from nodester side to 9884.

**Comment by matbeedotcom** [comment]
Step 1) Created empty RSA KEy.
mathieu@mathieu-VirtualBox:~/node$ ssh-keygen -t rsaGenerating public/private rsa key pair.
Enter file in which to save the key (/home/mathieu/.ssh/id_rsa): 
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /home/mathieu/.ssh/id_rsa.
Your public key has been saved in /home/mathieu/.ssh/id_rsa.pub.
The key fingerprint is:
57:8c:fd:8c:a8:c9:29:ca:12:18:d4:8f:98:f4:17:32 mathieu@mathieu-VirtualBox
The key's randomart image is:
+--[ RSA 2048]----+
|  .              |
| o E .     +     |
|o + = .   . +    |
|.o o o     o +   |
| o  .   S o . o  |
|. .    . =       |
|   .  . =        |
|  .. . .         |
|   .o            |
+-----------------+

---

Step 2) nodester user setkey

mathieu@mathieu-VirtualBox:~/node$ nodester user setkey
nodester info sending sshkey: /home/mathieu/.ssh/id_rsa.pub
nodester info ssh key successfully sent

---

Step 3) Create and initialize git folder.....

mathieu@mathieu-VirtualBox:~/node$ mkdir anonysms
mathieu@mathieu-VirtualBox:~/node$ cd anonysms/
mathieu@mathieu-VirtualBox:~/node/anonysms$ git init
Initialized empty Git repository in /home/mathieu/node/anonysms/.git/

---

Step 4) Git remote add....
mathieu@mathieu-VirtualBox:~/node/anonysms$ git remote add nodester git@nodester.com:/node/git/matbee/1952-368e68bfa6269daab666e67f004cec3f.git

---

Step 5) git push...
mathieu@mathieu-VirtualBox:~/node/anonysms$ git push nodester master
Agent admitted failure to sign using the key.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

---

Step 6) Repeated failure.

---

mathieu@mathieu-VirtualBox:~/node$ nodester app clone anonysms
nodester info initializing git repo for anonysms into folder anonysms
nodester info cloning the repo git clone git@nodester.com:/node/git/matbee/1952-368e68bfa6269daab666e67f004cec3f.git anonysms
nodester info Writing app data to config in anonysms/.nodester.appconfig
mathieu@mathieu-VirtualBox:~/node$ cd anonysms/
mathieu@mathieu-VirtualBox:~/node/anonysms$ ls
mathieu@mathieu-VirtualBox:~/node/anonysms$ cd ..
mathieu@mathieu-VirtualBox:~/node$ 

---

mathieu@mathieu-VirtualBox:~/node$ git clone ec2-user@nodester.com:/node/hosted_apps/matbee/1952-368e68bfa6269daab666e67f004cec3f.git 
Cloning into 1952-368e68bfa6269daab666e67f004cec3f...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
mathieu@mathieu-VirtualBox:~/node$

**Comment by yocontra** [comment]
Our git server might not be accepting the changes. I'll have a look at the key changing right now and make sure it's working

**Comment by monjohn** [comment]
I am trying to launch my first app and think I ran into the same issue. I haven't set up ssh keys before and I misunderstood the directions on entering coupon, saying don't put a password into the ssh key, and left the box empty on submission. I have subsequently generated a key and tried to add it to user using "nodester user setkey". However, when I try to list apps,  I get: { response: '{"status" : "No authentication data sent."}\n', errorCode: 401 }

**Comment by yocontra** [comment]
Have you entered your account information locally before trying to reset the key? setkey should automatically send your stored information up the pipe and it seems like nothing is being sent

**Comment by monjohn** [comment]
I don't like asking dumb questions, so I have gone back over the instructions again, but I don't know how to "enter my account information locally." Any help is appreciated.

**Comment by yocontra** [comment]
Please see https://github.com/nodester/nodester/issues/241
