### ISSUE TITLE
NPM modules which require compile seem to fail

### ISSUE THREAD

**Issue by snelis** [nodester/nodester#199]
nodester npm install impact-node canvas
nodester info installing to app: impact-node
nodester info installing these npm packages: canvas
nodester > canvas@0.7.0 preinstall /node/app/nielslensink/3534-158139f7fc0f0d72f9ac6de468662440_rw/node_modules/canvas
nodester > node-waf configure build
nodester Checking for program g++ or c++          : /usr/bin/g++ 
nodester Checking for program cpp                 : /usr/bin/cpp 
nodester Checking for program ar                  : /usr/bin/ar 
nodester Checking for program ranlib              : /usr/bin/ranlib 
nodester Checking for g++                         : ok  
nodester Checking for node path                   : not found 
nodester Checking for node prefix                 : ok /usr 
nodester Checking for library gif                 : not found 
nodester Checking for library jpeg                : not found 
nodester Checking for cairo                       : not found 
nodester /node/app/nielslensink/3534-158139f7fc0f0d72f9ac6de468662440_rw/node_modules/canvas/wscript:30: error: the configuration failed (see '/node/app/nielslensink/3534-158139f7fc0f0d72f9ac6de468662440_rw/node_modules/canvas/build/config.log')
nodester npm ERR! error installing canvas@0.7.0 Error: canvas@0.7.0 preinstall: `node-waf configure build`
nodester npm ERR! error installing canvas@0.7.0 `sh "-c" "node-waf configure build"` failed with 1
nodester npm ERR! error installing canvas@0.7.0     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error installing canvas@0.7.0     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error installing canvas@0.7.0     at ChildProcess.onexit (child_process.js:192:12)
nodester npm ERR! canvas@0.7.0 preinstall: `node-waf configure build`
nodester npm ERR! `sh "-c" "node-waf configure build"` failed with 1
nodester npm ERR! 
nodester npm ERR! Failed at the canvas@0.7.0 preinstall script.
nodester npm ERR! This is most likely a problem with the canvas package,
nodester npm ERR! not with npm itself.
nodester npm ERR! Tell the author that this fails on your system:
nodester npm ERR!     node-waf configure build
nodester npm ERR! You can get their info via:
nodester npm ERR!     npm owner ls canvas
nodester npm ERR! There is likely additional logging output above.
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.11-83.9.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "canvas"
nodester npm ERR! cwd /node/app/nielslensink/3534-158139f7fc0f0d72f9ac6de468662440_rw
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.18
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /node/app/nielslensink/3534-158139f7fc0f0d72f9ac6de468662440_rw/npm-debug.log
nodester npm not ok

nodester warn you should restart your app after you are finished installing packages.

**Comment by snelis** [comment]
The canvas module im trying to install is this one:
https://github.com/learnboost/node-canvas

**Comment by yocontra** [comment]
```
nodester Checking for library gif : not found 
nodester Checking for library jpeg : not found 
nodester Checking for cairo : not found 
```

Looks like it just has some dependencies that the nodester box isn't running. I'll hop on and install them right now, keep trying and let me know if it spontaneously starts to work

**Comment by yocontra** [comment]
```
$ npm install canvas

> canvas@0.7.2 preinstall /home/contra/node_modules/canvas
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++
Checking for program cpp                 : /usr/bin/cpp
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
Checking for g++                         : ok
Checking for node path                   : not found
Checking for node prefix                 : ok /usr
Checking for library gif                 : not found
Checking for library jpeg                : not found
Checking for cairo                       : yes
'configure' finished successfully (0.892s)
Waf: Entering directory `/home/contra/node_modules/canvas/build'
[1/9] cxx: src/CanvasGradient.cc -> build/default/src/CanvasGradient_1.o
[2/9] cxx: src/Image.cc -> build/default/src/Image_1.o
[3/9] cxx: src/ImageData.cc -> build/default/src/ImageData_1.o
[4/9] cxx: src/Canvas.cc -> build/default/src/Canvas_1.o
[5/9] cxx: src/PixelArray.cc -> build/default/src/PixelArray_1.o
[6/9] cxx: src/CanvasRenderingContext2d.cc -> build/default/src/CanvasRenderingContext2d_1.o
[7/9] cxx: src/init.cc -> build/default/src/init_1.o
[8/9] cxx: src/color.cc -> build/default/src/color_1.o
[9/9] cxx_link: build/default/src/CanvasGradient_1.o build/default/src/Image_1.o build/default/src/ImageData_1.o build/default/src/Canvas_1.o build/default/src/PixelArray_1.o build/default/src/CanvasRenderingContext2d_1.o build/default/src/init_1.o build/default/src/color_1.o -> build/default/canvas.node
Waf: Leaving directory `/home/contra/node_modules/canvas/build'
'build' finished successfully (3.625s)
canvas@0.7.2 ./node_modules/canvas
```

Appears to be fixed, I just had to install the dependencies. Closing this now, let me know if you run across any other bugs
