### ISSUE TITLE
No REST equivalent of `nodester app logs` on API page

### ISSUE THREAD

**Issue by eric-wieser** [nodester/nodester#201]
I'm running from windows with cURL. I want to inspect the logs for my app, but have no way of doing so: the [api page](http://nodester.com/api.html) does not list a url to get the log from.

Could this be added to the api page?

**Comment by eric-wieser** [comment]
I found the url by browsing [nodester-api](https://github.com/nodester/nodester-api): http://api.nodester.com/applogs/appname.

This should definitely go on the API page.

**Comment by yocontra** [comment]
I'll go ahead and add that to the API page now

Quick question: Have you tried installing nodester-cli on windows yet? I'm curious as to it's compatibility

**Comment by yocontra** [comment]
http://nodester.com/api.html#app

Added, closing now.
