### ISSUE TITLE
npm install rss not working?

### ISSUE THREAD

**Issue by jtwebman** [nodester/nodester#205]
I wanted to use the rss npm package. The command runs fine on my local see output:

$ npm install rss
rss@0.0.1 ../node_modules/rss 
├── xml@0.0.5
└── logging@2.0.10

But when I run it with nodester I get this:

$ nodester npm install googleplus2rss rss
nodester info installing to app: googleplus2rss
nodester info installing these npm packages: rss
nodester npm ERR! 404 'rss' is not in the npm registry.
nodester npm ERR! 404 You should bug the author to publish it.
nodester npm ERR! 404 Note that you can also install from a tarball or folder.
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.11-83.9.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "rss"
nodester npm ERR! cwd /node/app/jtwebman/3672-ef78e464596020a6bce989932b9021dd_rw
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.18
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /node/app/jtwebman/3672-ef78e464596020a6bce989932b9021dd_rw/npm-debug.log
nodester npm not ok

nodester warn you should restart your app after you are finished installing packages.

**Comment by jtwebman** [comment]
For now I will just pull in the js files manually and register them with ./ so it will work though it looks like you guys are totally down now :(

**Comment by yocontra** [comment]
How recent is the rss package? We run a separate NPM registry and sync it regularly but if the package has been created within the last 24 hours it won't be synced

**Comment by jtwebman** [comment]
It's been there un-modified for over 145 days. http://search.npmjs.org/#/rss

**Comment by yocontra** [comment]
I'll see if @DanBUK can sync up NPM again, I have a feeling the last one didn't finish completely

**Comment by jtwebman** [comment]
This looks fixed now :)
