### ISSUE TITLE
install.js error with sed

### ISSUE THREAD

**Issue by divadrei** [nodester/nodester#206]
STDERR: "sed: -e expression #1, char 26: unknown option to `s'

Solution :

index 1be70d1..4a5163b 100755
--- a/bin/install.js
+++ b/bin/install.js
@@ -82,7 +82,7 @@ add_c(host_base, 'sudo chmod -R 0700 ' + app_homedir + '/.ssh', '', false);

 add_c(host_app, 'git clone http://github.com/nodester/nodester.git ./nodester', '', true);
 add_c(host_app, 'cp ./nodester/example_config.js ./nodester/config.js', '', true);
-add_c(host_app, 'sed -i -e "s/\\/var\\/nodester/' + app_homedir.replace('/', '\\/') + '/g" ./nodester/config.js', '', false);
+add_c(host_app, 'sed -i -e "s#/var/nodester#' + app_homedir + '#g" ./nodester/config.js', '', false);
 add_c(host_app, 'sed -i -e "s/couch_user: \'nodester/couch_user: \'' + couch_db_user + '/" ./nodester/config.js', '', false);
 add_c(host_app, 'sed -i -e "s/couch_pass: \'password/couch_pass: \'' + couch_db_pass + '/" ./nodester/config.js', '', false);
 add_c(host_app, 'sed -i -e "s/couch_host: \'127.0.0.1/couch_host: \'' + couch_db_host + '/" ./nodester/config.js', '', false);

**Comment by yocontra** [comment]
The installation is WAY out of date. We're working on that now

**Comment by divadrei** [comment]
Great news I can't get nodester running....

**Comment by yocontra** [comment]
V2 will have a fully automated install. I recommend waiting until then before trying to run your own.
