### ISSUE TITLE
Nodester app management offline

### ISSUE THREAD

**Issue by jtwebman** [nodester/nodester#207]
I created a application this morning called googleplus2rss and I can push to the git and get info but it never starts and I get no log ether. See commands:

$ nodester app start googleplus2rss
nodester info Attemping to start app: googleplus2rss
nodester ERROR socket hang up

Though I was getting earlier: nodester info app started.

$ nodester app info googleplus2rss
nodester info Gathering information about: googleplus2rss
nodester info googleplus2rss on port 11825 running: failed-to-start (pid: unknown)
nodester info gitrepo: git@nodester.com:/node/git/jtwebman/3672-ef78e464596020a6bce989932b9021dd.git
nodester info appfile: googleplusrss.js

$ nodester app logs googleplus2rss
nodester ERROR [HTTP 500] No logs available.

My code for this is up on Github here as well and runs locally with no issues: https://github.com/jtwebman/GooglePlusToRSSFeed

**Comment by yocontra** [comment]
Changed your issue title to reflect what's going on. I'm expecting a lot of people to have the same issue

Waiting on @DanBUK to wake up until this can be fixed, sorry for the inconvenience.

**Comment by jtwebman** [comment]
No problem thanks for the status!

**Comment by jtwebman** [comment]
How long until you think this will be up. I wanted to try out a few other things it's still down and not responding. :(

**Comment by yocontra** [comment]
Still waiting on @DanBUK, not sure where he is

**Comment by jtwebman** [comment]
Ok cool. I forked Nodester and was going to try and get it up and running locally so that I could help you guys out. I think it would be a fun project to work on :) What would be the thing you need the most help on, i'll start there?

**Comment by yocontra** [comment]
We're working on doing a complete overhaul for Nodester 2.0

What we're doing first is breaking out all core functionality into npm packages and making them as generic as possible (for example a unionfs package or a chroot package) just to make writing a 2.0 as simple as possible

**Comment by jtwebman** [comment]
Is that already started in the code base here?

**Comment by yocontra** [comment]
Not yet, we'll be starting from scratch once we fix the current system

**Comment by jtwebman** [comment]
Well lets see if I can't get it running and help you guys out then.

**Comment by funkytek** [comment]
Seems everything is fixed, closing now.

**Comment by jtwebman** [comment]
This was not closed? The nodester app logs is still erroring as well as the start isn't starting the service

**Comment by funkytek** [comment]
this was working based on our tests, sorry it didn't work for you will follow up in other thread
