### ISSUE TITLE
Hostname not known

### ISSUE THREAD

**Issue by johnstuarthunter** [nodester/nodester#208]
I created an app called couchracing just now by:  
   nodester app init couchracing
All seemed to go well.
When it finished it told me a useful command would be: 
   curl http://couchracing.nodester.com/
When I run it it says: 
   hostname not known

Same from the browser.

Thanks.

**Comment by yocontra** [comment]
Please see https://github.com/nodester/nodester/issues/207

**Comment by yocontra** [comment]
Went ahead and got it running manually for you. You still won't be able to push any code up (sadly) due to the issue I linked

Everything should be operational within 24 hours

**Comment by johnstuarthunter** [comment]
Tried it 10 minutes later - WORKS NOW!

THANKS!
