### ISSUE TITLE
Host Name not Known / failure - application already running.

### ISSUE THREAD

**Issue by wesbos** [nodester/nodester#210]
Hey Guys, I'm following the super basic example from the website and I cant seem to get it running

> nodester app create mytestapp
> //good
>  nodester app init mytestapp
> //nodester ERROR [HTTP 408] failure - application already running.

when i go to mytestapp.nodester.com it gives me host name is not known.

Here is a video detailing my problems. Am I doing something wrong? 

http://www.screenr.com/bfCs

**Comment by yocontra** [comment]
https://github.com/nodester/nodester/issues/207
