### ISSUE TITLE
app init should fail or at least warn when being run over existing repo

### ISSUE THREAD

**Issue by martypdx** [nodester/nodester#211]
Creating a nodester app for existing repo then running nodester app init clobbers existing server.js and does other damage, and then pushes those changes to github as well.

Looking for a kinder, gentler app init

**Comment by yocontra** [comment]
I've experienced this myself. I agree, this needs to be fixed. Re-submit this under the nodester-cli repo and I'll get to it at some point today

**Comment by martypdx** [comment]
Ok, moved to nodester-cli.
