### ISSUE TITLE
Nodester app not showing up on site

### ISSUE THREAD

**Issue by jtwebman** [nodester/nodester#213]
My new applications are not showing up on *.nodester.com. Here is the info I am getting back with a curl for each one as they are different errors coming back from each.
### Here is the info for the jtwebman start application

``` bash
$ nodester app info
nodester info Gathering information about: jtwebman
nodester info jtwebman on port 11907 running: true (pid: 2392)
nodester info gitrepo: git@nodester.com:/node/git/jtwebman/3754-3ba96823a165be92a0504f0712efd1e9.git
nodester info appfile: server.js

$ nodester app logs
nodester info Showing logs for: jtwebman
New PID: 2392
chroot_runner
chroot_runner

$ curl -i jtwebman.nodester.com
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain
Connection: keep-alive
Transfer-Encoding: chunked

An error has occurred: {"stack":"Error: ECONNREFUSED, Connection refused\n    at Socket._onConnect (net.js:601:18)\n    at IOWatcher.onWritable [as callback] (net.js:186:12)","message":"ECONNREFUSED, Connection refused","errno":111,"code":"ECONNREFUSED","syscall":"connect"}
```
### Here is the info for googleplusrss applications:

``` bash
$ nodester app info
nodester info Gathering information about: googleplusrss
nodester info googleplusrss on port 11908 running: true (pid: 2782)
nodester info gitrepo: git@nodester.com:/node/git/jtwebman/3755-5d89ebef597064815371ffff22be1154.git
nodester info appfile: googleplusrss.js

$ nodester app logs
nodester info Showing logs for: googleplusrss
New PID: 2782
chroot_runner
chroot_runner

$ curl -i googleplusrss.nodester.com
HTTP/1.1 404 Not Found
Content-Type: text/plain
Connection: keep-alive
Transfer-Encoding: chunked

hostname not known
```

**Comment by yocontra** [comment]
http://googleplusrss.nodester.com/ is online as of the last proxy reset. It seems we need to fix the file watching mechanism that dynamically updates the proxy tables, will keep this open.

**Comment by jtwebman** [comment]
Nice thanks. Now it's time to put it in a real site express. I am loving Node.js now it's time to find a job doing it :)

**Comment by jtwebman** [comment]
Bummer it went down as soon as I pushed a change :(

**Comment by funkytek** [comment]
@jtwebman http://googleplusrss.nodester.com/ seems to be up and we are able to create and start new apps in our tests - can you make sure your cli is updated to the latest version ($ npm install -g nodester-cli) and try again

**Comment by yocontra** [comment]
Fixed it in the latest set of commits, closing now.

**Comment by jtwebman** [comment]
Thanks guys looks good :)
