### ISSUE TITLE
Add enforcement to ports

### ISSUE THREAD

**Issue by marcosvm** [nodester/nodester#214]
Every app should be listening to it's assigned port given during the app setup to avoid apps binding to the wrong port.

**Comment by chrismatthieu** [comment]
Actually we should add @DavGlass' update back into the project where the app's ports are overridden by proxy.js based on the proxy table or app table in couch.

**Comment by yocontra** [comment]
It looks like the code is still there, any reason why it was put out of use? I can either use @davglass' old code or write a new temporary sandboxing system while we work on our final implementation for nodester 2.0

**Comment by yocontra** [comment]
Looked into it, AFAIK the chroot_runner DOES enforce ports. Marcos - your issue was entirely unrelated and an issue with the proxy assigning two apps to the same port. Closing this now since it is a non-issue
