### ISSUE TITLE
Remove domain from app when app is deleted

### ISSUE THREAD

**Issue by tonyto** [nodester/nodester#215]
I had a domain assigned to an app, but after I deleted the app, the domain does not get released to reassign to another app.
Could this be because some sort of active/inactive flag gets assigned to the app upon deletion, rather than recycling the host name?

**Comment by yocontra** [comment]
Subdomain (*.nodester.com) or custom domain?

**Comment by tonyto** [comment]
a custom domain

**Comment by yocontra** [comment]
You can delete it via the cli using the same functions you used to create it. I do agree that it should automatically delete it though, I'll leave this open and tag it for my next batch of fixes

Command should be `nodester appdomain delete <appname> <domain-name>`

**Comment by tonyto** [comment]
I tried running that command to delete the custom domain, but that can't be executed when the app has already been deleted.

**Comment by yocontra** [comment]
You can try to create the app again and then run the appdomain delete. Working on a fix right now

**Comment by tonyto** [comment]
ah yea, that could be a solution, I'll look into it...

Thanks for being so responsive. Keep up the good work

**Comment by yocontra** [comment]
AFAIK This has been fixed. Let me know if you are still having the issue
