### ISSUE TITLE
Coffeescript app won't start

### ISSUE THREAD

**Issue by marcosvm** [nodester/nodester#216]
curl http://coffeescript.nodester.com

An error has occurred: {"stack":"Error: ECONNREFUSED, Connection refused\n    at Socket._onConnect (net.js:601:18)\n    at IOWatcher.onWritable [as callback](net.js:186:12)","message":"ECONNREFUSED, Connection refused","errno":111,"code":"ECONNREFUSED","syscall":"connect"}

$ nodester npm list
nodester info list npm packages for app: coffeescript
nodester └── coffee-script@1.1.2 
nodester

**Comment by yocontra** [comment]
Can you show your app logs?

**Comment by marcosvm** [comment]
There goes the logs:

$ nodester app logs
nodester info Showing logs for: coffeescript
New PID: 4207
chroot_runner
chroot_runner
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Error: Restarted too many times, bailing.

On Thu, Sep 15, 2011 at 7:45 PM, Contra
reply@reply.github.com
wrote:

**Comment by reaktivo** [comment]
I'm getting exactly this error, for another app in coffeescript. Has anyone find out what is causing this?

**Comment by yocontra** [comment]
It looks like runInNewContext (a NodeJS util for running code) only accepts javascript. Finished a fix, just need to test it!

**Comment by reaktivo** [comment]
Didn't work for me, still getting 
Process died with exit code 127. Restarting... [5 times]
Error: Restarted too many times, bailing.

**Comment by yocontra** [comment]
@reaktivo - Sorry for the misunderstanding, I meant that I need to do testing before I pull it into the production server. Shouldn't take long, for now just compile it before you run it or start your file with require('coffee-script'); before you use any coffee-script code.

**Comment by pl** [comment]
@Contra – I'm having the same problem, is there any chance to push the patch into the production soon? I'm simplifying my apps and being able not to compile coffee files would be very handy…

**Comment by yocontra** [comment]
Since NodeJS doesn't support runInNewContext with coffee-script essentially we would just compile it at runtime and pass in the resulting JS. I have the code commented out in the repo right now because I'd rather find a more elegant way of doing it or wait until coffee-script adds support for runInNewContext. If I get a chance to do more testing and it seems like the only way I will pull it into production ASAP

**Comment by yocontra** [comment]
Closed, most likely won't be fixed before V2. I guess you have to compile until then since we are focusing all of our time on that
