### ISSUE TITLE
App is not running

### ISSUE THREAD

**Issue by marcosvm** [nodester/nodester#217]
curl http://techbinding.nodester.com

"blank", nothing, nada.

I think it's related to the port hijacking issue we're having

**Comment by yocontra** [comment]
Closed, post in the related issue https://github.com/nodester/nodester/issues/214

What site did you say was hijacking your port again?

**Comment by marcosvm** [comment]
Last time was sudoku. We'll have to netstat -anp to find which process
is listening on port 8888

On Thu, Sep 15, 2011 at 7:46 PM, Contra
reply@reply.github.com
wrote:

**Comment by yocontra** [comment]
Nothing is listening on 8888

Looking through the proxy table it seems it had a hiccup and assigned 8888 twice. I'll remove the other 8888 to a new port since you had it first
