### ISSUE TITLE
I can't start any app or read logs

### ISSUE THREAD

**Issue by texli** [nodester/nodester#218]
The last couple of days I've been unable to start any of my apps and instead I'm getting this message:

```
$ nodester app restart texli
nodester info Attemping to restart app: texli
nodester info { response: undefined, errorCode: null }
nodester ERROR socket hang up
```

I'm using:

```
nodester-cli@0.2.34
├── colors@0.3.0
├── iniparser@1.0.1
└── nodester-api@0.1.15
```

It may be my code but one of my repos hasn't really changed and have worked previously. If it helps i think this started a couple of days before the "500 Application is offline"-error page went live.

Thanks!

**Comment by cybear** [comment]
I'm having the same problem. Here's a gist of my entire log:
https://gist.github.com/1232588

**Comment by ghost** [comment]
Same here. One of my apps is available and 2 others do not.

**Comment by yocontra** [comment]
I've updated the API. Please reinstall nodester-cli and try again

**Comment by yocontra** [comment]
Closing issue, seems to be resolved.
