### ISSUE TITLE
Can't use CNAME with app hosted on Nodester

### ISSUE THREAD

**Issue by dimastopel** [nodester/nodester#221]
Hello

If this is not the correct place for such questions I'd be glad if you could redirect me. 

My app is hosted on Nodester, under the following URL: http://dimastopel.nodester.com/

It works well. 

I've tried to make it accessible through my personal domain name with CNAME record (http://www,stopel.org). However, it returns 404, "application not found". I guess, this happens since the app differentiation happens according to the request URL.

Is there any way to make it accessible not through the original URL (http://dimastopel.nodester.com)? If not, are there any plans to enable this in the future?

Thank you in advance!

**Comment by dimastopel** [comment]
I've just discovered "appdomains". If this is the answer to my issue, please ignore :)

**Comment by dimastopel** [comment]
Appdomains solved the issue, indeed. However, it didn't work before I restarted the app. If this is by design, I think this should be added to the documentation. 

Thanks!

**Comment by marcosvm** [comment]
Dima,

Did you set the domains configuration via nodester-cli?

You'll need to issue the following command:

nodester appdomain add <appname> <domain-name>

where app name is your app name and domain-name is your domain.

Any problem please let us know

-- Marcos

On Fri, Sep 30, 2011 at 1:31 PM, Dima Stopel
reply@reply.github.com
wrote:

**Comment by yocontra** [comment]
Yep, the "appdomains" command is for this. I've updated the cli to display a message suggesting a restart on appdomain changes (https://github.com/nodester/nodester-cli/commit/c16e4e3fd699e6bd29479c415da16b94c0786454)

Closing this now.

**Comment by dimastopel** [comment]
This is great! Thanks
