### ISSUE TITLE
Add git support 

### ISSUE THREAD

**Issue by alejandro** [nodester/nodester#222]
Add more support for git commands like `git submodule` or `git pack-refs` since we use `git` for connect apps with ->  nodester. Thanks

**Comment by yocontra** [comment]
Nodester should be a standard git server. What errors are you getting when you try those commands?

**Comment by alejandro** [comment]
Correct me If I'm wrong but we're not allowed to do any git command. (e.g.
via CLI `nodester app gitreset` [It's OK] but what about `nodester app git
submodule update` [? Not OK]) via `cURL` I don't know.

**Comment by chrismatthieu** [comment]
Nodester includes a standard git server.  This allows us to do things like git push nodester master.  Have you tried straight git commands to nodester when working with remote submodules?

**Comment by chrismatthieu** [comment]
Nevermind, just tested it.  Nodester does not currently support submodules.  You'll need to include the code from your submodules in your actual git repo and repush.

**Comment by alejandro** [comment]
Yeah I tried without success ! As I said before what I was trying to do is `git pack-refs` but I'm not allowed to do any standard git command. But it's ok because I did what you say in your last comment.
