### ISSUE TITLE
Set merge strategy for git operations to "theirs"

### ISSUE THREAD

**Issue by dobesv** [nodester/nodester#224]
Currently it is possible to create a conflicted state when pushing to nodester if you amend a commit.  This puts things in an sort of unrecoverable state from what I can tell.

I think it should be possible to avoid this by specifying the merge strategy of "theirs" or possibly using some other git command to switch to the new HEAD, like git reset --hard or git checkout -f.

**Comment by dobesv** [comment]
Note that deleting and creating the app again can fix this, although it is a nuisance resetting the port numbers and git remote URL.

**Comment by yocontra** [comment]
`nodester app gitreset` should fix this. That's a garbage response, but V2 won't have git at all so this issue will go unfixed until then. Sorry for the inconvenience.
