### ISSUE TITLE
Unable to install nodester-cli

### ISSUE THREAD

**Issue by rmadhuram** [nodester/nodester#225]
Hi,

I'm getting the following errors. Any pointers would be appreciated. 

Thanks,
Raj

---

raj@raj-VirtualBox:~/projects/nodejs$ sudo npm install nodester-cli -g
npm ERR! error installing nodester-api@0.1.15 Error: Not found: querystring@''
npm ERR! error installing nodester-api@0.1.15 Valid install targets:
npm ERR! error installing nodester-api@0.1.15 ["latest"]
npm ERR! error installing nodester-api@0.1.15     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:410:10)
npm ERR! error installing nodester-api@0.1.15     at /usr/local/lib/node_modules/npm/lib/cache.js:403:17
npm ERR! error installing nodester-api@0.1.15     at saved (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:136:7)
npm ERR! error installing nodester-api@0.1.15     at Object.cb [as oncomplete](/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:36:9)
npm ERR! error installing nodester-cli@0.2.34 Error: Not found: querystring@''
npm ERR! error installing nodester-cli@0.2.34 Valid install targets:
npm ERR! error installing nodester-cli@0.2.34 ["latest"]
npm ERR! error installing nodester-cli@0.2.34     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:410:10)
npm ERR! error installing nodester-cli@0.2.34     at /usr/local/lib/node_modules/npm/lib/cache.js:403:17
npm ERR! error installing nodester-cli@0.2.34     at saved (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:136:7)
npm ERR! error installing nodester-cli@0.2.34     at Object.cb [as oncomplete](/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:36:9)
npm ERR! Error: Not found: querystring@''
npm ERR! Valid install targets:
npm ERR! ["latest"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:410:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:403:17
npm ERR!     at saved (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:136:7)
npm ERR!     at Object.cb [as oncomplete](/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:36:9)
npm ERR! Report this _entire_ log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Linux 3.0.0-12-generic
npm ERR! command "node" "/usr/local/bin/npm" "install" "nodester-cli" "-g"
npm ERR! cwd /home/raj/projects/nodejs
npm ERR! node -v v0.5.10-pre
npm ERR! npm -v 1.0.101
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/raj/projects/nodejs/npm-debug.log
npm not ok

**Comment by yocontra** [comment]
Please reopen this in the nodester-cli repository. In the mean time, this is a quick fix and it should be up shortly!

**Comment by yocontra** [comment]
Sorry, I meant nodester-api. I just pushed a fix up for this, reinstall nodester-cli and try again.

**Comment by rmadhuram** [comment]
Thanks! It worked.
