### ISSUE TITLE
./start.sh is not working on nodester.com

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester#23]

**Comment by DanBUK** [comment]
My IRC is down at the moment, i'll login and take a look

**Comment by DanBUK** [comment]
I had to
    rm -Rf deps/nodemon
    git submodule init
    git submodule update
(Need to repoint the submodule to a more recent version of nodemon, it's using daemon-tools now rather than daemon)

Also there was a new config paramater in example_config.js - username, I have updated config.js to reflect.

Everything is a back up now.
