### ISSUE TITLE
500 response for my app (and chat.nodester.com)

### ISSUE THREAD

**Issue by JavascriptMick** [nodester/nodester#231]
My site (its new and I am a noob) showing 500 response, despite indicating its up.  I also noticed that http://chat.nodester.com/ is similarly returning a 500 response, no idea if they are related.

michael@michael-VirtualBox:~$ nodester apps list
nodester info spodgic on port 12623 running: true

michael@michael-VirtualBox:~$ nodester app logs spodgic
nodester info Showing logs for: spodgic
New PID: 15585
chroot_runner
chroot_runner
Server running at http://127.0.0.1:8000/

michael@michael-VirtualBox:~$ nodester app info spodgic
nodester info Gathering information about: spodgic
nodester info spodgic on port 12623 running: true (pid: 15585)
nodester info gitrepo: git@nodester.com:/node/git/mdausmann/4470-70b821ef04a6168ee42ae9c06192758a.git
nodester info appfile: server.js

michael@michael-VirtualBox:~$ curl http://spodgic.nodester.com
<html><head><title id="title">Application Error</title></head><body><br/></br/></br/></br/></br/><center><img src="http://nodester.com/images/rocket-md-right.png" alt="logo" /></br/><h1 style ="color:#000;font-family:Arial,Helvetica,sans-serif;font-size:38px;font-weight:bold;letter-spacing:-2px;padding:0 0 5px;margin:0;">500</h1><h3 style ="color:#000;font-family:Arial,Helvetica,sans-serif;font-size:24px;font-weight:bold;padding:0 0 5px;margin:0;">Application is offline</h3></center></body></html>michael@michael-VirtualBox:~$ clear

**Comment by chrismatthieu** [comment]
I stopped and started chat.nodester.com and it's running now.

Have you updated your port in your app to run on the one that we assigned your app (12623)?

Regards,
Chris

**Comment by JavascriptMick** [comment]
Thanks Chris, that did the trick.
