### ISSUE TITLE
nodester npm list fails

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester#232]
Using nodester-cli@0.2.34

nodester npm list
nodester info list npm packages for app: 

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object [object Object] has no method 'appnpm_list'
    at Object.list (/usr/local/lib/node/.npm/nodester-cli/0.2.34/package/lib/npm.js:85:13)
    at Object.run (/usr/local/lib/node/.npm/nodester-cli/0.2.34/package/lib/commands.js:99:51)
    at Object.<anonymous> (/usr/local/lib/node/.npm/nodester-cli/0.2.34/package/bin/nodester.js:12:5)
    at Module._compile (module.js:411:26)
    at Object..js (module.js:417:10)
    at Module.load (module.js:343:31)
    at Function._load (module.js:302:12)
    at Array.<anonymous> (module.js:430:10)
    at EventEmitter._tickCallback (node.js:126:26)

**Comment by yocontra** [comment]
`npm install nodester-cli -g` should clear it up by updating the API.

**Comment by chrismatthieu** [comment]
npm says that nodester-cli@0.2.34 is the latest cli

**Comment by yocontra** [comment]
The API was updated not the CLI. Doing an install again will update the API as a dependency of the CLI

**Comment by chrismatthieu** [comment]
Re-installed nodester-cli, created a new app, and nodester npm list failed again.  Here are my steps and results:

sudo npm install nodester-cli -g
Password:
npm info it worked if it ends with ok
npm info using npm@0.3.18
npm info using node@v0.4.9
npm info preinstall nodester-cli@0.2.34
npm info install nodester-cli@0.2.34
npm info postinstall nodester-cli@0.2.34
npm info preactivate nodester-cli@0.2.34
npm info activate nodester-cli@0.2.34
npm info postactivate nodester-cli@0.2.34
npm info build Success: nodester-cli@0.2.34
npm ok
topher:src topher$ nodester app create nodeaz
nodester info creating app: nodeaz server.js
nodester info successfully created app nodeaz to will run on port 12667 from server.js
nodester info run nodester app init nodeaz to setup this app.
topher:src topher$ cd nodeaz
-bash: cd: nodeaz: No such file or directory
topher:src topher$ cd ..
topher:local topher$ cd src
topher:src topher$ nodester app init nodeaz
nodester info initializing git repo for nodeaz into folder nodeaz
nodester info cloning the repo git clone git@nodester.com:/node/git/topher/4514-c5d8e9286367f4294dadcbdff2701e7d.git nodeaz
nodester info clone complete
nodester info Writing app data to config in nodeaz/.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
nodester info nodeaz started.
nodester info Some helpful app commands:

```
 cd ./nodeaz
 curl http://nodeaz.nodester.com/
  nodester app info
  nodester app logs
  nodester app stop|start|restart
```

topher:src topher$ cd nodeaz
topher:nodeaz topher$ nodester npm list
nodester info list npm packages for app: nodeaz

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object [object Object] has no method 'appnpm_list'
    at Object.list (/usr/local/lib/node/.npm/nodester-cli/0.2.34/package/lib/npm.js:85:13)
    at Object.run (/usr/local/lib/node/.npm/nodester-cli/0.2.34/package/lib/commands.js:99:51)
    at Object.<anonymous> (/usr/local/lib/node/.npm/nodester-cli/0.2.34/package/bin/nodester.js:12:5)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)
topher:nodeaz topher$

**Comment by d-adamkiewicz** [comment]
Nodester online API docs do not mention 'nodester npm list' command http://nodester.com/api.html

**Comment by yocontra** [comment]
Try these

`npm remove nodester-cli -g`
`npm remove nodester-api -g`
`npm install nodester-cli -g`

That bug is with the older API. For some reason your npm really doesn't want to upgrade it to the latest version

**Comment by chrismatthieu** [comment]
npm rm nodester-api -g returned these errors (related to bejes.us)

npm rm nodester-api -g
npm info it worked if it ends with ok
npm info using npm@0.3.18
npm info using node@v0.4.9
npm ERR! Error: nodester-api@0.1.1 depended upon by bejesus-cli@0.1.3.
npm ERR! Cannot remove
npm ERR!     at /usr/local/lib/node/.npm/npm/0.3.18/package/lib/uninstall.js:101:28
npm ERR!     at cb (/usr/local/lib/node/.npm/npm/0.3.18/package/lib/utils/async-map.js:48:28)
npm ERR!     at /usr/local/lib/node/.npm/npm/0.3.18/package/lib/uninstall.js:89:42
npm ERR!     at /usr/local/lib/node/.npm/npm/0.3.18/package/lib/utils/load-package-defaults.js:35:25
npm ERR!     at cb (/usr/local/lib/node/.npm/npm/0.3.18/package/lib/utils/async-map.js:48:28)
npm ERR!     at /usr/local/lib/node/.npm/npm/0.3.18/package/lib/utils/load-package-defaults.js:34:59
npm ERR!     at /usr/local/lib/node/.npm/npm/0.3.18/package/lib/utils/async-map.js:53:35
npm ERR!     at Array.forEach (native)
npm ERR!     at /usr/local/lib/node/.npm/npm/0.3.18/package/lib/utils/async-map.js:53:11
npm ERR!     at Array.forEach (native)
npm ERR! Report this _entire_ log at http://github.com/isaacs/npm/issues
npm ERR! or email it to npm-@googlegroups.com
npm ERR! Just tweeting a tiny part of the error will not be helpful.
npm ERR! System Darwin 11.2.0
npm ERR! argv { remain: [ 'nodester-api' ],
npm ERR! argv   cooked: 
npm ERR! argv    [ 'rm',
npm ERR! argv      'nodester-api',
npm ERR! argv      '-g' ],
npm ERR! argv   original: 
npm ERR! argv    [ 'rm',
npm ERR! argv      'nodester-api',
npm ERR! argv      '-g' ] }
npm not ok

**Comment by chrismatthieu** [comment]
This worked for me:

npm rm bejesus-cli@0.1.3 -g
npm rm nodester-cli -g 
npm rm nodester-api -g 
npm install nodester-cli -g

nodester npm list

nodester info list npm packages for app: shelly
nodester ├── crypto@0.0.1 
nodester ├─┬ express@2.4.3 
nodester │ ├── connect@1.6.0 
nodester │ ├── mime@1.2.2 
nodester │ └── qs@0.3.0 
nodester ├── imageable@0.3.4 
nodester └── jade@0.13.0 
nodester /bin/sh: line 0: cd: /node/app/topher/4594-614b9cbdf6b3d66f07d4eae172512fe7_rw: No such file or directory
