### ISSUE TITLE
Unable to start created new application

### ISSUE THREAD

**Issue by vipankumar87** [nodester/nodester#233]
when i run following command
nodester app start
then its end with 
nodester info attempting to start app: vipan
nodester warn false

there is any solution my app vipan is still offline
this is following url for my app
http://vipan.nodester.com/

**Comment by yocontra** [comment]
Run a `npm install nodester-cli -g` and try again. It won't fix the problem but the new CLI/API has more verbose error messages that might help me out

**Comment by mariandev** [comment]
I have the same problem

$ nodester app start

nodester info Attemping to start app: mysuperapp
nodester warn false

**Comment by mariandev** [comment]
I installed nodejs 0.6.2 and npm 1.0.106 and the error is: 

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:376:11)
    at Object.<anonymous> (/home/mariandev/bin/nodester@0.2.34:4:21)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Array.0 (module.js:470:10)
    at EventEmitter._tickCallback (node.js:192:40)

P.S. : Sorry for  my english .

**Comment by yocontra** [comment]
nodester-cli and it's dependencies haven't been tested for the new nodejs.

**Comment by mariandev** [comment]
Ok. Thank you for answer. Now i will wait. I hope that the error will be fixed soon.

**Comment by Befzz** [comment]
Have same issue
nodester-cli 0.2.34
node versions: tryed up to 0.6.4

```
C:\Users\befree\Documents\nodester_use>nodester app start test_app_name
The "sys" module is now called "util". It should have a similar interface.
nodester info Attemping to start app: test_app_name
nodester warn false
```

Also i can't delete an application: request timeout

**Comment by yocontra** [comment]
Please see https://github.com/nodester/nodester/issues/241
