### ISSUE TITLE
git commands connection closed unexpectedly

### ISSUE THREAD

**Issue by sheldon** [nodester/nodester#235]
I've just signed up a new account from the keys dished out on friday. thanks a lot for the account!

I'm having trouble getting git commands to work, e.g.:

git clone git@nodester.com:/node/git/sheldon/4582-7b341c5c280285bef29c1f20f1a27dfa.git

Cloning into 'sheldon'...
Connection closed by 50.16.203.53
fatal: The remote end hung up unexpectedly

I can interact with nodester via the cli and the http api just fine, but all ssh/git commands are closing before giving any output. I've tried resetting my ssh key, but that doesn't seem to be the problem anyway, as I can connect just fine. It's after the connection that it gets closed as far as I can tell.

**Comment by sheldon** [comment]
some more debugging, seems like my ssh-key is the problem. a "ssh git@nodester.com -v" shows that I get disconnected right after offering my ssh key.

**Comment by yocontra** [comment]
Have you tried updating your SSH key?

**Comment by sheldon** [comment]
I did yep, via the cli and the api directly following the instructions on the site. I'm not too sure beyond that what's wrong from this side, but if you need me to test connecting or want my ssh public key to test with separately just let me know.

**Comment by yocontra** [comment]
Discussion of this issue has moved to https://github.com/nodester/nodester/issues/241
