### ISSUE TITLE
unable to git push or npm install

### ISSUE THREAD

**Issue by willwhitney** [nodester/nodester#239]
Having created an account, set up my account and RSA key, created an app with appropriate remote, when I try to git push nodester, I get 

Connection closed by 50.16.203.53
fatal: The remote end hung up unexpectedly

I can still list my apps and issue restart commands, but not push code. When I try "nodester npm install windowsync socket.io", I get 

nodester info installing to app: windowsync
nodester info installing these npm packages: socket.io
nodester /bin/sh: line 0: cd: /node/app/wfwhitney/4599-42305438a3453f72b36181db1b96a4a3_rw: No such file or directory
nodester npm ERR! Could not create /node_modules/___socket.io.npm
nodester npm ERR! error installing socket.io@0.8.7 Error: EACCES, Permission denied '/node_modules/___socket.io.npm'
nodester npm ERR! Error: EACCES, Permission denied '/node_modules/___socket.io.npm'
nodester npm ERR! Report this _entire_ log at:
nodester npm ERR!     http://github.com/isaacs/npm/issues
nodester npm ERR! or email it to:
nodester npm ERR!     npm-@googlegroups.com
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-103.47.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "socket.io"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.93
nodester npm ERR! path /node_modules/___socket.io.npm
nodester npm ERR! code EACCES
nodester npm ERR! Error: EACCES, Permission denied 'npm-debug.log'
nodester npm ERR! Report this _entire_ log at:
nodester npm ERR!     http://github.com/isaacs/npm/issues
nodester npm ERR! or email it to:
nodester npm ERR!     npm-@googlegroups.com
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-103.47.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "socket.io"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.93
nodester npm ERR! path npm-debug.log
nodester npm ERR! code EACCES
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /npm-debug.log
nodester npm not ok

Any insight?

**Comment by maleck13** [comment]
I am also having this problem

**Comment by rnrodrigues** [comment]
Me too

**Comment by ghost** [comment]
Me three

**Comment by yocontra** [comment]
Your _rw app folder gets created on git push. Since nothing has been pushed, the folder doesn't exist and npm installs to it are failing. Try pushing code first and trying again.

If you keep getting the git disconnect send me your RSA key via GitHub and I'll make sure everything is working properly.

**Comment by mechanicles** [comment]
Me too having same problem :(

**Comment by mechanicles** [comment]
Any solution? I waiting for solution. :(

**Comment by yocontra** [comment]
Working on it now, sorry for the inconvenience. Will update with details

**Comment by yocontra** [comment]
Discussion of this issue has moved to https://github.com/nodester/nodester/issues/241
