### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by jgoodall** [nodester/nodester#240]
I registered after getting coupon on the web, but I used spaces in the password. The result returned ok, but now I cant seem to set up my account on the CLI. If I try to use double or single quotes of escape spaces with a \, I get:
nodester info verifying credentials
nodester info { response: undefined, errorCode: undefined }
nodester ERROR Fatal Error! API Response: undefined

Because I cant set up the account, I cant reset the password. Seem to be stuck.

**Comment by yocontra** [comment]
Disturbing how this slipped through the cracks... will take a look at fixing it now!

**Comment by yocontra** [comment]
Fixed in 8bf41369a0c6e753f507801bebd1339fd2fbfc9d. I'll message you about changing your password. Sorry for the inconvenience!

EDIT: Looks like you disabled github messaging. Shoot me a message when you get a chance with your preferred password and I'll take care of it for you.
