### ISSUE TITLE
Git repo not created after cloning project

### ISSUE THREAD

**Issue by quantumpotato** [nodester/nodester#242]
Steps:

-Clone a nodester app with nodester app clone APPNAME eg 
-Go into the directory
-Run git
-No git repo initialized

```
>nodester app clone node-rps
>cd node-rps
>git
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by yocontra** [comment]
Discussion of this issue has moved to https://github.com/nodester/nodester/issues/241
