### ISSUE TITLE
Install.txt upgrade?

### ISSUE THREAD

**Issue by akumpf** [nodester/nodester#243]
Nodester is a great platform.  I can't say enough good things about you guys. :)

There is one major gap though that I think would be great for the team to look into: make deployment of Nodester on other servers super easy!  

It's seems core to Nodester that it's a PaaS that allows "anyone to host apps", but so far in the few evenings I've spent on trying to get it up and running on my own server, it hasn't been very straight-forward.

This might be as simple as updating the Install.txt file (there's currently a note at the top explaining that it is "horribly out of date"), or even better, a shell script that automates the whole process on a fresh Linux install (Ubuntu would be nice :).

Trying to follow the current Install.txt file and making some basic assumptions about new versions (of NPM for example), I have yet to get a Nodester server running. I know V2 is underway, but in the meantime it'd be great to update the install text and/or a shell script to make it accessible to tons of people who want to do the same.

Looking forward to the streamlined install process. You guys are awesome -- keep rocking out!

**Comment by yocontra** [comment]
Besides bug fixes all development on V1 is halted. Look forward to V2 where an install will be as simple as `curl http://nodester.com/install.sh | sudo sh`. We have V2 estimated for late December/early January.

**Comment by akumpf** [comment]
awesome! can't wait ti try it out. :)
