### ISSUE TITLE
Problem with node-expat

### ISSUE THREAD

**Issue by mborho** [nodester/nodester#245]
Hi,

I'm having problem with node-expat. "nodester npm install node-expat" does fine, but when the my app is started, following error occurs:

Error: libexpat.so.1: cannot open shared object file: No such file or directory
    at Object..node (module.js:414:11)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/node_modules/node-expat/lib/node-expat.js:6:14)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)

node-expat is required from node-xmpp.

I'm new to node.js, so actually I don't know if something is missing on my side...

Cheers 
Martin

**Comment by superfeedr** [comment]
mborho, I'm afraid it means nodester has to add libexpat to the server. Libexpat is a XML parser library written in C. It's the probably one of the most efficient libraries for stream parsing.

**Comment by yocontra** [comment]
Native libraries aren't available to free users (yet). V2 will have this fixed! Just hold out a little longer

**Comment by mborho** [comment]
Thanks, good to hear!

**Comment by marcelduran** [comment]
I'm still seeing this problem, is V2 (with the fix) available for free users already?

**Comment by alejandro** [comment]
@marcelduran well, I don't think so! [We've joined to AppFog](http://blog.nodester.com/post/30434216604/nodester-joins-appfog) so I recommend you to go to [appfog.com](https://www.appfog.com/) and create an account.

**Comment by marcelduran** [comment]
thanks @alejandro! I've just created an account and app but same problem there too: `Error: Cannot find module '../build/default/node-expat'`

**Comment by alejandro** [comment]
I advice you to open a new thread on https://groups.google.com/forum/#!forum/appfog-users. And they'll help you...
