### ISSUE TITLE
Unable to nc into server

### ISSUE THREAD

**Issue by quantumpotato** [nodester/nodester#246]
Hi,

When I run locally I can do
node server.js
(new tab): nc localhost 12861

But when try to netcat to the server, nothing happens (just waits)

[11:26][X3N0@SwarmFormer:~/rps-node(master)]$ nodester app info
nodester info Gathering information about: rps-node
nodester info rps-node on port 12861 running: true (pid: 8857)
nodester info gitrepo: git@nodester.com:/node/git/quantumpotato/4708-a775f636c9882269055a5d368c9abce1.git
nodester info appfile: server.js
[11:27][X3N0@SwarmFormer:~/rps-node(master)]$ nc rps-node.nodester.com 12861
^C
[11:27][X3N0@SwarmFormer:~/rps-node(master)]$ nc http://rps-node.nodester.com 12861
[11:29][X3N0@SwarmFormer:~/rps-node(master)]$ nc http://rps-node.nodester.com 12861

How do I connect?

```
var server = net.createServer(function (stream) {
  var client = new Client(stream);
  clients.push(client);

  stream.setTimeout(0);
  stream.setEncoding("utf8");

  stream.addListener("connect", function () {
        stream.write("Welcome! Please enter your name\n> ");
    });

    stream.addListener("data", function (data) {
    if (client.name === null) {
                nameClient(client, data);
                return;
    }

        processInput(client, data);    
     });            
});

server.listen(12861);
```

**Comment by yocontra** [comment]
nc rps-node.nodester.com 80

When any packet for port 80 comes to our server the reverse proxy (bouncy) will forward it to your apps port and anything sent back will be forwarded from port 80. Let me know if this works for you

**Comment by quantumpotato** [comment]
Here's what happens, listening on port 12861: (I changed server.js to listen on 80 and pushed, same thing happened. Reverted to 12861 and pushed)

```
[12:51][X3N0@SwarmFormer:~/rps-node(master)]$ nodester info
nodester info Gathering information about: rps-node
nodester info rps-node on port 12861 running: true (pid: 16053)
nodester info gitrepo: git@nodester.com:/node/git/quantumpotato/4708-a775f636c9882269055a5d368c9abce1.git
nodester info appfile: server.js
[12:51][X3N0@SwarmFormer:~/rps-node(master)]$ nc rps-node.nodester.com 80

<here I press return>

HTTP/1.1 404 Not Found
Connection: keep-alive
Transfer-Encoding: chunked

1fc
<html><head><title id="title">404 - Application not found!</title></head><body><br/><br/><br/><br/><br/><center><img src="http://nodester.com/images/rocket-down.png" alt="logo" /><br/><h1 style ="color:#000;font-family:Arial,Helvetica,sans-serif;font-size:38px;font-weight:bold;letter-spacing:-2px;padding:0 0 5px;margin:0;">404</h1><h3 style ="color:#000;font-family:Arial,Helvetica,sans-serif;font-size:24px;font-weight:bold;padding:0 0 5px;margin:0;">Application does not exist</h3></center></body></html>
0
```

**Comment by yocontra** [comment]
Working on it now, will update when I fix it!

**Comment by yocontra** [comment]
https://github.com/substack/bouncy/issues/19 is relevant

**Comment by quantumpotato** [comment]
Ah so that's the stack nodester is running on?
Thanks for the follow-up

On Thu, Dec 15, 2011 at 1:33 PM, Contra <
reply@reply.github.com

**Comment by yocontra** [comment]
For now use websockets or http as a transfer protocol. Leaving this open though as it is very important that we have a reverse TCP proxy

**Comment by quantumpotato** [comment]
So I'll have to have a frontend app / site to manage the connections then?
Or is there an easy way to do this from the command line. Curls I guess.

**Comment by yocontra** [comment]
What exactly are you trying to make here?

**Comment by quantumpotato** [comment]
a command line rock paper scissors game.
you nc to the server, enter your name then get paired with another player.
Both players enter r/p/s then server tells who won. Repeat.
https://github.com/quantumpotato/node-rps/blob/prompt/rps.js

**Comment by yocontra** [comment]
You might have to design a web interface for it, reverse proxying is impossible for non-http traffic because the incoming message doesn't have a host property.
