### ISSUE TITLE
Native Modules

### ISSUE THREAD

**Issue by diorahman** [nodester/nodester#248]
Please help us with native modules! :-) at least for zombie.js and hiredis ; and how about imagemagick runtime? :-P

Thank you!

**Comment by yocontra** [comment]
I said a few times this wouldn't be in before V2 but it seems doable to propagate some dependencies across sandboxes. Looking into it now

**Comment by chrismatthieu** [comment]
Contra, do you have an update? Can we close this ticket?

**Comment by chrismatthieu** [comment]
no updates...
