### ISSUE TITLE
My Application can't be stopped

### ISSUE THREAD

**Issue by solisoft** [nodester/nodester#251]
I'm trying to stop and restart my application but it don't work.

$ nodester app info
The "sys" module is now called "util". It should have a similar interface.
nodester info Gathering information about: solicms
nodester info solicms on port 13031 running: false (pid: unknown)
nodester info gitrepo: git@nodester.com:/node/git/obonnaure/4878-b1bcb4416136cd2e7e0158db7f4283ba.git
nodester info appfile: server.js

but http://solicms.nodester.com is up.

If I commit and push my code : no change.

Thank you for your help.

**Comment by chrismatthieu** [comment]
That's strange. Git push should automatically restart your application.  Have you tried nodester app restart or nodester app stop and nodester app start CLI commands?

**Comment by solisoft** [comment]
$ nodester app stop
The "sys" module is now called "util". It should have a similar interface.
nodester info Attemping to stop app: solicms
nodester info app stopped.

In fact the app is still running ...

olivier@iMac:~/workspace/solicms (master)$ nodester app start
The "sys" module is now called "util". It should have a similar interface.
nodester info Attemping to start app: solicms
nodester info app started.

**Comment by yocontra** [comment]
Have you tried a restart?

**Comment by solisoft** [comment]
$ nodester app restart didn't work neither ...
I just stopped the application using : $ nodester app stop

then I do :
$ nodester app  info
The "sys" module is now called "util". It should have a similar interface.
nodester info Gathering information about: solicms
nodester info solicms on port 13031 running: false (pid: unknown)
nodester info gitrepo: git@nodester.com:/node/git/obonnaure/4878-b1bcb4416136cd2e7e0158db7f4283ba.git
nodester info appfile: server.js

The app seems down ... but actually the app is up (http://solicms.nodester.com) I think that there is a problem with processes running in the background.

**Comment by chrismatthieu** [comment]
Sounds like this issue could be related to nodester running node.js 0.4.x and solisoft running 0.6.x.  It looks like this error (The "sys" module is now called "util") is related to a difference in the versions of node. 
http://groups.google.com/group/nodejs/browse_thread/thread/44ccefc8d9f4a5ac

**Comment by yocontra** [comment]
@chrismatthieu - That's unrelated. That error is just a nuisance, the sys module is linked to util so the functionality still works as expected. The CLI needs to be updated for that to go away

**Comment by solisoft** [comment]
For information :
$ nodester app info
The "sys" module is now called "util". It should have a similar interface.
nodester info Gathering information about: solicms
nodester info solicms on port 13031 running: false (pid: unknown)
nodester info gitrepo: git@nodester.com:/node/git/obonnaure/4878-b1bcb4416136cd2e7e0158db7f4283ba.git
nodester info appfile: server.js

but http://solicms.nodester.com/ is UP

Maybe there is a ghost process running?

**Comment by chrismatthieu** [comment]
This ticket is really old and a lot has changed on our platform.  Please open a new ticket if you are still having an issue.
