### ISSUE TITLE
can you let me know how to retrieve my username and password

### ISSUE THREAD

**Issue by buzzshiva** [nodester/nodester#256]
can you let me know how to retrieve my username and password;

I think i have created username : nodebuzz. 

last application i created was apptest.nodester.com

**Comment by chrismatthieu** [comment]
We have recently added password reset support to the Nodester API.  You should be able to run the following commands:

nodester user setpass sendtoken - Sends password reset token to user email
nodester user setpass <token> <new_password> - Set a new password for this user
