### ISSUE TITLE
cannot install node-sqlite and ejs

### ISSUE THREAD

**Issue by dfhuynh** [nodester/nodester#257]
## I cannot install node-sqlite and ejs. Attempting to install node-sqlite yields the following output

$ nodester npm install clbc-explorer node-sqlite
nodester info installing to app: clbc-explorer
nodester info installing these npm packages: node-sqlite
nodester /bin/sh: line 0: cd: /node/app/dfhuynh/5086-7dc23edec540ed54fe9ff7370de1947d_rw: No such file or directory
nodester npm WARN crypto@0.0.1 package.json: bugs['web'] should probably be bugs['url']
nodester npm ERR! 404 'node-sqlite' is not in the npm registry.
nodester npm ERR! 404 You could maybe bug the author to publish it
nodester npm ERR! 404 Maybe try 'npm search sqlite'
nodester npm ERR! 404 Note that you can also install from a tarball or folder.
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.49.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "node-sqlite"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! code E404
nodester npm ERR! Error: EACCES, Permission denied 'npm-debug.log'
nodester npm ERR! Report this _entire_ log at:
nodester npm ERR!     http://github.com/isaacs/npm/issues
nodester npm ERR! or email it to:
nodester npm ERR!     npm-@googlegroups.com
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.49.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "node-sqlite"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path npm-debug.log
nodester npm ERR! code EACCES
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /npm-debug.log
nodester npm not ok
## nodester warn you should restart your app after you are finished installing packages

node-sqlite is at https://github.com/grumdrig/node-sqlite.git and npm should already know ejs.

**Comment by dfhuynh** [comment]
Please help? :) I filed this issue on 12/26 and have been anxious to start using nodester. Thank you.

**Comment by yocontra** [comment]
There is no such thing as 'node-sqlite'. The package name for that is actually 'sqlite' if you read the documentation.

**Comment by dfhuynh** [comment]
Yes, there is such a thing. I just want to install this: https://github.com/orlandov/node-sqlite

@Contra Please do not close this issue without actually verifying that you have resolved it properly for me. Especially when this UI does not allow me to re-open it.

**Comment by yocontra** [comment]
If you search npm for "node-sqlite" nothing will come up. You are using the wrong package name. I have verified that this is true, please do not reply to this issue without actually verifying that you are using the right package name. Please see https://github.com/orlandov/node-sqlite/blob/master/package.json and look at the name field. The git repository may be node-sqlite but the npm package is not.
