### ISSUE TITLE
Reason: JSON Parse error!

### ISSUE THREAD

**Issue by deivinsontejeda** [nodester/nodester#258]
Hello Guys,

I following step by step instruction to setup my account on nodester, but i received this error: Reason: JSON Parse error!

This issue is by using npm of nodester, when i used the Rest API everything works fine.

greats work!

**Comment by jimjh** [comment]
Hey! I had this error too, and it was because I left out my app name. Hope this helps.

Try `nodester npm install my-app`

**Comment by deivinsontejeda** [comment]
Thanks!
