### ISSUE TITLE
"nodester app logs" shouldn't require app name

### ISSUE THREAD

**Issue by jimjh** [nodester/nodester#259]
Feature Request.

`nodester app logs` shouldn't require an app name appended at the end if it is executed in a configured directory.

The same goes for other `app` commands.

**Comment by brianewing** [comment]
This is already possible.

Run `nodester app setup <appname>` and future `app` commands will remember the app.

There's also a nodester-cli project for CLI issues :)

**Comment by yocontra** [comment]
Open this in the CLI. V2 has a brand new CLI that will manage all of this a lot better
