### ISSUE TITLE
Internal Server Error using Express w/HBS

### ISSUE THREAD

**Issue by mundizzle** [nodester/nodester#261]
I was able to get the the basic example working just fine. Then I switched template engines from Jade to HBS (handlebars). Everything runs locally, but "Internal Server Error" on Nodester. 

$ nodester app logs

The "sys" module is now called "util". It should have a similar interface.
nodester info Showing logs for: talkshoppe
New PID: 7208
chroot_runner
chroot_runner
Express server listening on port 13372 in production mode

 nodester npm list

The "sys" module is now called "util". It should have a similar interface.
nodester info list npm packages for app: talkshoppe
nodester ├─┬ express@2.5.4 
nodester │ ├─┬ connect@1.8.5 
nodester │ │ └── formidable@1.0.8 
nodester │ ├── mime@1.2.4 
nodester │ ├── mkdirp@0.0.7 
nodester │ └── qs@0.4.0 
nodester ├─┬ hbs@1.0.1 
nodester │ └─┬ handlebars@1.0.2beta 
nodester │   ├─┬ optimist@0.2.8 
nodester │   │ └── wordwrap@0.0.2 
nodester │   └── uglify-js@1.0.7 
nodester ├── nib@0.3.1 
nodester └─┬ stylus@0.21.2 
nodester   ├── cssom@0.2.0 
nodester   ├── growl@1.1.0 
nodester   └── mkdirp@0.0.7 
nodester 

Any ideas? thanks.

**Comment by yocontra** [comment]
This is an issue with your application and doesn't belong in our platform related issues list. I recommend posting your code and verbose errors on the HBS page and they will probably give you a hand.

**Comment by mundizzle** [comment]
sorry for posting in the wrong place.

express running in 'production' mode was hiding the errors. once i figured that out, was able to see that i didn't have the handlebars dependency for hbs.
