### ISSUE TITLE
The application is offline

### ISSUE THREAD

**Issue by bagusflyer** [nodester/nodester#262]
I've tried delete an reinstall the app and I still can't get it through.

My latest app is chatsvr. 

But I found something strange. When I call nodester app info chatsvr, it always ask me to input password, I tried my password I used when I can nodester user setup, but it seems not correct. Anyway the result seems correct:

The "sys" module is now called "util". It should have a similar interface.
nodester info Gathering information about: chatsvr
nodester warn chatsvr on port 13343 running: false (pid: unknown)
nodester info gitrepo: git@nodester.com:/node/git/bagusflyer/5190-fa34f22eb0b8b2429248143d842dfc0c.git
nodester info appfile: server.js

Except the running status is false.

What could be wrong? Thanks

**Comment by yocontra** [comment]
`nodester app init <your app name>`

Please read the documentation before opening any more issues.http://nodester.com/help.html

**Comment by bagusflyer** [comment]
Sorry, I don't get you. I've read the page and I've run the command you mentioned after nodester create <app name> command.

The problem now is the application is always in offline mode. What should I do next? Thanks

**Comment by yocontra** [comment]
Post the results from `nodester app logs` and `nodester app restart`

**Comment by bagusflyer** [comment]
1. nodester app logs chatsvr

The "sys" module is now called "util". It should have a similar interface.
nodester info { response: '{"status":"failure","message":"No logs available."}\n',
  errorCode: 500 }
nodester ERROR Fatal Error! API Response: {"status":"failure","message":"No logs available."}

Reason: No logs available.
1. nodester app restart chatsvr

The "sys" module is now called "util". It should have a similar interface.
nodester info Attemping to restart app: chatsvr
nodester warn false

**Comment by icarusin** [comment]
Am facing the exact same issue. I created a demo app with 'create' and 'init' command but the app fails to start. 

Am using node.js (v0.6.6) and trying this from Windows. Could the version be an issue ?

**Comment by jachinte** [comment]
I have the same problem icarusin, have you found the problem?

**Comment by bagusflyer** [comment]
No. I'm waiting for somebody's help.

**Comment by 1engels** [comment]
if you log in on the nodester website and check your apps you will see the app status, it says "failed-to-start" for me because I restarted it.

**Comment by jachinte** [comment]
It says "failed-to-start" and when I try to start the application it does nothing

**Comment by bagusflyer** [comment]
Any suggestions? I tried to recreate another app, it had the same problem.

**Comment by ms-cownie** [comment]
ditto for me

**Comment by bagusflyer** [comment]
No idea about how to solve the problem? I tried in my another Macbook, still the same problem.

**Comment by jachinte** [comment]
I think it has to be an issue in the server, nothing related to us

**Comment by bagusflyer** [comment]
Can you explain what you mean? I just follow the instruction to create the server. I never touch anything in node.js yet.

Thanks

**Comment by jachinte** [comment]
I mean, the problem has to be an issue in nodester's server. Is nothing related to us.

**Comment by bagusflyer** [comment]
I'm a bit confused.Yes, I think this is the nodester's issue. But isn't this the place for reporting nodester's issue? Anybody can help me to solve the issue? Thanks

**Comment by yocontra** [comment]
It is an issue and we are working on it. Please quit spamming this issue, it isn't helping.

**Comment by bagusflyer** [comment]
ok, sorry for that. But I don't know there is anybody can help until just now through your post.

**Comment by antosubash** [comment]
i'm also having the same problem some one help...........

**Comment by lucasaug** [comment]
Do you guys think this issue will take long to be fixed?
Thanks.

**Comment by yocontra** [comment]
I need the following info: nodester username, email, application name, node version, npm version, OS, nodester-cli version

**Comment by jachinte** [comment]
Nodester username: migueljimenez
email: migue.hit@hotmail.com
App name: migueljimenez
Node version: 0.6.6
OS: Windows 7 32 bits

I dont know the version for npm and nodester-cli because in this right moment I am not in my computer.

I just note that my applications has gone, but if I want to create a new one with the same name it says that already exists.

**Comment by bagusflyer** [comment]
I change to another machine (iMac), everything is fine.

在 2012-1-23，上午06:53， migueljimenez 写道：

**Comment by yocontra** [comment]
@bagusflyer - Nice to see that everything is working for you now.
@migueljimenez - Gone from your local computer? Try cloning it with the CLI then restarting it

**Comment by XULRunner42** [comment]
not another "me too" post -- sorry, my nodester account has been inactive for a while, just was able to log in to the website today and I found I could not kickstart apps in 36 seconds

```
Nodester user: yebyen
email: kingdon@tuesdaystudios.com
App name: nofrack
Node version: 0.6.10
OS: 64 bit linux (Debian Squeeze)

npm: 1.1.0-3
nodester-cli: 0.2.37
```

the results of `nodester app init nofrackny`:
http://pastebin.com/raw.php?i=9Hpsey6G

you can see it's prompting me for my password (to nodester acct?) three times, I enter it correctly three times or enter nothing, same result, the repository clones successfully, so I am led to believe that my password is correctly set using `nodester user setup <username> <password>`...

```
yebyen@minnah:~/nofrack$ nodester apps
nodester warn nofrack on port 14377 running: failed-to-start
```

ok, so...

```
yebyen@minnah:~/nofrack$ nodester start; nodester logs
nodester info Attemping to start app: nofrack
nodester warn false
nodester ERROR Fatal Error! API Response: {"status":"failure","message":"No logs available."}

Reason: No logs available.
```

**Comment by yocontra** [comment]
It's asking for your SSH password not your nodester password. We have nothing to do with your local SSH configuration. If you put a password on your key, you have to enter it to unlock it before using anything git-related on our service.

**Comment by XULRunner42** [comment]
Well.  I have installed nodester locally and I am very impressed.

I think that I would still like to use your hosted service, since I might experiment with this one.  But bravo!

**Comment by ergoback** [comment]
Kingdon!

**Comment by XULRunner42** [comment]
@Contra no ssh key password here, sorry but that's not it...

like I said, the clone succeeds

**Comment by yocontra** [comment]
@XULRunner42 - Strange... are you trying to start an old app or a freshly made one?

**Comment by XULRunner42** [comment]
From `nodester app init nofrack` it's clear (at least to me) that I'm starting a new one, so I'll confirm that out loud, and we're back on the same page.  I experimented with several values of "start file" parameter to add a new server, calling it `hello`, `start`, then once I figured out what it was for, `server.js`.

The server.js file that is created by nodester init looks reasonable, it's trying to listen to a numbered port, which is a different number every time I `destroy`, `app create`, and `app init`, instead of "Undefined" which I think is seen when I am able to make the clone fail (probably when no `nodester user setup` or when no `nodester app create` has been done)

I think I could run it locally as `forever ./server.js` or just `node ./server.js` to test and develop in the interrim,

I was going to set up a Wheat blog, from howtonode.org... I'm really new to the node scene.  Lots of good stuff.

**Comment by ergoback** [comment]
dunno. just wrote something.

On Wed, Feb 8, 2012 at 6:08 AM, Contra <
reply@reply.github.com

**Comment by chrismatthieu** [comment]
Yes, every call to the create app API assigns the next sequential port number available on the platform.  We do not reuse ports.  

Can we close this ticket or is there another issue that needs to be addresses in it?

**Comment by XULRunner42** [comment]
i was posting here because my nodester.com account won't launch brand new apps, from `nodester app init [foo]`

it still won't launch them... you can close this issue though, I'm not sure my problem has anything to do with original post

**Comment by chrismatthieu** [comment]
Hmm, I just ran the following and my app is now online:

nodester app create rollypolly
nodester app init rollypolly

http://rollypolly.nodester.com

Let's open a new ticket...

**Comment by ergoback** [comment]
Harry Davis sent you an invitation

Twitter helps you stay connected with what's happening right now and with the people and organizations you care about.

  Accept invitation

https://twitter.com/i/dc4e45c7-fc7b-4218-87b7-334c77f9b4e6

---

This message was sent by Twitter on behalf of Twitter users who entered your email address to invite you to Twitter.
Unsubscribe: https://twitter.com/i/o?t=1&iid=e4d4dbbc-4685-434b-8a26-b4f03d0f95c8&uid=0&c=IuVwbCB3dgGPPuHvPCnfjWtTrVOB2i13asWkcD3gpGd1UfkCA3U2Wy0LOwFav2EeFPBQiVq2UdytIiVBrOgdgm7ZLhNWZLuL1PSEy1ACVVvvqRD4zP0CBg%3D%3D&nid=9+26

Need help?
https://support.twitter.com

**Comment by ergoback** [comment]
Harry Davis sent you an invitation

Twitter helps you stay connected with what's happening right now and with the people and organizations you care about.

```
Accept invitation
```

https://twitter.com/i/092ef8b5-97d1-4e17-9db9-b84ad0291c2c

## 

This message was sent by Twitter on behalf of Twitter users who entered your email address to invite you to Twitter.
Unsubscribe: https://twitter.com/i/o?t=1&iid=181fcadb701242dd8d0b7827560fe613&uid=0&c=IuVwbCB3dgGPPuHvPCnfjWtTrVOB2i13asWkcD3gpGd1UfkCA3U2Wy0LOwFav2EeFPBQiVq2UdytIiVBrOgdgm7ZLhNWZLuL1PSEy1ACVVvvqRD4zP0CBg%3D%3D&nid=9+26

Need help?
https://support.twitter.com

**Comment by ergoback** [comment]
Harry Davis sent you an invitation

Twitter helps you stay connected with what's happening right now and with the people and organizations you care about.

```
Accept invitation
```

https://twitter.com/i/2ef7112d-38c0-44dd-80ed-5d05df0ca607

## 

This message was sent by Twitter on behalf of Twitter users who entered your email address to invite you to Twitter.
Unsubscribe: https://twitter.com/i/o?t=1&iid=979e45117cac47d98145b8faf2a8e608&uid=0&c=IuVwbCB3dgGPPuHvPCnfjWtTrVOB2i13asWkcD3gpGd1UfkCA3U2Wy0LOwFav2EeFPBQiVq2UdytIiVBrOgdgm7ZLhNWZLuL1PSEy1ACVVvvqRD4zP0CBg%3D%3D&nid=9+26

Need help?
https://support.twitter.com
