### ISSUE TITLE
Can't connect to app using websocket.

### ISSUE THREAD

**Issue by supertunaman** [nodester/nodester#263]
Hey guys,

I've been having an issue connecting to my app boatduinode.nodester.com using websockets with socket.io. This pcap shows that it's actually returning an HTTP 404 upon the initial GET request to /socket.io/websocket. A pcap is available here:

http://supertunaman.com/websocket.pcap

And here is the script that I'm using to connect to WebSocket, as well as the smallish WebSocket library that I'm using.

https://github.com/supertunaman/Boatduinode/blob/master/boatduinode.rb
https://github.com/supertunaman/Boatduinode/blob/master/web_socket.rb

Could you please look into this? Let me know if there's anything I need to change on my end. Thanks!

**Comment by yocontra** [comment]
Can you post your server-side code?

**Comment by supertunaman** [comment]
Here you are:

https://github.com/supertunaman/Boatduinode/blob/master/boatduinode.js

**Comment by chrismatthieu** [comment]
Your code looks good to me.  Contra, any idea?

**Comment by chrismatthieu** [comment]
I noticed that you are doing something with a TCP server in your code.  I wonder if that could be causing an issue with your web sockets running on our platform.

**Comment by supertunaman** [comment]
Hm, are you referring to my use of the express library? Oddly, it's worked fine on Nodester in the past.

I'll experiment with it a bit locally when I have a bit more time. Hate to bother you guys with my awful code, so I really appreciate you looking at this. <3

**Comment by juzerali** [comment]
Isn't this issue similar to `issue:304`

**Comment by juzerali** [comment]
Same problem but under certain conditions. Windows 7, Google Chrome 19+ and Mozilla Firefox 11+. 
It works fine on Win 7 Opera and Safari and Win XP

**Comment by kaven276** [comment]
It seems that app in nodester can not make request to other website

my app breakjail run on my notebook well, but when run on nodester.com, it can not make http request to outside, all response return 404 connection:close.

Why???

**Comment by juzerali** [comment]
UPDATE: When I use `var everyone = require("now").initialize(app, {socketio: {transports: ['xhr-polling', 'jsonp-polling', 'htmlfile']}});`. That is disabling websocket, it performs better. But yet not satisfying. It keeps hanging on above mentioned configuration.

**Comment by alejandro** [comment]
no response, too old!
