### ISSUE TITLE
App Offline Error

### ISSUE THREAD

**Issue by icarusin** [nodester/nodester#265]
Hi,

 Am using node.js version 0.6.6 and am unable to create and init  the sample app. There are no log entries also. Is the version of node an issue ?

Also, when trying to install express I was getting a EACCES Error consistently. This was after having pushed changes to my repository. Are these issues related to using node.js version 0.6.6 ?

Thanks,

**Comment by yocontra** [comment]
OS and npm version? Try using 0.6.7 - nodester-cli works fine for me on it. If it is still having issues try running it as sudo. If it's still broken I'll be glad to help out

**Comment by chrismatthieu** [comment]
No response received. If you are still having this issue, please open a new ticket.
