### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by Fayded** [nodester/nodester#266]
My username is: fayded and I am receiving an invalid username or password after using a registration Coupon when tyring to install nodester. Every attempt to reset thus far has failed.

**Comment by yocontra** [comment]
Are you positive your coupon registration went through?

**Comment by Fayded** [comment]
No, I am not positive but I was under that impression going through the process. I did however request a coupon a few days prior with the same email. And was given one a day afterwards which I was attempting to use. 

Thanks.

**Comment by yocontra** [comment]
Try registering again, it's possible it didn't go through.

**Comment by nkhine** [comment]
hi i got my coupon and am also having an issue:

☹  nodester user setup (email i used to register) coupon  
nodester info verifying credentials
nodester info { response: '<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.0.6</center>\r\n</body>\r\n</html>\r\n',
  errorCode: 404 }
nodester ERROR Fatal Error! API Response: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.0.6</center>
</body>
</html>

Reason: HTTP Error 404 returned.

Is it a problem if i use the zsh shell?

**Comment by Fayded** [comment]
When I try to create an account this is what I get
{"status": "failure - account exists"}

When trying to setup the account:

nodester ERROR Fatal Error! API Response: {"status" : "failure", "message": "Invalid username or password."}

Reason: Invalid username or password.

Thanks. 

-Kevin

**Comment by yocontra** [comment]
@nkhine - Strange, we don't run nginx. For some reason your connection is hitting a server that doesn't belong to us.
@Fayded - You'll have to reset your password.

```
nodester user setpass sendtoken
nodester user setpass <the key that got sent to your email> <your new password>
```

**Comment by nkhine** [comment]
hello, i tried the above commands, but it did not work as i got this:

```
☺  nodester user setpass sendtoken                                                                                                                                                
    nodester ERROR Username and password not set in config.
    Please run nodester user setup <username> <password>
```

and then when i run the:

```
  ☹  nodester user setup (my email address) (pasword)                                                                                                                                  
       nodester info verifying credentials
       nodester info { response: '<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr <center>nginx/1.0.6</center>\r\n</body>\r\n</html>\r\n', errorCode: 404 }
       nodester ERROR Fatal Error! API Response: <html>
       <head><title>404 Not Found</title></head>
       <body bgcolor="white">
       <center><h1>404 Not Found</h1></center>
       <hr><center>nginx/1.0.6</center>
       </body>
       </html>

       Reason: HTTP Error 404 returned.
```

i have shut down my nginx on my machine. besides the version i am running is:

```
       ☺  nginx -v                                                                                                                                       
            nginx: nginx version: ngx_openresty/1.0.10.24
```

any advice much appreciated

**Comment by yocontra** [comment]
@nkhine - Those instructions were @Fayded. Your issue has something to do with your local nginx. Can you run a `ping nodester.com` and tell me what IP you're hitting?

**Comment by nkhine** [comment]
well as i said my version of nginx is ngx_openresty/1.0.10.24

```
☺  ping nodester.com                                                                                                                                                              
PING nodester.com (50.16.203.53): 56 data bytes
64 bytes from 50.16.203.53: icmp_seq=0 ttl=43 time=116.725 ms
64 bytes from 50.16.203.53: icmp_seq=1 ttl=43 time=117.325 ms

☺  nslookup 50.16.203.53                                                                                                                                                          
Server:     192.168.0.254
Address:    192.168.0.254#53

Non-authoritative answer:
53.203.16.50.in-addr.arpa   name = nodester.com.

Authoritative answers can be found from:
203.16.50.in-addr.arpa  nameserver = pdns2.ultradns.net.
203.16.50.in-addr.arpa  nameserver = pdns1.ultradns.net.
203.16.50.in-addr.arpa  nameserver = pdns6.ultradns.co.uk.
203.16.50.in-addr.arpa  nameserver = pdns5.ultradns.info.
203.16.50.in-addr.arpa  nameserver = pdns4.ultradns.org.
203.16.50.in-addr.arpa  nameserver = pdns3.ultradns.org.
```

**Comment by yocontra** [comment]
@nkhine - Whatever you have going on should be it's own issue. Open one up and I'll be glad to help you out.

**Comment by lehelmatyus** [comment]
hi, I have no idea what to do
my password (I registered on website ) contains " &-IT; "
nodester user setup <username> <password> throws
-iT command not found

Fatal error api resonce invalid username or password

**Comment by nkhine** [comment]
try to put the  password within quotes

**Comment by lehelmatyus** [comment]
## hey, thx for the reply, i did try it with " " and it says

info verifying credentials
info user verified
info writing user data to config
warn No key file found, encrypt is not going to be strong.

## [1]+ Exit 1                               nodester user setup <username> <mypass until &-iT mark in it

what do?

**Comment by lehelmatyus** [comment]
sorry for large font had no idea

**Comment by yocontra** [comment]
You need to set up an SSH key. Please read the help page http://nodester.com/help.html

**Comment by chrismatthieu** [comment]
No response received. If you are still having this issue, please open a new ticket.
