### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by lucasaug** [nodester/nodester#268]
I got my registration coupon, but when I try to get the RSA keys, by using the command "cat ~/.ssh/id_rsa.pub | pbcopy", it says the folder couldn't be found. I am using Ubuntu 11.10, and I am really new using it. I guess I just did some obvious thing wrong. Can anyone give me some help please?

**Comment by lucasaug** [comment]
Oh, I figured it out!
Sorry for annoying you guys for nothing!

**Comment by nodester** [comment]
You should be able to use your same github RSA key (id_rsa.pub). If you do
not have in your ~/.ssh directory, you will need to search for it or tell
nodester where it is...

-chris

On Fri, Jan 13, 2012 at 7:08 PM, lucasaug <
reply@reply.github.com

**Comment by marcosvm** [comment]
Two things to help you:

1) You need to create your ssh key, there's a nice tutorial here:
http://www.virtualhelp.me/linux/65-ssh-and-authorized-keys
2) I don't think linux has the pbcopy command, so you can manually
copy and paste the key

On Fri, Jan 13, 2012 at 6:08 PM, lucasaug
reply@reply.github.com
wrote:

**Comment by antosubash** [comment]
not able to start the app.........it shows 503 error........

**Comment by lucasaug** [comment]
I got it working now,thanks for all the answers!
