### ISSUE TITLE
Apps on Nodester are not starting.

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester#27]
I walked through our example on the home page of creating an app on nodester and pushing it and starting it.  All API calls returned success.  Git repo, app directory, and database look fine.

App is not running.  Check out http://b.nodester.com
/hosted_apps/topher/106-b7efb3592c125951a411e5e84801966d

**Comment by DanBUK** [comment]
I've taken a look and manually starting it seemed to have worked.

Can you hit the API for b.nodester.com and stop/start/restart it and see if it works for each of them. (I'm now logging on the server so will hopefully spot errors.)

**Comment by chrismatthieu** [comment]
I was able to stop it and verify that it stopped and start it and verify that it started fine.

The issue seemed to be with the initial start of the app.  I'll create a new app again to verify.  We have a couple of other reports of apps with the same issue - not starting.

Thanks,
Chris

**Comment by chrismatthieu** [comment]
I created c.nodester.com and everything started up just fine.  Not sure what the issue could have been...

**Comment by chrismatthieu** [comment]
How do you start an app manually like you did to get b running?  I wanted to try that on a couple of user apps that are reporting to have not started as well:

a.nodester.com
campfiresessions.nodester.com
typing.nodester.com

Thanks,
Chris

**Comment by chrismatthieu** [comment]
I was able to start http://a.nodester.com just fine but both http://typing.nodester.com and http://campfiresessions.nodester.com result in the following error:

[ec2-user@domU-12-31-39-00-E2-52 nodester]$ sudo scripts/launch_app.sh /home/ec2-user/nodester /home/ec2-user/hosted_apps/meso/101-ac28fd404e3ce1fb61ac87d2a95fbc62 server.js

node.js:68
      throw e; // process.nextTick error, or 'error' event on first tick
      ^
Error: Failed do chroot to the folder.
    at Object.<anonymous> (/home/ec2-user/nodester/scripts/launch_chrooted_app.js:45:13)
    at Module._compile (node.js:364:32)
    at Object..js (node.js:372:14)
    at Module.load (node.js:295:27)
    at Array.<anonymous> (node.js:386:26)
    at EventEmitter._tickCallback (node.js:60:24)

---

[ec2-user@domU-12-31-39-00-E2-52 nodester]$ sudo scripts/launch_app.sh /home/ec2-user/nodester /home/ec2-user/hosted_apps/bnferguson/63-3ac1962ed3a84247487decb4186fc6b0 app.js

node.js:68
      throw e; // process.nextTick error, or 'error' event on first tick
      ^
Error: Failed do chroot to the folder.
    at Object.<anonymous> (/home/ec2-user/nodester/scripts/launch_chrooted_app.js:45:13)
    at Module._compile (node.js:364:32)
    at Object..js (node.js:372:14)
    at Module.load (node.js:295:27)
    at Array.<anonymous> (node.js:386:26)
    at EventEmitter._tickCallback (node.js:60:24)

---

Not sure if this matters but I noticed that both of their hosted_apps directories have an extra write permission that half of the other directories do not.

Any ideas?

**Comment by chrismatthieu** [comment]
Here's another example of an app that says it's running on nodester.com and i have tried to manually start it but it doesn't run.  No external modules are used.

http://cloudnode.nodester.com/
dvbportal 102-c1edd972c316548941e3a670bf4d51e2 main.js

**Comment by chrismatthieu** [comment]
sudo scripts/launch_app.sh /home/ec2-user/nodester /home/ec2-user/hosted_apps/dvbportal 102-c1edd972c316548941e3a670bf4d51e2 main.js

[ec2-user@domU-12-31-39-00-E2-52 nodester]$ /usr/local/bin/node: symbol lookup error: /home/ec2-user/.node_libraries/daemon-tools.node: undefined symbol: ev_loop_fork

**Comment by DanBUK** [comment]
Hey chris,

Did you downgrade nodejs again?

I had to uninstall and re-install via npm daemon-tools.

Things are working for me atm on the dvb portal one.

**Comment by chrismatthieu** [comment]
i downgraded node to 0.3.4 and then I did an npm update daemon-tools

Should I have uninstalled it first?

**Comment by DanBUK** [comment]
It seems an uninstall doesn't do enough, I did a "rm ~/.node_libraries/daemon-tools.node" and then an npm install.

**Comment by chrismatthieu** [comment]
Thank you :)
