### ISSUE TITLE
Git push connection closed.

### ISSUE THREAD

**Issue by ashea-code** [nodester/nodester#271]
Hello, I just received my coupon code, I have a project setup and ready to go. However when I go to push it using git, I get this message:

Nodester!
Connection closed by 50.16.203.53
fatal: The remote end hung up unexpectedly

I used ssh git@nodester.com -v and it seems to be kicking me out after:

debug1: Offering public key: /root/.ssh/id_rsa

**Comment by yocontra** [comment]
Nodester username, email OS, npm version, node version, git version?

**Comment by chrismatthieu** [comment]
No response received. If you are still having this issue, please open a new ticket.
