### ISSUE TITLE
No git access

### ISSUE THREAD

**Issue by Scribblerockerz** [nodester/nodester#274]
Hey, 

I tryed to start a new app but the status is always "failed-to-start".
If I try to clone directly from the git repository, they says that I have no access...  I reset the key with "nodester user setkey" but it still doesn't work.

Some ideas?

**Comment by yocontra** [comment]
Nodester username, email OS, npm version, node version, git version?

**Comment by Scribblerockerz** [comment]
you have an email

**Comment by chrismatthieu** [comment]
Has this issue been resolved? If not, could you post the details of your email in this ticket?

**Comment by chrismatthieu** [comment]
no updates...
