### ISSUE TITLE
Possible to un railway.js apps on nodester?

### ISSUE THREAD

**Issue by prolificcoder** [nodester/nodester#277]
I was previously able to run a non- express/non- railway app on 
nodester but I am not seeing any output with railwayjs. Wondering if I 
need to do something special. I am using redistogo and the 
configuration as it is runs on my localhost. 
I have installed all the remote apps with 
http://taskreward.nodester.com/ is the app the logs are not too useful 
except that it says some problem with jugglingdb. 
Copy pasting the logs. 
nodester info Showing logs for: taskreward 
New PID: 24831 
chroot_runner 
chroot_runner 
/app/node_modules/railway/node_modules/jugglingdb/package.json:2 
  "name": "jugglingdb", 
^ 
Railway server listening on port 13395 within production environment

**Comment by chrismatthieu** [comment]
It looks like express isn't setup to handle a GET "/" request. Could that be possible?

**Comment by chrismatthieu** [comment]
No response received.  Please open another ticket if you are still experiencing an issue.
