### ISSUE TITLE
Password containing "#" symbol causes an undefined errorCode

### ISSUE THREAD

**Issue by ynov** [nodester/nodester#278]
I am trying to do "nodester user setup <username> <password>", but it always return an undefined errorCode, seems it caused by a password containg "#" symbol.

I have tried to use escaped "#" (#), and still got the same error, even I tried a wrong password with "#" symbol, it returns an undefined errorCode (not "Invalid username or password")

**Comment by yocontra** [comment]
@brianewing - This.

@ynov - Can you paste the full logs?

**Comment by ynov** [comment]
Using whatever password contains "#", (I tried to escaped it, and double quotes it too, and even with my correct password):

```
$ nodester user setup ynov xxx#yyy
nodester info verifying credentials
nodester info { response: undefined, errorCode: undefined }
nodester ERROR Fatal Error! API Response: undefined
Reason: No response received.
```

But, wrong password should return 401 errorCode:

```
$ nodester user setup ynov xxxyyy
nodester info verifying credentials
nodester info { response: '{"status" : "failure", "message": "Invalid username or password."}\n',
errorCode: 401 }
nodester ERROR Fatal Error! API Response: {"status" : "failure", "message": "Invalid username or password."}
```

Web login works with my password

**Comment by ynov** [comment]
Problem solved, this is probably caused by unencoded baseurl (nodester-api / nodester.js line 21).
Modifying this line should fix the problem:

```
this.baseurl = "" + this.protocol + username + ":" + encodeURIComponent(this.password) + "@" + basehost + "/";
```

**Comment by yocontra** [comment]
https://github.com/nodester/nodester-api/commit/c6cb1538292f7c02dade85769a1e1530470116a6 - pushing now, should be live in a minute or two

**Comment by ynov** [comment]
thanks, closed

**Comment by yocontra** [comment]
Online now, run a `npm update -g` to pull the new version. Thanks for the report!
