### ISSUE TITLE
npm install puts nodester in ~ directory

### ISSUE THREAD

**Issue by nkhine** [nodester/nodester#279]
when running the $ npm install nodester-cli -g command, all the files are installed within the ~/ directory

  fetching: http://registry.npmjs.org/npm/-/npm-1.1.0-2.tgz
  0.6.9-pre
  1.1.0-2

  All clean!
  ./configure prefix=/home/ec2-user
  /home/ec2-user/bin/npm -> /home/ec2-user/lib/node_modules/npm/bin/npm-cli.js
  npm@1.1.0-2 /home/ec2-user/lib/node_modules/npm 
  It worked
  [ec2-user@ip-10-250-158-215 ~]$ npm -v
  1.1.0-2
  [ec2-user@ip-10-250-158-215 ~]$ npm install nodester-cli -g
  npm http GET https://registry.npmjs.org/nodester-cli
  npm http 200 https://registry.npmjs.org/nodester-cli
  npm http GET https://registry.npmjs.org/nodester-cli/-/nodester-cli-0.2.36.tgz
  npm http 200 https://registry.npmjs.org/nodester-cli/-/nodester-cli-0.2.36.tgz
  npm http GET https://registry.npmjs.org/nodester-api
  npm http GET https://registry.npmjs.org/colors/0.3.0
  npm http GET https://registry.npmjs.org/iniparser/1.0.1
  npm http 200 https://registry.npmjs.org/iniparser/1.0.1
  npm http 200 https://registry.npmjs.org/colors/0.3.0
  npm http GET https://registry.npmjs.org/iniparser/-/iniparser-1.0.1.tgz
  npm http GET https://registry.npmjs.org/colors/-/colors-0.3.0.tgz
  npm http 200 https://registry.npmjs.org/nodester-api
  npm http GET https://registry.npmjs.org/nodester-api/-/nodester-api-0.1.20.tgz
  npm http 200 https://registry.npmjs.org/iniparser/-/iniparser-1.0.1.tgz
  npm http 200 https://registry.npmjs.org/colors/-/colors-0.3.0.tgz
  npm http 200 https://registry.npmjs.org/nodester-api/-/nodester-api-0.1.20.tgz
  npm http GET https://registry.npmjs.org/request
  npm http 200 https://registry.npmjs.org/request
  npm http GET https://registry.npmjs.org/request/-/request-2.9.100.tgz
  npm http 200 https://registry.npmjs.org/request/-/request-2.9.100.tgz
  /home/ec2-user/~/bin/nodester -> /home/ec2-user/~/lib/node_modules/nodester-cli/bin/nodester.js
  iniparser@1.0.1 /home/ec2-user/~/lib/node_modules/nodester-cli/node_modules/iniparser 
  colors@0.3.0 /home/ec2-user/~/lib/node_modules/nodester-cli/node_modules/colors 
  request@2.9.100 /home/ec2-user/~/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request 
  nodester-api@0.1.20 /home/ec2-user/~/lib/node_modules/nodester-cli/node_modules/nodester-api 
  nodester-cli@0.2.36 /home/ec2-user/~/lib/node_modules/nodester-cli

**Comment by yocontra** [comment]
This is an issue with your npm installation. Opening this on the npm repository will provide more help than us.
