### ISSUE TITLE
Incorporate hosted app PORT and IPADDRESS into startup of app.

### ISSUE THREAD

**Issue by DanBUK** [nodester/nodester#28]
In order to make it easier to scale apps we need to move to using variables defined from the app to hosted app to allow for different node's running on multiple machines.

Therefore rather than the current:
.listen(8001);
We have
.listen(process.env['APPPORT'], process.env['APPIPADDRESS']
Although I might prefer:
.listen(APPPORT, APPIPADDRESS)
But I'm still undecided; comments welcome!

**Comment by chrismatthieu** [comment]
Would the user still need to modify their app to include the port address that we provide or would we overwrite the port address in their application?

**Comment by DanBUK** [comment]
When the process starts, we pull in the parms, so that they do just use the above strings in their apps, cause they will appear as if variables.

**Comment by chrismatthieu** [comment]
So that could hardcode it to match the assigned port or use these vars.  I like it.

**Comment by DanBUK** [comment]
Have deployed this using the process.env['app_port'] and ['app_host'] env vars. Needs adding to example code.
