### ISSUE TITLE
"err" message in My Apps list

### ISSUE THREAD

**Issue by cadermino** [nodester/nodester#280]
every time when i access to Nodester Admin Panel i have a err instead of apps list.

**Comment by yocontra** [comment]
The admin panel was not made by us, it's a user app that uses ajax calls to the API. I'll ask the creator to have a look at it

**Comment by chrismatthieu** [comment]
Most of the Nodester users use the CLI and REST API.  If you would like to help with the admin panel, you can send pull requests to https://github.com/nodester/admin-panel

**Comment by yocontra** [comment]
Fixed, update your nodester-cli but you most likely shouldn't need to.

**Comment by cadermino** [comment]
thx very much!
