### ISSUE TITLE
Error with command "logs"

### ISSUE THREAD

**Issue by lucasaug** [nodester/nodester#281]
When I run "nodester app logs appnamehere" on the command line, it gives me a 404 error. I tried this with all my apps and the same problem happens. Is this a bug or did I use the wrong command?

**Comment by yocontra** [comment]
Go into your app folder and run `nodester app logs`. If you still get an error let me know and I'll fix this up really quick.

**Comment by yocontra** [comment]
Fixed, update your nodester-cli but you most likely shouldn't need to.

**Comment by lucasaug** [comment]
Didn't need to update. Thanks!
