### ISSUE TITLE
Issues about files with node 0.4.9

### ISSUE THREAD

**Issue by albertosantini** [nodester/nodester#284]
With node 0.4.9, using readFileSync I get

Error: EBADF, Bad file descriptor '/node_modules/trammi/lib/db/line_01_0.xml'

Changing the logic to async read, I get an error with xml2js module (converting from xml to json):

(node) warning: possible EventEmitter memory leak detected. 11 listeners added.
Use emitter.setMaxListeners() to increase limit.

Trace:
    at Parser.<anonymous> (events.js:126:17)
    at Parser.<anonymous> (/node_modules/trammi/node_modules/xml2js/lib/xml2js.j
s:132:14)
    at Parser.parseString (/node_modules/trammi/node_modules/xml2js/lib/xml2js.j
s:3:63)
    at /node_modules/trammi/lib/trammiDB.js:86:16
    at [object Object].<anonymous> (fs.js:80:5)
    at [object Object].emit (events.js:64:17)
    at fs.js:820:12

I get also:

Error: ENOENT, No such file or directory '/node_modules/trammi/lib/public/favicon.ico'

Locally, using 0.6.x, I cannot reproduce those issues.

**Comment by yocontra** [comment]
@albertosantini - xmlson > xml2js. 

This seems to be an issue with your code and not our service. If you paste it I can probably help you troubleshoot it. I recommend you have 0.4.9 on your local machine to see if you can reproduce the errors too. Try using https://github.com/creationix/nvm to switch versions easily

**Comment by albertosantini** [comment]
I agree, it is an issue with the code. What else? :)

I opened the issue because the node release is not the latest (0.6.x) and, via twitter, I asked when v2 was ready: the reply was for JSConf. It is a bit late for me.

The point of the issue is to give a few evidences for (or against) 0.4.x release, maybe speeding up v2 containing 0.6.x. :)

For instance, EBADF, using readFileSync, was a known node issue, then resolved with the latest releases of 0.4.x.

I have been developing on windows box and it is not a viable suggestion to install 0.4.x, feasible only with cygwin (but not supported): in the past months I worked with that configuration and it is not nice. For instance, npm has a few issues with process handling: installing the modules was a panic.

Workarounds.

I used the async version of readFile to resolve the first issue (EBADF).

I will convert locally the xml files to json: so the app will read the file generated with "require", resolving the issue for xml2js module.

Then I will investigate the ENOENT error for favicon.ico.

Reference: https://github.com/albertosantini/node-trammi
lib/trammiDB.js
lib/trammi.js - startServer()

**Comment by albertosantini** [comment]
I modifed the code according to my previous comment.

Restarting the app, I don't see any error message in the logs.

Browsing the app (http://trammi.nodester.com/), the following message is displayed:
Cannot GET /

the file server.js:

```
/*jslint node:true, sloppy:true */

var trammi = require('trammi');

// process.on('uncaughtException', function (err) {
//     console.log(err);
// });

trammi.startServer(13259);
```

and startServer method in trammi:

```
function startServer(port) {
    var connect = require('connect'),
        dnode = require('dnode'),
        p = port || 8081,
        server;

    server = connect(
        // connect.favicon(__dirname + '/public/favicon.ico'),
        connect.static(__dirname + '/public')
    );

    dnode(function (client) {
        this.getStops = function (cb) {
            cb(stopsAC);
        };

        this.getStopInfo = function (stopNumber, lineCode, cb) {
            getStopInfo(stopNumber, lineCode, function (err, stopInfo) {
                var i, n = stopInfo.length, stopLine;

                for (i = 0; i < n; i += 1) {
                    stopLine = stopInfo[i].line;

                    if (stopLine === lineCode) {
                        cb(stopInfo);
                    }
                }
            });
        };

        this.getTimetable = function (lineName, stopNumber, cb) {
            getWaitingTime(lineName, stopNumber, function (err, timetable) {
                cb(timetable);
            });
        };
    }).listen(server);

    server.listen(p);
}
```

Any open issue with connect or dnode (websockets)?

**Comment by albertosantini** [comment]
I understood the issue.

If the "lib/public" directory is not in the module, but it is moved to 'trammi/public/, that's in the same directory of the server.js file, the app works fine.

Basically I moved the code contained in startServer to server.js (and also I moved the public dir).

Maybe there are permission issues for files contained in the modules.

Any idea?

**Comment by chrismatthieu** [comment]
Is this issue resolved?  

The directory must be present before creating files. You should be able to write files to other directories within your application.

**Comment by albertosantini** [comment]
No.

If the module needs to access a file inside the module (using "fs" api vs. require), it throws an error. 

At the moment I have been using the workaround, copying the "public" directory of the module, I mean the public dir for connect module (or express one), to the "server.js" directory. 

See node-conpa or node-trammi modules of mine: they have the same approach.

(In a Joyent machine I have no issues).

**Comment by albertosantini** [comment]
I read https://github.com/nodester/nodester/issues/292.

What if the files are included in a module?

For instance, I installed myModule and myModule starts a connect server where the public directory is "myModule/lib/public".

As I said, as a workaround, I have been copying that directory to the "server.js" directory and setting 

connect.static(__dirname + '/public'); // dirname of "server.js"

Any suggestion?

**Comment by chrismatthieu** [comment]
I'm not familiar enough with the sandboxing system and modules to answer your question.  You may want to dig through the code.  We need a new sandboxing expert on the project.

**Comment by alejandro** [comment]
Just my 2 cents, we can see in the log this line:

> Error: ENOENT, No such file or directory '/node_modules/trammi/lib/public/favicon.ico'

Probably the problem here is because the process is tryining to run an absolute path who doesn't exist. You may want to add `process.cwd()` to stay in the `server.js` dir and then go deep. Basically I ran both and what it log is the follow:

```
/home/alejandromg/APPE01  // process.cwd()
/home/alejandromg/APPE01/node_modules/express // __dirname
```

And if I generate and error:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module '../lib/express'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/home/alejandromg/APPE01/node_modules/express/index.js:2:18)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
```

We can see this: 

```
at Object.<anonymous> (/home/alejandromg/APPE01/node_modules/express/index.js:2:18)
```

What I'm trying to point out is that your logs is showing paths on the root of the server (`/node_modules/...`) instead of the app dir (`/app/username/dir/...`) so you may want to take a look at the paths with `process.cwd()` and tell us if that fix the problem. 

**Edit:**
Another fix will be add the node_modules in the git repo, maybe if you are installing on nodester via nodester-cli is causing the problem.

**Comment by albertosantini** [comment]
Thanks @alejandromg to give a look at this issue.

Very nice attempt and illuminating.

Sadly process.cwd() (logged in server.js) returns "/" and not "/home/alejandromg/APPE01".

I should add __dirname (in trammi.js in trammi module) returns "/node_modules/trammi/lib" and not as you described.

However I think you are on right path.

Because the environment is chrooted, the user file root is "/app".

The question is the following one: where is the node_modules folder?

It is not process.cwd() + "/node_modules/...".
It is not "/app/node_modules/...".

Logging __dirname in the module it returns "/node_modules/trammi/...".

**Comment by albertosantini** [comment]
At all confused.

I can read the file '/node_modules/express/LICENSE' with fs.readFile.
So the modules path should be '/node_modules/..." as stated by previous logs.

If I set connect.static path with '/node_modules/trammi/lib/public', the browser displays

Cannot GET /

Sigh.

I may add node_modules to the repo and the path should be, for instance, '/app/node_modules/...', but, I think, this workaround cuts any flexibility added with 'nodester npm' commands.

**Comment by albertosantini** [comment]
Weirdly yesterday I installed a module using express (and not connect) and setting static as  '__dirname + '/public', where, as you know, 'public' is a folder inside the module.

It works fine.

Well... I will investigate the difference between express and connect.

**Comment by alejandro** [comment]
Well express is based on connect, even that middleware that you are point out is using directly from connect, maybe a old connect version was installed in the repo and probably that was causing the error or the push fix the error, definetely weird.

**Comment by albertosantini** [comment]
I tried two configurations.

I replaced connect with express. 
No success: "Cannot get /" 
Of course, as @alejandromg said, express is based on connect.

I moved outside the module the initialization of connect object.
No success: "Cannot get /" 
Thinking about a sort of lock if the connect or the express module is required inside the module itself and not, for instance, in server.js.

Now I see only one difference between the working module (node-conpa) and the module of this issue (node-trammi): dnode, a websocket based module.

I continue to investigate...

**Comment by albertosantini** [comment]
The good news is not an issue of nodejs release: with 0.6.12 the app has the same behaviour.

So it should a mix of chrooted environment and connect + dnode.

**Comment by alejandro** [comment]
@albertosantini Could you please try again, I found a problem at the moment of installing dependencies and maybe that was causing the problem (since the process jump to 0.4.9)

**Comment by marcoslima** [comment]
I'm with this problem too, with a new project I started today, but my old projects are ok.
So, instead of use connect that I installed with npm today, I copied the connect directory from that old project and the problem gone.
Based on this, I uninstalled connect and installed versions 2.0.1, 2.0.0 and 1.8.5. The problem persisted in the first two, but gone on 1.8.5.
Some change between 1.8.5 and 2.0.0 introduced this, I think.

**Comment by marcoslima** [comment]
I teared down this problem to connect/lib/proto.js where layer.route is undefined when it must not be.
It appears that creating the app with the constructor like
`app = connect(<middleware>,<middleware>)`
is not working like before.
Instead, I used the form:
``` var connect = require('connect');
    var app = connect();
    app.use(connect.static('www'));
    app.listen(3000);

```
and the problem gone.
```

**Comment by alejandro** [comment]
Hi @marcoslima The last weekend we added support to node-v0.6.12 you might want to add it to your package.json with "node":"0.6.12" also you can install any version of the module appending an @x.x.x where the x's are the working version number of the module (if you keep using the 0.4.9 node version)

**Comment by albertosantini** [comment]
I think the problem is related to the creation on the file of the resource "/dnode.js" (the client side of dnode - websocket).

If my hypothesis is correct, I think the main issue is the following one:
https://github.com/nodester/nodester/issues/313

I don't know, if it makes sense with Alejandro's changes in required path.

@marcoslima this is issue is not related with
https://github.com/substack/dnode/issues/92
