### ISSUE TITLE
Can't register a username via CLI

### ISSUE THREAD

**Issue by PabloEskimo** [nodester/nodester#286]
Having just received my nodester token last night I'm trying to follow the instructions and register a username.

```
[pabloeskimo@mini ~]$ nodester user setup anyusername anypassword
nodester info verifying credentials
nodester ERROR Fatal Error! API Response: {"status" : "failure", "message": "Invalid username or password. CouchDB lookup failed."}

Reason: Invalid username or password. CouchDB lookup failed.
```

No matter what username/password combination I try I always get that error suggesting that there is a problem with your DB.

**Comment by yocontra** [comment]
Have you tried using the web form yet? http://nodester.com/help.html - This is being looked at

**Comment by PabloEskimo** [comment]
That worked perfectly. Thanks!

**Comment by nodester** [comment]
Hi Pablo,

You cannot register from the CLI.  User setup is basically a login for your
CLI.

Please register at http://nodester.com/help.html#register or by using our
REST API:

curl -X POST -d
"coupon=mycoupon&user=testuser&password=123&email=chris@nodester.com&rsakey=ssh-rsa
AAAA..." http://nodester.com/user

Regards,
Chris

On Thu, Feb 2, 2012 at 1:02 AM, PabloEskimo <
reply@reply.github.com
