### ISSUE TITLE
Cannot install NPM modules

### ISSUE THREAD

**Issue by PabloEskimo** [nodester/nodester#287]
Hi, me again - sorry!

I'm having trouble installing NPM modules - it looks like my rw folder isn't working properly.
I understand from reading previous issues that the rw folder is created on git push - but mine doesn't seem to have been.

My app is pushed, and running successfully but I still can't install any modules. 
I've tried installing both bouncy and socket.io

Thanks!

[pabloeskimo@macbook ~/sonelli-balancer]$ nodester npm install socket.io
nodester info installing to app: sonelli-balancer
nodester info installing these npm packages: socket.io
nodester /bin/sh: line 0: cd: /node/app/PabloEskimo/6042-fed2e7636ae2ceeca8374f1ca974b10c_rw: No such file or directory
nodester npm WARN crypto@0.0.1 package.json: bugs['web'] should probably be bugs['url']
nodester npm ERR! Could not create /node_modules/___socket.io.npm
nodester npm ERR! error installing socket.io@0.8.7 Error: EACCES, Permission denied '/node_modules/___socket.io.npm'
nodester npm ERR! Error: EACCES, Permission denied '/node_modules/___socket.io.npm'
nodester npm ERR! Report this _entire_ log at:
nodester npm ERR!     http://github.com/isaacs/npm/issues
nodester npm ERR! or email it to:
nodester npm ERR!     npm-@googlegroups.com
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.49.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "socket.io"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path /node_modules/___socket.io.npm
nodester npm ERR! code EACCES
nodester npm ERR! Error: EACCES, Permission denied 'npm-debug.log'
nodester npm ERR! Report this _entire_ log at:
nodester npm ERR!     http://github.com/isaacs/npm/issues
nodester npm ERR! or email it to:
nodester npm ERR!     npm-@googlegroups.com
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.49.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "socket.io"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path npm-debug.log
nodester npm ERR! code EACCES
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /npm-debug.log
nodester npm not ok

nodester warn you should restart your app after you are finished installing packages.
[pabloeskimo@macbook ~/sonelli-balancer]$

**Comment by yocontra** [comment]
Can you please give me your NPM version, node version, nodester-cli version, and git version? Thanks

**Comment by PabloEskimo** [comment]
Sure...

```
[pabloeskimo@macbook ~/sonelli-balancer]$ git --version
git version 1.7.5.4 
[pabloeskimo@macbook ~/sonelli-balancer]$ npm --version
1.1.0-beta-4
[pabloeskimo@macbook ~/sonelli-balancer]$ nodester --version
0.2.37
[pabloeskimo@macbook ~]$ node --version
v0.6.6
```

**Comment by PabloEskimo** [comment]
I'm not sure if this is relevant but I previously created & deleted an app with the same name.
For some reason my SSH key was bad and it didn't clone the repo properly.
After deleting it, I set my SSH key again via 'nodester user setkey id_rsa.pub'.
Then I removed the whole local app directory and started again and it cloned properly

Also, when I try and stop my app I get this (and it doesn't stop the app):

```
[pabloeskimo@macbook ~/sonelli-balancer]$ nodester app stop 
nodester info Attemping to stop app: sonelli-balancer
nodester warn false
```

However 'git push' is certainly working and restarts the app properly.
Changes I make to the application are reflected when viewing it in a browser after pushing.

**Comment by nodester** [comment]
This sounds like you may not have access to your repo on Nodester.  Access
is controlled by the RSA key you provided us at registration or using the
Nodester User SetKey CLI.  There is more info online about RSA keys at
http://nodester.com/help.html#faq

Regards,
Chris

On Thu, Feb 2, 2012 at 4:01 AM, PabloEskimo <
reply@reply.github.com

**Comment by PabloEskimo** [comment]
I'm sorry - I know this is a free service and I don't want to seem like i'm complaining but my RSA key _is_ working.
As I said in the previous reply I can push to your git repo no problem with my SSH key, and the changes are reflected in the application when I use a browser.

What's not working is installing new NPM modules due to my rw directory not being accessible.

**Comment by PabloEskimo** [comment]
Ok after a bit of playing I've managed to fix it by once again deleting the application and starting again from fresh.

Now all that is left is that the old app is still running under the old name but on the old port and I can't remove the domain I assigned to it:

```
[pabloeskimo@mini ~/sonelli-balancer]$ nodester apps
nodester info sonelli-balancer on port 14234 running: true      <-- This is the correct app/port

[pabloeskimo@mini ~/sonelli-balancer]$ nodester domain 
nodester info fetching your list of domain aliases
nodester info www.sonelli.com aliased to app sonelli-balancer running on port 14195      <-- This is the old port number

[pabloeskimo@mini ~/sonelli-balancer]$ nodester domain delete www.sonelli.com
nodester info removing domain www.sonelli.com from sonelli-balancer
nodester ERROR Fatal Error! API Response: undefined
Reason: No response received.
```

Can you please just forcefully remove the domain mapping and kill the old version of sonelli-balancer running on port 14195 and then we should be good! Who knows how it got into this inconsistent state.

**Comment by yocontra** [comment]
Will do that now - your account must have been caught in limbo between our old sandboxing preferences and our new ones. Sorry for the inconvenience!

**Comment by ghost** [comment]
Hello!

I appear to be having a similar problem. My versions:

``` shell
msnyder@Diogenes ~/Projects/dicer (git)-[master] % git --version
git version 1.7.4.4
msnyder@Diogenes ~/Projects/dicer (git)-[master] % npm --version
1.1.0-2
msnyder@Diogenes ~/Projects/dicer (git)-[master] % nodester --version
0.2.37
msnyder@Diogenes ~/Projects/dicer (git)-[master] % node --version
v0.6.8
```

And the output of the installation attempt:

``` shell
msnyder@Diogenes ~/Projects/dicer (git)-[master] % nodester npm install dicer
nodester npm install dicer
nodester info grabbing dependencies from package.json...
nodester info installing to app: dicer
nodester info installing these npm packages: bootstrap-stylus,coffee-script,connect-assets,express,jade,nib,socket.io,stylus
nodester /bin/sh: line 0: cd: /node/app/msnyder/6132-866b77b5a75d290349d0f370811a75c2_rw: No such file or directory
nodester npm WARN crypto@0.0.1 package.json: bugs['web'] should probably be bugs['url']
nodester npm ERR! Could not create /node_modules/___bootstrap-stylus.npm
nodester npm ERR! error installing bootstrap-stylus@0.2.0 Error: EACCES, Permission denied '/node_modules/___bootstrap-stylus.npm'
nodester npm ERR! Could not create /node_modules/___connect-assets.npm
nodester npm ERR! error installing connect-assets@2.1.8 Error: EACCES, Permission denied '/node_modules/___connect-assets.npm'
nodester npm ERR! Could not create /node_modules/___coffee-script.npm
nodester npm ERR! error installing coffee-script@1.2.0 Error: EACCES, Permission denied '/node_modules/___coffee-script.npm'
nodester npm ERR! Could not create /node_modules/___socket.io.npm
nodester npm ERR! error installing socket.io@0.8.7 Error: EACCES, Permission denied '/node_modules/___socket.io.npm'
nodester npm ERR! Could not create /node_modules/___nib.npm
nodester npm ERR! error installing nib@0.3.2 Error: EACCES, Permission denied '/node_modules/___nib.npm'
nodester npm ERR! Could not create /node_modules/___stylus.npm
nodester npm ERR! error installing stylus@0.23.0 Error: EACCES, Permission denied '/node_modules/___stylus.npm'
nodester npm ERR! Error: EACCES, Permission denied '/node_modules/___bootstrap-stylus.npm'
nodester npm ERR! Report this *entire* log at:
nodester npm ERR!     <http://github.com/isaacs/npm/issues>
nodester npm ERR! or email it to:
nodester npm ERR!     <npm-@googlegroups.com>
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.49.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "bootstrap-stylus" "coffee-script" "connect-assets" "express" "jade" "nib" "socket.io" "stylus"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path /node_modules/___bootstrap-stylus.npm
nodester npm ERR! code EACCES
nodester npm ERR! Error: EACCES, Permission denied 'npm-debug.log'
nodester npm ERR! Report this *entire* log at:
nodester npm ERR!     <http://github.com/isaacs/npm/issues>
nodester npm ERR! or email it to:
nodester npm ERR!     <npm-@googlegroups.com>
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.49.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "bootstrap-stylus" "coffee-script" "connect-assets" "express" "jade" "nib" "socket.io" "stylus"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path npm-debug.log
nodester npm ERR! code EACCES
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /npm-debug.log
nodester npm not ok

nodester warn you should restart your app after you are finished installing packages.
```

I deleted the app and recreated it once, and I am able to push to git after running `nodester user setkey`.

**Comment by yocontra** [comment]
Try installing the demo app to your repo before installing  npm modules.

**Comment by PabloEskimo** [comment]
Hi Contra - did you get a chance to remove that domain mapping? Looks like its still there pointing to different ports still.

```
[pabloeskimo@mini ~/sonelli-balancer]$ nodester domain
nodester info fetching your list of domain aliases
nodester info sonelli.com aliased to app sonelli-balancer running on port 14234
nodester info www.sonelli.com aliased to app sonelli-balancer running on port 14195

[pabloeskimo@mini ~/sonelli-balancer]$ nodester domain delete www.sonelli.com
nodester info removing domain www.sonelli.com from sonelli-balancer
nodester ERROR Fatal Error! API Response: undefined
Reason: No response received.
```

Port 14195 is the old (bad) one that needs removing.
Thanks for your help

**Comment by yocontra** [comment]
@PabloEskimo - done.

**Comment by chrismatthieu** [comment]
Thanks Contra!
