### ISSUE TITLE
No key file found

### ISSUE THREAD

**Issue by taytus** [nodester/nodester#288]
Hi guys, I'm having this problem trying to setup nodester:

http://screencast.com/t/PDZpvIJR6K9X

Any ideas how to fix this?

Thank you.

**Comment by nodester** [comment]
Do you have an RSA key on your machine?  Our FAQs should help:
http://nodester.com/help.html#faq

Regards,
Chris

On Thu, Feb 2, 2012 at 7:58 AM, Roberto Inetti <
reply@reply.github.com

**Comment by taytus** [comment]
Hi Chris,

Yes, I do have a RSS key. I also tried the command "nodester user setkey <path-to-my-key> but it shows me this error:http://screencast.com/t/VkHzvecQMB9m

Thank you.

**Comment by chrismatthieu** [comment]
Are you still having this issue?  It looks like the Nodester CLI may not have access to create a user config file in your app directory.

**Comment by taytus** [comment]
I think there's a problem with my computer running windows, I didn't had any problems with my mac :S

**Comment by davidmurdoch** [comment]
I have the same issue and followed the directions http://nodester.com/help.html to the letter.

**Comment by davidmurdoch** [comment]
I was running node v0.6.9. Updating to v0.6.14 fixed it. I'm not sure why that fixed it; if nodester requires a minimum node version it'd be nice if you could specify that on the help page. :-)

**Comment by chrismatthieu** [comment]
NodeJS version 0.6.x should work fine.  If you are running Windows, you may want to check out a couple of extra posts that I wrote when I setup Nodester on a Windows environment - http://blog.nodester.com
