### ISSUE TITLE
Replace Base64 module with Buffer.toString('base64')

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester#29]
This may require a newer version of node.js than the stable version.

**Comment by chrismatthieu** [comment]
I've only seen examples for encoding - not decoding base64 to text.  The update will need to be made to function authenticate.

**Comment by DanBUK** [comment]
I think this will work:
Decode Base64:
var buff = new Buffer(var_base_64_data, encoding='base64');
buff.toString('utf8')
Encode Base64:
var buff = new Buffer(var_utf8_data, encoding='utf8');
buff.toString('base64')

Not sure upon this needing v0.3.X or v0.4 so will start to make a v0.4 compatible tag...

**Comment by chrismatthieu** [comment]
replaced node-base64 with native base64 support Closed by 850c14c7a976c97abf5937991279005d4bc57769
