### ISSUE TITLE
Cannot delete app

### ISSUE THREAD

**Issue by lht** [nodester/nodester#290]
Hi,

I cannot delete an app by the "destroy" button from admin.nodester.com. The wheel keeps spinning for a long time. And I can push to the repo still.

App: upstart 
    git@nodester.com:/node/git/lihaitao/6060-31cec23a0aabdc25de5bdba4df6e5dc1.git

Thank you!

**Comment by chrismatthieu** [comment]
This issue is already logged under our admin-panel repo.  Please use our CLI and/or REST API for deleting apps until it is fixed or send us a pull request ;)
