### ISSUE TITLE
Nodester and fs

### ISSUE THREAD

**Issue by shezard** [nodester/nodester#292]
Are fs actions allowed under nodester ?

e.g :

``` javascript
var fs = require('fs'),
    app = require('express').createServer();

app.get('*', function(req, res){
  fs.createReadStream('index.html').pipe(res);
});

app.listen(14223);
```

result : 

``` javascript
stream.js:99
      throw er; // Unhandled stream error in pipe.
      ^
Error: ENOENT, No such file or directory './index.html'

Process died with exit code 1. Restarting...
```

**Comment by yocontra** [comment]
Yep - you need to pass absolute paths though

**Comment by nodester** [comment]
Yes, you can read and write to your sandbox FS but you will need to create
a directory in your git repo and then target that directory for reads and
writes.

-Chris

On Thu, Feb 2, 2012 at 12:57 PM, damien fayol <
reply@reply.github.com
