### ISSUE TITLE
App running and info = false (pid: unknown)

### ISSUE THREAD

**Issue by rucheat** [nodester/nodester#294]
I am putting me log in this post anyone can please help me in this issue.
I have write my nodester account password when it ask for password in below log. my password is correct but may be it is asking for some other password. please give me solution for this problem. 
I am using windows 7 operating system. 
ask me for any information u want regarding this issues.

C:\Users\rucheat>nodester app create test001
nodester info creating app: test001 server.js
nodester info successfully created app test001 to will run on port 14324 from server.js
nodester info run nodester app init test001 to setup this app.

C:\Users\rucheat>nodester app init test001
nodester info initializing git repo for test001 into folder test001
nodester info cloning the repo git clone git@nodester.com:/node/git/rucheat/6171-8bcd3165d23f5cf9752058333cea9960.git test001
Password:(nodester password)
Password:(nodester password)
Password:(nodester password)
nodester info clone complete
nodester info Writing app data to config in test001.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
nodester info test001 started.
nodester info Some helpful app commands:

```
 cd ./test001
 curl http://test001.nodester.com/
  nodester app info
  nodester app logs
  nodester app stop|start|restart
```

C:\Users\rucheat>nodester app info test001
nodester info Gathering information about: test001
nodester warn test001 on port 14324 running: false (pid: unknown)
nodester info gitrepo: git@nodester.com:/node/git/rucheat/6171-8bcd3165d23f5cf9752058333cea9960.git
nodester info appfile: server.js

C:\Users\rucheat>curl http://test001.nodester.com/
<html><head><title id="title">503 - Application offline</title></head><body><br/><br/><br/><br/><br/><center><img src="http://nodester.com/images
/rocket-down.png" alt="logo" /><br/><h1 style ="color:#000;font-family:Arial,Helvetica,sans-serif;font-size:38px;font-weight:bold;letter-spacing:
-2px;padding:0 0 5px;margin:0;">503</h1><h3 style ="color:#000;font-family:Arial,Helvetica,sans-serif;font-size:24px;font-weight:bold;padding:0 0
 5px;margin:0;">Application offline</h3></center></body></html>
C:\Users\rucheat>

Regards,
Ruchit.

**Comment by chrismatthieu** [comment]
This sounds like an RSA key or passphrase issue - not your nodester password.  You can learn more about setting up your RSA key on a Windows machine on our FAQ page at http://nodester.com/help.html#faq

Another option would be to generate a new RSA key without a passphrase.  Basically your code is not actually being pushed to our servers because you do not have access to your git repo due to an RSA key issue on your machine.

**Comment by rucheat** [comment]
I have tried all this options still i am not getting application running ,,,
its still showing same error and in browser application offline message.
so tell me what to do ??
