### ISSUE TITLE
fs, bad file descriptor

### ISSUE THREAD

**Issue by iatek** [nodester/nodester#296]
I saw the previous closed issues re: this. I'm trying to write image files using 'fs', but I'm still unable to do so.

I have created a 'files' folder off my app root, but when I try:

fs.writeFileSync(__dirname + '/files/' + filename, body, 'binary');

I get:

"Error: EBADF, Bad file descriptor '/app/files/6415031459_c3ce9f86e2_z.jpg'"

I have also tried:
fs.writeFileSync( './files/' + filename, body, 'binary')

AND

fs.writeFileSync( 'files/' + filename, body, 'binary');

What am I doing wrong> Is this possible?

**Comment by XULRunner42** [comment]
How about `/app/files/`?

**Comment by chrismatthieu** [comment]
Did you already create a "files" directory in the root of your app before pushing your app to Nodester? You may need to put a temp file in the directory before pushing too - not sure.  Local sandbox file system reads/writes is permitted.

**Comment by iatek** [comment]
Yes, I did make a files and it's in my local repo. I did "git add -A" before push so I'm pretty sure it's there. I'll do some more work with 'fs' to make sure. Thanks.

**Comment by XULRunner42** [comment]
Git does not ever commit empty directories, so if you have one, careful to put a file (even `.keep` or another empty file) in there before assuming it has been committed into the repository.

**Comment by nodester** [comment]
We made a permission change on the directories. Would it be possible for you to create a new app on nodester and re-test to see it this resolves the issue?

**Comment by alejandro** [comment]
no response, to old! Moved to #313.
