### ISSUE TITLE
trying to set up nodester: user document/database

### ISSUE THREAD

**Issue by XULRunner42** [nodester/nodester#297]
Hello, I am trying to deploy nodester on my local machine, so far I have succeeded in making the proxy respond to the addresses I specified in config.js, and I have reconfigured nodester-cli to talk to my local instance, so that `nodester user register CouponCode` apparently succeeds.  However no user is created, from the looks of couchdb... there doesn't even appear to be a table to create them into.

Only nodester_coupons, which I guess is working, even if there's only room for one coupon code in this version.  Also the other databases that were named in example_config.js

That is as far as I can get without diving into more code, which I will probably do next.  I haven't really found the slightest clue how to install `nodester-admin`, all I found is that I need to make `admin.nodester.com` an entry in `/etc/hosts` or change the string in a bunch of places in HTML files and one javascript file where the redirect is declared.  Also that it can't be installed by a regular user in the "admin" slot.  Maybe I could install it with an app name of my own, and move it... except for the fact that

Login fails.  The couponcode register passes with no error that I can detect, and I can't guess where to look for it, if the result of that might have been written somewhere.  I would create the user document myself in couchdb, and just move past, but not sure what it should look like.  That is probably the easiest thing for me to figure out for myself.  I don't think it's necessary to use the admin app, if you can just get past `nodester user setup`.  It would be nice to have the whole shebang deployable as git submodules...

I would like to take a stab at updating your documentation, if you will help me deploy on my own machine!

Thanks,
Kingdon

**Comment by XULRunner42** [comment]
I made a lot of progress, creating my user's document through the function in user.js attached to post:

Needed to make some commands sudo'able, which was not exactly covered in the ancient tome of installation... there also may have been some typos in there, I don't know for sure, I copied the important bits out and ran it in `node` console locally, replacing calls to `res.`anything with `sys.puts`

I can connect now, and I found out about view functions that need (to be enclosed in parenthesis), another surprise: http://stackoverflow.com/a/9045077

I do `nodester app create nofrack server.js`
I get some very sensible looking reports about a `gitrepo: nodester@localhost:/git/yebyen/3-5a5aaa1ee168f58d51ad7865ef6ac088.git` (which I cannot locate on closer inspection, but the clone succeeds...)

Now I `Cannot PUT /app` and I'm stuck there.  At least I'm getting errors again.

I'm going to try this until I get successful results from only using documentation... since I seem to be so close

Should I start a wiki page to place the updated installation document?  I will at least send a pull request to make this not so hard, soon.

**Comment by chrismatthieu** [comment]
I am very excited to see you helping us work through a private cloud deployment of Nodester!  We would appreciate documentation updates or even the completion of our nodester installer project https://github.com/nodester/nodester-installer 

The user table in Couch is NodeFu. (We should have just called it users.)  Other tables in our couch database include: aliasdomains, apps, coupons, nextport, password_resets, and repos.

Nodester-amin is a third-party app deployed as appname admin.  It's repo is located at https://github.com/nodester/admin-panel.  It's a good start for an admin panel but needs more features plus we need to fix the delete apps issue.

I agree with you on the submodules idea.  It would also be cool to build an nodester npm installer.

**Comment by chrismatthieu** [comment]
Yes, please feel free to create new wiki installation pages.  I can also add you as a collaborator on the nodester installer project (and others) if you are interested!  

We appreciate your help :)

**Comment by XULRunner42** [comment]
Thanks :)

Where do the bare git repos go, after they are created?  I think they belong in `/git`, but none seems to have materialized there.  It's owned by the nodester user, there was no trouble writing to ssh `authorized_keys` file.  I guess I should look into the git scripts?  Please confirm there should be something in `/git` after `nodester app init foo`

**Comment by chrismatthieu** [comment]
We have the repos organized under /app/{username}/{git_repo_name}.  There are actually 4 directories currently being created for each app (repo, repo_chroot, repo_pre_chroot, repo_rw).  I think that this should definitely be cleaned up.

**Comment by chrismatthieu** [comment]
Just checking in to see how your private cloud deployment of nodester is coming along.  We are very interested in updating the steps on our site with your lessons learned and would love to get your help on standing up a public AMI and writing an install.js app to help ease this installation for others.

Thanks,
Chris

**Comment by XULRunner42** [comment]
I will give my effort a second push now that I have your perspective and blessing... install.js approach to deployment.

I have added a FreeBSD9.0 system to my testing cluster, as previous system was a fun (scary) hybrid of both Debian Lenny and also Debian Squeeze and Sid, not even sure what versions are underneath the various versions of system software that I have running nodester-cli and nodester and couch, I had to test a lot of versions and node/npm install strategies to "get it right" and make the dependencies-verify.sh succeed without complaining and without adding extra cruftiness in local node_modules.

If I hit the same blocker on both my BSD and Linux test systems, I will be sure to create an issue for it.

Thanks for taking a (public) interest!
Kingdon

**Comment by XULRunner42** [comment]
Trying to figure out the meaning of AMI,

So far best meaning I have found is "American Mustache Institute."

OK, I got it, you must mean an Amazon Machine Image.  I guess that working `npm install nodester` is preferable, although maybe not in some cases.  I got all of the dependencies installed on FreeBSD 9.0, except for CouchDB, which is still compiling something called Erlang-Lite.  I'll be giving the setup process another go tonight on this platform.  I was using nodester-installer and the latest node.js (v0.6.10) that comes with npm bundled.

**Comment by chrismatthieu** [comment]
Yea, sorry about that :) Amazon Machine Images allow AWS customers to spin up pre-configured servers. We would love to offer a publicly available AMI that would allow anyone to launch a Nodester cloud on EC2 in a couple of minutes.

Your NPM Nodester installer is _even_ more attractive because it would allow people to install a Nodester private cloud on other cloud services as well as private datacenters and even localhost development machines.  We believe that this enable more Node.JS developers to get involved with contributing to our cool open source PaaS.

I will be adding you as a collaborator on the nodester installer repo so you can feel free to begin committing directly to that repo!

Thanks,
Chris

**Comment by XULRunner42** [comment]
Thanks!

I am having a problem that I think is somewhere between nodester-cli and nodester-api now,

If I issue the user register command directly with curl, it succeeds:

```
curl -X POST -d "coupon=nodelinger&user=yebyen&password=wilbur&email=XULRunner42@gmail.com&rsakey=ssh-rsa AAAAB3..." http://api.nerdland.info/user
{"status":"success"}
```

which is followed up with creation of /git and /app folders for my user, though no repos are ever created...

however, 

```
nodester register couponcode nodelinger
```

(regular success messages)

But nothing is created in nodefu, nor any folders in /git or /app for my user.

I feel awful asking you these simple questions, but I'm just coming into layers upon layers of problems that look like nobody has attempted to deploy this stuff in a while.  In the last installation attempt, I was having strange problems with my CouchDB views, they are gone (those problems) now that I'm on FreeBSD.  I read something about a strange version of spidermonkey causing problems in a Debian forum.  Chalk that one down...

I'm going to try to issue the `app create` command directly to the HTTP interface, since that worked for `user register`, to rule out any possibility of error caused by `nodester-cli` or `nodester-api`

**Comment by XULRunner42** [comment]
- The working version of CouchDB was installed with correct dependencies from FreeBSD ports tree...

I installed the latest version of node.js manually, v0.6.10

FYI

**Comment by XULRunner42** [comment]
Once I found `mkdir`, and `git init --bare`, the missing pieces...

```
curl -X PUT -u "userstring:password" -d "appname=nofrack&running=true" \
  http://api.nerdland.info/app
Cannot PUT /app
```

... not sure, looking at app.js: `put: function (req, res, next)`

I don't see anything that should be writing a message back like "`Cannot PUT /app`"

Any ideas?

**Comment by XULRunner42** [comment]
Just to come full-circle,

I get almost the same thing on nodester.com instance:

```
nodester info Some helpful app commands:

     cd ./nofracktest
     curl http://nofracktest.nodester.com/
      nodester app info
      nodester app logs
      nodester app stop|start|restart
[nodester@minnah-bsd ~]$ cd nofracktest/
[nodester@minnah-bsd ~/nofracktest]$ nodester app info
nodester info Gathering information about: nofracktest
nodester warn nofracktest on port 14603 running: false (pid: unknown)
nodester info gitrepo: git@nodester.com:/node/git/yebyen/6450-08fe078d0bc030a3cd8cd37ba9bb3d57.git
nodester info appfile: server.js
[nodester@minnah-bsd ~/nofracktest]$ nodester app start
nodester info Attemping to start app: nofracktest
nodester ERROR Fatal Error! API Response: Cannot PUT /app
Reason: HTTP Error 404 returned.
```

**Comment by chrismatthieu** [comment]
We are having the same Cannot PUT errors on the Nodester.com.  https://github.com/nodester/nodester/issues/305

I have been researching this issue off and on for a day now.  That message is not in our codebase.  It must be coming from Express but not sure yet why.  I love a good mystery :)

**Comment by chrismatthieu** [comment]
The /app API source is in lib/app.js

**Comment by XULRunner42** [comment]
I haven't dug any deeper into Express... I was using Mustache/Sinatra for this, I get the idea that Express supports a lot of things listed in the third-party modules section, messages and expose, param, ...

Kind of get the idea that I will need to read about all of the dependencies of Nodester to get the most out of the platform.

I see that the admin application on nodester.com has gone down.  503.  You are probably aware of this.  I haven't had time to push it further, I was stuck on cannot put /app when attempting to start the new app.  I think I know how to launch node apps on my own (and manage them into subdomains with Apache), is there anything funny about the way this happens with nodester that's worth reading about?  There's forever, and from this discussion I guess "express" might be involved too

**Comment by chrismatthieu** [comment]
We fixed the /apps and /app PUT issues yesterday.  We are working on an issue with starting and cloning apps today.  Hopefully services will be restored shortly.

BTW, I just commented out the admin panel login on the site.  It's not meeting people's needs and confusing them in the process (i think).  We need to do a little more work to it and then relaunch the admin panel.

**Comment by XULRunner42** [comment]
I see just what you say, you can PUT /app now, and issue the start command, app shows status of running: true, but there's no sign that the app has started.  Visiting the app shows 503 Application offline, 

Thanks!  I think that the admin app was important, but if it's not working/misleading people, disabling it in the short term is probably the way to go.  This is pretty interesting, from nodester logs:

```
yebyen@easyone:~/kpbtestapp$ nodester app logs
nodester info Showing logs for: kpbtestapp
New PID: 8508
chroot_runner
chroot_runner
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Process died with exit code 127. Restarting...
Error: Restarted too many times, bailing.
```

I'm not sure if those are from the logs, or from the attempt to retrieve the logs...

Am I spamming this issue?  Are you in an IRC channel somewhere that could use some spam of this type?

I'll be working on nodester this weekend, too

**Comment by chrismatthieu** [comment]
Please see my response on ticket 308. I will be working on nodester this weekend to resolve the issue with apps not starting.

**Comment by XULRunner42** [comment]
I'd love to pick your brain (or @glassdav) how it was fixed, I pulled the nodester repo and did npm update, not sure where you made changes, or what configuration is needed to make the chroot_runner go, in /app, or 

My project is actually based on howtonode.org, and that's a wheat blog, which means it's trying to read .git/packed-refs to find out about the history of its articles.

I guess nodester is "unpacking" the git repository and stripping it from .git before it puts it into /app

http://nofracktest.nodester.com/ Error: ENOENT, No such file or directory '/app/.git/packed-refs'

when you try to click on the only link, you get this.  Is the git dir still available from within the running app (chroot)?  I'm trying to figure out if I have access to `ls`, or some function that performs the job of `ls`, you can see I am a real node-newb.

I wish I could provide more information, but `nodester app logs` from my local instance won't permit it... :(

**Comment by chrismatthieu** [comment]
The issue with with apps not starting was related to the "node_base_folder" directory being empty.  The location of this folder is setup in the config.js but apparently was empty from the new AWS EBS volume update.  This directory includes the base files for chroot sandbox.

Yes, I believe that the git repos are being unpacked into app directories on the nodester platform i.e. /app/xulrunner42/{repos_names}

Hope this helps...
Chris

**Comment by XULRunner42** [comment]
I was able to use a function traverseFileSystem from the implementation based on readdirSync to see that /app/ does contain the `.git/` folder, and some of the other parts of the chroot.  Neat.  You can't use the system version of `ls`, not because it's not included, but because of bad libcap or somesuch

I guess you might not want to put certain binaries in the chroot, but could you consider some of these:

stderr: ls: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory
`git pack-refs` -- there is no `git` client installed in the chroot

if you would just run `git pack-refs` on your repos, that would really solve my problem.  Maybe you can run it in a post-commit hook?

**Comment by XULRunner42** [comment]
I found `scripts/start_hosted_apps.js` which seems to have got me a lot further, I've discovered some more things that should be in `sudoers` file that are not...

I've also discovered that something is going to try a unionfs mount, so this FreeBSD-Nodester is maybe not going to happen!  I'll go back to linux and see how much of my progress I can re-apply there.  I don't have a system with upstart support, so maybe I will spawn an ubuntu machine and "move out of the dark ages" as my colleague suggests sometimes, where debian is in the dark ages and Ubuntu is what I ought to be using... maybe they have chosen the right version of spidermonkey where I don't need to manhandle the default couchdb views created in the nodester setup process.

I am going to close this issue and set up a wiki page, just as soon as I've rebooted to the platform with unionfs support.

Thanks for all the help Chris and others!

I don't think there is anything like unionfs in FreeBSD... maybe zfs v28 with dedup support could provide a similar experience, I haven't tested that at all yet.

**Comment by XULRunner42** [comment]
On my way to Linux now, since I want the unionfs chroot stuff to work,

I was wondering if you made the `nodester npm install` command work the way it does...

My local package.json includes some url/tarball refs now, because I needed to make a change to git-fs module, a deep-down dependency in my wheat blog.  The git-fs (node-git) module had a change somewhere that did not get pulled, to prevent this ENOENT, it should just call gc for itself and let the packed-refs be generated that way.

However, `nodester npm install` seems to ignore my url deps, installing what npmjs registry has scoped out as the newest version, instead of the tarball url that is actually specified in the package.json file, leaving me high and dry to test my fix at nodester.com.  I confirmed that `npm install` in my app will install everything from my own forked repos into node_modules, what I was not able to confirm is that my forked version of git-fs actually solves the issue with packed-refs in the absence of a git binary.

I saw that you gave me push access, would you prefer if I fork and submit a pull request rather than just start making updates into your repository?

Like I said, still kind of a newb here.

**Comment by chrismatthieu** [comment]
XULRunner, Could you email your skype address?  I would like to add you to our installer chat with @marcosvm and @gleicon.  chris@nodester.com
