### ISSUE TITLE
Can't run any commands after npm install

### ISSUE THREAD

**Issue by chaselee** [nodester/nodester#300]
Install globally with npm, can't run any commands after successful install, not even help.  Always get this:

```
chaselee@dexter:~$ nodester user setup woot woot

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
          ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:378:11)
    at Object.<anonymous> (/usr/local/bin/nodester@0.2.37:4:21)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

Any ideas on why would be greatly appreciated!  I'm pretty new to node/npm, so sorry if this is really dumb =/

**Comment by chrismatthieu** [comment]
Hi Chase,

A couple of questions: 
1. Did you already register for your nodester account using our coupon at http://nodester.com/help.html#register
2. Did you install the Nodester CLI with sudo permissions?
3. If yes to both of the above, please provide us with more information such as your OS, Node.JS version, and actual username so we can verify that your account was created properly.

Thanks,
Chris

**Comment by chaselee** [comment]
Ubuntu 11.10
v0.6.10
chase

Thanks!

**Comment by chrismatthieu** [comment]
Yep, your account looks good on our platform and we do support both ubuntu and node.js v.6.10 with our REST API and CLI.  Hosted apps will run under node.js v0.4.9.  

Did you run sudo npm install nodester-cli -g on the installation of the CLI?

**Comment by chaselee** [comment]
Yep
On Feb 10, 2012 2:51 PM, "Chris Matthieu" <
reply@reply.github.com>
wrote:

**Comment by chrismatthieu** [comment]
You stumped me, bro :)  It looks like a local pathing issue with your node.js.

**Comment by chaselee** [comment]
Damn. I'll report back when I figure it out.
On Feb 10, 2012 3:37 PM, "Chris Matthieu" <
reply@reply.github.com>
wrote:

**Comment by chaselee** [comment]
So I found the problem.
The require.paths function has been removed in all 5.xx releases and on of Node.

**Comment by iancrowther** [comment]
I have the same issue, what is the solution?

**Comment by boricles** [comment]
Same problem here, would you please let me know how to fix it?
TIA

**Comment by chrismatthieu** [comment]
Weird. I am running node.js v0.6.7 on my MBP and the nodester-cli installed and runs fine so I dont think it's a require.paths deprecation issue.  

Are you guys upgrading from a previous version of nodester-cli?  
Are you also running ubuntu like Chase?

**Comment by iancrowther** [comment]
Hi boricles,

My exact setup was node, npm, express & nodester.  I ended up removing all the installs and cloning from github.  Everything works fine now, I must have corrupted something whilst experimenting.  Do you have VM's? this may be a safe environment to experiment.

I think it will be easier to simply start again.  Sorry there was no silver bullet.

**Comment by chrismatthieu** [comment]
Thanks for the info.  There are several guys working on our installer project: https://github.com/nodester/nodester-installer

This will allow you to easily install a nodester private cloud instance on your localhost of cloud platform of your choice.
