### ISSUE TITLE
Strange websocket issues

### ISSUE THREAD

**Issue by akavlie** [nodester/nodester#304]
Just sent this to Chris via email, but this is probably a better place for it:

I just put Subway (successor to web-irc) up on Nodester the other day (subway.nodester.com). I'm getting some weird problems that may (or may not) be websockets related... have you seen anything like this?

If you put in a valid IRC server, things seem to be OK. If you don't, the IRC backend sends an error event over socket.io, which works perfectly in local development.

On Nodester however, when I put in a gibberish server name, I get this in my console:

`GET http://subway.nodester.com/assets/images/loading.gif 503 (Service Unavailable)`
`GET http://subway.nodester.com/socket.io/1/?t=1328936483638 503 (Service Unavailable)`

Furthermore, I'm seeing something else weird on connection... the registration event isn't sending back the arguments it should be.

I just tried running with node 0.4.9 locally via nvm, with the same module versions as I have on nodester, and I can't reproduce the issue.

This is what I'm using to connect to socket.io from the client:

`io.connect(null, {port: PORT})`

where `PORT` is 80 in production.

**Comment by yocontra** [comment]
Did you confirm the version of socket.io for your app is the same as on your local machine?

**Comment by akavlie** [comment]
Yes, both are on socket.io 0.8.7

**Comment by chrismatthieu** [comment]
Are you going to the NodeAZ meetup tonight?  Perhaps we can take a look at it there...

**Comment by akavlie** [comment]
Yep, see you soon.

On Mon, Feb 20, 2012 at 5:37 PM, Chris Matthieu <
reply@reply.github.com

**Comment by chrismatthieu** [comment]
To recap, Aaron and I met last night to walk through his Subway app.  It looks like nodester may not have a copy of _all_ of his most recent files.  He is pushing from specific git branches and we noticed at least 1 file between nodester and his localhost with different file dates.

I recommended that he do a nodester app gitreset to clear out his nodester repo and do a fresh git post of his application.

**Comment by akavlie** [comment]
I tried `nodester app gitreset`, and pushing it to a new app instance ("subway2"), but I'm seeing the same problems.  :-(
I can't make heads or tails of it.

**Comment by chrismatthieu** [comment]
The only other idea I have at this point would be to ask that you push the
app as master to rule out a git branching bug.

-Chris

On Thu, Feb 23, 2012 at 10:47 PM, Aaron Kavlie <
reply@reply.github.com

**Comment by akavlie** [comment]
OK, our master branch has bcrypt now, and that doesn't play well with Nodester (https://github.com/nodester/nodester/issues/264). So... I made a separate source checkout, did some branch renaming, deleted/recreated the app, and pushed a local branch now named "master". And... no change.  :-(

**Comment by alejandro** [comment]
@akavlie anything new about your issue?

**Comment by juzerali** [comment]
Facing the same issue with nowjs demo chat app. See http://chatterbox.nodester.com
I am unable to communicate with the server however, this app runs fine on my private LAN.

**Comment by alejandro** [comment]
@juzerali can you please join us on freenode#nodester or irc.nodester.com to help you out :)

**Comment by juzerali** [comment]
@alejandromg I tried many a times accessing http://irc.nodester.com But I am unable to login. The page asks only for my username. When I put `juzerali`, which is my nodester userid, the page simply refreshes.

**Comment by alejandro** [comment]
That's weird. Well, then what are the logs saying about it?

**Comment by juzerali** [comment]
About IRC: I can see a loader and a message that it is trying to log me in.

I am getting nothing in the logs.

```
$ nodester app logs chatterbox
nodester info Showing logs for: chatterbox
New PID: 22518
chroot_runner
chroot_runner
Running node v-0.4.9
Express server listening on port 16464 in production mode
```

On my page I am seeing following error in javascript console. I can supposedly call methods on my server through `now` variable.

```
Uncaught TypeError: Object #<Object> has no method 'distributeMessage' http://chatterbox.nodester.com/:14
(anonymous function) http://chatterbox.nodester.com/:14
d.event.handle jquery.min.js:16
d.event.add.k.handle.m jquery.min.js:16
```

**Comment by alejandro** [comment]
@juzerali I'm more than sure that that's causing because the sync process between your front end and the server is failing.  Check out this http://nowjs.org/doc/variables and let me know if that fix the problem....

**Comment by juzerali** [comment]
Nopes. I have copy pasted this example from http://nowjs.org only. There is nothing to variable assignments. I also tried putting the variable assignments inside `now.ready` but that event keeps firing and is not something like `window.onload` or `document.ready`. Moreover this app is running fine on local.

**Comment by akavlie** [comment]
@alejandromg Sorry I haven't been responsive re: Subway. I should try it out on Nodester w/ Node 0.6 and see if there are still socket.io issues.

We've got it hosted on another server (http://ridezap.com:3000/) with MongoDB for logging, so there isn't a practical need for the Nodester instance any longer.

**Comment by chrismatthieu** [comment]
## LinkedIn

Aaron,

I'd like to add you to my professional network on LinkedIn.
- Chris

Chris Matthieu
Manager of Systems and Technology Architecture at Bechtel Corporation
Phoenix, Arizona Area

Confirm that you know Chris Matthieu:
https://www.linkedin.com/e/-qxhe85-h2apfc2w-9/isd/7124163723/P4VnsBQW/?hs=false&tok=0K8gw8B2D045g1

## 

You are receiving Invitation to Connect emails. Click to unsubscribe:
http://www.linkedin.com/e/-qxhe85-h2apfc2w-9/IC7JtWAcMh9r3mfyO28KJZifV_NkTVb0Nhti2a8xM_lmAty5oyoKEdGNEpNmUVM0f_X0iRZf2VQIPM50ODwJylCBip_IPVW1OLA3KN2N1N1wQcQ/goo/reply%2Bi-3186994-a6b5f88382388bb751c59dc5e24eaeb0b5923886-12523%40reply%2Egithub%2Ecom/20061/I2431433544_1/?hs=false&tok=3TEvZuNMj045g1

(c) 2012 LinkedIn Corporation. 2029 Stierlin Ct, Mountain View, CA 94043, USA.
