### ISSUE TITLE
I am getting a error starting my app

### ISSUE THREAD

**Issue by jtwebman** [nodester/nodester#305]
nodester info Attemping to start app: googleplusrss
nodester info { response: 'Cannot PUT /app', errorCode: 404 }
nodester ERROR Fatal Error! API Response: Cannot PUT /app
Reason: HTTP Error 404 returned.

JT

**Comment by chrismatthieu** [comment]
I am too. Trying to research it now. It's happening on start, stop, and restart.  The git push is restarting the apps correctly but the API is not responding correctly.  Let me know if you see anything in the code that could cause this issue.  The funny thing is that I think "Cannot PUT" is coming from express and not our code.  Something is wonky...

It seems to have started happening when we upgraded the storage last night.

**Comment by chrismatthieu** [comment]
We are still researching this issue.  Pull requests from anyone watching would be appreciated.

**Comment by jtwebman** [comment]
This looks fixed now.

**Comment by chrismatthieu** [comment]
THANKS TO @davglass NODESTER APPS ARE STARTING AGAIN! PLEASE GIVE HIM A SHOUT OUT ON TWITTER!
