### ISSUE TITLE
ssh_exchange_identification and failed-to-setup_unionfs_chroot

### ISSUE THREAD

**Issue by odrix** [nodester/nodester#307]
I cannot push my app to nodester
Error message return : "ssh_exchange_identification: Connection closed by remote host
 fatal: The remote end hung up unexpectedly"

And when I watch the info of my app, I see :
  app status    failed-to-setup_unionfs_chroot
  process id    unknown

My app name on nodester is "jsairhockey"

What can i do ?
Create a new app ?

**Comment by chrismatthieu** [comment]
I am getting these errors too as are others.  We are researching...

**Comment by chrismatthieu** [comment]
fixed.

**Comment by odrix** [comment]
It's ok I can push my app with git.
When I ask Nodester with "nodester app info jsairhockey", Nodester answer my app running.
But when I go to jsairhockey.nodester.com the browser respond "503 - application offline"
What can (must) I do to work fine?

**Comment by chrismatthieu** [comment]
We are tracking that as a separate issue.  See https://github.com/nodester/nodester/issues/308

**Comment by odrix** [comment]
ok I wait :)
