### ISSUE TITLE
Integration with DocPad

### ISSUE THREAD

**Issue by balupton** [nodester/nodester#309]
Hey Nodester,

I run a Node.js based CMS application called [DocPad](https://github.com/bevry/docpad), and for a while now I've been wondering about how one could integrate deployment directly into the CMS. I have a few ideas, which I'll share hear.

My goal is to add a GUI to DocPad, and up the top right there will be a sync button. So say you are working locally, you've now changed a few files, sweet, looks good, lets click the sync button - this will trigger a git commit of the changed files, a git push, and then a deploy to the server.

With html5 push notifications enabled, other windows you have open will automatically pull in the changes, and refresh their displays.

So that is the vision. Now how to accomplish this? Ideally, I'd love for the deployment infrastructure to revolve around plugins, well rather adapters - so you have a nodester adapter, a no.de adapter, a github pages adapter, a ftp adapter, whatever. However, nodester seems really promising from a more completely integrated solution.

Let me talk about what I mean about integrated solution for a moment. For DocPad to really kick ass, people need to be able to try it, right away, without downloading it. For instance when running locally, DocPad kicks JSFiddle's ass! Like big time. But the problem is you have to install it. Now, what would be better is you go to docpad.com, signup for an account, and bang you've got a docpad instance in the cloud - and alas a nodester instance. You can then make a bunch of changes, sweet. Okay now it is time to get DocPad on my local machine, I really want to start hacking on this locally so I can use my local editor instead of Cloud9. So I click the clone local button, and it gives me the instructions or does it automatically. Now I'm up and running locally, great edit a few files, and click sync locally to deploy my new local changes to the docpad in the cloud I just setup a few minutes ago.

Now say I setup docpad locally on my laptop as well as iMac, on the laptop I'll see there are new changes to pull in, I can review these changes, and then click sync to grab them in.

So that is where I want DocPad to go, and I'm hoping nodester will be one of the main pieces of the puzzle there. So how crazy am I???? Would this work beautifully?

**Comment by chrismatthieu** [comment]
DocPad sounds awesome! 

Nodester uses git to push and clone apps.  You should be able to create an app on nodester and run nodester info to see the git repo url and then run a git remote add nodester {repo url} and then git add . / git commit -m "updates" and git push. 

We are also looking into adding github post commit hooks which could be an interesting way to sync repos too.

I would love to learn more about DocPad and the help you brainstorm ways to integrate it with Nodester.  I see that we are now connected on Skype.  Let's pick this discussion up there!

Cheers,
Chris
