### ISSUE TITLE
Get a list of current domain aliases for the domain

### ISSUE THREAD

**Issue by agnoster** [nodester/nodester#31]
Something like either:

```
GET /appdomains/{appname}
```

Or simply add the data to `GET /app/{appname}`

**Comment by chrismatthieu** [comment]
Added support for GET /appdomains via cURL.  This command lists all of a user's domains and apps and returns output as follows:

curl http://topher:secret@api.nodester.com/appdomains

[{"domain":"clm.nodester.com","appname":"clm101","host":"127.0.0.1","port":8579}]

This command needs to be added to CLI.

**Comment by agnoster** [comment]
Sweet! Was adding this to the nodester-api, but it looks like it's not live yet (so I can't test it). Looking forward to it though!

**Comment by chrismatthieu** [comment]
Ok, the updates have been pushed to production.  You can proceed with the nodester-api and cli updates!

**Comment by agnoster** [comment]
Update API: https://github.com/nodester/nodester-api/pull/3

Probably won't get to the CLI update myself, have a bunch of studying to do...

**Comment by nodester** [comment]
I added the update to the CLI in the repo - just need to test it now. Not sure how to do so locally.

**Comment by davglass** [comment]
Just fixed this all up, the next release of the CLI will have this fix in it..
