### ISSUE TITLE
ssh_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by albertosantini** [nodester/nodester#310]
Executing the command "git push" I get the following message:

ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly

I tried to set the ssh key again (nodester user setkey), but the result is the same.

I tried with different apps.

**Comment by chrismatthieu** [comment]
There was an issue on our server.  Please try again...

Chris

On Mon, Feb 20, 2012 at 6:26 AM, albertosantini <
reply@reply.github.com

**Comment by albertosantini** [comment]
Now it is ok. Thanks.
