### ISSUE TITLE
Application offline

### ISSUE THREAD

**Issue by bernatfortet** [nodester/nodester#312]
http://yourshelf.nodester.com application is offline.

**nodester app logs says:**

```
nodester ERROR Fatal Error! API Response:
....
( some html, css an other stuff ) 
...
Reason: JSON Parse error!
```

Any idea? Thanks!

**Comment by nodester** [comment]
Hmm, there's not enough information in your update to help with
troubleshooting.  Are you able to run nodester app logs to see your logs?
 If not, you may want to verify that your RSA key was setup correctly or
verify that you have updated your NPM modules if using any.  You may also
want to checkout our FAQs at http://nodester.com/help.html#faq

Regards,
Chris

On Thu, Feb 23, 2012 at 6:57 PM, Bernat <
reply@reply.github.com

**Comment by arcamdev** [comment]
Hi! I've the same problem, please let me know if you solve it!

Thanxs

Fabiana

**Comment by ghost** [comment]
I had this issue a while ago. Most likely, your startup file is configured incorrectly. By default, it expects a "server.js". To change this setting, do a PUT request to the API, like so:

curl -X PUT -u "_username_:_password_" -d "appname=_appname_&start=_filename_" http://api.nodester.com/app

Or you can rename the file.

**Comment by chrismatthieu** [comment]
also make sure that you are using the port address that nodester assigned you (although i think this returns a different error)

**Comment by alejandro** [comment]
@socrattes you need to pass the app name in the request:

```
nodester app logs APPNAME
```

Maybe that can show you the logs.

TODO: We need to fix that response (when there is no appname in the request) nice catch btw....
