### ISSUE TITLE
REST api docs out of date for env GET

### ISSUE THREAD

**Issue by wachunga** [nodester/nodester#314]
The (http://nodester.com/api.html#rest)[REST api docs] are out of date for env GET

Following that method does not work:

```
 > curl -u "bla:bla" -d "appname=whatever&key=app_port" http://api.nodester.com/env
Cannot POST /env
```

There was a change a while back that made it consistent with other GETs. The new syntax is:

```
curl -u "testuser:123" http://api.nodester.com/env/<appname>
```

**Comment by chrismatthieu** [comment]
Fixed the docs.  Thanks!
