### ISSUE TITLE
env GET does not return environment variables

### ISSUE THREAD

**Issue by wachunga** [nodester/nodester#315]
This doesn't actually return my env variables:

```
curl -u "me:pass" http://api.nodester.com/env/omegatracker
```

yields:

```
{"status":"success","message":{}}
```

I have confirmed they are present with process.env... they're just not getting returned.

At the very least, I would expect app_port and NODE_ENV to be returned.

**Comment by nodester** [comment]
Just curious if you are able to post, get, and delete environment variables
using our REST API.
http://nodester.com/api.html#rest

-Chris

On Sat, Feb 25, 2012 at 12:05 PM, David Hirtle <
reply@reply.github.com

**Comment by wachunga** [comment]
I can definitely PUT new ones, so that part is working at least.
Haven't tried deleting.

On Sat, Feb 25, 2012 at 11:59 AM, Nodester
reply@reply.github.com
wrote:

**Comment by wachunga** [comment]
Weird, GETs are working now. Does the app need to be running, perhaps?

```
{"status":"success","message":{"foo":"bar","NODE_ENV":"nodester"}}
```

**Comment by chrismatthieu** [comment]
Interesting. Perhaps the app does need to be running.

**Comment by wachunga** [comment]
I just stopped my app and the GET is still returning my env variables.

Btw, updated the issue with a little more detail. Maybe it was "working" all along but I was expecting to see app_port and NODE_ENV at the very least.

**Comment by chrismatthieu** [comment]
That would be a good feature that someone would need to add.

**Comment by chrismatthieu** [comment]
resolved.
