### ISSUE TITLE
Can't start apps

### ISSUE THREAD

**Issue by pateras** [nodester/nodester#316]
None of my apps seem to start, even when they're just initialized. Just now, I did the following:

> nodester app create blanktest
> nodester app init blanktest

After entering my password, I saw this:

> nodester info clone complete
> nodester info Writing app data to config in blanktest.nodester.appconfig
> nodester info writing app files
> nodester info processing the initial commit
> nodester info blanktest started.
> nodester info Some helpful app commands:

```
 cd ./blanktest
 curl http://blanktest.nodester.com/
  nodester app info
  nodester app logs
  nodester app stop|start|restart
```

I then went to blanktest.nodester.com, which just said "Application offline".

Here are a few diagnostic attempts:

> $ nodester app info
> nodester info Gathering information about: blanktest
> nodester warn blanktest on port 14920 running: false (pid: unknown)
> nodester info gitrepo: git@nodester.com:/node/git/REMOVED.git
> nodester info appfile: server.js

I edited the repo url for this post (it doesn't actually say REMOVED). Not sure if that's something you'd want to make public. Anyway, notice the (pid: unknown). That doesn't look good.

> $ nodester app logs
> nodester ERROR Fatal Error! API Response: {"status":"failure","message":"No logs available."}
> Reason: No logs available.
> 
> $ nodester app start
> nodester info Attemping to start app: blanktest
> nodester warn false

For a little more complete history, shortly after I created my first nodester app (Kittenpick), I copied some source code to its directory, did an add, a commit, and a push, and it stopped working (Application offline). Every app I've made since has gotten "Application offline", so I'm guessing my commit/push broke something?

The Kittenpick diagnostics are a little different from blanktest:

> $ nodester app logs
> nodester info Showing logs for: kittenpick
> New PID: 16361
> chroot_runner
> chroot_runner
> Process exited cleanly. Dieing.

Not sure what the chroot_runners mean, or if that is even valid output when querying logs.

> $ nodester app info
> nodester info Gathering information about: kittenpick
> nodester info kittenpick on port 14917 running: true (pid: 16361)
> nodester info gitrepo: git@nodester.com:/node/git/REMOVED.git
> nodester info appfile: server.js

Notice how this one has a pid.

> $ nodester app start
> nodester info Attemping to start app: kittenpick
> nodester ERROR Fatal Error! API Response: {"status":"failure - application already running."}
> Reason: HTTP Error 408 returned.

Despite its claim that the app is running, kittenpick.nodester.com comes back with "Application offline". Same result after this:

> $ nodester app restart
> nodester info Attemping to restart app: kittenpick
> nodester info app restarted.

So that's where I'm at (pretty much dead in the water). It's clear that I've broken something, but I'm not sure what to do to fix or even further diagnose the problem. I'll provide any further info as needed.

Thank you.

**Comment by chrismatthieu** [comment]
If you are unable to nodester app init the standard hello world node.js app, it's usually an indicator that your git RSA key is not setup properly on nodester.  Without a working RSA key setup on nodester, your init and git push and git clone do not have access to your git repo on out platform.  

You may want to checkout our FAQs: http://nodester.com/help.html#faq

**Comment by pateras** [comment]
I've followed all of the steps to set up my RSA key, and everything seemed to work. I'm pretty sure I was able to initially create my first project (kittenpick) successfully, too. It was only after I did the push that things stopped working.

Here's what I'm seeing:

> $ ssh -T git@github.com
> Enter passphrase for key 'REMOVED/.ssh/id_rsa':
> Hi pateras! You've successfully authenticated, but GitHub does not provide shell access.

I got that message before, too.

> $ nodester user setkey
> nodester info sending sshkey: REMOVED.ssh\id_rsa.pub
> nodester info ssh key successfully sent

I got that one before, too.

What else can I do to verify that the RSA key is set up properly with nodester? I've done everything in the FAQ and general help pages.

**Comment by chrismatthieu** [comment]
Perhaps you could try to run nodester user setkey <path and key file> and then try to create and init a new hello world app to see if it now creates and runs.

**Comment by pateras** [comment]
> $ nodester user setkey ./id_rsa.pub
> nodester info sending sshkey: ./id_rsa.pub
> nodester info ssh key successfully sent

I switched to different directory for the following:

> $ nodester app create blanktest3
> nodester info creating app: blanktest3 server.js
> nodester info successfully created app blanktest3 to will run on port 14926 from server.js
> nodester info run nodester app init blanktest3 to setup this app.
> 
> $ nodester app init blanktest3
> nodester info initializing git repo for blanktest3 into folder blanktest3
> nodester info cloning the repo git clone git@nodester.com:/node/git/REMOVED
> Enter passphrase for key 'REMOVED/.ssh/id_rsa':
> nodester info clone complete
> nodester info Writing app data to config in blanktest3.nodester.appconfig
> nodester info writing app files
> nodester info processing the initial commit
> nodester info blanktest3 started.
> nodester info Some helpful app commands:

```
 cd ./blanktest3
 curl http://blanktest3.nodester.com/
  nodester app info
  nodester app logs
  nodester app stop|start|restart
```

cd'd to ./blanktest3.

> $ nodester app start
> nodester info Attemping to start app: blanktest3
> nodester warn false
> 
> $ nodester app info
> nodester info Gathering information about: blanktest3
> nodester info blanktest3 on port 14926 running: failed-to-start
> nodester info gitrepo: git@nodester.com:/node/git/REMOVED.git
> nodester info appfile: server.js

Application offline. No logs available.

**Comment by d60402** [comment]
For what it's worth, I ran into the same exact issue moments ago. Then I realized the machine I was running on did not have git installed. I installed git, restarted my terminal session, and then the app was properly init'd and started. (http://d6second.nodester.com)

**Comment by nodester** [comment]
Yea, that would explain the problem.  Without git installed or the RSA keys configured between your localhost and nodester, app files cannot be pushed to nodester.  Nodester will try to start an empty sandbox.

**Comment by pateras** [comment]
I definitely have Git installed. I'm doing all of this from within Git Bash.

Plus, Kitten pick worked prior to my attempt to push new code. Furthermore, Kittenpick behaves differently from my test projects. I think there's something to that. Is there a way that I can see Kittenpick's Git repository, to see if my files made it there?

**Comment by ghost** [comment]
I was facing the same issue. Any app i tried to create  failed to start. I followed the instructions given in the welcome email. I noticed that during init step .gitignore file was getting created but .git folder was not there. So just to be sure I executed the command 

nodester user setkey <file containing ssh public key>

and then recreated the app using 

nodester app create dang server.js  (rather than "nodester app create <appname>"  as given in the email).

this time the init command created the .git folder and my app is running on dang.nodester.com

**Comment by pateras** [comment]
Thanks for the suggestion, but sadly it did not work for me. I have .git folders for all of my projects, too.

The mystery continues...

**Comment by pateras** [comment]
So just to further rule out my RSA key as the problem, I tried creating and setting a new key, hoping that would help. I did the following:

1) Backed up my old key by copying id_rsa.pub to a backup directory.
2) $ ssh-keygen -t rsa -C "REMOVED@gmail.com"

> Your identification has been saved in REMOVED/.ssh/id_rsa.
> Your public key has been saved in REMOVED/.ssh/id_rsa.pub.
> The key fingerprint is:
> cd:7d:REMOVED REMOVED@gmail.com

3) Copied the created key to github (I opened the file using notepad++, selected everything and pasted it in).

4) $ nodester user setup myusername mypassword
nodester info verifying credentials
nodester info user verified..
nodester info writing user data to config

5) $ nodester user setkey

> nodester info sending sshkey: REMOVED.ssh\id_rsa.pub
> nodester info ssh key successfully sent

6) $ nodester app create blanktest9

> nodester info creating app: blanktest9 server.js
> nodester info successfully created app blanktest9 to will run on port 14987 from server.js
> nodester info run nodester app init blanktest9 to setup this app.

7) $ nodester app init blanktest9

> nodester info initializing git repo for blanktest9 into folder blanktest9
> nodester info cloning the repo git clone git@nodester.com:/node/git/REMOVED
> Enter passphrase for key 'REMOVED/.ssh/id_rsa':
> nodester info clone complete
> nodester info Writing app data to config in blanktest9.nodester.appconfig
> nodester info writing app files
> nodester info processing the initial commit
> nodester info blanktest9 started.
> nodester info Some helpful app commands:

8) $ nodester app start blanktest9

> nodester info Attemping to start app: blanktest9
> nodester warn false

And yet again, Application offline. Blanktest9 has a .git folder, populated just like the rest. I'm really not sure what I'm doing wrong here. Something that might shed a little light, though, is that this is what my Nodester app list looks like:

> blanktest  14920   failed-to-start start stop info
> blanktest2  14923   failed-to-start start stop info
> blanktest3  14926   failed-to-start start stop info
> blanktest9  14987   failed-to-start start stop info
> kittenpick  14917   true    start stop info

I removed a few of the blanktests, because they're all pretty much the same. Anyway, notice how nodester thinks that kittenpick is running. kittenpick.nodester.com still says Application offline, even after this:

> $ nodester app restart
> nodester info Attemping to restart app: kittenpick
> nodester info app restarted.

And lastly, the logs still say this:

> $ nodester app logs
> nodester info Showing logs for: kittenpick
> New PID: 32285
> chroot_runner
> chroot_runner
> Process exited cleanly. Dieing.

So have I at least managed to confirm that my Git authentication is not the problem? I'm happy to take any other steps necessary to verify that, I'm just not sure what else to do in that regard, or how to get this up and running in general.

I did notice that kittenpick's start file was incorrect, so I adjusted that using the API Explorer. It is now correctly set (and verified via the app info). I restarted kittenpick, but it still says Application offline, and the app list still claims that it's running.

Thank you for the continued assistance in trying to get this matter resolved. I eagerly await further advice, as my apps are still dead in the water.

**Comment by nodester** [comment]
The nodester app init should automatically create your git repos on nodester and your localhost and push your hello world app to nodester and start it for you.  

We see 10 apps that you have tried to create but only 1 that has created a successful sandbox.  Here are the details of this app:

{"appdir":"/node/nodester/nodester","userid":2002,"chroot_base":"/node/base/node-v0.4.9","apphome":"/node/app/pateras/6764-3fdba33a4c603c6e2af61b292c8435e4","apprwfolder":"/node/app/pateras/6764-3fdba33a4c603c6e2af61b292c8435e4_rw","appchroot":"/node/app/pateras/6764-3fdba33a4c603c6e2af61b292c8435e4_chroot","start":"index.js","port":14917,"ip":"127.0.0.1","name":"kittenpick","env":{}}

**Comment by pateras** [comment]
Yes, I've been saying as much. The question is, why is nodester app init failing to create the new projects properly, and why is the successfully created project saying "Application Offline" when Nodester says that it's running?

**Comment by nodester** [comment]
Usually the reasons for your app being offline are: 
1. There is an issue with your git or RSA key causing your code to not make it into your nodester git repo 
2. Your port address in your application does not match the one assigned by us (this shouldn't happen with a nodester app init since we do it for you).
3. Your startfile specified is not found in your nodester sandbox. Again this should not be the case on nodester app create and nodester app init since we default it to server.js.

Are you able to access your logs on kittenpick?  nodester app logs kittenpick
Which OS and version of Node.JS are you using?
Since nodester requires local write permissions, did you try installing the CLI using sudo npm install nodester-cli -g ?

**Comment by pateras** [comment]
As my second-most recent post says, these are the logs that I get for kittenpick:

> $ nodester app logs
> nodester info Showing logs for: kittenpick
> New PID: 32285
> chroot_runner
> chroot_runner
> Process exited cleanly. Dieing.

I'm running Windows 7 with the most recent version of Node.js (I just installed it last week).
I did run npm install nodester-cli -g. I only have to do this once, right?

As far as my RSA key goes, I've posted a lot on my efforts to verify that that is set up properly (and it really seems to be). My post as of 13 hours ago documents me thoroughly going through the setup guide, and everything seems to be going correctly. Is there something that I can do to definitively determine if my RSA key is properly set up, as I believe it is?

Thank you for all of your help with this. I would love to get this working, as Nodester seems like a great platform.

**Comment by chrismatthieu** [comment]
We have tested the Nodester CLI with Node.JS 0.4.x and 0.6.x. If you are running 0.7.x, you may want to downgrade to see if that fixes your issue.  As a side note: our platform is currently running 0.4.9.

I'm not sure what else to suggest to you at this time.  It's working for me and others.

**Comment by chrismatthieu** [comment]
I should also point out that another reason why apps don't start is that the NPM modules were not added to the sandbox.  Again, this does not matter running app init as the hello world app does not use npm modules.

**Comment by pateras** [comment]
I'll give a node.js downgrade a shot tonight.

I don't think iittenpick uses any installed modules, but I"ll check for that (I may have an unused reference to formidable). Nodester claims that it is, in fact, started, though, if that says anything.

If the downgrade doesn't work, I think I'm also going to try deleting all of my apps, as the problems started after I did my first push to kittenpick. I know that doesn't seem very likely to work, but it's worth a shot.

I'll report back later tonight. Thanks again.

**Comment by chrismatthieu** [comment]
Do you have an update?  Can you also confirm that your start file is server.js or that you have told nodester what it is if it is something other than server.js?

**Comment by pateras** [comment]
Sorry, been busy the last two nights. Haven't had a chance to downgrade yet.

I can confirm that I properly set the start file to index.js for kittenpick.

**Comment by pateras** [comment]
No luck using Node.js 0.6.11. Here's the attempt:

> c:\Tech>nodester app create blanktest2
> nodester info creating app: blanktest2 server.js
> nodester info successfully created app blanktest2 to will run on port 15072 from server.js
> nodester info run nodester app init blanktest2 to setup this app.
> 
> c:\Tech>nodester app init blanktest2
> nodester info initializing git repo for blanktest2 into folder blanktest2
> nodester info cloning the repo git clone git@nodester.com:/node/git/pateras/6919-4b707149ba66f2a4c438ea32388cc5de.git blanktest2
> Enter passphrase for key '/c/Users/mike/.ssh/id_rsa':
> nodester info clone complete
> nodester info Writing app data to config in blanktest2.nodester.appconfig
> nodester info writing app files
> nodester info processing the initial commit
> nodester info blanktest2 started.
> nodester info Some helpful app commands:

```
 cd ./blanktest2
 curl http://blanktest2.nodester.com/
  nodester app info
  nodester app logs
  nodester app stop|start|restart
```

> c:\Tech>nodester app start
> nodester info Attemping to start app:
> nodester warn Must pass an application name (appname).
> 
> c:\Tech>nodester app start blanktest2
> nodester info Attemping to start app: blanktest2
> nodester warn false

I also tried blowing away all of my apps (since this all started when I pushed to kittenpick), but that didn't help either.

**Comment by pateras** [comment]
I was looking at Kittenpick today, and I noticed that it did indeed reference formidable (even though it doesn't need it, I was just experimenting it at some point), which I had not installed for nodester. Since everything was fine until I did a push with a require("formidable") in it, it stands to reason that that's what could be wrong. However, two things give me pause:
1. Kittenpick did still claim to start, even though it never worked.
2. I don't see why that would cause all of my other, newly created apps, to become unstartable.

I deleted all of my old apps, so I can't really install it for Kittenpick. Might that have been the cause of the problem? And could it still be causing a problem with my account, which is why I can't get anything else to work? If so, can we purge it somehow?

**Comment by pateras** [comment]
Well, I'm willing to see this through as long as you guys are. Nodester seems like a great platform, and I'd love to work with it, but I'm out of things to try. If you have any further suggestions as to how to fix the problem, or to at least better define what is going wrong, I'll happily try them out.

Thank you for your help, and I hope to hear back.

**Comment by jopango** [comment]
I'm experiencing the same issu: the day I installed git, nodester, ... I was able to create and run a demo app, hello world. No problem. The first problem occurred when I first wanted to modify the server.php just to change the message ("Hello World\n ...").

It seems to me that the "git push origin master" command failed, and then, the application did not work anymore, and every new application create with nodester app create ... etc. don't work anymore. There is no error with app create and app init, but the apps never start, and cannot be started.

I even re-installed git with all the procedure given, and tried nodester user setkey again: no errors, but nothing changes. And I'm using node 0.6.13.

Great thanks for any help, as I  cannot use nodester anymore currently...

**Comment by pateras** [comment]
I never got it working on my Windows machine. As soon as I tried it on my Mac, all of the problems went away. There must have been something screwed up in my configuration by the push, I guess, since you're experiencing the same problem.

Good luck, and I'll answer any specific questions as I can.

**Comment by jopango** [comment]
Thanks for your answer, but I already work on a mac... I don't see what to do.

Nevertheless, I saw this topic: https://github.com/nodester/nodester/issues/345 which says that nodester is currently running low on disk space, in response to someone who seemed to have had the same problem when trying to update an app. Maybe there is a link?

**Comment by chrismatthieu** [comment]
We added more disk space yesterday.  This issue should be resolved.  Please try again.
