### ISSUE TITLE
Use package.json for npm dependencies

### ISSUE THREAD

**Issue by DanBUK** [nodester/nodester#32]
In order to make peoples life easier, lets use a package.json in the base of the apps git repo to install/update their npm modules.

**Comment by danielb2** [comment]
+1

Missing dependancies currently just result in an internal server error too, which isn't all that useful. Nothing shows up in the log.

**Comment by ricardobeat** [comment]
+5 to this

**Comment by blindsey** [comment]
+100. This would make deployments so much easier.

**Comment by gtramontina** [comment]
Any updates on this? I see it is open since Feb this year...
You could take a look at @agnoster 's yanc - https://github.com/agnoster/yanc
It has such feature... Hope it helps!

**Comment by troygoode** [comment]
+1, this would be a huge help

**Comment by yocontra** [comment]
Pushed update to nodester-cli. It reads dependencies from the local package.json file but setting it up to automatically run on git push is a whole different story. Will look into it more as we mess around on experimental

**Comment by yocontra** [comment]
Closed due to completion.
