### ISSUE TITLE
REST API irregularity

### ISSUE THREAD

**Issue by akavlie** [nodester/nodester#320]
The Nodester API exposes the list of apps at `GET /apps`, while an individual app is at `GET /app/<appname>`. It seems that the root in both cases should be consistent (i.e. change the latter to `GET /apps/<appname>`.

Also, the API to start an app is as follows:

`PUT /app?appname=<appname>&running=true`

Conforming with the standard pattern, it should be like this:

`PUT /apps/<appname>?running=true`

I'm not just being pedantic... Backbone.js expects URLs like this.

**Comment by akavlie** [comment]
Sorry... think this belongs in the nodester-api repo.

**Comment by chrismatthieu** [comment]
Hi Aaron,

I agree with your assessment of the API.  These recommendations will make it better.  We just need to coordinate the updates between the nodester platform, nodester-api, and possible the admin-panel.  We also need to assign this work to someone.

Thanks,
Chris

**Comment by akavlie** [comment]
You have to make changes in Nodester actual for the nodester-api to work like this?

**Comment by chrismatthieu** [comment]
Nice!

**Comment by akavlie** [comment]
Wow, awesome @mintplant 
If the API is in this codebase, what does nodester-api do?

Also, are you concerned about breakage for other apps that might be using the current API?

**Comment by ghost** [comment]
Oh, hey, that shows up here. I didn't get a chance to update nodester-api or admin-panel yet. nodester-api is a client module for the API, used by the cli, for example.

RE: breakage, perhaps the old routes could be left in as a fallback?

EDIT: Updated the API - https://github.com/mintplant/nodester-api/tree/issue-320

**Comment by akavlie** [comment]
Don't worry about admin-panel @mintplant, unless you really want to. I'm in the middle of rewriting the whole front end.

**Comment by ghost** [comment]
Oh, nice! Shiny new admin panel.

Okay, well, I added back in the old routes, and marked them as deprecated. API docs updated too. Going to send these in as pull requests.

**Comment by akavlie** [comment]
Yeah, well the "shiny new" will mostly be in the code. Help would be welcome if you have any design chops.

**Comment by ghost** [comment]
Sure, I can lend a hand, if needed.

**Comment by akavlie** [comment]
Would love to have some design help... the current design is pretty rough, but my ability to improve it is limited.

btw, best to take the conversation off of this message thread... I can't message you though. You need to add your email address to your github profile.

**Comment by ghost** [comment]
Ah, yes, heh. It's there now.

**Comment by chrismatthieu** [comment]
API updates have been deployed to Nodester and Nodester-API and Nodester-CLI.  Thanks @akavlie for your great recommendation and thanks @mintplant for your excellent code updates!
