### ISSUE TITLE
Cannot add a custom domain for an app

### ISSUE THREAD

**Issue by marcpires** [nodester/nodester#323]
When trying to create a custom domain for an application, i receive the following error.

nodester info adding domain jamboo.mobi to jamboomobi
nodester ERROR Fatal Error! API Response: Cannot POST /appdomains
Reason: HTTP Error 404 returned.

**Comment by chrismatthieu** [comment]
It looks like .mobi was not in our valid list of TLDs :)

I just added it.  Please retest and if fixed, close this issue.

Thanks,
Chris

**Comment by marcpires** [comment]
Hi  chrismatthieu, the issue is fixed.

**Comment by marcpires** [comment]
All working with no flaw
