### ISSUE TITLE
cannot setup user

### ISSUE THREAD

**Issue by 5worx** [nodester/nodester#325]
Hi,

i get an JSON parse error, if I try to setup my account:

i typed: nodester user setup myusername mypassword

nodester info verifying credentials
nodester ERROR Fatal Error! API Response: 
Reason: JSON Parse error!

i think its a simple error typing by a console-noob. ;)
(Oh, I'm using MAC Lion with npm and macport)

**Comment by chrismatthieu** [comment]
Which version of node.js are you using? We have tested our CLI with 0.4.x and 0.6.x.  I am running Mac OSX Lion with node v0.6.7 natively installed.  You may want to either try reinstalling nodester-cli as sudo like this:

sudo npm install nodester-cli -g

or perhaps try downgrading your version of node.js if you are running 0.7.x.

**Comment by 5worx** [comment]
Oh sorry, iForgot

i'm running node 0.6.8
npm 1.1.0-2

i reinstalled as sudo and what should i say:
nodester info verifying credentials
nodester info user verified..
nodester info writing user data to config

sorry, my mistake.

thank you very much for this very fast help ;)

**Comment by alejandro** [comment]
. @chrismatthieu Someone else was having this problem too (IRC). he was trying to add a domain when the JSON#parse failed. He is using 0.6.x... I think he opened an issue. I closed it because we fixed it then.

**Comment by chrismatthieu** [comment]
i fixed an issue with the domains yesterday.  We didn't have .mobi in our list of valid TLDs.
