### ISSUE TITLE
scripts/launch_chrooted_app.js is never actually referred to.

### ISSUE THREAD

**Issue by ghost** [nodester/nodester#326]
It _looks_ like it's supposed to provide sandboxing features, etc, but nothing ever runs it, as far as I can tell. scripts/chroot_runner.js, which is called when an app is launched, simply runs it through node or coffee, depending on the language. Is this an old file left over from something else, is it _supposed_ to be called, or what?

**Comment by alejandro** [comment]
Sorry for the late response :) But this is just an internal command. To launch via CLI apps. Nothing fancy, and I implemented a REST Endpoint so I think we are gonna delete this file ...
