### ISSUE TITLE
New app - Applicaton offline

### ISSUE THREAD

**Issue by Fannon** [nodester/nodester#331]
Hi there,

I've got this application offline issue too. Strange thing is, I even created a new App from scratch and changed nothing. Still it's offline: http://fannonsandbox.nodester.com/

Greets,
Simon

**Comment by Fannon** [comment]
`$ nodester app info fannonsandbox
←[35mnodester←[39m ←[37minfo←[39m Gathering information about: fannonsandbox
←[35mnodester←[39m ←[37minfo←[39m fannonsandbox on port 15289 running: ←[1mfailed-to-restart←[22m
←[35mnodester←[39m ←[37minfo←[39m gitrepo: git@nodester.com:/node/git/Fannon/7136-7ca59552d78450590c4149234957fe7c.git
←[35mnodester←[39m ←[37minfo←[39m appfile: server.js`

server.js:

`var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\nApp (fannonsandbox) is running on Node.JS ' + process.version);
}).listen(15289);`

**Comment by alejandro** [comment]
What about the logs? What are they saying? `nodester app logs AAPNAME`

**Comment by Fannon** [comment]
←[35mnodester←[39m ←[7m←[31mERROR←[39m←[27m Fatal Error! API Response: {"status":"failure","message":"No logs available."}

Reason: No logs available.

**Comment by alejandro** [comment]
OH I'm asuming that you git push the changes rigth? Did you add the nodester git URL to your repo? If you did: please
Delete it and create a new one I'll check to see what is happening...

**Comment by Fannon** [comment]
Sorry, I dont't know how to add the nodester git to my repo. But if you say what to test, i'll try to!

**Comment by alejandro** [comment]
Do you mind jump to IRC (freenode#nodester)? 
If you can't here we go:

```
nodester app info APPNAME
```

These command should return your git repo @ nodester so copy that and then:

```
git remote add nodester <the_url_given_by_the_previous_command>
```

So then, you do everything as normal:

```
git add <files|.|-u> // files to add or wherever
git commit -am 'YOUR AWESOME MESSAGE ABOUT CHANGES'
git push nodester master
```

And there you go...
