### ISSUE TITLE
Socket.io reconnection problem (Work on localhost)

### ISSUE THREAD

**Issue by macpie** [nodester/nodester#333]
Hi,

I have an issue using nodester and socket.io. 

My client keeps being disconnected and reconnected (every minute).

I have tried to do the same an local and it works (no disconnection or anything). 

So I guess, I must have done something wrong or need to configure my server differently on nodester ?

Thanks in advance !

**Comment by macpie** [comment]
The problem was socket.io. 

I downgrade to 0.9 and it's working now

**Comment by aymendr** [comment]
I have the same problem ! how did you do to downgrate to 0.9 please !

**Comment by macpie** [comment]
Try to uninstall & install it again, it should do the trick !

```
nodester npm list <appname>
nodester npm install <appname> <packages>
nodester npm update <appname> <packages>
nodester npm uninstall <appname> <packages>
```
