### ISSUE TITLE
App works locally, not on server

### ISSUE THREAD

**Issue by pateras** [nodester/nodester#334]
I switched to a Mac, and managed to get my apps working. However,, this very simple app is failing when I upload it to Nodester, but it works just fine if I run it locally:

``` javascript
var http = require('http');
var fs = require("fs");

http.createServer(function (req, res) {
    fs.readFile("./index.htm", function (err, data) {
        res.writeHead(200, {'Content-Type': 'text/html'});
        res.write(data);
        res.end();
    });
}).listen(15475);
```

nodester app logs returns this:

> nodester info Showing logs for: kittenpick
> New PID: 6990
> chroot_runner
> chroot_runner
> Running node-v0.6.12
> Running node v-0.6.12
> 
> http.js:593
> 
>    throw new TypeError('first argument must be a string or Buffer');

^

> TypeError: first argument must be a string or Buffer
>     at ServerResponse.write (http.js:593:11)
>     at /app/start.js:7:7
>     at [object Object].<anonymous> (fs.js:88:5)
>     at [object Object].emit (events.js:67:17)
>     at Object.oncomplete (fs.js:1064:12)
> 
> Process died with exit code 1. Restarting...
> Running node-v0.6.12
> Running node v-0.6.12

So it's clearly choking on res.write(data). This works just fine when I run locally (and if I replace that line with res.write("testing"), and I know that I'm uploading the index.htm because I cloned my nodester repository, and index.htm was there and the cloned instance works fine locally, too. I'm running node.js version 0.6.12, and I removed a bunch of white space that the logs spit out above and below the carrot (^), if that matters.

So the question is, why is my file read failing on the server and not locally?

Thank you.

**Comment by alejandro** [comment]
You may want to handle better the error. So we can see a better stack trace. Maybe it's an absolute path issue.

``` javascript
http.createServer(function (req, res) {
  fs.readFile(__dirname + "/index.htm", function (err, data) {
      if (!err) {
         ...
      } else {
        console.log(err)
     }
  });
} 
```

Also you can test your app with the `NODE_ENV=production` flag, so maybe you can reproduce the error locally.

**Comment by chrismatthieu** [comment]
Hi Pateras

Your apps are sandboxed on nodester as chrooted directories. Please review our FAQ tab on the help page for more information on reading/writing to the nodester filesystem.  

This post may help you too. 
https://groups.google.com/group/nodester/browse_thread/thread/bc72520119eb8775

Regards,
Chris

**Comment by pateras** [comment]
Thanks, guys. The logging confirmed that it was indeed a path issue, and adding the directory to the path fixed it. I'm all up and running now.

**Comment by alejandro** [comment]
@pateras cool! If you have any other problem, just ask :)

**Comment by jaydeepw** [comment]
"fs.readFile(__dirname + "/index.htm", function (err, data)"

Thanks a lot, I was facing the same issue.
The above lines solved it.
