### ISSUE TITLE
Password Reset API didn't send Reset eMail

### ISSUE THREAD

**Issue by rmetzler** [nodester/nodester#335]
I tried to reset my password but I never got a mail.
I checked my spam folder. No mail.
It's the right email address.

```
rmetzler-macbook:nodester(master) richard$ curl -X POST -d "user=rmetzler" http://nodester.com/reset_password 
{"status":"Reset password token sent to richard@eaglefeed.me"}
rmetzler-macbook:nodester(master) richard$
```

**Comment by alejandro** [comment]
Hi @rmetzler look like we have some issues with the email sender, we are goint to look at it. I'll try to send you the email.

**Comment by rmetzler** [comment]
Haven't received any email yet.

**Comment by rmetzler** [comment]
Cool. I recognized you changed the sender email and now I receive password reset tokens.

I'm not able to set a new password though

```
    $ nodester user setpass mynewpw 280395647fba9b51568dede55806f410
    nodester ERROR Fatal Error! API Response: {"status":"failure","messages":"No such token"}
    Reason: HTTP Error 404 returned.
    $ nodester user setpass 280395647fba9b51568dede55806f410 mynewpw
    nodester ERROR Fatal Error! API Response: {"status":"failure","messages":"No such token"}
    Reason: HTTP Error 404 returned.
```

I suspect the problem to be in https://github.com/nodester/nodester/blob/master/lib/reset_password.js#L52 or the next line. Maybe the wrong key is stored here https://github.com/nodester/nodester/blob/master/lib/reset_password.js#L35 or there are more than one `doc`s returned by the `list` view.

I would love to write a test for these assumptions, but I haven't found any tests. Also I recognized you put `test` in the .gitignore file. https://github.com/nodester/nodester/blob/master/.gitignore#L10
I wonder why?

**Comment by alejandro** [comment]
@rmetzler good catch! I just fixed it. I test it and it's working, try again please, and tell me your history :)

**Comment by rmetzler** [comment]
yes, I'm in! finally! :)

ok, thanks a lot @alejandromg !

I've found some more issues, and I really would like to write some tests. But I'm not that solid in nodejs testing.

I guess unit tests would need to work around require().
Acceptance tests might just issue http requests and check the response, but you would need to setup CouchDB before.

**Comment by alejandro** [comment]
np.OH! What issues? You can add them to the list? BTW any patch is welcome! :)  

Glad to help

Cheers
