### ISSUE TITLE
Unable to initialize my app

### ISSUE THREAD

**Issue by juzerali** [nodester/nodester#336]
I created a sample app and ran the command `nodester app init nosuccess`. it shows success and gives me additional instructions to curl my url. I tried curl immediately there after `curl http://nosuccess.nodester.com`. An HTML content is returned which has in it `App is currently offline`. When I hit the url from browser same message is displayed with an image. Kinldy help. When I try to run from REST API, I get this message >>

```
 {
  "status": "false",
  "port": 15535,
  "gitrepo": "git@nodester.com:/node/git/juzerali/7382-bca62324762942f9411f9945280307ee.git",
  "start": "server.js",
  "running": "failed-to-start",
  "pid": null
}
```

**Comment by nodester** [comment]
We would need more information about your OS, node.js, npm versions to
help.  In the meantime, please checkout our FAQ tab on our help page (
http://nodester.com/help.html).  It sounds like you may have an issue with
your RSA key.  We have lots of tips in our FAQ to help you.

Regards,
Chris

On Tue, Mar 13, 2012 at 12:24 AM, Juzer Ali <
reply@reply.github.com

**Comment by juzerali** [comment]
I am on Windows 7. My SSH key is successfully registered on github. Also I am able to download the basic demo app that nodester provides on my local so that should mean that my SSH key is fine. I have checked out FAQ page and I have tried everything. Any help would be appreciated. Thanks in advance.

**Comment by chrismatthieu** [comment]
Your push did not make it to your Nodester repo.  This is indicative that your RSA key is not setup properly on Nodester.  Try running:

nodester user setkey {and the full path including your key name of id_rsa.pub}

**Comment by juzerali** [comment]
Is this what you mean??
I tried this but no luck, Am I missing something??
[image: Inline image 1]

On Tue, Mar 20, 2012 at 9:45 PM, Chris Matthieu <
reply@reply.github.com

> wrote:
> 
> Your push did not make it to your Nodester repo.  This is indicative that
> your RSA key is not setup properly on Nodester.  Try running:
> 
> nodester user setkey {and the full path including your key name of
> id_rsa.pub}
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nodester/nodester/issues/336#issuecomment-4599014

## 

Regards,
Juzer Ali

**Comment by juzerali** [comment]
It seems strange but my app doesn't immidiated start running after init and start. But after I clone the app on local, make some changes, save and commit again, it start running fine.

**Comment by chrismatthieu** [comment]
I just fixed this issue in the nodester-cli.  You will need to reinstall it by running:

npm install nodester-cli -g

More details can be found here: http://blog.nodester.com/post/19908106874/new-nodester-cli-fixes-windows-git-issue
