### ISSUE TITLE
my applications is closing after 1 day

### ISSUE THREAD

**Issue by ocracy** [nodester/nodester#337]
I created my appliacation and deployed my server.js so everything is fine that my website were using nodester.com. My applications closed after 1 day everytime. My applications that closed is ocracy.nodester.com and ocrtest3.nodester.com.

I'll restart my application but i cant login http://admin.nodester.com/login

Web page error 324 (net::ERR_EMPTY_RESPONSE)

**Comment by nodester** [comment]
You should be able to log into the admin dashboard but we had to stop your
ocrtest3 app yesterday for consuming too many files open on the nodester
servers.  It was causing performance problems for other applications. I
sent you a separate email but since we did not hear back from you, I
changed your startfile's name to serverx.js so it could not be restarted
without changing it back first.  Could you please rework your application
before starting it again.

Thanks,
Chris

On Tue, Mar 13, 2012 at 6:08 AM, ocracy <
reply@reply.github.com

**Comment by ocracy** [comment]
Hello,

Yes I had a problem about ocrtest3, If i joined admin panel, I would delete ocrtest3 app.. Now I am using only ocracy.nodester.com. I few minutes ago, I restared my app via "nodester app restart ocracy".. my server is working now. Is there any problem about ocracy ?

**Comment by nodester** [comment]
You should be able to log into the admin portal unless your credentials are
invalid.  You can also use the REST API or CLI to delete ocrtest3.

Regards,
Chris

On Tue, Mar 13, 2012 at 7:04 AM, ocracy <
reply@reply.github.com

**Comment by chrismatthieu** [comment]
I restarted the admin app. Please try again...

**Comment by ocracy** [comment]
Thank you chris, I joined admin panel soon. I tried to destroy my application but system is waiting then there is no response. for reason, i cant destroy my application.

**Comment by chrismatthieu** [comment]
Ocracy, 

Could you open a ticket on our admin-panel repo related to deleting apps?  On another note, your new app (ocracy.nodester.com) is also now causing our proxy to throw "Error: EMFILE, Too many open files" errors.  I think that we will need to take this application offline too unless you can rework your code base to prevent this error from occurring.

Thanks,
Chris

**Comment by ocracy** [comment]
Okey , I'll open. 

My code is simple, i didn't find EMFILE error. This is my server.js 

var io = require('socket.io').listen(15555);
var clients = [];
var coupling = [];
io.sockets.on('connection', function (socket) {

```
clients[socket.id] = socket;
socket.on('setUserID', function (userID) {

    socket.set('userID', userID, function () {
        coupling[userID] = socket.id;
    });
});

socket.on('send', function (from,to,message)
{
    var sender = 0;
    socket.get('userID', function (err, name) {
        sender = name;
    });
    var userSocket = clients[coupling[to]];
    if(userSocket != null || userSocket != undefined)
    userSocket.emit('message', {from :from,to : to,message:message});
});
socket.on('disconnect', function () {

    var sender = 0;
    socket.get('userID', function (err, name) {
        sender = name;
    });
    var userSocket = clients[coupling[sender]];
    if(userSocket != null || userSocket != undefined)
    clients[coupling[sender]] = null;
});
```

});

is it syntax error ?

**Comment by chrismatthieu** [comment]
Are you still experiencing issues with your application?  If so, could you provide your nodester log?

nodester app logs {appname}

**Comment by ocracy** [comment]
I changed my code and deployed which running on akorbul.nodester.com. I have deleted ocracy application..

**Comment by ocracy** [comment]
Hi again, My changed code is runing on akorbul.nodester.com, but again the same problem.. Every day I restart my application. Why my app is getting offline ?
