### ISSUE TITLE
Admin panel destroy application problem

### ISSUE THREAD

**Issue by ocracy** [nodester/nodester#338]
Hi, System couldn't respond, when I destroy my application.

**Comment by alejandro** [comment]
Did you try with the nodester-cli:

```
> nodester apps # to get APPNAME
...
> nodester app delete APPNAME
```

If it's yes, what's your app name, also, what's your node-version?

**Comment by ocracy** [comment]
thanks it worked

**Comment by alejandro** [comment]
Cool! 

**PS**: Just for further info, read this: ["nodester-cli help sheet"](http://nodester.com/api.html#cli)
