### ISSUE TITLE
First app install will end up with undefined in repo

### ISSUE THREAD

**Issue by DanBUK** [nodester/nodester#34]
Due to the derivation route of the repo_id from nextport table, the very first app that is created will end up with a wonky repo_id. Like

```
/var/nodester/hosted_apps/dan/undefined.git
```

Should probably move to some guid generator for repo_ids.

**Comment by chrismatthieu** [comment]
I just created a new app on nodester and ran nodester init.  The app started fine and the database successfully showed the correct repo_id.  

Could you confirm that this issue can be closed?

Thanks,
Chris

**Comment by davglass** [comment]
I added a "prep" for the nextport table in the migrate_views.js file. This sets "port:address" to 8000 if the document is empty. This allows for the first app to have a repo_id.

**Comment by chrismatthieu** [comment]
Sweet!  Thanks :)
