### ISSUE TITLE
Cannot use own module

### ISSUE THREAD

**Issue by saturngod** [nodester/nodester#340]
I got the error in info

Error: Cannot find module './modules/zg2uni/zg2uni'

I can run perfect in my localhost . However , running on nodester is not working.

I just use my own module and can't run on nodester server

var zg2uni = require("./modules/zg2uni/zg2uni");

**Comment by alejandro** [comment]
Howdy @saturngod at nodester you need to specify absolute paths, using the `__dirname` keyword (?).... try to change that line by:

```
var zg2uni = require(__dirname + "/modules/zg2uni/zg2uni");
```

And tell me if that fix the problem...

**Comment by saturngod** [comment]
thanks. It's working .
