### ISSUE TITLE
Stylus: Internal Server Error

### ISSUE THREAD

**Issue by skimberk** [nodester/nodester#344]
When I attempt to access style.css, I receive an Internal Server Error. Nothing is logged.
If I push the already compiled file (style.css), the first request will receive an Internal Server error, whilst the rest will return the already compiled copy (it isn't recompiled on Nodester, even if changes have been made to the .styl file). I'm using Stylus on Node 0.6.12.

Also, the same project works great locally.

Thanks!

**Comment by alejandro** [comment]
Hi @skimberk1 we have a similar issues at #339. I don't know much about stylus, but it seems like the compile stuff need some time to end. As you say a 500 error is throw it. Maybe you can give me your repo id and i'll take a look at it.

**Comment by skimberk** [comment]
It'd be understandable if it took a couple seconds to compile, but it here it doesn't compile at all. No matter how long I wait.

Anyway, here's the git: git@nodester.com:/node/git/skimberk1/7726-d21c1de1383a211862c1f082e74cd1d2.git

**Comment by alejandro** [comment]
I tried to run your app inside, Did you npm install your dependencies (stylus,nib ...) Also the compiler path needs to be absoute (_dirname) I don't know if the compiler is getting the full path. That would  handy to know.

**Comment by skimberk** [comment]
Yes, I've installed all the dependencies. I believe the path is absolute, although I'm not positive. Have a look:

``` javascript
function compile(str, path) {
    return stylus(str)
        .set('filename', path)
        .set('compress', true)
        .define('url', stylus.url())
        .use(nib());
}

app.configure(function(){
    app.use(express.cookieParser());
    app.use(express.session({secret: 'random_string'}));

    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(require('stylus').middleware({ src: __dirname + '/public', compile: compile }));
    app.use(app.router);
    app.use(express.static(__dirname + '/public'));
    //app.use(gzippo.staticGzip(__dirname + '/public'));
});
```

**Comment by jupapios** [comment]
@skimberk1 here is a piece of code I use for compile stylus, and works perfect in nodester

``` javascript
var stylus = require('stylus');

.....

app.configure(function(){
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser());
    app.use(stylus.middleware({ 
        src: __dirname + '/stylus',
        dest: __dirname + '/public',
        compile: function (str, path) {
            return stylus(str)
                .set('filename', path)
                .set('compress', true)
                .use(nib())
                .import('nib');
            }
    }));    
    app.use(app.router);

....
```

You need this (example)
your_project/stylus/css/main.styl
your_project/public/css/
