### ISSUE TITLE
Can't update app: "The remote end hung up unexpectedly"

### ISSUE THREAD

**Issue by andrewfiorillo** [nodester/nodester#345]
I can't update my app, but it is still running. When I run `git push origin master` it tells me this:

```
ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly
```

Also when I run `nodester app restart site` it tells me this:

```
nodester info Attemping to restart app: site
nodester warn false
```

Am I doing something wrong?

**Comment by dchymko** [comment]
I'm getting this as well. Just started in the last 24 hours.

**Comment by purepear** [comment]
Same here
git push...

```
ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly
```

**Comment by ddsakura** [comment]
Same situation in my account

**Comment by nodester** [comment]
We are running low on disk space.  We hope to have this issue resolved
today.

Thanks for your patience.
Chris

On Sun, Mar 18, 2012 at 11:36 PM, Andrew Fiorillo <
reply@reply.github.com

**Comment by alejandro** [comment]
@andrewfiorillo, @ddsakura, @purepear, @dchymko  can you please try again please?  We added more space...

**Comment by ddsakura** [comment]
I have created testing app, it works, thank you!!

**Comment by dchymko** [comment]
Yup, deployed earlier today Thanks for getting on this so quick @alejandromg.

**Comment by alejandro** [comment]
Great 2 oks! So, I'm closing this :)

**Comment by andrewfiorillo** [comment]
Yeah, it's working for me now. Thanks!

**Comment by purepear** [comment]
Works here :). Many thanks
