### ISSUE TITLE
Mongo Lab connection

### ISSUE THREAD

**Issue by vg2** [nodester/nodester#348]
Hi,

I recently started using nodester to test out a site I am creating, and wanted to use Mongo Lab (mongolab.com) to host a temporary database for the site. I am using mongoose for mongodb in node, and try to connect to the Mongo Lab database using the URI provided by Mongo Lab: (similar to: mongodb://user:pass@ds031466.mongolab.com:31466/dbname).

I connect using "mongoose.connect('mongodb://user:pass@ds031466.mongolab.com:31466/dbname')"

However, when using any page on the site that tries to access the database, it simply tries to access it for a minute before getting an "Empty Response Error" and nothing reported in the nodester logs.

I know that the link to the database is correct as when I hosted the site on my localhost using the same database it connected correctly and I was able to add and read information from it. 

Any help you can provide will be greatly appreciated! Thank you

**Comment by alejandro** [comment]
In your side everything looks fine... Interesting is that yesterday I had a similar problem with one of my dB at mongolab it was timing up but in my localhost everything was fine (i don't have this app in nodester ). Maybe is mongolab, but try this

```
> NODE_ENV=production node yourapp.js
```

And let me know If that is working...

**Comment by vg2** [comment]
Thanks for the quick response alejandromg!

I used NODE_ENV=production when running the node app locally and the site is working on my localhost using the mongo lab database, but using the exact same site on nodester and it just does not retrieve any information from the database (If that is what "Error 324: net::ERR_EMPTY_RESPONSE" means). 

On my nodester admin panel, it says that it is running in production as well, so that shouldn't be the problem. It just seems like it should work but it's not...

**Comment by vg2** [comment]
Used the exact same site on a free account on cloudfoundry and the site connects correctly to the database. I did have to specify that it would be using mongodb upon creation, perhaps there is some command like that for nodester that I am missing. If someone can clarify this please send me a message, but this case will be closed as of now.
