### ISSUE TITLE
git repo doesn't exist

### ISSUE THREAD

**Issue by abefetterman** [nodester/nodester#349]
I just created a new app today, and was trying to upload my project. However, I haven't been able to connect to the git repository. I know there were some other issues yesterday, is it possible the repo wasn't created properly?

$ nodester app info bagsoakeat
nodester info Gathering information about: bagsoakeat
nodester warn bagsoakeat on port 15993 running: false (pid: unknown)
nodester info gitrepo: git@nodester.com:/node/git/qandabe/7840-c911b6ee23a228c26a6c8ba8b78631fe.git
nodester info appfile: server.js
$ git remote add nodester git@nodester.com:node/git/qandabe/7840-c911b6ee23a228c26a6c8ba8b78631fe.git
$ git push nodester master
The authenticity of host 'nodester.com (50.16.203.53)' can't be established.
RSA key fingerprint is a1:64:54:7c:9b:73:9f:22:a8:95:44:4f:7b:25:15:68.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'nodester.com,50.16.203.53' (RSA) to the list of known hosts.
Nodester!
fatal: 'node/git/qandabe/7840-c911b6ee23a228c26a6c8ba8b78631fe.git' does not appear to be a git repository
fatal: The remote end hung up unexpectedly

**Comment by alejandro** [comment]
If you copy/paste your git URL as your logs said, there is a `/` missing between `:` and `node/app...` try that as:

```
> git remote set-url nodester NEWURLFixed.git
```

Try that and let me know If that works

**Comment by abefetterman** [comment]
Yep, that did it, I thought I checked and there was no leading slash. Thanks for the help.
