### ISSUE TITLE
Slow/failure responses

### ISSUE THREAD

**Issue by Velojet** [nodester/nodester#350]
3 days ago, everything was going fine. I had a test Express/socket.io app (tttapp) that was executing just as expected (and I was most impressed with Nodester!).

But today, on coming back to it (without any file mods), it gave a 503 Application Offline response in the browser - though it still runs fine on localhost.
I tried stripping it back to a bare Express app (minus socket.io) and recommitting it.
It took 2-3 minutes to get through the restart (it's never taken anywhere near that long before) but then still gave a 503 error.
Same result on further retries.

And now 'nodester user setup Velojet [password]' in the CLI, while it immediately gives 'info verifying credentials', takes a minute or more to return 'ERROR Fatal Error! API response: undefined'.
(OS: Windows 7 Pro)

**Comment by alejandro** [comment]
OH! Well not only you, we are looking at it, the whole platform is timing out. Thanks for the issue... Stay tuned

**Comment by alejandro** [comment]
@Velojet sorry for the downtime, aws had problem this evening, we are back again :)

**Comment by Velojet** [comment]
@alejandromg Brilliant! All back in perfect working order! Thanks for the super-prompt feedback!

And thanks HUGELY for setting up and maintaining this open platform.

**Comment by Velojet** [comment]
Brilliant! All back in perfect working order! Thanks for the super-prompt 
feedback!

And thanks HUGELY for setting up and maintaining this open platform.

John

-----Original Message-----
