### ISSUE TITLE
"Process exited. Dieing. N01"

### ISSUE THREAD

**Issue by Velojet** [nodester/nodester#351]
My app (c2exapp) returned a 503 error after functioning flawlessly and without any changes to files.

I stripped server.js back to the basic 'hello world' version and it still gives a 503 error.

The log shows:

New PID: 1111
chroot_runner
chroot_runner
Process exited. Dieing. N01

Thanks!

**Comment by alejandro** [comment]
@Velojet sorry for the late response, we were making some changes to manage our resources, the `N01` code means that your app couldn't fullfill our initial setup & configuration. Try again and let me see if you keep seeing this error.

**Comment by Velojet** [comment]
@alejandromg No worries - thanks for getting back to me.

Still getting the 503 error (works fine on locahost) - and now the rocket image (on the 503 page) doesn't display either (IE9, Firefox, Safari, Chrome - the alt text 'logo' shows in a couple).

**Comment by Velojet** [comment]
@alejandromg Update! Just tried another CLI restart and it's now working (in all 4 browsers)! Thanks again for your help.

**Comment by alejandro** [comment]
@Velojet great! Sometimes that happen  :) Just do `nodester app logs APPNAME` to see what is actually going on.

**Comment by Velojet** [comment]
@alejandromg Sorry about this, but it's offline again (c2exapp) and what's more both the CLI and the Admin Panel give me:
No logs available.
- although both the CLI and the Admin Panel say it's running.

I have 3 other apps (jmcapp, chapp, tttapp) which are in exactly the same situation (running but no logs available) - they were all running flawlessly up till now.

(Also the rocket image on the 503 page is not displaying.)

Thanks for investigating!

**Comment by alejandro** [comment]
Did you try to restart the apps. This morning the server crashed without notice.
About the rocket, is because it's cached a mainteinance version on your browser :) (I had the same issue)

**Comment by alejandro** [comment]
@Velojet I tried to restart your apps manually, tell me if they are working

**Comment by Velojet** [comment]
@alejandromg All working now. Many thanks! (I didn't try to restart the apps myself, because both the CLI and the Admin Panel told me they were running - but in future, I'll try a restart anyway).
And I hope I never see the 503 rocket again :)
