### ISSUE TITLE
Merge errors; "undefined is not a function"

### ISSUE THREAD

**Issue by ghost** [nodester/nodester#352]
Been trying to deploy an app, http://marmot-bounder.nodester.com/

Problem is, when the startup file was server.js, even after doing "gitreset"s and deleting/re-creating the app twice, I kept getting merge errors. So, I changed the startup file from server.js to main.js, but when I restart it _now_, it still fails. The logs say:

```
Process died with exit code 1. Restarting...
Running node v-0.6.12
App in audit mode by Watcher...



node.js:201

        throw e; // process.nextTick error, or 'error' event on first tick















^


TypeError: undefined is not a function
    at Object.<anonymous> (/app/main.js:1:231)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

Not sure what to make of it. Seems like some sort of git issue, mangling the files, perhaps? The script works fine locally.

**Comment by alejandro** [comment]
@mintplant hi! What's your repo id?

**Comment by alejandro** [comment]
@mintplant I think that I just fixed your problem. Could you please confirm that.

**Comment by ghost** [comment]
Whatever you did, yep, works! Danke.

**Comment by ghost** [comment]
What caused it in the first place, if I may ask?

**Comment by alejandro** [comment]
OH! Well, yesterday we were implementing a new library for manage resources in our server, and we are including some headers to the app process, if you look at your logs now you'll see a "App in audit mode by Watcher", so that process was failing, but now it's working again.
