### ISSUE TITLE
My application is offline bug

### ISSUE THREAD

**Issue by samarpanda** [nodester/nodester#353]
Below is dump of my app in nodester. Kind help will be appreciated. Thanks.

samar@sp:~/nodester/mexp$ nodester app logs
nodester info Showing logs for: mexp

^

SyntaxError: Unexpected token <<
    at Module._compile (module.js:429:25)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

Process died with exit code 1. Restarting...
Running node v-0.6.12

/app/index.js:2

<<<<<<< HEAD

^
^

node.js:201

```
    throw e; // process.nextTick error, or 'error' event on first tick
```

^

SyntaxError: Unexpected token <<
    at Module._compile (module.js:429:25)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

Process died with exit code 1. Restarting...
Running node v-0.6.12

/app/index.js:2

<<<<<<< HEAD

^
^

node.js:201

```
    throw e; // process.nextTick error, or 'error' event on first tick
```

^

SyntaxError: Unexpected token <<
    at Module._compile (module.js:429:25)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

Process died with exit code 1. Restarting...
Running node v-0.6.12

/app/index.js:2

<<<<<<< HEAD

^
^

node.js:201

```
    throw e; // process.nextTick error, or 'error' event on first tick
```

^

SyntaxError: Unexpected token <<
    at Module._compile (module.js:429:25)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

Process died with exit code 1. Restarting...
Running node v-0.6.12

/app/index.js:2

<<<<<<< HEAD

^
^

node.js:201

```
    throw e; // process.nextTick error, or 'error' event on first tick
```

^

SyntaxError: Unexpected token <<
    at Module._compile (module.js:429:25)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

Process died with exit code 1. Restarting...
Running node v-0.6.12

/app/index.js:2

<<<<<<< HEAD

^
^

node.js:201

```
    throw e; // process.nextTick error, or 'error' event on first tick
```

^

SyntaxError: Unexpected token <<
    at Module._compile (module.js:429:25)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

Error: Restarted too many times, bailing.

**Comment by chrismatthieu** [comment]
<<<<<<< HEAD 

^-- Looks like a merge error on your git repo. Can you try to clone your app from nodester to localhost and edit the failed merge and commit and repush?

**Comment by alejandro** [comment]
@samarpanda howdy! Could you please give us your app name?

**Comment by samarpanda** [comment]
@alejandromg @chrismatthieu - Thanks for looking into my problem. My app name is "mexp".

**Comment by alejandro** [comment]
@samarpanda It's a Hello World one right? It's running again. That leading `<<<` are happening because a merge conflict between your local version and the nodester one. If you have an app already please avoid the hello world one and better just add the remote to your local repo:

```
> nodester app info APPNAME
```

This is going to show you your git repo url something like git@nodester.com:/node/git/samar/.....23asda2.git
So after that, you just do:

```
# inside your app dir
> git remote add nodester GITURLFROMPREVIOUSCOMMAND.git

# Then just commit your changes and push it to nodester
> git push nodester master
```

That always is better than changing your Hello World one

**Comment by samarpanda** [comment]
@alejandromg - I tried a lot of stuffs and it seems working for me locally. But when i try pushing it to nodester it shows my app as offline. So i tried with the default hello world app. Even that gave me some problem. So i was bit annoyed. 
Anyways now its fixed. Thanks a lot. I will do as per your instruction in future.

Could you please let me know how did you fixed this git merge conflict problem. So i could fix similar problems if i face in future. Thanks.

**Comment by samarpanda** [comment]
Now i can successfully commit and push my changes to nodester. Thanks @alejandromg.

**Comment by alejandro** [comment]
@samarpanda good to hear that :) Hack the world \m/

**Comment by samarpanda** [comment]
I got the same error again. Could you please help me @alejandromg ?
Things i tried are as per our previous discussion :
1. nodester app info mexp
2. git clone (nodester_git_repo_url_as_per_app_info)
3. I committed my changes to git.
4. git push nodester master
Now if i check log of my app i.e "mexp". It shows the same error as previous. Please guide me where did i went wrong. Thanks.

**Comment by alejandro** [comment]
@samarpanda well, what I think you are doing wrong it 's the part where you `clone` the remote repo. At this step I recommend you to recreate the app, to avoid any future conflict.

If you have an app already the steps are this:

```
> nodester app create mexp SERVER|APP|INIT.js
> nodester app info mexp 
# this will log your remote git url

> git remote add nodester GITURLFROMPREVIOUSCOMMAND.git

# Do the changes
> git add .; git commit -am '[master] Pushing to nodester' 

# Push the changes
> git push nodester master
```

And go to : http://mexp.nodester.com

I think this step will fix your problems. 

Cheers

**Comment by samarpanda** [comment]
Thanks for you reply, @alejandromg 
I recreated the app. Followed your instructions. But i still experience the same problem :( !

**Comment by alejandro** [comment]
@samarpanda could you please join us at freenode#nodester or irc.nodester.com?

**Comment by samarpanda** [comment]
Thanks @alejandromg for all your help. I appreciate.
