### ISSUE TITLE
App offline, App in audit mode by Watcher in logs

### ISSUE THREAD

**Issue by rikbrowning** [nodester/nodester#354]
My app is offline (503) when you browse to it. In the logs I get the following:

New PID: 14015
chroot_runner
chroot_runner
Running node v-0.6.12
App in audit mode by Watcher...

App ID is rikstar

Any advice would be appreciated,
Thanks

**Comment by alejandro** [comment]
Just that? No restarting process or anything? What's your app name...

**Comment by rikbrowning** [comment]
App name is rikstar,
When I restart the app via nodester app restart rikstar that is what is left in the logs

**Comment by alejandro** [comment]
@rikstar Offline? For me it's running? A todo app right? Today we are having problems about speed of the server, we are investigation about it. Maybe that's causing what you see, just restart your app.

**Comment by rikbrowning** [comment]
Yeah it's now just not loading, will keep trying it hopefully I will be able to see it soon

**Comment by alejandro** [comment]
@rikstar fyi today we are seeing some slowness in the server... Sorry for hthis
