### ISSUE TITLE
503 App offline

### ISSUE THREAD

**Issue by Meesayen** [nodester/nodester#355]
I've created an app and pushed my own sources with git. But something went wrong.
Here's the log from the app:

nodester info Showing logs for: ditodes
New PID: 4274
chroot_runner
chroot_runner
Running node v-0.6.12

/app/app.js:2

<<<<<<< HEAD

^
^

node.js:201

```
    throw e; // process.nextTick error, or 'error' event on first tick
```

^

SyntaxError: Unexpected token <<
    at Module._compile (module.js:429:25)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

Process died with exit code 1. Restarting...
Running node v-0.6.12

And here is the result of the last push, the problem is the failed merge, but I don't know how to solve it.
I've also cloned the remote sources but there wasn't any problem in the app.js file...

Nodester!
Counting objects: 4, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.62 KiB, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: 
remote: 
remote: 
remote:                           _          _
remote:           _ __   ___   **| | ___ ___| |_ ___ _ __
remote:          | '_ \ / _ \ / _  |/ _ \ __| __/ _ \ '**|
remote:          | | | | (_) | (_| |  **\** \ |_  **/ |
remote:          |_| |_|_**/ __,_|_**|_**/_____|_|  
remote: 
remote:           Open Source Node.js Hosting Platform
remote:               http://github.com/nodester
remote: 
remote: 
remote: Syncing repo with chroot
remote: From /node/git/Meesayen/8117-24fb6575386af7e950e5d1e776efd976
remote:    d99cca7..cc12982  master     -> origin/master
remote: Auto-merging app.js
remote: CONFLICT (add/add): Merge conflict in app.js
remote: Automatic merge failed; fix conflicts and then commit the result.
remote: Attempting to restart your app: 8117-24fb6575386af7e950e5d1e776efd976
remote: {"status":"restarted"}
remote: App restarted..
remote: 
remote:   \m/ Nodester out \m/
remote: 
To git@nodester.com:/node/git/Meesayen/8117-24fb6575386af7e950e5d1e776efd976.git
   d99cca7..cc12982  master -> master

Any ideas?

**Comment by alejandro** [comment]
Wow! that's weird. Did you create a hello world app and then change it for your local app? That's a merge conflict error, I look to the repo and it's really strange, could you please recreate the app....

**Comment by alejandro** [comment]
Checkout https://gist.github.com/5452b0afbef19fea5395

**Comment by Meesayen** [comment]
No I've just created the app without the init part. I'm trying to delete the app, so I can create it again, but the admin panel doesn't list my app in there, so I don't know exactly what to do. Is there an API for the deletion?

**Comment by Meesayen** [comment]
What a mess! :S I don't understand how it happened.

**Comment by alejandro** [comment]
via nodester cli:

```
nodester app delete appname
```

**Comment by Meesayen** [comment]
Perfect, thanks, I'll create it again and see what happens.

**Comment by alejandro** [comment]
I'll let this open meanwhile, if it works just close it....

**Comment by Meesayen** [comment]
Again. I've created the app. Pushed it. Installed the required modules with npm. So long there was no problem with bad merges, but the app still didn't work, so I've modified the app.js, and when I pushed the new changes, git went in conflict, and now the app.js on the server is a mess again.

**Comment by alejandro** [comment]
hmmm! Weird... At the beginning what were the logs? When it didn't work...

**Comment by Meesayen** [comment]
meesayen@Janos:~/workshop/ditodes/ditodes-home$ nodester app logs ditodes
nodester info Showing logs for: ditodes
New PID: 24965
chroot_runner
chroot_runner
Running node v-0.6.12
App in audit mode by Watcher...

Starting Express server.

It hanged on the first lines of code, maybe the emailjs initialization was failing, so I've commented that out, git commit -am, git push nodester, and then the mess.

**Comment by Meesayen** [comment]
Well, I've created the app again. Now the problem is different. Everything seems ok with the app.js. Here is the log:

nodester info Showing logs for: ditodes
New PID: 3601
chroot_runner
chroot_runner
Running node v-0.6.12
App in audit mode by Watcher...

Acquiring required modules.

Starting Express server.

Configuring Express environment.

Configuring Mongoose.

Configuring routes.

Express server listening on http://localhost:16302 in production mode

But opening http://ditodes.nodester.com/ shows an "Internal Server Error" message, and nothing else. 
In local it all works fine, so I don't know exactly what to do next.

**Comment by alejandro** [comment]
`Express server listening on http://localhost:16302 in production mode` 

Don't use localhost, the port I think is ok, the `Internal Server Error` is a custom msg from express.The code that I pasted to the gist is the same? If its, I saw a `mongoose.connect` to a local database which is incorrect, you need to reference to a remote one like mongolab or mongohq.

**Comment by Meesayen** [comment]
No, of course, the localhost message is just a reminder I use in development mode. Ok for the mongodb advice, thanks.

**Comment by alejandro** [comment]
:) I thought that...

**Comment by Meesayen** [comment]
Anyway, I think I've solved the git push issue. Not sure if it was the real problem, but it seems to give conflict when I use git commit -am "message" and then push; now, instead, I use git add . && git commit -m "message", and everything goes fine.
Now the problem for the internal error is express.js related, so I'm gonna close this issue :) 
Thanks for your patience.

**Comment by alejandro** [comment]
That's new for me... I'll check that param. Thanks for the tip. And there is no problem, I'm glad to help you out. Hack the planet \m/
