### ISSUE TITLE
Express.js - Problem serving static files

### ISSUE THREAD

**Issue by Meesayen** [nodester/nodester#356]
Hi, I'm experiencing a problem with static files not being served. 

Here is the express configuration:

app.configure(function(){
    app.set('views', __dirname + '/views');
    app.set("view options", {layout: false});
    app.register('.html', {
        compile: function(str, options){
            return function(locals){
                return str;
            };
        }
    });
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(gzippo.staticGzip(__dirname + '/statics', {clientMaxAge: maxAge}));
    // app.use(express.static(__dirname + '/statics'));
});

app.get('/', function(req, res) {
    res.render('index.html');
});

Neither the gzippo middleware nor the default express one are working properly.
When the index.html is fetched, all the GET requests for the .js/.css/.png files remain pending for at least 3 minutes, then they fails.
But if I go straight to the link of a file, it loads almost immediately. 
Any ideas?

**Comment by alejandro** [comment]
Sorry, I didn't response when I saw this message, we are experimenting some issues with our aws instance. We are planing to restart the server. This is not a problem with node.js in general. Sorry for the problem...

**Comment by alejandro** [comment]
Restart again your app, we just restarted the server @Meesayen

**Comment by Meesayen** [comment]
Oh great, now it works like a charm. Thanks :)

**Comment by alejandro** [comment]
@Meesayen sorry for this! Hope everything is normal again. Closing this :)

**Comment by gotdibbs** [comment]
I had this problem but it ended up being an issue with web.config (I'm running node using iisnode). I removed the static handlers from my node app, and tweaked an existing boilerplate web.config to resolve the issue. This is the updated web.config: http://pastebin.com/hULgnCTg
