### ISSUE TITLE
When try to push to Git repository getting error as ssh_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by KITSVineetMore** [nodester/nodester#357]
Hi ,

When i am trying to push my local repo onto the GITHub site repo i am getting following error:

ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly.

I have crossed verified with the keys at both end but no help.

Please help me out as i am newbie to GITHUB.

Regards,
Vineet More

**Comment by chrismatthieu** [comment]
Please try it again. Our database provider had server issues a couple of hours ago.  If it still does not work for you, you may have an RSA key problem.  Check out our FAQ tab on our help page for more details - http://nodester.com/help.html?faq

**Comment by ghost** [comment]
Sorry, but why are you trying to push your code to GitHub, rather than the repo on Nodester?

**Comment by KITSVineetMore** [comment]
@mint sry  not getting you exactly...well i am trying to push a local repo onto the GIT HUB repo. where you trying to tell something else..please guide me if i was wrong..
