### ISSUE TITLE
Problem serving static files

### ISSUE THREAD

**Issue by Meesayen** [nodester/nodester#358]
I have the same problem again today. Opening http://ditodes.nodester.com results in a very long waiting for images and other static resources serving, and at the end all the requests are timed out.
I don't know what causes it. Here http://gvg.playground.nodester.com/ is the same app with a different name, and it loads lightning fast!

**Comment by alejandro** [comment]
@Meesayen we just rollbacked some changes that maybe was causing this errors. Can you recreate the app?

**Comment by alejandro** [comment]
BTW nice UI :)

**Comment by Meesayen** [comment]
Uhm...

$ nodester npm install ditodes express
nodester info installing to app: ditodes
nodester info installing these npm packages: express
nodester /bin/sh: line 0: cd: /node/app/Meesayen/8245-c039e54be38b9ec85cfcdfbe0accc52e_rw: No such file or directory
nodester npm WARN crypto@0.0.1 package.json: bugs['web'] should probably be bugs['url']
nodester npm http GET https://registry.npmjs.org/express
nodester npm http 304 https://registry.npmjs.org/express
nodester npm ERR! error installing express@2.5.8
nodester npm ERR! error rolling back express@2.5.8 Error: EACCES, permission denied '/node_modules/.bin/express'
nodester npm ERR! Error: EACCES, permission denied '/node_modules/.bin/express'
nodester npm ERR! 
nodester npm ERR! Please try running this command again as root/Administrator.
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.53.amzn1.x86_64
nodester npm ERR! command "/node/base/node-v0.4.9/usr/local/n/versions/0.6.12/bin/node" "/node/base/node-v0.4.9/usr/local/n/versions/0.6.12/bin/npm" "install" "express"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.6.12
nodester npm ERR! npm -v 1.1.4
nodester npm ERR! path /node_modules/.bin/express
nodester npm ERR! code EACCES
nodester npm ERR! message EACCES, permission denied '/node_modules/.bin/express'
nodester npm ERR! errno {}
nodester npm ERR! Error: EACCES, permission denied 'npm-debug.log'
nodester npm ERR! 
nodester npm ERR! Please try running this command again as root/Administrator.
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.53.amzn1.x86_64
nodester npm ERR! command "/node/base/node-v0.4.9/usr/local/n/versions/0.6.12/bin/node" "/node/base/node-v0.4.9/usr/local/n/versions/0.6.12/bin/npm" "install" "express"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.6.12
nodester npm ERR! npm -v 1.1.4
nodester npm ERR! path npm-debug.log
nodester npm ERR! code EACCES
nodester npm ERR! message EACCES, permission denied 'npm-debug.log'
nodester npm ERR! errno {}
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /npm-debug.log
nodester npm not ok

nodester warn you should restart your app after you are finished installing packages.

**Comment by alejandro** [comment]
Did you delete the app and then create a new one?

**Comment by Meesayen** [comment]
Yep

**Comment by alejandro** [comment]
the problem is here.

```
nodester /bin/sh: line 0: cd: /node/app/Meesayen/8245-c039e54be38b9ec85cfcdfbe0accc52e_rw: No such file or directory
```

Did you push your code?

**Comment by Meesayen** [comment]
Yes and it was fine:

 git push nodester master
Nodester!
Counting objects: 691, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (627/627), done.
Writing objects: 100% (691/691), 4.47 MiB | 48 KiB/s, done.
Total 691 (delta 53), reused 0 (delta 0)
remote: 
remote: 
remote: 
remote:                           _          _
remote:           _ __   ___   **| | ___ ___| |_ ___ _ __
remote:          | '_ \ / _ \ / _  |/ _ \ __| __/ _ \ '**|
remote:          | | | | (_) | (_| |  **\** \ |_  **/ |
remote:          |_| |_|_**/ __,_|_**|_**/_____|_|  
remote: 
remote:           Open Source Node.js Hosting Platform
remote:               http://github.com/nodester
remote: 
remote: 
remote: Syncing repo with chroot
remote: From /node/git/Meesayen/8245-c039e54be38b9ec85cfcdfbe0accc52e
remote:  \* [new branch]      master     -> origin/master
remote: Attempting to restart your app: 8245-c039e54be38b9ec85cfcdfbe0accc52e
remote: {"status":"failed to restart"}
remote: App restarted..
remote: 
remote:   \m/ Nodester out \m/
remote: 
To git@nodester.com:/node/git/Meesayen/8245-c039e54be38b9ec85cfcdfbe0accc52e.git
- [new branch]      master -> master

I'm gonna try it again.

**Comment by Meesayen** [comment]
Ok, done. Now it loads perfectly. Thanks. I've still a little problem, with the "emailjs" module. It gives error at require time, but I'll open a dedicated issue tomorrow maybe, after a few troubleshooting. :) 
I close this one.
