### ISSUE TITLE
application hanging/timing out

### ISSUE THREAD

**Issue by mundizzle** [nodester/nodester#359]
my app has been working fine for a month. i have not made any code changes.

in the last two weeks, it has consistently been hanging or timing out resulting in a "No data received" error. many times i get the nodester rocket 503 messsage.

restarting via nodester-cli also takes a few minutes. the result is the same.

logs say this: ERROR Fatal Error! API Response: {"status":"failure","message":"No logs available."}

the app is at talkshoppe.nodester.com

any insight appreciated. thanks.

**Comment by alejandro** [comment]
Hi @mundizzle, the last two weeks we had several problems with our server and db provider, everything is normal again. Also we had to roll back some changes in our code that were introducing a huge memory leak in our apps. I fix the environment of your app, And I think everything is as you spec! 

**Edit:**  Sorry for the problems. Hack the planet \m/

**Comment by mundizzle** [comment]
it is. thanks!
