### ISSUE TITLE
I can't run my Hello World app

### ISSUE THREAD

**Issue by urielhdz** [nodester/nodester#361]
I'm new with this, but I created an app and I would like to show it to people by using nodester.

So I create my app just like in the video on the index of nodester.com I try to go to my app and nothing happens it says "App offline" so I try to run with "nodester app start rndlabchat" and It sends me this error:

nodester warn false

I have not edited the server.js so, What could be my problem?

Thanks a lot for the help

**Comment by alejandro** [comment]
Hi! First of all I want to know what OS are you running, because we have found some errors with users running windows. If this is not your problem could you please join us at freenode#nodester or irc.nodester.com for give you further explanation :)

**Comment by urielhdz** [comment]
Yes, I'm in Windows, but also I have Ubuntu on my computer, do you suggest to use Ubuntu?

**Comment by alejandro** [comment]
It'll be better. But if you keep on windows take a look to our first 2 post on the [blog](http://blog.nodester.com) that'll help you understand how to work from windows to nodester...

**Comment by urielhdz** [comment]
Wel, I would like if you can hel me with this, but I would undestand if not because this is not about the topic but I don't know what I have to type when this message appear Enter passphrase for key... as you say I'm not an advanced user in git

**Comment by alejandro** [comment]
@dxvtuts12345 do you mind join us on irc freenode#nodester or irc.nodester.com? We can help you better... Your problem is a RSA problem check out http://help.github.com/win-set-up-git/ you need to upload your RSA key to our servers (the same that you use in github). Also read this http://articles.nodester.com/posts/2012/mar/01. But I'd like to have you on irc :)

**Comment by chrismatthieu** [comment]
no response...
