### ISSUE TITLE
port should be in env

### ISSUE THREAD

**Issue by hsch** [nodester/nodester#363]
Rather than hard-coding your app's port it should be available from the environment. I know that I can probably configure nodester that way, but it would be nice to see this as a default.

Could make developing locally or generally in different environments a lot easier!

**Comment by hsch** [comment]
Or, make "app_port" more obvious in the default script :)

**Comment by alejandro** [comment]
Hi @hsch you don't need to hardcode your port, you can add `process.env['app_port']` instead of a port. 

From [nodester.com/help](http://nodester.com/help.html)

> Your application's port must match the port that we assign your application. This port is provided at the time of app creation but your can retrieve your application's port, starting javascript file, and nodester git repository address at any time by running "nodester app info <appname>" from the CLI. You can also simply use process.env['app_port'] as an environmental variable and Nodester will automatically use the port assigned or you could do something like this to make it easy to switch between localhost and production: appPort = process.env['app_port'] || 3000

Cheers

**Comment by hsch** [comment]
yup, my fault.

**Comment by alejandro** [comment]
I proposed the changes :: [0614be](https://github.com/alejandromg/nodester-cli/commit/0614be0ffea7c42bcf36608f4fe7f39bdc7dce93) 

**Closing this**

**Comment by hsch** [comment]
wow, awesome :)
