### ISSUE TITLE
all http.request to outside receive 404 connection:close at nodester

### ISSUE THREAD

**Issue by kaven276** [nodester/nodester#369]
It seems that app in nodester can not make request to other website

my app breakjail run on my notebook well, but when run on nodester.com, it can not make http request to outside, all response return 404 connection:close.

Why???

**Comment by chrismatthieu** [comment]
Nodester can make external requests.  Is there anything in your logs? 

nodester app logs {appname}

**Comment by alejandro** [comment]
no response
