### ISSUE TITLE
How to delete some file of remote branch

### ISSUE THREAD

**Issue by KITSVineetMore** [nodester/nodester#370]
Hello,

I want to delete some files from the remote branch being pushed in the github.com. I tried to delete the branch but still the old commits are coming in the new branch created in the remote repo.

WIll be glad if someone can help me out as it is very urgent.

THanks in Advance.

**Comment by nodester** [comment]
Nodester is not connected to GitHub but you can reset your Nodester repo by running nodester app gitreset.

Regards,
Chris
