### ISSUE TITLE
Cannot find app_start.sh & proxy_start.sh

### ISSUE THREAD

**Issue by pietrorobbi** [nodester/nodester#374]
After complete nodester install i can't find the file app_start.sh and proxy_start.sh in /nodester/nodester/bin/

**Comment by alejandro** [comment]
Sorry, that's outdated, we are using upstart scripts now, what you need to do is copy the two files inside `upstart` dir to the path where upstart reads processes wich in most of the cases is `/etc/init`

``` bash
> cd nodester
> sudo cp upstart/* /etc/init
# then you can start the proxy and the app with:
> sudo start proxy
> [sudo] start app
```

And there you go.

Cheers

**Comment by pietrorobbi** [comment]
Ok, thank you. 
Now is ready to go!
