### ISSUE TITLE
Error trying to install npm packages

### ISSUE THREAD

**Issue by alvarosaco** [nodester/nodester#380]
When I try to install npm packages, I get the following error:

```
nodester npm install poesiacolaborativa express socket.io jade
nodester info installing to app: poesiacolaborativa
nodester info installing these npm packages: express,socket.io,jade
nodester /bin/sh: line 0: cd: /node/app/alvarosaco/9965-d9b5a5aaddf52c4b3a56dfad4d1698ad_rw: No such file or directory
nodester npm WARN crypto@0.0.1 package.json: bugs['web'] should probably be bugs['url']
nodester npm ERR! Could not create /node_modules/___socket.io.npm
nodester npm ERR! error installing socket.io@0.9.6 Error: EACCES, Permission denied '/node_modules/___socket.io.npm'
nodester npm ERR! Error: EACCES, Permission denied '/node_modules/___socket.io.npm'
nodester npm ERR! Report this *entire* log at:
nodester npm ERR!     <http://github.com/isaacs/npm/issues>
nodester npm ERR! or email it to:
nodester npm ERR!     <npm-@googlegroups.com>
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.53.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "express" "socket.io" "jade"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path /node_modules/___socket.io.npm
nodester npm ERR! code EACCES
nodester npm ERR! Error: EACCES, Permission denied 'npm-debug.log'
nodester npm ERR! Report this *entire* log at:
nodester npm ERR!     <http://github.com/isaacs/npm/issues>
nodester npm ERR! or email it to:
nodester npm ERR!     <npm-@googlegroups.com>
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.53.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "express" "socket.io" "jade"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path npm-debug.log
nodester npm ERR! code EACCES
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /npm-debug.log
nodester npm not ok
```

**Comment by alejandro** [comment]
HI! Looks like the process is trying to install your packages on a different directory.  Becuase your app dir is not created yet. Try to make a push then try again please.

**Comment by alvarosaco** [comment]
I did it, but the app failed to restart:

```
$git push nodester master
Nodester!
Identity added: /Users/alvarosaco/.ssh/id_rsa (/Users/alvarosaco/.ssh/id_rsa)
Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 763 bytes, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: 
remote: 
remote: 
remote:                           _          _
remote:           _ __   ___   __| | ___ ___| |_ ___ _ __
remote:          | '_ \ / _ \ / _  |/ _ \ __| __/ _ \ '__|
remote:          | | | | (_) | (_| |  __\__ \ |_  __/ |
remote:          |_| |_|\___/ \__,_|\___|___/\__\___|_|   
remote: 
remote:           Open Source Node.js Hosting Platform
remote:               http://github.com/nodester
remote: 
remote: 
remote: Syncing repo with chroot
remote: From /node/git/alvarosaco/9965-d9b5a5aaddf52c4b3a56dfad4d1698ad
remote:    5f291ec..ab49b7f  master     -> origin/master
remote: Updating 5f291ec..ab49b7f
remote: Fast-forward
remote:  README.md |   60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
remote:  1 files changed, 60 insertions(+), 0 deletions(-)
remote: Attempting to restart your app: 9965-d9b5a5aaddf52c4b3a56dfad4d1698ad
remote: {"status":"failed to restart"}
remote: App restarted..
remote: 
remote:   \m/ Nodester out \m/
remote: 
To git@nodester.com:/node/git/alvarosaco/9965-d9b5a5aaddf52c4b3a56dfad4d1698ad.git
   5f291ec..ab49b7f  master -> master
```

**Comment by alejandro** [comment]
Because you still haven't installed the packages ;-) Try now to reinstall the packages.

**Comment by alvarosaco** [comment]
I get again the same error:

$ nodester npm install poesiacolaborativa socket.io express jade
nodester info installing to app: poesiacolaborativa
nodester info installing these npm packages: socket.io,express,jade
nodester /bin/sh: line 0: cd: /node/app/alvarosaco/9965-d9b5a5aaddf52c4b3a56dfad4d1698ad_rw: No such file or directory
nodester npm WARN crypto@0.0.1 package.json: bugs['web'] should probably be bugs['url']
nodester npm ERR! Could not create /node_modules/___socket.io.npm
nodester npm ERR! error installing socket.io@0.9.6 Error: EACCES, Permission denied '/node_modules/___socket.io.npm'
nodester npm ERR! Error: EACCES, Permission denied '/node_modules/___socket.io.npm'
nodester npm ERR! Report this _entire_ log at:
nodester npm ERR!     http://github.com/isaacs/npm/issues
nodester npm ERR! or email it to:
nodester npm ERR!     npm-@googlegroups.com
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.53.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "socket.io" "express" "jade"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path /node_modules/___socket.io.npm
nodester npm ERR! code EACCES
nodester npm ERR! Error: EACCES, Permission denied 'npm-debug.log'
nodester npm ERR! Report this _entire_ log at:
nodester npm ERR!     http://github.com/isaacs/npm/issues
nodester npm ERR! or email it to:
nodester npm ERR!     npm-@googlegroups.com
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.53.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "socket.io" "express" "jade"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path npm-debug.log
nodester npm ERR! code EACCES
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /npm-debug.log
nodester npm not ok

nodester warn you should restart your app after you are finished installing packages.

**Comment by alejandro** [comment]
Two things to mention first your node version is on 0.4.9 maybe that's the problem. TO fixt this add in your package.json the nex key/value:

```
"node":"0.6.17"
```

Do a push and then run the command again.

**Comment by alvarosaco** [comment]
Now, the push command was run sucessfully but not installing npm packages

 $git push nodester master
Nodester!
Everything up-to-date

$ nodester npm install poesiacolaborativa socket.io express jade
nodester info installing to app: poesiacolaborativa
nodester info installing these npm packages: socket.io,express,jade
nodester /bin/sh: line 0: cd: /node/app/alvarosaco/9965-d9b5a5aaddf52c4b3a56dfad4d1698ad_rw: No such file or directory
nodester npm WARN crypto@0.0.1 package.json: bugs['web'] should probably be bugs['url']
nodester npm ERR! Could not create /node_modules/___socket.io.npm
nodester npm ERR! error installing socket.io@0.9.6 Error: EACCES, Permission denied '/node_modules/___socket.io.npm'
nodester npm ERR! Error: EACCES, Permission denied '/node_modules/___socket.io.npm'
nodester npm ERR! Report this _entire_ log at:
nodester npm ERR!     http://github.com/isaacs/npm/issues
nodester npm ERR! or email it to:
nodester npm ERR!     npm-@googlegroups.com
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.53.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "socket.io" "express" "jade"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path /node_modules/___socket.io.npm
nodester npm ERR! code EACCES
nodester npm ERR! Error: EACCES, Permission denied 'npm-debug.log'
nodester npm ERR! Report this _entire_ log at:
nodester npm ERR!     http://github.com/isaacs/npm/issues
nodester npm ERR! or email it to:
nodester npm ERR!     npm-@googlegroups.com
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.53.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "socket.io" "express" "jade"
nodester npm ERR! cwd /
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! path npm-debug.log
nodester npm ERR! code EACCES
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /npm-debug.log
nodester npm not ok

nodester warn you should restart your app after you are finished installing packages.

**Comment by alejandro** [comment]
> $git push nodester master
> Nodester!
> Everything up-to-date

You are not commiting the changes. And still the version is the same  (0.4.9) so it's no picking the changes. Also checkout the logs with `nodester app logs APPNAME`

**Comment by alvarosaco** [comment]
Sorry for my ignorance.
How can I commit the changes? 

 nodester app logs poesiacolaborativa
 nodester ERROR Fatal Error! API Response: {"status":"failure","message":"No logs available."}
 Reason: No logs available.

**Comment by alejandro** [comment]
well:

```
> git add .
> git commit -am '[MY SUPER MESSAGE'
> git push nodester master
```

And there you go. If this fail. Try to delete and create a new app :)

**Comment by alvarosaco** [comment]
Now yes!

The app is running but nothing appears in http://poesiacolaborativa.nodester.com
The server is http://poesiacolaborativa.nodester.com/ and the port 18118

**Comment by alvarosaco** [comment]
The log shows: 

You are running in node-0.4.9. You might want to upgrade to node-v0.6.17

Is about this? How it is possible to upgrade?

**Comment by alejandro** [comment]
Well as I said before to upgrade your app you need to add to your
package.json this:

"node":"0.6.17"

With this you'll upgrade your app. Also to be sure that your package.json
is ok lint it in http://jsonlint.com

2012/5/29 Álvaro <
reply@reply.github.com

> The log shows:
> 
> You are running in node-0.4.9. You might want to upgrade to node-v0.6.17
> 
> Is about this? How it is possible to upgrade?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nodester/nodester/issues/380#issuecomment-5991271

## 

Atentamente
_Víctor Alejandro Morales Gámez_
_CTO at numbus_
_"The best way to get cheer yourself is to try to cheer someone else up."- Mark
Twain_

**Comment by alvarosaco** [comment]
Great!
The package.json file was wrong. Now my app is running!
Thanks so much!

**Comment by alejandro** [comment]
Cool! Closing this :)

Hack the planet \m/
