### ISSUE TITLE
 failed-to-start

### ISSUE THREAD

**Issue by fquintelagit** [nodester/nodester#384]
```
C:\Users\fjq\levantaodedo>nodester app info levantaodedo
nodester info Gathering information about: levantaodedo
nodester info levantaodedo on port 18296 running: failed-to-start
nodester info gitrepo: git@nodester.com:/node/git/fquintela/10143-8cbb79edec12dd
34cda3a92e6fffaa3c.git
nodester info appfile: server.js
```

**Comment by alejandro** [comment]
well we need a little bit more than this ;)

What are the logs saying? `nodester app logs APPNAME`

**Comment by fquintelagit** [comment]
C:\Users\fjq\levantaodedo>nodester app logs levantaodedo
nodester ERROR Fatal Error! API Response: {"status":"failure","message":"No logs
 available."}
Reason: No logs available.

**Comment by alejandro** [comment]
ok! When did you try to create your app? In the last 30 minutes? If that answer is yes. Please delete this app and try to do it again. I just fixed an issue with the platform.

**Comment by fquintelagit** [comment]
after delete, create, init and start app
C:\Users\fjq\levantaodedo>nodester app info levantaodedo
nodester info Gathering information about: levantaodedo
nodester info levantaodedo on port 18358 running: failed-to-start
nodester info gitrepo: git@nodester.com:/node/git/fquintela/10205-64ac318f4c5cf6
a55e4a008bf5861327.git
nodester info appfile: server.js

**Comment by alejandro** [comment]
Oh well did you try to push something? Or are you just creating apps? Because looks like you havent' pushed anything  (i just check)

**Comment by fquintelagit** [comment]
seems like i am having an issue pussing to github

**Comment by alejandro** [comment]
@levantaodedo what about to **nodester**?

**Comment by alejandro** [comment]
Fixed: http://levantaodedo.nodester.com/

Closed!
