### ISSUE TITLE
[Critical] Apps are only deleted from db

### ISSUE THREAD

**Issue by alejandro** [nodester/nodester#388]
Recently I was cleaning my apps on nodester (a lot of nonsense stuff) so I run 

`>  nodester app destroy {appname}`

For each of my apps, but turns out that they are not owned by me anymore, they are destroyed. BUT the thing is that the apps are still alive without users control. E.g. http://ideasbox.nodester.com as well as http://test0100.nodester.com they should response with a 404 error because they are not anymore in the platform. But they are. Crazy stuff.

Looking for the origin of this.

**Comment by andbas** [comment]
I think that was a cache issue, because right now both apps returns 404 as they should.

**Comment by alejandro** [comment]
Yes you are right! Closing this
