### ISSUE TITLE
user setup stuck because of blank password

### ISSUE THREAD

**Issue by bgulian** [nodester/nodester#389]
Ok, here's the series of unfortunate events:
1. Registered but because of my failure to copy a valid RSA key the first time, I submitted the second time with a blank password.
2. Got my json success method.
3. Was able to do a successful user setup with "nodester user setup <myloginname> ""
    Result: 
    nodester info verifying credentials
    nodester info user verified..
    nodester info writing user data to config
4. Realized this was bad and tried to do a "nodester user setpass sendtoken" to change my password:
   Result: Please run nodester user setup <username> <password>

Now every nodester command has the same result as step 4.

**Comment by bgulian** [comment]
Sorry, step 3 should be:
1. Was able to do a succesful user setup with: nodester user setup myusername ""

**Comment by chrismatthieu** [comment]
You can reuse your coupon to setup a new account.  It may be easier that fixing this issue for you.

-Chris

**Comment by bgulian** [comment]
Ok, done.  Thanks

On Fri, Jun 29, 2012 at 2:22 PM, Chris Matthieu <
reply@reply.github.com

> wrote:
> 
> You can reuse your coupon to setup a new account.  It may be easier that
> fixing this issue for you.
> 
> -Chris
> 
> On Jun 29, 2012, at 11:18 AM, Bob Gulian wrote:
> 
> > Ok, here's the series of unfortunate events:
> > 1. Registered but because of my failure to copy a valid RSA key the
> >    first time, I submitted the second time with a blank password.
> > 2. Got my json success method.
> > 3. Was able to do a successful user setup with "nodester user setup
> >    <myloginname> ""
> >    Result:
> >    nodester info verifying credentials
> >    nodester info user verified..
> >    nodester info writing user data to config
> > 4. Realized this was bad and tried to do a "nodester user setpass
> >    sendtoken" to change my password:
> >    Result: Please run nodester user setup <username> <password>
> > 
> > Now every nodester command has the same result as step 4.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/nodester/nodester/issues/389
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nodester/nodester/issues/389#issuecomment-6671273

## 

Bob Gulian
bgulian@gmail.com
