### ISSUE TITLE
last commit broke use of socket.io 

### ISSUE THREAD

**Issue by graemeworthy** [nodester/nodester#39]
https://github.com/nodester/nodester/commit/4eb4d6b63280d7e4f0071eb97707a0fb1a3a778c

By escaping strings here. I can no longer load the npm package for socket.io.

allow me to elaborate:

nodester appnpm install "socket.io"
stdout: 
stderr: npm info it worked if it ends with ok
npm info using npm@0.2.16
npm info using node@v0.2.6
npm ERR! Error: 404 Not Found: socketio
npm ERR!     at IncomingMessage.<anonymous> (/home/ec2-user/.node_libraries/.npm/npm/0.2.16/package/lib/utils/registry/request.js:150:16)
npm ERR!     at IncomingMessage.emit (events:48:20)
npm ERR!     at HTTPParser.onMessageComplete (http:107:23)
npm ERR!     at Client.onData [as ondata](http:854:27)
npm ERR!     at IOWatcher.callback (net:494:29)
npm ERR!     at node.js:773:9
npm ERR! 404 
npm ERR! 404 Looks like 'socketio' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it.
npm ERR! 404 Note that you can also install from a tarball or local folder.
npm ERR! 404
npm not ok

**Comment by DanBUK** [comment]
I'll fix this in the next couple of hours.

**Comment by graemeworthy** [comment]
i just went through the node list, and there are some underscores and some hyphens there, as well as the aforementioned period. 
Also, versions are specified with @ symbols
and sometimes with ranges sax@">=0.1.0 <0.2.0"

**Comment by DanBUK** [comment]
I've updated the code; and deployed. Commit 9d5635a44caeff5dc118 fixes this.

**Comment by graemeworthy** [comment]
sorry to be a nag, but we still need periods.
`
"socket.io".replace(/[^a-zA-Z0-9 \-_=<>@]+/g,''); // => "socketio"
`

`
"socket.io".replace(/[^a-zA-Z0-9 \.\-_=<>@]+/g,''); // => "socket.io"
`

**Comment by DanBUK** [comment]
Doh! Sorry! /me goes to fix.

**Comment by DanBUK** [comment]
Deployed with . in there sorry about that!

**Comment by graemeworthy** [comment]
Success! Thank you dan.
