### ISSUE TITLE
nodester setup stays at writing user data to config

### ISSUE THREAD

**Issue by orlando** [nodester/nodester#391]
when i do `nodester user setup username password` stays at  `writing user data to config`.. how much time that step its suppose to take?

thanks for your time.

``` bash
nodester info verifying credentials
nodester info user verified..
nodester info writing user data to config
```

node --version = 0.6.6
npm --version = 1.1.0-beta-4
ubuntu 11.10
**nodester-cli installed without sudo**

**Comment by alejandro** [comment]
You should run this command with root permissions since it writes to the fs.
It should take less than 3 seconds and output an error message, though.

**Comment by orlando** [comment]
mmm weird, same result installing and running with sudo

**Comment by alejandro** [comment]
What's your `nodester-cli` version? If it's 1.0.x try to downgrade to 0.2.50 (`npm install -g nodester-cli@0.2.50`) The 1.0.x series is specially written for node-v>=0.7.x. If not try to upgrade ¬¬.

**Comment by orlando** [comment]
updating to node v0.8.1 fixed the problem, also doesn't require to run (or install) nodester using sudo.. thanks :)
