### ISSUE TITLE
Getting error npm doesn't work with node 0.8.1

### ISSUE THREAD

**Issue by juzerali** [nodester/nodester#392]
I am trying to install dependencies but receiving this error `npm doesn't work with node v0.8.1`. My `package.json` has correct node version `0.6.18`. Check error log and package.json

```
$ nodester npm install crowdfund
nodester info grabbing dependencies from package.json...
nodester info installing to app: crowdfund
nodester info installing these npm packages: derby,express,gzippo,racer-db-mongo
nodester Error: npm doesn't work with node v0.8.1
nodester Required: node@0.4 || 0.5 || 0.6
nodester     at /usr/lib/node_modules/npm/bin/npm-cli.js:57:23
nodester     at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:77:3)
nodester     at Module._compile (module.js:449:26)
nodester     at Object.Module._extensions..js (module.js:467:10)
nodester     at Module.load (module.js:356:32)
nodester     at Function.Module._load (module.js:312:12)
nodester     at Module.runMain (module.js:487:10)
nodester     at process.startup.processNextTick.process._tickCallback (node.js:244:9)

nodester warn you should restart your app after you are finished installing packages.
```

`package.json`

```
{
  "name": "derby-ice-cream-parlor",
  "description": "Demo of Derby features",
  "version": "1.0.0-20",
  "node": "0.6.18",
  "main": "./server.js",
  "dependencies": {
    "derby": "*",
    "express": "3.0.0beta2",
    "gzippo": ">=0.1.4",
    "racer-db-mongo": "*",
    "connect-mongo": ">=0.1.9",
    "racer": "*"
  },
  "private": true,
  "devDependencies": {
    "coffee-script": ">=1.3.1"
  },
  "subdomain": "icecream-parlor",
  "scripts": {
    "start": "server.js"
  },
  "engines": {
    "node": "0.6.17"
  }
}
```

**Comment by alejandro** [comment]
That's the problem... We don't have `0.6.18` in our server. 

Available versions: `0.6.17`,`0.8.1`.

**Comment by esunder** [comment]
I created a new project following the guide on the 'Help' page. By default, the nodester hello world project requires express. I had to install this manually using 'nodester npm install express'. This fails when using node v0.8.1 with the following relevant log information:

nodester info installing these npm packages: express
nodester Error: npm doesn't work with node v0.8.1
nodester Required: node@0.4 || 0.5 || 0.6
nodester at /usr/lib/node_modules/npm/bin/npm-cli.js:57:23
nodester at Object. (/usr/lib/node_modules/npm/bin/npm-cli.js:77:3)
nodester at Module._compile (module.js:449:26)
nodester at Object.Module._extensions..js (module.js:467:10)
nodester at Module.load (module.js:356:32)
nodester at Function.Module._load (module.js:312:12)
nodester at Module.runMain (module.js:487:10)
nodester at process.startup.processNextTick.process._tickCallback (node.js:244:9)

**Comment by KenjiTakahashi** [comment]
+1. I'm having same problem since yesterday's restarts (it worked OK before).
I have "node": "0.8.1" set in my package.json.

**Comment by alejandro** [comment]
Sorry for that. But for some reason there is an error reading those packages with "node":"0.8.1". 
it's failing with packages with big package.json. I used this template and it's working though:

```
{
  "name": "nowjs-helloworld-example",
  "version": "0.0.6",
  "author": "ericz (Eric Zhang) <eric@nowjs.com>",
  "description": "'Hello world' example for NowJS.",
  "node":"0.8.1",
  "keywords": [
    "nowjs",
    "example"
  ],
  "dependencies" : {
    "now"     :  ">=0.7",
    "express": "3.0.0beta5",
    "nhouston":"https://github.com/alejandromg/Houston/tarball/master"
  },
  "engine": {
    "node": ">=0.4"
  }
} 

```

Maybe you can adapt to your package and see if it's working.

**EDIT** Sorry about yesterday.

**Comment by KenjiTakahashi** [comment]
Still nothing :(.
Here's my whole package.json, just in case:

``` json
{
    "name": "kenji",
    "version": "0.0.4",
    "private": true,
    "node": "0.8.1",
    "dependencies": {
        "flatiron": "0.2.x",
        "union": "0.3.x",
        "director": "1.1.x",
        "mongoose": "2.7.x",
        "jade": "0.26.x",
        "stylus": "0.28.x",
        "connect": "2.3.5",
        "date-ext": "1.0.x",
        "coffee-script": "1.3.x"
    },
    "engine": {
        "node": ">=0.4"
    }
}
```

**Comment by alejandro** [comment]
Can you try again, please?

**Comment by KenjiTakahashi** [comment]
Thanks, it worked now!
