### ISSUE TITLE
API returns wrong status of apps running on nodester.

### ISSUE THREAD

**Issue by jaydeepw** [nodester/nodester#394]
Hi all,

   I have been working on nodesterapp watcher plugin for Chrome.
What I have found is

{
    "name": "myapis",
    "port": 16510,
    "gitrepo": "<repo-url>",
    "running": "true",
    "pid": 12412
  },
   {
    "name": "nodedb",
    "port": 16945,
    "gitrepo": "<repo-url>",
    "running": "true",
    "pid": 20784
  },

When I call the /apps/ API, an array of objects is returned.
This shows the status of all of my apps as 'running': 'true'

Even though some of them are currently down.
I want to work on it, will anybody please direct me, how to setup and get 
nodester running locally.

**Comment by alejandro** [comment]
Yeah! The main problem with this is that our api response depends on the database. So if the app crashed and it wasn't updated it'll return as a `"running":true` when it's not running.

A workaround is to ping the app e.g [roskoff/nodesterappswatcher#cbcd4e5](https://github.com/roskoff/nodesterappswatcher/commit/cbcd4e5e1bf9e9d80dceb49b85e925af88ad1508)

If you want to setup a nodester instance there is the [nodester installer](http://github.com/nodester/nodester-installer) which is really helpful.

**Comment by jaydeepw** [comment]
Yes, we are using the same workaround in the nodester app watcher extension for Chrome.

Thanks for the link,
I will take a look at nodester-installer.
