### ISSUE TITLE
How to install specific package version?

### ISSUE THREAD

**Issue by KenjiTakahashi** [nodester/nodester#396]
I need to have connect <= 2.3.5, due to a compatibility problem in [union](https://github.com/flatiron/union), but `nodester npm install` seems to ignore versions stored in `package.json` file and I found no way to install it manually. Is there any way to do this?

**Comment by alejandro** [comment]
Try to update your nodester-cli with:

```
npm install https://github.com/nodester/nodester-cli/master/tarball
```

We've fixed this already ;)

**Comment by KenjiTakahashi** [comment]
Dah, It is indeed working using cli from master branch. Thanks for pointing me at this, closing.
