### ISSUE TITLE
My app couldn't start due to FATAL ERROR: v8::HandleScope::Close()

### ISSUE THREAD

**Issue by cheeaun** [nodester/nodester#400]
This is my current app: http://node-hnapi.nodester.com/

It was working for last few weeks, when I found that it suddenly breaks yesterday. I'm not very sure what's the cause, tried googling around and found this: https://github.com/mranney/node_redis/issues/150 which I think could be related?

```
>nodester app logs
nodester info Showing logs for: node-hnapi
New PID: 8813
chroot_runner
chroot_runner
Spawing /app/server.js
Running node v-0.8.1
FATAL ERROR: v8::HandleScope::Close() Local scope has already been closed

Process died with exit code 1. Restarting...
Spawing /app/server.js
Running node v-0.8.1
FATAL ERROR: v8::HandleScope::Close() Local scope has already been closed

Process died with exit code 1. Restarting...
Spawing /app/server.js
Running node v-0.8.1
FATAL ERROR: v8::HandleScope::Close() Local scope has already been closed

Process died with exit code 1. Restarting...
Spawing /app/server.js
Running node v-0.8.1
FATAL ERROR: v8::HandleScope::Close() Local scope has already been closed

Process died with exit code 1. Restarting...
Spawing /app/server.js
Running node v-0.8.1
FATAL ERROR: v8::HandleScope::Close() Local scope has already been closed

Process died with exit code 1. Restarting...
Spawing /app/server.js
Running node v-0.8.1
FATAL ERROR: v8::HandleScope::Close() Local scope has already been closed

Error: Restarted too many times, bailing.
nodester info ok!
```

**Comment by alejandro** [comment]
Sorry! I didn't get a notification for this. The main problem here is the redis module. An user ran into this issue a while back. Try to reinstall redis, and also hiredis as a standalone module (not as a dependency)

**Comment by cheeaun** [comment]
I've tried reinstalling redis and installing hiredis as a standalone module but still getting the same error. Here are the packages my app is using:

```
>nodester npm list
nodester info list npm packages for app: node-hnapi
nodester ├── hiredis@0.1.14
nodester ├── journey@0.4.0-pre-3
nodester ├─┬ jsdom@0.2.15
nodester │ ├─┬ contextify@0.1.3
nodester │ │ └── bindings@1.0.0
nodester │ ├── cssom@0.2.5
nodester │ └── htmlparser@1.7.6
nodester ├─┬ nconf@0.6.4
nodester │ ├── async@0.1.22
nodester │ ├── ini@1.0.2
nodester │ ├─┬ optimist@0.3.4
nodester │ │ └── wordwrap@0.0.2
nodester │ └── pkginfo@0.2.3
nodester ├─┬ nodetime@0.4.3
nodester │ ├── agent.io@0.1.5
nodester │ ├─┬ timekit@0.1.9
nodester │ │ └── bindings@1.0.0
nodester │ └─┬ v8tools@0.1.1
nodester │   └── bindings@1.0.0
nodester ├── redis@0.7.2
nodester └── request@2.9.203
```

**Comment by alejandro** [comment]
Hmm weird. What about downgrading to 0.6.x?

**Comment by cheeaun** [comment]
Tried downgrading to 0.6.17, reinstalling redis and hiredis, the problem is still there :(

```
>nodester app logs
nodester info Showing logs for: node-hnapi
New PID: 12914
chroot_runner
chroot_runner
Spawing /app/server.js
Running node v-0.6.17
FATAL ERROR: v8::HandleScope::Close() Local scope has already been closed
```

**Comment by alejandro** [comment]
hmm... Try to uninstall _all_ the modules and then try to reinstall. Also try to commit something to your nodester repo. If not. Try to deploy the app from scratch. This is really weird.

**Comment by cheeaun** [comment]
I've tried the following:
- Uninstall all modules, reinstall them. Doesn't work.
- Delete the whole app, recreate it from scratch again. Doesn't work.

I've then try create another app with very minimal code (hello world app) and little module dependencies to confirm if the problem is _really_ in the redis module. Still doesn't work. Then, I try to make the redis module **NOT** to use the hiredis parser by passing `parser: javascript` into the options. **It works.** No more FATAL ERROR messages.

I'm not very sure what's the actual problem but at least I can confirm it's related to the hiredis module.
