### ISSUE TITLE
Possibly unnecessary username check

### ISSUE THREAD

**Issue by Tenzer** [nodester/nodester#401]
While looking through the code, I came to wonder why there is a check for the validity of a username at this location:
https://github.com/nodester/nodester/blob/master/lib/user.js#L72-77

It would make better sense to put further up in the code base, by which all methods may take benefit from it. I have however not made a pull request to change this, in case I have misunderstood the code.

**Comment by alejandro** [comment]
Hmm I think you are right! @chrismatthieu what do you think about it?

**Comment by nodester** [comment]
Yep, I say we go for it.

**Comment by Tenzer** [comment]
I have made a pull request to remove the check at #402.
