### ISSUE TITLE
Use PORT instead of app_port

### ISSUE THREAD

**Issue by mildsunrise** [nodester/nodester#408]
It's better to use the `PORT` environment variable than `app_port`.
Simpler, standard and upper-case.
In fact, the following PaaS already use `PORT`:
- Nodejitsu
- Cloud9
- Heroku

I know it's already supported, now it's better
to recommend the use of `PORT` and deprecate `app_port`
in the help pages.

**Comment by alejandro** [comment]
Yeah! I've thought about this for a long time. But not sure right now
because of the nodester status. @chrismatthieu what do you think?

2012/11/20 Xavier Mendez notifications@github.com

> It's better to use the PORT environment variable than app_port.
> Simpler, standard and upper-case.
> In fact, the following PaaS already use PORT:
> - Nodejitsu
> - Cloud9
> - Heroku
> 
> I know it's already supported, now it's better
> to recommend the use of PORT and deprecate app_port
> in the help pages.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodester/nodester/issues/408.

## 

Atentamente
_Víctor Alejandro Morales Gámez_
*
*
*
*

**Comment by chrismatthieu** [comment]
I like the idea of using port too.  Hopefully this will make it easier to move from external services to Nodester.

**Comment by alejandro** [comment]
@jmendeth done! You can use "PORT" instead of "app_port" now. Hack the Planet \m/

**Comment by mildsunrise** [comment]
@alejandro Great, thanks! Now it would be great to favour its use and deprecate `app_port` in the help pages.

@chrismatthieu
Not only that, Nodester is now compatible with the [also open-source] [Cloud9 IDE](https://c9.io)!
I can see if I can work on a way to deploy from C9 -> Nodester.

**Comment by chrismatthieu** [comment]
w00t!  BTW, You may find this article helpful: https://github.com/nodester/nodester/wiki/How-to-deploy-to-Nodester-from-Cloud9-IDE

**Comment by mildsunrise** [comment]
Yeah, I master both APIs. :sunglasses:
By the way, the image in the article is broken.
