### ISSUE TITLE
'nodester app init x' consistently fails

### ISSUE THREAD

**Issue by martypdx** [nodester/nodester#48]
Marty.Nelson@Laptop-Mnelson7 ~
$ nodester app create sometestapp some.js
nodester info Checking config..
nodester info creating app: sometestapp some.js
nodester info successfully created app sometestapp to will run on port  from som
e.js
nodester info run nodester app init sometestapp  to setup this app.

Marty.Nelson@Laptop-Mnelson7 ~
$ nodester app init sometestapp ./sometestapp
nodester info Checking config..
nodester info initializing git repo for sometestapp into folder ./sometestapp
nodester info cloning the repo git clone ec2-user@nodester.com:/home/ec2-user/ho
sted_apps/martypdx/440-a0004c6c9ab39f06d57c50f8d77d4333.git ./sometestapp
nodester info writing app data to config

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: EBADF, Bad file descriptor 'sometestapp/.nodester.appconfig'
    at Object.openSync (fs.js:197:18)
    at Object.writeFileSync (fs.js:449:15)
    at Object.writeApp (/usr/local/lib/node/.npm/nodester-cli/0.2.3/package/lib/
config.js:46:8)
    at /usr/local/lib/node/.npm/nodester-cli/0.2.3/package/lib/app.js:172:37
    at ChildProcess.exithandler (child_process.js:85:7)
    at ChildProcess.emit (events.js:45:17)
    at Socket.<anonymous> (child_process.js:151:12)
    at Socket.emit (events.js:42:17)
    at Array.<anonymous> (net.js:800:12)
    at EventEmitter._tickCallback (node.js:108:26)

Marty.Nelson@Laptop-Mnelson7 ~
$ nodester app init sometestapp sometestapp
nodester info Checking config..
nodester info initializing git repo for sometestapp into folder sometestapp
nodester info cloning the repo git clone ec2-user@nodester.com:/home/ec2-user/ho
sted_apps/martypdx/440-a0004c6c9ab39f06d57c50f8d77d4333.git sometestapp
nodester info writing app data to config

fs.js:197
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'sometestapp/.nodester.appconfig'
    at Object.openSync (fs.js:197:18)
    at Object.writeFileSync (fs.js:449:15)
    at Object.writeApp (/usr/local/lib/node/.npm/nodester-cli/0.2.3/package/lib/
config.js:46:8)
    at /usr/local/lib/node/.npm/nodester-cli/0.2.3/package/lib/app.js:172:37
    at ChildProcess.exithandler (child_process.js:85:7)
    at ChildProcess.emit (events.js:45:17)
    at ChildProcess.onexit (child_process.js:171:12)

Marty.Nelson@Laptop-Mnelson7 ~
$

**Comment by JacksonTian** [comment]
I have the same issue, can somebody help us to resolve it?

**Comment by JacksonTian** [comment]
Hello, you should try app user setkey first.

**Comment by martypdx** [comment]
Ok, got a little further, now I'm getting this error:

$ nodester app init sometestapp
nodester info Checking config..
nodester info initializing git repo for sometestapp into folder sometestapp
nodester info cloning the repo git clone ec2-user@nodester.com:/home/ec2-user/ho
sted_apps/martypdx/440-a0004c6c9ab39f06d57c50f8d77d4333.git sometestapp
Enter passphrase for key '/c/Users/marty.nelson/Documents/Marty/.ssh/id_rsa':
nodester info writing app data to config
Enter passphrase for key '/c/Users/marty.nelson/Documents/Marty/.ssh/id_rsa':
nodester ERRO false

I tried "nodester user setkey <file containing ssh public key>" both with the file as-is, and by using "cat ~/.ssh/id_rsa.pub | sed s/'+'/'%2B'/g | pbcopy" to replace '+' (btw there's a type, the last | should be a >). 

Same error either way. Passphrase is correct.

I can start the app, but it fails when I try and go to sometestapp.nodester.com
