### ISSUE TITLE
Problem when using require()

### ISSUE THREAD

**Issue by leeadkins** [nodester/nodester#49]
When I try to require a JS module that has been included with my project, like this:

var utils = require('./utils.js');

where "utils.js" is a JS file in the same project root directory as server.js, I get this error in my logs:

{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Cannot find module \'./utils.js\'' }{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Cannot find module \'./utils.js\'' }

The same error is given with various versions of the same situation (with or without .js, module in a folder with the require() statement updated accordingly).

I guess I should also note that this is an otherwise functioning app. Without the additional require(), the app has been deployed and runs fine on nodester.

**Comment by DanBUK** [comment]
Can you try using require paths relative to the root of your git repo. Therefore require('/utils.js')

**Comment by leeadkins** [comment]
Yep, it will load the file with require('/utils.js'), which breaks when this isn't running on nodester because it's looking for utils.js at the root of the filesystem.

A workaround is to be even more specific about the location and use __dirname, so require(__dirname + '/utils.js'). 

Still seems strange that typical relative paths don't work, but the alternative (with __dirname) isn't too much of a hassle.

**Comment by neojp** [comment]
I'm having the same issue, and I actually remember using __dirname + '/config.js' althought iirc didn't work either.

I wonder if it's a node 0.4 bug, or a nodester configuration.

**Comment by fhemberger** [comment]
__dirname + '/file.js' worked for me.

**Comment by davglass** [comment]
I will have this fixed in the next deploy, it's currently working on my staging server.

**Comment by davglass** [comment]
I pushed my changes today, can you check to see if this now works for you?

**Comment by davglass** [comment]
Closing based on my latest deployment.
