### ISSUE TITLE
Problem? nodejs0.4.0 with Express

### ISSUE THREAD

**Issue by uchiyama2000** [nodester/nodester#50]
My app can't run though I tried that the app that uses Express. 
nodester npm install express -> YES

**Comment by uchiyama2000** [comment]
my local environments
% node --version
v0.4.0
% express --version
2.0.0-pre

i think that the installation of express is as follows.
OK:git clone express...git && cd express && npm install
NG:npm install express

**Comment by chrismatthieu** [comment]
Could you try it again?  We believe that this issue has been resolved.  Let us know so that we can close this ticket if it is or continue working on it.

Thanks,
Chris

**Comment by uchiyama2000** [comment]
thanks!
i could try myapp again. but, it could not run.
In my PC, it runs fine. 

so, this is error message.

Connect
500 ReferenceError: //views/index.jade:1 1. 'h1= title' title is not defined
1. 'h1= title'
title is not defined

**Comment by nodester** [comment]
did you add jade to your list of npm modules in your sandbox?

nodester npm install jade

**Comment by uchiyama2000** [comment]
yes.
Of course, it has been installed.

**Comment by chrismatthieu** [comment]
What's the github repo of your app?  I would like to try to clone and install it myself to try to replicate the issue.

Thanks
Chris

**Comment by chrismatthieu** [comment]
There's also a possibility that this issue is related to issue 32 (NPM not installing dependencies automatically) https://github.com/nodester/nodester/issues#issue/32

**Comment by uchiyama2000** [comment]
I have not registered in my repo only it is to do 
express appname.

**Comment by uchiyama2000** [comment]
this issue was closed.
but i opened the following issue...
https://github.com/nodester/nodester/issues#issue/55
