### ISSUE TITLE
Error: EBADF, Bad file descriptor 'suncity/.nodester.appconfig'

### ISSUE THREAD

**Issue by JacksonTian** [nodester/nodester#51]
I execute nodester app suncity init, it return following error. How to resolve it.
nodester info writing app data to config

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
WideCharToMultiByte: 
Error: EBADF, Bad file descriptor 'suncity/.nodester.appconfig'

**Comment by chrismatthieu** [comment]
You may need to setup you CLI.  After running npm install nodester-cli, you will need to run nodester user setup <username> <password> to configure it.

We also fixed an issue with the initial launch of an app.  Could you try it again after setting your username and password?  You may also want to make sure that you don't have any non-base64 characters in your creds like $ or @ or :

Thanks,
Chris

**Comment by JacksonTian** [comment]
Yes, I didn't execute the nodester user setup.
After run it, init app is ok, I can push the git, and start app success.
But when I access appname.nodester.com, it return  "The application is not running..
ECONNREFUSED, Connection refused". I think it's another issue.

**Comment by JacksonTian** [comment]
It's seem like the start issue has been resolved.
