### ISSUE TITLE
"nodester app init [appname]" fails

### ISSUE THREAD

**Issue by martypdx** [nodester/nodester#52]
I still have been able to use nodester :(

$ nodester app init sometestapp 
nodester info Checking config..
nodester info initializing git repo for sometestapp into folder sometestapp
nodester info cloning the repo git clone ec2-user@nodester.com:/home/ec2-user/ho
sted_apps/martypdx/440-a0004c6c9ab39f06d57c50f8d77d4333.git sometestapp
Enter passphrase for key '/c/Users/marty.nelson/Documents/Marty/.ssh/id_rsa':
nodester info writing app data to config
Enter passphrase for key '/c/Users/marty.nelson/Documents/Marty/.ssh/id_rsa':
nodester ERRO false

I tried "nodester user setkey " both with the file as-is, and by using "cat ~/.ssh/id_rsa.pub | sed s/'+'/'%2B'/g | pbcopy" to replace '+' (btw there's a typo on help page, the last | should be a >).

Same error either way. Passphrase is correct.

**Comment by chrismatthieu** [comment]
Could you try it again?  We fixed an issue with starting new apps and this issue may be related.  Let us know so that we can close this ticket if it is or continue working on it.

Thanks,
Chris

**Comment by davglass** [comment]
The command line tool doesn't take into account passphrase prompting, it doesn't know that it needs to halt and accept the passphrase.

Can you try using an ssh-agent so you can preload your unlocked ssh key?
http://mah.everybody.org/docs/ssh

**Comment by martypdx** [comment]
Wow, It's going to take some time for me to work through getting an ssh-agent setup. 

Coming from the darkside of the windows world, that's all new to me.

**Comment by martypdx** [comment]
Ok, got the ssh-agent set up. This was best (and simpliest) resource for cygwin:  http://www.newmedialogic.com/node/55. I verified with another service/server that agent is working. 

Here's the nodester failure:
    Marty.Nelson@Laptop-Mnelson7 ~
    $ mkdir another-nodester-test-app

```
Marty.Nelson@Laptop-Mnelson7 ~
$ cd another-nodester-test-app/

Marty.Nelson@Laptop-Mnelson7 ~/another-nodester-test-app
$ nodester app create another-nodester-test-app
nodester info Checking config..
nodester info creating app: another-nodester-test-app server.js
nodester info successfully created app another-nodester-test-app to will run on
port  from server.js
nodester info run nodester app init another-nodester-test-app  to setup this app
.

Marty.Nelson@Laptop-Mnelson7 ~/another-nodester-test-app
$ nodester app init another-nodester-test-app
nodester info Checking config..
nodester info initializing git repo for another-nodester-test-app into folder an
other-nodester-test-app
nodester info cloning the repo git clone ec2-user@nodester.com:/home/ec2-user/ho
sted_apps/martypdx/645-b9ce12ca4a690bc715e67ef5867fd215.git another-nodester-tes
t-app
nodester info writing app data to config
nodester ERRO false

Marty.Nelson@Laptop-Mnelson7 ~/another-nodester-test-app
$
```

**Comment by davglass** [comment]
What version of the nodester-cli are you using? Can you install the latest? `npm install nodester-cli`

**Comment by martypdx** [comment]
Updated to `nodester-cli@0.2.5`, but still same error.

The apps /appear/ to deploy and are updatable when I do a `git push nodester master`, always uneasy about what problems may be lurking though...

**Comment by martypdx** [comment]
also, I now have a ton of test apps from this, but doesn't appear to be a delete app command?

**Comment by davglass** [comment]
`nodester app delete <appname>`
