### ISSUE TITLE
Delete && nodester app init ERROR

### ISSUE THREAD

**Issue by uchiyama2000** [nodester/nodester#55]
I had to make the application newly, and executed the following commands. 

1.curl -X DELETE -u "testuser:testpwd" -d "appname=a" http://api.nodester.com/app

2.rm -rf a

3.nodester app create a app.js
nodester info Checking config..
nodester info creating app: a app.js
nodester info successfully created app a to will run on port  from app.js
nodester info run nodester app init a  to setup this app.

4.nodester app init a
nodester info Checking config..
nodester info initializing git repo for a into folder a
nodester info cloning the repo git clone ec2-user@nodester.com:/home/ec2-user/hosted_apps/xxxxx.git a
nodester info writing app data to config
nodester ERRO false

**Comment by uchiyama2000** [comment]
the following commands are done. it runs well, though app init error has occurred.
is it OK?

5.cd a

6.git remote add nodester ec2-user@nodester.com:/home/ec2-user/hosted_apps/xxx.git

7.git push nodester master

8.browse http://a.nodester.com

**Comment by uchiyama2000** [comment]
app was made with 
express appname

It run well after title elements were deleted from view/*jade.
???

**Comment by uchiyama2000** [comment]
express default template bug?
but it run well with the default jade files on my pc.
Which express is correct?

<pre><code>
--- ../tmp/a/app.js 2011-02-28 19:03:57.000000000 +0900
+++ app.js  2011-02-28 18:58:31.000000000 +0900
@@ -30,7 +30,7 @@
 
 app.get('/', function(req, res){
   res.render('index', {
-    title: 'Express'
+    locals:{title: 'Express'}
   });
 });
</code></pre>

**Comment by davglass** [comment]
Make sure you are calling `nodester npm install express` in your app dir.

You may actually be running different versions of express on nodester than what's on your machine. If you need a specific version of express, you can install it this way: `nodester npm install express@1.0.3`

**Comment by uchiyama2000** [comment]
ok, i see!.
i try the way.

my machine's environments

node --version 
v0.4.1

express --version 
2.0.0-pre
