### ISSUE TITLE
Delivery of static files fail using paperboy

### ISSUE THREAD

**Issue by fhemberger** [nodester/nodester#56]
I'm using paperboy (https://github.com/felixge/node-paperboy/) as static file server.
Somehow delivery of static content fails.

Example app:

```
var http = require('http'),
    paperboy = require('paperboy'),
    util = require('util');

var SERVER_PORT    = '8702',
    SERVER_PUBLIC  = __dirname + '/public';


http.createServer(function(req, res) {
paperboy
    .deliver(SERVER_PUBLIC, req, res)
    .addHeader('Expires', 300)
    .addHeader('X-PaperRoute', 'Node')
    .error(function(statCode, msg) {
        console.log(statCode, req.url, req.ip, msg);
    })
    .otherwise(function(err) {
        res.writeHead(404, {'Content-Type': 'text/plain'});
        res.end("Error 404: File not found");
        console.log(404, req.url, req.ip, err);
    });

}).listen(SERVER_PORT);
util.puts('Server running at port ' + SERVER_PORT);
```

Put a file in <app-root>/public/ and try to request it. The above app works fine on my local node installation (0.4.1) but seems to fail on nodester. In issue #49 (https://github.com/nodester/nodester/issues#issue/49) it's reported that `require('./lib/myfile.js')` fails. Guess what's the first line of paperboy's package … ;)

**Comment by davglass** [comment]
This should work now with my latest deployment. Can you give it a shot and close if it now works?

**Comment by davglass** [comment]
This now works, provided that you change a couple of lines (which is probably a bug in Node). You need to make sure you use path.join() when joining paths. Your path before ended up being: //public instead of /public. I think Node's path processor breaks on that.

```
var http = require('http'),
    path = require('path'),
    paperboy = require('paperboy'),
    util = require('util');

var SERVER_PORT    = 8734,
    SERVER_PUBLIC  = path.join(__dirname, 'public');
```

**Comment by fhemberger** [comment]
Thanks it's working now.
