### ISSUE TITLE
Problems with express@1.0.8 install using npm

### ISSUE THREAD

**Issue by zr0z** [nodester/nodester#58]
I've tried to create a new app which uses express, and after 
    $ nodester app npm install express
    [...]
    nodester npm info build Success: express@1.0.8
    nodester npm info build Success: connect@0.5.10
    nodester npm info build Success: qs@0.0.6
    nodester npm ok
and pushing the default sample express app on master, the app refuse to start due to a path problem
    $ nodester app logs
    nodester info Checking config..
    nodester info Nodester wrapped script starting (24794) at  Wed, 02 Mar 2011 21:26:23 GMT
    nodester info Error: Cannot find module 'express'
    nodester info     at Function._resolveFilename (module.js:289:11)
    nodester info     at Function._load (module.js:241:25)
    nodester info     at Function.require (module.js:317:19)
    nodester info     at /home/ec2-user/nodester/scripts/launch_chrooted_app.js:111:26
    nodester info     at tops.js:1:15
    nodester info     at /home/ec2-user/nodester/scripts/launch_chrooted_app.js:153:20
    nodester info     at [object Object].<anonymous> (fs.js:86:5)
    nodester info     at [object Object].emit (events.js:39:17)
    nodester info     at afterRead (fs.js:840:12){ stack: [Getter/Setter],
    nodester info   arguments: undefined,
    nodester info   type: undefined,
    nodester info   message: 'Cannot find module \'express\'' }
I haved installed several other npm packages on this app and I have no path problems
Beside that I already have one instance on express running on another app fine...

**Comment by davglass** [comment]
I'm looking into it now..

**Comment by davglass** [comment]
Can you tell me what app it is? I need a repo id. Show me the output of this:

`nodester app info`

**Comment by uchiyama2000** [comment]
hi,zr0z!
After having done 
<code>nodester npm install express</code>
did you restart your application?
<code>nodester app restart <app-name></code>

Is jsdom also necessary possibly?
<code>nodester npm install jsdom</code>

At last, my first express app run yesterday.
http://a.nodester.com/

**Comment by zr0z** [comment]
@davglass :
Here are my app infos

```
nodester info Checking config..
nodester info Gathering information about: top
nodester info top on port 8726 running: true
nodester info gitrepo: ec2-user@nodester.com:/home/ec2-user/hosted_apps/0z/573-ddb7fd369c9a374a6def0b5321e2f6f8.git
nodester info appfile: server.js
```

I've this final line when pushing on the repo for this app maybe its related :

```
error: failed to push some refs to 'ec2-user@nodester.com:/home/ec2-user/hosted_apps/0z/573-ddb7fd369c9a374a6def0b5321e2f6f8.git'
```

@uchiyama2000 :
I've tried to add jsdom but the logs are still telling me that the require failed on express
Beside that I already have an app with express running fine

**Comment by davglass** [comment]
Try this now: `nodester npm install express@express@1.0.7` 

I deployed a fix after you reported this issue, I think it's resolved with a new install.

**Comment by davglass** [comment]
Sorry, that should be `nodester npm install express@1.0.7`

**Comment by davglass** [comment]
I just confirmed that I had to do this:

`nodester npm install connect@0.5.10 express@1.0.7`

**Comment by zr0z** [comment]
@davglass

Hurray it works! thanks very much for the help!

**Comment by ghost** [comment]
If you Windows user add location to your path. 

<pre>export NODE_PATH="C:\Users\IMarek\AppData\Roaming\npm\node_modules"</pre>

Change: IMarek to your user name :) 

I explained in bit more details on my post <a href="http://blog.i-evaluation.com/2012/09/17/error-cannot-find-module-express/">Error can not find module</a> but bottom line it can be fixed (on Windows) by:
