### ISSUE TITLE
nodester app delete ?

### ISSUE THREAD

**Issue by zr0z** [nodester/nodester#59]
I was thinking that it may be handy to be able to delete a created app.
Something like :
    $ nodester app delete [app]

**Comment by chrismatthieu** [comment]
We have support for deleting apps in the API
curl -X DELETE -u "testuser:123" -d "appname=test" http://api.nodester.com/app

I agree that we should add this feature to the CLI.

Thanks,
Chris

**Comment by davglass** [comment]
Next CLI release will have it:
nodester/nodester-cli@248589cded714fcb21bd56c0b016c5efeb2e0c21

**Comment by zr0z** [comment]
@chrismatthieu yeah thanks I always forget about the curl commands 

@davglass thanks very much to add that to the cli application
