### ISSUE TITLE
App not being fully deleted

### ISSUE THREAD

**Issue by Fabryz** [nodester/nodester#62]
Recently my app was always on a mysterious failed-to-start status, also the latest pushes were not really changing the server.js, so I decided to delete it via:
    curl -X DELETE -u "testuser:123" -d "appname=test" http://api.nodester.com/app

Now if I check via nodester-cli the app does not exist anymore, but actually it's still there if I connect to it via HTTP:

http://sawket.nodester.com/

**Comment by davglass** [comment]
Sounds like the proxy table is not being updated on delete, I will look into it.

**Comment by davglass** [comment]
Just pushed an update, it should now delete the proxytable entry, the chroot, the git repo and kill the process.
