### ISSUE TITLE
need password reset option 

### ISSUE THREAD

**Issue by SynnaxCrab** [nodester/nodester#63]
forget my password(or maybe username!) at Nodester. 

Please add the password reset option,  either web interface or cli api or better both.

Thanks!

**Comment by chrismatthieu** [comment]
Tested.  Both the REST API and the CLI work for changing password

curl -X PUT -u "testuser:123" -d "password=111111" http://api.nodester.com/user

nodester user setpass <password> - Set a new password for this user

**Comment by jgoodall** [comment]
This is how to change the password, but what if you dont know the password (i.e. '123' in the example above)?

**Comment by yocontra** [comment]
@jgoodall - The system is fundamentally flawed right now and will be completely revamped in V2. If you'd like to try our current implementation (may not work) you can run these.

`curl -i -X POST -d '{"user":"your username"}' http://api.nodester.com/reset_password/` for a password reset code

`curl -i -X PUT -d '{"password":"your new password"}' http://api.nodester.com/reset_password/<reset token>` to change the password.

If this is in relation to the issue you opened I'd be glad to help you change your password

**Comment by jgoodall** [comment]
Yes, can you help me reset the password?

The following command did not work:

 $ curl -i -X POST -d '{"user":"jgoodall"}'
http://api.nodester.com/reset_password/
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: Keep-Alive
Age: 0
Date: Tue, 06 Dec 2011 15:01:57 GMT

TypeError: Cannot call method 'split' of undefined
    at Object.escape
(/node/nodester/nodester/node_modules/cradle/lib/cradle.js:673:61)
    at Object.get
(/node/nodester/nodester/node_modules/cradle/lib/cradle.js:318:42)
    at loadAccount (/node/nodester/nodester/lib/reset_password.js:7:10)
    at /node/nodester/nodester/lib/reset_password.js:29:5
    at callbacks
(/node/nodester/nodester/node_modules/express/lib/router/index.js:272:11)
    at param (/node/nodester/nodester/node_modules/express/lib/router/index.js:246:11)
    at pass (/node/nodester/nodester/node_modules/express/lib/router/index.js:253:5)
    at Router._dispatch
(/node/nodester/nodester/node_modules/express/lib/router/index.js:280:4)
    at Object.handle
(/node/nodester/nodester/node_modules/express/lib/router/index.js:45:10)
    at next (/node/nodester/nodester/node_modules/connect/lib/http.js:198:15)

Thanks for your help.
-john

On Tue, Dec 6, 2011 at 9:26 AM, Contra
reply@reply.github.com
wrote:

> @jgoodall - The system is fundamentally flawed right now and will be completely revamped in V2. If you'd like to try our current implementation (may not work) you can run these.
> 
> `curl -i -X POST -d '{"user":"your username"}' http://api.nodester.com/reset_password/` for a password reset code
> 
> `curl -i -X PUT -d '{"password":"your new pasword"}' http://api.nodester.com/reset_password/<reset token>` to change the password.
> 
> If this is in relation to the issue you opened I'd be glad to help you change your password
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nodester/nodester/issues/63#issuecomment-3032813

## 

jgoodall

**Comment by jgoodall** [comment]
you can set the new password to temp1234 and I will change it. thanks again.
-john

On Tue, Dec 6, 2011 at 9:26 AM, Contra
reply@reply.github.com
wrote:

> @jgoodall - The system is fundamentally flawed right now and will be completely revamped in V2. If you'd like to try our current implementation (may not work) you can run these.
> 
> `curl -i -X POST -d '{"user":"your username"}' http://api.nodester.com/reset_password/` for a password reset code
> 
> `curl -i -X PUT -d '{"password":"your new pasword"}' http://api.nodester.com/reset_password/<reset token>` to change the password.
> 
> If this is in relation to the issue you opened I'd be glad to help you change your password
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nodester/nodester/issues/63#issuecomment-3032813

## 

jgoodall

**Comment by yocontra** [comment]
Your password has been changed. Let me know if you have any more issues!
