### ISSUE TITLE
Install socket.io on Cygwin (Windows)

### ISSUE THREAD

**Issue by Rinow** [nodester/nodester#64]
Hi,

When i try "nodester npm install socket.io", an error message appears : ERROR no packages to install.

Anyway, it is a success with the following command : curl -X POST -u "testuser:123" -d "appname=a&action=install&package=socket.io" http://api.nodester.com/appnpm

My results with it :

{"status":"success","output":"stdout: \nstderr: npm info it
th ok\nnpm info using npm@0.2.16\nnpm info using node@v0.4.
p://registry.npmjs.org/socket.io/-/socket.io-0.6.16.tgz\nnp
a1 /tmp/npm-1299351204130/1299351204130-0.20952210412360728
asum fb4d8e053f6d7376e4561d46949fd21dc210a894\nnpm info cal
c2-user/hosted_apps/rinow/587-90f68a88e0c4dd3de461893db763a
npm/.cache/socket.io/0.6.16/package.tgz\nnpm info shasum 55
358b196e7b37b3650\nnpm info preinstall socket.io@0.6.16\nnp
.io@0.6.16\nnpm info postinstall socket.io@0.6.16\nnpm info
o@0.6.16\nnpm info activate socket.io@0.6.16\nnpm info post
6.16\nnpm info build Success: socket.io@0.6.16\nnpm ok\n"}

**Comment by davglass** [comment]
What version of the cli? What version of node? Can you paste the entire output of the cli?

**Comment by Rinow** [comment]
Cygwin 1.124
Nodejs 0.4.1

Which output do you need ?

Thx !

Rinow

**Comment by davglass** [comment]
Everything the cli printed.

**Comment by Rinow** [comment]
nodester appnpm install socket.io
nodester info Checking config..
nodester ERRO no packages to install

Then i tried : 

curl -X POST -u "testuser:123" -d "appname=a&action=install&package=socket.io" http://api.nodester.com/appnpm
{"status":"success","output":"stdout: \nstderr: npm info it th ok\nnpm info using npm@0.2.16\nnpm info using node@v0.4.
p://registry.npmjs.org/socket.io/-/socket.io-0.6.16.tgz\nnp
a1 /tmp/npm-1299351204130/1299351204130-0.20952210412360728
asum fb4d8e0\nnpm info cal
c2-user/hosted_apps/rinow/587-90f68a88e0c4dd3de461893db763a
npm/.cache/socket.io/0.6.16/package.tgz\nnpm info shasum 55
358b196e7b37b3650\nnpm info preinstall socket.io@0.6.16\nnp
.io@0.6.16\nnpm info postinstall socket.io@0.6.16\nnpm info o@0.6.16\nnpm info activate socket.io@0.6.16\nnpm info post
6.16\nnpm info build Success: socket.io@0.6.16\nnpm ok\n"}

**Comment by davglass** [comment]
That's strange, it's like the cli can't read the argument passed. What if you wrap socket.io in quotes?

**Comment by davglass** [comment]
Asking because I don't use windows..

**Comment by Rinow** [comment]
I think the problem is linked with my git folder...My socket.io folder seems to not be in the right place

**Comment by davglass** [comment]
I don't think that's the issue, the command you are executing has nothing to do with local data. It's `npm installing` something on the nodester server. It looks like the arguments aren't being passed to the cli. Can you attempt to install something else via npm? `nodester npm install express@1.0.7` and `nodester npm install dust` and give me the output of both? (checking to see if '.' is a problem on cygwin.)

**Comment by Rinow** [comment]
nodester npm install express@1.0.7
nodester info Checking config..
nodester ERRO no packages to install

nodester npm install dust
nodester info Checking config..
nodester ERRO no packages to install

Same errors ! :(
'.' seems not to be the issue.

To be sure, modules mustn't be installed on my local?

**Comment by davglass** [comment]
No, it has to be an issue with the arguments not getting passed in. I'll have to see if I can get my hands on a Windows machine and get node installed under Cygwin to test it.

**Comment by Rinow** [comment]
allright thx davglass ;)
