### ISSUE TITLE
Unable to make my Socket.io app work

### ISSUE THREAD

**Issue by Fabryz** [nodester/nodester#65]
I'm making a socket.io chatroom ( https://github.com/Fabryz/sawket ): on local it works fine, once I push it to nodester ( temporary on http://sahket.nodester.com/ ) I'm not able to make it work.

I've installed socket.io module via 
    nodester appnpm install sahket socket.io
retrieved my app port (8756) with
    nodester app info sahket
and used it on server.listen on the backend.

On the frontend I used
    var socket = new io.Socket('sahket.nodester.com', {port: 80})
but also tried with "localhost" as hostname, and with "8756" as port, but it still keeps not working.

What am I doing wrong?

**Comment by davglass** [comment]
Try this:
    var socket = new io.Socket(null, {port: 80, rememberTransport: false});
    socket.connect();

**Comment by Fabryz** [comment]
Looks like it's working now, thanks
