### ISSUE TITLE
Port not shown on app creation message

### ISSUE THREAD

**Issue by Fabryz** [nodester/nodester#66]
Minor bug, port is not shown on the confirmation message:
    $ nodester app create newapp server.js 
    nodester info Checking config..
    nodester info creating app: newapp server.js
    nodester info successfully created app newapp to will run on port  from server.js
    nodester info run nodester app init newapp  to setup this app.

A quick workaround is:
    nodester app info newapp

**Comment by davglass** [comment]
This is fixed in master, we just need to publish a new version of the CLI. I don't have access to do it yet..
