### ISSUE TITLE
App is running, but its status is still on "failed-to-start"

### ISSUE THREAD

**Issue by Fabryz** [nodester/nodester#67]
Created an app, pushed it on nodester and manually restarted it.
I still see that with "nodester app info" it tells me that the status is "failed-to-start", but the app is actually running on the server.

Is that because I didn't use "nodester app init"?

"nodester app stop" returns an error, "nodester app restart" returns ok, but i'm not sure it is really restarted.

**Comment by davglass** [comment]
I need to know that app that you are dealing with? Give me the output of:
`nodester app info`

**Comment by Fabryz** [comment]
The app name is "sawket":

```
 $ nodester app info sawket
nodester info Checking config..
nodester info Gathering information about: sawket
nodester info sawket on port 8765 running: failed-to-start
nodester info gitrepo: blabla.git
nodester info appfile: server.js
```

**Comment by davglass** [comment]
That `blahblah`.git is what I needed ;)

**Comment by davglass** [comment]
Fixed..
