### ISSUE TITLE
Something crashes when trying to make SSL HTTP requests

### ISSUE THREAD

**Issue by abraham** [nodester/nodester#68]
Code to reproduce,  response, and error logs: https://gist.github.com/4c11c2e6ac332732d8a8

if the Twitter object has `rest_base: 'http://api.twitter.com/1' added then the error does not occur.

**Comment by davglass** [comment]
I think I have isolated the issue. I will work on it later this evening..

**Comment by davglass** [comment]
Restart your app, I just deployed a fix ;)

**Comment by davglass** [comment]
Fixed..
