### ISSUE TITLE
DELETE /app returns 500 error

### ISSUE THREAD

**Issue by abraham** [nodester/nodester#69]
Snapshot of request/response: https://apigee.com/console/apigee-console-snapshots-1298955600000_725b0685-69e0-46d5-bed0-4a443db743f1/rendersnapshotview

**Comment by davglass** [comment]
This wasn't "technically" an issue on our side, but I put a work around in for it anyway. DELETE requests are similar to POST requests, they are expected to be form-encoded data. apigee was adding them as request parameters and not posted data.

**Comment by abraham** [comment]
Yep. That worked. Looks like Apigee has a bug too. They completely ignore post data for DELETEs.
