### ISSUE TITLE
mixed case appnames fail in creation

### ISSUE THREAD

**Issue by janewilkin** [nodester/nodester#70]
I just attempted to create an app named 'iFM' and though I got what looked like good output from the 'nodester create' command, the command 'nodester app info iFM' would fail.  I'm sure this could be replicated by simple attempting to create an app with mixed case.  My resolution was to use the app name 'ifm'.

From my experience:

```
garrett@garrett-VirtualBox:~/github/iFM$ nodester app create iFM begin.js
nodester info Checking config..
nodester info creating app: iFM begin.js
nodester info successfully created app iFM to will run on port  from begin.js
nodester info run nodester app init iFM  to setup this app.
garrett@garrett-VirtualBox:~/github/iFM$ nodester app init iFM
nodester info Checking config..
nodester info initializing git repo for iFM into folder iFM
nodester ERRO [HTTP 400] {"status" : "failure - app not found (" + appname + ")"}
```

**Comment by janewilkin** [comment]
Mixed case might also be an issue for other nodester commands.  I had trouble with nodester npm install as well.  My git repo for the project is 

   https://github.com/garrettwilkin/iFM

And the folder on my PC is also mixed case, just like the repo name.  Maybe that is causing problems too?

**Comment by davglass** [comment]
Thank's for catching that, it should `toLowerCase` all appname/folder names. 

Checked in: nodester/nodester-cli@1bbb526762e6c808b705af13a21e4380f7eec7e1
