### ISSUE TITLE
REST API not return domain list for application

### ISSUE THREAD

**Issue by grender** [nodester/nodester#75]
But application work from custom domain and when i try add it, i get 'alredy exist' error.
Here is console output:
    grender@grender-laptop ~/QouteOnNode
    $ curl -u "USER:PASS" http://api.nodester.com/appdomains
    []

```
grender@grender-laptop ~/QouteOnNode
$ curl -X POST -u "USER:PASS" -d "appname=APPNAME&action=a
dd&domain=DOMAIN" http://api.nodester.com/appdomains
{"status":"{\"status\": \"failure - domain already exists\"}\n"}
```

UPD: application name: justanotherquote

**Comment by davglass** [comment]
What domain?

**Comment by grender** [comment]
beta.justanotherquote.com

**Comment by chrismatthieu** [comment]
I just updated nodester to fix the issue with the REST API.  It wasn't returning the list of domains.  

Once the new site is deployed, we can test it again with the CLI.

**Comment by chrismatthieu** [comment]
CLI: nodester domain

nodester info fetching your list of domain aliases
nodester info chats.io aliased to app chats running on port 8764
nodester info clm.nodester.com aliased to app clm101 running on port 8579
nodester info example.com aliased to app clm300 running on port 8728

REST API 

curl -u "testuser:123" http://api.nodester.com/appdomains

[{"domain":"chats.io","appname":"chats","host":"127.0.0.1","port":8764},{"domain":"clm.nodester.com","appname":"clm101","host":"127.0.0.1","port":8579},{"domain":"example.com","appname":"clm300","host":"127.0.0.1","port":8728}]
