### ISSUE TITLE
require() cannot find file

### ISSUE THREAD

**Issue by anm** [nodester/nodester#78]
```
require.paths.push('./lib');
var util = require('util.js');
```

`lib/util.js` exists in project directory.

Nodester app logs:

```
Nodester wrapped script starting (24062) at  Sat, 12 Mar 2011 17:41:45 GMT
Error: Cannot find module 'util.js'
    at Function._resolveFilename (module.js:289:11)
    at Function._load (module.js:241:25)
    at Function.require (module.js:317:19)
    at /home/ec2-user/nodester/scripts/launch_chrooted_app.js:121:26
    at talker.js:6:12
    at /home/ec2-user/nodester/scripts/launch_chrooted_app.js:167:20
    at [object Object].<anonymous> (fs.js:86:5)
    at [object Object].emit (events.js:39:17)
    at afterRead (fs.js:840:12){ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Cannot find module \'util.js\'' }
```

I have also tried calling lib '/lib', 'lib', '/project/lib' and 'project/lib' with no change.

**Comment by davglass** [comment]
`var util = require('./lib/util');`

**Comment by anm** [comment]
Removing the .js suffix stops the error for that module but not for others I have tried. I tried renaming the module to utila as well and it didn't work. Could it be loading some other util module? Very weird.

**Comment by anm** [comment]
The direct require, without using the require path, does seem to work more generally.

**Comment by anm** [comment]
It is not, however, working with a file in the same directory as the server. 
    var conf = require("./config");

**Comment by davglass** [comment]
I can't replicate your issue, here is my test deployed to: http://davglass.nodester.com/

https://gist.github.com/867559

All the includes are working, sub includes, main dir includes..

**Comment by chrismatthieu** [comment]
I'm currently having the same problem on http://chats.nodester.com.  I've tried using:

io = require('./libs/socket-io-node')

and 

io = require('./libs/socket-io-node/index')

Here's my gist: 
https://gist.github.com/094ecd74d8f9fdcb71c8

Here's my repo:
topher/611-93d14e4c205b165d72865cb2e58d4008

**Comment by chrismatthieu** [comment]
i just noticed i'm missing files in my repo - it may be my bad :)

**Comment by chrismatthieu** [comment]
once i added the appropriate files to my repo, the local libraries are loading fine with require

**Comment by anm** [comment]
It turns out the problem with ./config was actually something else (which I shall open another bug for).

The require('./foo') solution is now working.

**Comment by davglass** [comment]
Closing now that this is resolved..

**Comment by anm** [comment]
I'm afraid I disagree. If it works locally it should work on nodester. Telling people they must change how they do their includes is not a good solution. Left like this, there will undoubtedly be much time wasted.

Unless of course you mean it will work anyway, in which case disregard this comment.

**Comment by davglass** [comment]
@anm, What is there to disagree with? They had errors, not functional problems. As I pointed out, all of these requires work both locally and on nodester: https://gist.github.com/867559

No one is asking them to change anything.

**Comment by anm** [comment]
Does my original example work now? Does using the require path work? Does it work without the ./ prefix? What about when you use the .js suffix?

**Comment by davglass** [comment]
Yes, here is the gist I am using: https://gist.github.com/867559

I just checked in another change to help with other requires issues, but yours works ;)
