### ISSUE TITLE
Need a way to add more SSH Keys

### ISSUE THREAD

**Issue by AbeEstrada** [nodester/nodester#79]
Right now nodester only accepts 1 ssh key, but what if I have more than one computer where I develop, there's no option to add more ssh keys.

**Comment by chrismatthieu** [comment]
One option for now could be to create multiple nodester accounts.  Each account can have a different RSA key attached to it.

**Comment by stephanepericat** [comment]
Hi Chris,

what about if we want to work on the same project both at work and home ? :)

Cheers,
Stephane

**Comment by DanBUK** [comment]
I've been testing some code to store ssh keys into couch per user, then generate the auth keys file on updates, max 1 time per n mins.

**Comment by yocontra** [comment]
Closed, this has been fixed.
