### ISSUE TITLE
globals undefined

### ISSUE THREAD

**Issue by anm** [nodester/nodester#80]
Variables assigned to global are undefined on read.

Test case:
    global.test = "test";
    console.log(test);

Locally, prints "test'.
On nodester:

nodester info Showing logs for: talker
Munging require paths..
Globallizing Buffer
Reading file...
Nodester wrapped script starting (740) at  Sun, 13 Mar 2011 01:40:47 GMT
ReferenceError: test is not defined
    at talker.js:2:1
    at /home/ec2-user/nodester/scripts/launch_chrooted_app.js:167:20
    at [object Object].<anonymous> (fs.js:86:5)
    at [object Object].emit (events.js:39:17)
    at afterRead (fs.js:840:12){ stack: [Getter/Setter],
  arguments: [ 'test' ],
  type: 'not_defined',
  message: [Getter/Setter] }

**Comment by davglass** [comment]
I'll look into it, but I can't think of  good fix off the top of my head. The global object is a "special" object, I'm not really sure how we can "fake" that inside of our chroot.

**Comment by chrismatthieu** [comment]
I think that this issue is related to https://github.com/nodester/nodester/issues/103

**Comment by DanBUK** [comment]
This will be resolved when #143 has been fully tested.
