### ISSUE TITLE
Error while using 'connect'

### ISSUE THREAD

**Issue by grender** [nodester/nodester#83]
I try to use connect middleware and get error.
Here is log:
    Munging require paths..
    Globallizing Buffer
    Reading file...
    Nodester wrapped script starting (28343) at  Mon, 14 Mar 2011 19:45:39 GMT
    TypeError: Object [object Function] has no method 'apply'
        at Object.createServer (/home/ec2-user/nodester/scripts/launch_chrooted_app.js:108:29)
        at server.js:29:22
        at /home/ec2-user/nodester/scripts/launch_chrooted_app.js:167:20
        at [object Object].<anonymous> (fs.js:86:5)
        at [object Object].emit (events.js:39:17)
        at afterRead (fs.js:840:12){ stack: [Getter/Setter],
      arguments:
       [ 'apply',
         { [Function: createServer]
           utils: [Object],
           HTTPServer: [Function: HTTPServer],
           HTTPSServer: [Function: HTTPSServer],
           version: '1.0.1',
           createServer: [Function],
           middleware: [Object] } ],
      type: 'undefined_method',
      message: [Getter/Setter] }

**Comment by fhemberger** [comment]
Which version of connect do you use?
Have you seen this note on the connect repo (https://github.com/senchalabs/connect):
    Connect < 1.0.0 is compatible with node 0.2.x
    Connect >= 1.0.0 is compatible with node 0.4.x

**Comment by grender** [comment]
connect-1.0.3
but in their package.json i found 
    "engines": { "node": ">= 0.4.1 < 0.5.0" }
API reference says that node version is 4.0.

**Comment by grender** [comment]
Sorry, I accidentally pressed the "Comment and Close". What i must do now?
