### ISSUE TITLE
Nodester CLI crashes when node is compiled --without-ssl

### ISSUE THREAD

**Issue by fhemberger** [nodester/nodester#84]
In some cases, it's recommended to compile node.js without ssl support (e.g. mingw builds). When you try to run a nodester CLI command in such an environment, it just crashes. It would be good to have a check/speaking error message instead.

**Comment by davglass** [comment]
Yeah, that would be the auth crypting, it's using the crypto module to crypt the users auth in the config. Let me see if I can fall back to an unsecure crypt if it's not available.

**Comment by davglass** [comment]
I have this working on our side, but it requires a patch to the "request" module to make it fully usable. request does a raw "require" of the "https" module, which itself, throws if SSL is not installed.

I have submitted a pull request to fix this issue, I will bump the package version when a new version of request is published.
https://github.com/mikeal/request/pull/19

**Comment by davglass** [comment]
This should be working now, we have a new request version that we can use.
