### ISSUE TITLE
npm installing bins outside PATH

### ISSUE THREAD

**Issue by fhemberger** [nodester/nodester#86]
Just tried to install the JSON module via npm:

```
nodester info installing these npm packages: json
nodester npm info it worked if it ends with ok
nodester npm info using npm@0.2.19
nodester npm info using node@v0.4.0
nodester npm info fetch http://registry.npmjs.org/json/-/json-0.0.8.tgz
nodester npm info calculating sha1 /tmp/npm-1300348218388/1300348218388-0.354355699615553/tmp.tgz
nodester npm info shasum 70fd27f71db65a78e9aa83243ae30a51f0a2031a
nodester npm info calculating sha1 /home/ec2-user/hosted_apps/USER/HASH/.node_libraries/.npm/.cache/json/0.0.8/package.tgz
nodester npm info shasum 662dc770367dc33501696d2fedf0a86639f4b45f
nodester npm info preinstall json@0.0.8
nodester npm WARN bins installing to /home/ec2-user/hosted_apps/USER/HASH/.npm_bin, outside PATH
nodester npm WARN man pages installing to /home/ec2-user/share/man, outside MANPATH
nodester npm info install json@0.0.8
nodester npm info postinstall json@0.0.8
nodester npm info preactivate json@0.0.8
nodester npm info activate json@0.0.8
nodester npm info postactivate json@0.0.8
nodester npm info build Success: json@0.0.8
nodester npm ok
```

A `nodester app logs` confirms, that the package was not installed correctly:

```
Nodester wrapped script starting (1687) at  Thu, 17 Mar 2011 07:50:45 GMT
Error: Cannot find module 'json'
    at Function._resolveFilename (module.js:289:11)
    at Function._load (module.js:241:25)
    at require (module.js:317:19)
    at Object.<anonymous> (/lib/view.js:3:9)
    at Module._compile (module.js:373:26)
    at Object..js (module.js:379:10)
    at Module.load (module.js:305:31)
    at Function._load (module.js:271:10)
    at Function.require (module.js:317:19)
    at /home/ec2-user/nodester/scripts/launch_chrooted_app.js:121:26{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Cannot find module \'json\'' }
```

**Comment by davglass** [comment]
Actually, that message confirms that it was, in fact, installed correctly. You are in a chroot environment, you are not allowed to install things to the main system. Hence, the notice of bin/man paths.

As far as I can tell, the json package is a command line tool, it's not a "require"able module.

**Comment by fhemberger** [comment]
> Actually, that message confirms that it was, in fact, installed correctly. You are in a chroot environment, you are not allowed to install things to the main system. Hence, the notice of bin/man paths.

Hmm. Haven't noticed this message on other installs. This problem can be circumvented by an npm config in `~/.npmrc`:

```
root=$HOME/npm_root
binroot=$HOME/bin
manroot=$HOME/man
```

> As far as I can tell, the json package is a command line tool, it's not a "require"able module.

I'm using it on my local machine via 'require', it just breaks after deployment to nodester.

**Comment by davglass** [comment]
On my local machine:
`npm ls installed`
json@0.0.8

node

> require('json');

Error: Cannot find module 'json'
    at Function._resolveFilename (module.js:299:11)
    at Function._load (module.js:245:25)
    at require (module.js:327:19)
    at [object Context]:1:1
    at Interface.<anonymous> (repl.js:150:22)
    at Interface.emit (events.js:42:17)
    at Interface._onLine (readline.js:132:10)
    at Interface._line (readline.js:387:8)
    at Interface._ttyWrite (readline.js:564:14)
    at ReadStream.<anonymous> (readline.js:52:12)

**Comment by fhemberger** [comment]
Just tested it again: json@0.0.8, node@0.4.2:

node:
    > var json = require('json');  
    > json.stringify({ hello: 'world' });
    '{"hello":"world"}'

**Comment by davglass** [comment]
What version of npm?

**Comment by fhemberger** [comment]
npm@0.3.15
