### ISSUE TITLE
cant remove domain via CLI

### ISSUE THREAD

**Issue by anthonywebb** [nodester/nodester#87]
trying to remove a custom domain I added via the CLI, doesnt seem to work.  Here are the details:

255:lmsocket awebb$ nodester appdomain
nodester info fetching your list of domain aliases
nodester info node.localmedia.fm aliased to app lmsocket running on port 8916

255:lmsocket awebb$ nodester appdomain remove node.localmedia.fm
nodester info fetching your list of domain aliases
nodester info node.localmedia.fm aliased to app lmsocket running on port 8916

(NOTE the above call never actually seems to do anything at all, just simply lists out the aliases again.)

**Comment by davglass** [comment]
Fix pushed in `nodester-cli@0.2.11`

You could also call: `nodester domain delete node.localmedia.fm`
