### ISSUE TITLE
typo in the CLI docs

### ISSUE THREAD

**Issue by anthonywebb** [nodester/nodester#88]
If I look at the help for appdomain it says:

255:lmsocket awebb$ nodester help appdomain
nodester In a configured app dir, <appname> is optional
nodester appdomain add <appname> <domainname> - Add a domain router for this app
nodester appdomain remove <appname> <domainname> - Remove a domain router from this app
nodester appdomains - List domains

From the above it looks like if you did "nodester appdomains" it would give you a list.  However, it does not:

255:lmsocket awebb$ nodester appdomains
nodester app or <appname> is not required if inside an app directory after you call setup
nodester app setup <appname> - Configure this app for future app commands
nodester app info <appname> - Returns app specific information
nodester app logs <appname> - Returns app logs
nodester app stop|start|restart <appname> - Controls app status.
nodester app create <appname> <startfile> - Creates a new app named <appname>, <startfile> is optional.
nodester app delete <appname> - Deletes the app.
nodester app gitreset <appname> - Resets the app to git HEAD (in case you want a clean restart).
nodester app init <appname> - Fetches the remote repo and sets it up.
nodester app clone <appname> - Fetches the remote repo.

BUT, if you run this ("appdomain" singular, not plural) it will:

255:lmsocket awebb$ nodester appdomain
nodester info fetching your list of domain aliases
nodester info node.localmedia.fm aliased to app lmsocket running on port 8916

**Comment by davglass** [comment]
Fixed in `nodester-cli@0.2.10`
