### ISSUE TITLE
custom domains not working

### ISSUE THREAD

**Issue by anthonywebb** [nodester/nodester#89]
I created a custom domain for my app, configured DNS, but am still not able get my app to pull up on the custom domain I set up.  I know the app is running fine.

255:lmsocket awebb$ nodester appdomain add nodester.localmedia.fm
nodester info adding domain nodester.localmedia.fm to lmsocket
nodester info Domain added.

255:lmsocket awebb$ nodester appdomain
nodester info fetching your list of domain aliases
nodester info node.localmedia.fm aliased to app lmsocket running on port 8916
nodester info nodester.localmedia.fm aliased to app lmsocket running on port 8916

255:lmsocket awebb$ ping nodester.localmedia.fm
PING nodester.localmedia.fm (50.16.203.53): 56 data bytes
64 bytes from 50.16.203.53: icmp_seq=0 ttl=49 time=453.604 ms
64 bytes from 50.16.203.53: icmp_seq=1 ttl=49 time=551.322 ms

(But still, cant hit this from a web browser)

**Comment by davglass** [comment]
This works for me: http://nodester.localmedia.fm/

**Comment by anthonywebb** [comment]
Yep, working now, someone must have done something on your end.  Thanks.
