### ISSUE TITLE
Git repository seems to have vanished

### ISSUE THREAD

**Issue by kmiyashiro** [nodester/nodester#92]
nodester info
nodester info Gathering information about: yelpvis
nodester info yelpvis on port 8932 running: failed-to-start (pid: unknown)
nodester info gitrepo: ec2-user@nodester.com:/node/hosted_apps/kelly/779-90dfa8334ab4f222a38db97a6f0bdb53.git
nodester info appfile: server.js

git push
bash: /usr/local/bin/git-shell-enforce-directory: No such file or directory
fatal: The remote end hung up unexpectedly

Just started happening over this last weekend, must have been after the server change since I had to update my ssh key.

**Comment by davglass** [comment]
Thanks, we moved to a new EC2 image yesterday, I just fixed this. Can you test to confirm?

**Comment by kmiyashiro** [comment]
Fixed! Pushing is much faster too.

**Comment by davglass** [comment]
Awesome!

**Comment by kmiyashiro** [comment]
Oops, spoke too soon. Looks like it's saying that my app is starting but it's actually not. Logs do not say anything when I restart. I had to re-install oauth and validator modules from npm, but after I did that there are no error messages.

Status says failed-to-start, but when running the app start command it says 'app started'.
