### ISSUE TITLE
App says it starts, but status show it failed-to-start

### ISSUE THREAD

**Issue by kmiyashiro** [nodester/nodester#93]
https://github.com/nodester/nodester/issues/closed#issue/92

After my git repos issue was resolved, I did a successful push and tried to start my app. It complained about missing modules, which I nodester npm installed. I then tried to start my app and it says it started, hooray!

But then I tried navigating to it and it says it was not running. Nodester info says it failed-to-start. Sometimes it will say "running", but navigating to it still says "not running" and then if I check info again it says "failed-to-start".

Logs return nothing. Works on my local machine.

I tried deleting my project, creating it again, and I also tried creating different projects and they also have the same problems, not even the automatically created hello-world server.js works.

**Comment by davglass** [comment]
You must have removed the app in the previous ticket, I can't see it on the server. What app are you talking about here? I need the full output of: `nodester app info`

**Comment by atestu** [comment]
I have the same problem and my output is :

```
nodester info Gathering information about: knox
nodester info knox on port 8964 running: failed-to-start (pid: unknown)
nodester info gitrepo: ec2-user@nodester.com:/node/hosted_apps/atestu/811-35c350ac153ff4bbae0e60f97f9d58f9.git
nodester info appfile: index.js
```

**Comment by davglass** [comment]
This should be working now. That app won't start because it's throwing errrors, you can see them from the cli. Run `nodester logs` from the app directory

**Comment by atestu** [comment]
I see the errors. Thanks a lot!

**Comment by kmiyashiro** [comment]
Sorry, I was creating and deleting it and forgot to re-create it again. I re-created it just now and for some reason it worked this time. It was definitely NOT working before when I re-created it, so I'm not sure what changed.

BUT, another app that I created during this time to test to see if it was just my particular appname that was causing it is _still_ not working, but nodester says it is running. Here is the info:

```
nodester info Gathering information about: yelp-vis
nodester info yelp-vis on port 8986 running: true (pid: 25766)
nodester info gitrepo: ec2-user@nodester.com:/node/hosted_apps/kelly/833-bc7e541b82a6cd8dea8f114a6e908a7c.git
nodester info appfile: server.js
```

**Comment by davglass** [comment]
It's running now: http://yelp-vis.nodester.com/
