### ISSUE TITLE
Cannot push changes to Git

### ISSUE THREAD

**Issue by richardanaya** [nodester/nodester#94]
Everything seems to be operating normal through nodester-cli, I can create, delete, setup myuser, create an app, but I can't seem to git push.  I get this error (my app is 'fontmap'): 

[579][Richard.HARDAC: fontmap]$ git push origin master
Counting objects: 22, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (20/20), done.
Writing objects: 100% (22/22), 48.18 KiB, done.
Total 22 (delta 0), reused 0 (delta 0)
error: insufficient permission for adding an object to repository database ./objects

fatal: failed to write object
error: unpack failed: unpack-objects abnormal exit
To ec2-user@nodester.com:/node/hosted_apps/Richard/856-01c58eaaa435a88bb013ad186ae58081.git
 ! [remote rejected] master -> master (n/a (unpacker error))
error: failed to push some refs to 'ec2-user@nodester.com:/node/hosted_apps/Richard/856-01c58eaaa435a88bb013ad186ae58081.git'

**Comment by davglass** [comment]
Can you try it now?

**Comment by richardanaya** [comment]
fontmap is working fine now.  I seem to be having a different type of permissions problem when creating a new project though ( this is for a project called 'ubermush').  Here is the output on first push:

[596][Richard.HARDAC: ubermush]$ git push origin master
Counting objects: 1692, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (1664/1664), done.
fatal: Unable to create temporary file: Permission denied
error: pack-objects died of signal 13
error: failed to push some refs to 'ec2-user@nodester.com:/node/hosted_apps/Richard/867-92affecd4592f02d47072a312bd6248c.git'
