### ISSUE TITLE
Can't run an app

### ISSUE THREAD

**Issue by alamboley** [nodester/nodester#97]
Hello,

I've tried several times to create a project and start running it... but without success.

Here is what I tried : 
Aymeric:~ Aymeric$ cd /Users/Aymeric/Documents/Workspace/Nodester

Aymeric:Nodester Aymeric$ nodester app create kinessia hello.js
nodester info creating app: kinessia hello.js
nodester info successfully created app kinessia to will run on port 9088 from hello.js
nodester info run nodester app init kinessia to setup this app.

Aymeric:Nodester Aymeric$ nodester app init kinessia ./kinessia
nodester info initializing git repo for kinessia into folder ./kinessia
nodester info cloning the repo git clone ec2-user@nodester.com:/node/hosted_apps/Aymeric/935-9cd267341159e030244479d3b9bae1d3.git ./kinessia
nodester info clone complete
nodester info writing app data to config
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERRO false

Aymeric:Nodester Aymeric$ nodester app info kinessia
nodester info Gathering information about: kinessia
nodester info kinessia on port 9088 running: failed-to-start 
nodester info gitrepo: ec2-user@nodester.com:/node/hosted_apps/Aymeric/935-9cd267341159e030244479d3b9bae1d3.git
nodester info appfile: hello.js

Aymeric:Nodester Aymeric$ nodester app start kinessia
nodester info Attemping to start app: kinessia
nodester ERRO false

Aymeric:Nodester Aymeric$ nodester apps
nodester warn kinessia on port 9088 running: failed-to-start

The page of the project is http://kinessia.nodester.com/

Is there something wrong with the syntax ?
Thanks for helping me !

**Comment by chrismatthieu** [comment]
We have made updates to the platform.  Please try restarting your app again.

**Comment by alamboley** [comment]
Hello Chris, thanks for you answer !

I deleted my app, and I try to create a new one, but I still have a problem :

Aymeric:Nodester Aymeric$ nodester app create kinessia hello.js
nodester info creating app: kinessia hello.js
nodester info successfully created app kinessia to will run on port 9114 from hello.js
nodester info run nodester app init kinessia to setup this app.

Aymeric:Nodester Aymeric$ nodester app init kinessia ./kinessia
nodester info initializing git repo for kinessia into folder ./kinessia
nodester info cloning the repo git clone ec2-user@nodester.com:/node/hosted_apps/Aymeric/961-63cde6a7526307d1bd8e1c7f45a96c0a.git ./kinessia
nodester info clone complete
nodester info writing app data to config

fs.js:200
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'kinessia/.nodester.appconfig'
    at Object.openSync (fs.js:200:18)
    at Object.writeFileSync (fs.js:452:15)
    at Object.writeApp (/usr/lib/node/.npm/nodester-cli/0.2.12/package/lib/config.js:54:8)
    at /usr/lib/node/.npm/nodester-cli/0.2.12/package/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:85:7)
    at ChildProcess.emit (events.js:45:17)
    at ChildProcess.onexit (child_process.js:171:12)

Aymeric:Nodester Aymeric$ nodester app info kinessia
nodester info Gathering information about: kinessia
nodester warn kinessia on port 9114 running: false (pid: unknown)
nodester info gitrepo: ec2-user@nodester.com:/node/hosted_apps/Aymeric/961-63cde6a7526307d1bd8e1c7f45a96c0a.git
nodester info appfile: hello.js

**Comment by chrismatthieu** [comment]
I don't see any apps in your directory.  Could you try running:

nodester app create mycoolnewapp5 hello.js
nodester app init mycoolnewapp5

and then see if you can access http://mycoolnewapp5.nodester.com

**Comment by alamboley** [comment]
I try it, same problem :

Aymeric:~ Aymeric$ nodester app create mycoolnewapp5 hello.js
nodester info creating app: mycoolnewapp5 hello.js
nodester info successfully created app mycoolnewapp5 to will run on port 9123 from hello.js
nodester info run nodester app init mycoolnewapp5 to setup this app.

Aymeric:~ Aymeric$ nodester app init mycoolnewapp5
nodester info initializing git repo for mycoolnewapp5 into folder mycoolnewapp5
nodester info cloning the repo git clone ec2-user@nodester.com:/node/hosted_apps/Aymeric/970-046f4ac8771ee788c3b73b9954c58159.git mycoolnewapp5
nodester info clone complete
nodester info writing app data to config

fs.js:200
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'mycoolnewapp5/.nodester.appconfig'
    at Object.openSync (fs.js:200:18)
    at Object.writeFileSync (fs.js:452:15)
    at Object.writeApp (/usr/lib/node/.npm/nodester-cli/0.2.12/package/lib/config.js:54:8)
    at /usr/lib/node/.npm/nodester-cli/0.2.12/package/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:85:7)
    at ChildProcess.emit (events.js:45:17)
    at ChildProcess.onexit (child_process.js:171:12)

Aymeric:~ Aymeric$ nodester app info mycoolnewapp5
nodester info Gathering information about: mycoolnewapp5
nodester warn mycoolnewapp5 on port 9123 running: false (pid: unknown)
nodester info gitrepo: ec2-user@nodester.com:/node/hosted_apps/Aymeric/970-046f4ac8771ee788c3b73b9954c58159.git
nodester info appfile: hello.js

Aymeric:~ Aymeric$ nodester apps
nodester warn kinessia on port 9114 running: failed-to-start
nodester warn mycoolnewapp5 on port 9123 running: false

**Comment by uchiyama2000** [comment]
the same problem now, me too. 
i run with mac & node0.4.3

<pre>
% nodester app delete a
nodester warn deleting app: a
nodester warn Are you sure you want to do this?
     Waiting 10 seconds before continuing, Ctrl+C to abort)
...........
nodester warn Really deleting app now, you were warned..
nodester warn successfully deleted app a

% nodester app create a app.js
nodester info creating app: a app.js
nodester info successfully created app a to will run on port 9129 from app.js
nodester info run nodester app init a to setup this app.

% nodester app init a
nodester info initializing git repo for a into folder a
nodester info cloning the repo git clone ec2-user@nodester.com:/node/hosted_apps/uchiyama2000/xxx.git a
nodester info clone complete
nodester info writing app data to config

fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'a/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:473:15)
    at Object.writeApp (/Users/uchiyama/.node_libraries/.npm/nodester-cli/0.2.12/package/lib/config.js:54:8)
    at /Users/uchiyama/.node_libraries/.npm/nodester-cli/0.2.12/package/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)

</pre>

**Comment by chrismatthieu** [comment]
Can you try this again?  We just made an update to the platform.

**Comment by alamboley** [comment]
It works like a charm ! Thank you :-)
