### ISSUE TITLE
Can't push the repository : "Unable to create temporary file: Permission denied"

### ISSUE THREAD

**Issue by atestu** [nodester/nodester#99]
This is what I get when I try to push my repository for the first time:

```
Counting objects: 107, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (97/97), done.
fatal: Unable to create temporary file: Permission denied
error: pack-objects died of signal 13
error: failed to push some refs to 'ec2-user@nodester.com:/node/hosted_apps/atestu/999-cae612264dcd597871bb4437b6fd9fe8.git'
```

Obviously I can't get my app "rps" to start. Am I doing something wrong?

**Comment by chrismatthieu** [comment]
Can you try this again?  We just made an update to the platform.

**Comment by atestu** [comment]
Nope, still the same issue. It's weird because I have another app that works ("knox").

EDIT: dammit I accidentally closed the issue while commenting…

**Comment by chrismatthieu** [comment]
could you reset your git repo on nodester and try pushing again?

nodester app gitreset your_app_name

**Comment by atestu** [comment]
Just tried it. Same issue…

**Comment by chrismatthieu** [comment]
Do you by chance have a challenge passphrase on your RSA key?

**Comment by atestu** [comment]
Nope…

**Comment by chrismatthieu** [comment]
Are you still having issues pushing apps to nodester?

**Comment by chrismatthieu** [comment]
Not enough information to troubleshoot...
